### ISSUE TITLE
Demo error: Badly formed genome unclippedLoc

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#119]
Hi, I'm getting this error in the demo for every chromosome:

Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
chr7
Using GATK jar /gpfs/data/evronylab/bin/drop-conda/share/gatk4-4.1.9.0-0/gatk-package-4.1.9.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gpfs/data/evronylab/bin/drop-conda/share/gatk4-4.1.9.0-0/gatk-package-4.1.9.0-local.jar ASEReadCounter -R /gpfs/scratch/evrong01/drop_demo/Data/chr21.fa -I /gpfs/scratch/evrong01/drop_demo/Data/rna_bam/HG00103.4.M_120208_3_chr21.bam -V /gpfs/scratch/evrong01/drop_demo/Data/qc_vcf_1000G.vcf.gz -L chr7 --verbosity ERROR --disable-sequence-dictionary-validation True
[October 25, 2020 6:14:35 PM EDT] org.broadinstitute.hellbender.tools.walkers.rnaseq.ASEReadCounter done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2496135168

A USER ERROR has occurred: Badly formed genome unclippedLoc: Query interval "chr7" is not valid for this input.

**Comment by mumichae** [comment]
Hi, this error shouldn't cause the pipeline to fail, i.e. it should only be a cosmetic problem.
It is due to the fact that the VCF had a chromosome that is not in the BAM file. Incidentally I have fixed this issue in #118, so it will be in the next drop release which I'll be opening soon. That release should also address #105

**Comment by gevro** [comment]
Thanks. What is the best way to update my conda environment with the new drop 1.0.1 version?

**Comment by mumichae** [comment]
Jus install it via pip and git into your current drop environment as described in the documentation.

https://gagneurlab-drop.readthedocs.io/en/latest/installation.html#other-drop-versions
