### ISSUE TITLE
Run without internet connection?

### ISSUE THREAD

**Issue by marcDabad** [gagneurlab/drop#121]
Hi all, 

I run successfuly demo dataset in a computer with internet connection and everything works perfectly.

My problem appears when I try it again in a compute node without internet connection. It trys a cURL and crash (obviously). 

There is any option to run it without connection?

Thanks.

**Comment by mumichae** [comment]
Hi,
Unfortunately the aberrant splicing module requires internet, as it uses `biomaRt`. The other pipelines should work fine though. I will check if that's the case.
We are working on annotating the splice junctions by the gtf provided, but that is still work in progress.

**Comment by marcDabad** [comment]
Only MAE can be run without internet connection. 

Aberrant Splicing crashes, as you explained. 

Aberrant Expression tries to run curl:

```
Error in curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress) :
  Timeout was reached: [] Failed to connect to www.cmm.in.tum.de port 443: Connection timed out
Calls: add_HPO_cols -> fread -> <Anonymous>
Execution halted
```

**Comment by mumichae** [comment]
Thanks for the info. The aberrant expression and splicing pipelines rely on external resources for annotation.
Fixing the annotation for aberrant splicing properly might take some time, but we can come up with a workaround for the meantime providing output without these annotations.

@vyepez88 Could you look into that?

**Comment by c-mertes** [comment]
FRASER can use installed R packages for annotation. its already build into the package of FRASER. I guess if its only relying on GTF annotation we should be able to make it internet connection independent.

**Comment by vyepez88** [comment]
Hi @marcDabad, we identified the problem in both modules and are fixing it. It should be ready early next week.

**Comment by vyepez88** [comment]
Hi Marc,
the problem is that we download a file containing HPO terms and that we connect to ensembl to annotate the splice junctions. The first one is fixed. Please download the hpo_genes file from our webserver: https://www.cmm.in.tum.de/public/paper/drop_analysis/resource/
Then, add a key in the config file:
`hpoFile: /path/to/hpo_genes.tsv.gz`

Reinstall DROP using: 
pip install git+https://github.com/gagneurlab/drop.git@dev

This should have your aberrant expression module fully running.
We'll have the solution to the ensembl annotation problem next week.

**Comment by marcDabad** [comment]
II run the pip command and tried snakemake mae -j 1 and I get an error:

```bash
check for missing R packages
Error: <stdin>: syntax error in line 1 near 'install'
Warning: syntax ambiguity - badly delimited number '1.30.' in line 2 of <stdin> splits into two tokens
Warning: syntax ambiguity - badly delimited number '4.0.' in line 2 of <stdin> splits into two tokens
WARNING: Less than 30 IDs in DROP_GROUP outrider
WARNING: Less than 30 IDs in DROP_GROUP import_exp
WARNING: Less than 30 IDs in DROP_GROUP fraser
Structuring dependencies...
Dependencies file generated at: /scratch_tmp/tmpfy3innsk

Building DAG of jobs...
Error: Directory cannot be locked. This usually means that another Snakemake instance is running on this directory. Another possibility is that a previous run exited unexpectedly.
[Mon Nov 23 13:18:06 2020]
Error in rule mae_dependency:
    jobid: 4
    output: /scratch/devel/mdabad/PIPELINE/ext/drop_201021/drop_new/Output/html/mae-pipeline_dep.svg
    shell:
        snakemake --rulegraph /scratch/devel/mdabad/PIPELINE/ext/drop_201021/drop_new/Output/html/mae-pipeline_index.html | dot -Tsvg -Grankdir=TB > /scratch/devel/mdabad/PIPELINE/ext/drop_201021/drop_new/Output/html/mae-pipeline_dep.svg
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by vyepez88** [comment]
Hi, we're currently having an issue with the rule to produce the snakemake graphs. Can you please rerun using:
 `snakemake mae -j 1 -k`
The -k argument tells the pipeline to keep going even if it finds an error. Also, if possible, use more than 1 core.

**Comment by marcDabad** [comment]
I am sorry, I trie again with -k 3 and I have the same error. 

I tried whole pipeline (with internet connection) and I have this one:

```bash
[...]
Building DAG of jobs...
Error: Directory cannot be locked. This usually means that another Snakemake instance is running on this directory. Another possibility is that a previous run exited unexpectedly.
[Tue Nov 24 09:35:35 2020]
Error in rule Index:
    jobid: 0
    output: /scratch/devel/mdabad/PIPELINE/ext/drop_201021/drop_new/Output/html/drop_new_index.html, /scratch/devel/mdabad/PIPELINE/ext/drop_201021/drop_new/Output/html/drop_new_dep.svg

RuleException:
CalledProcessError in line 413 of /scratch_tmp/tmpykosdfkp:
Command 'set -euo pipefail;  snakemake --rulegraph | dot -Tsvg -Grankdir=RL > /scratch/devel/mdabad/PIPELINE/ext/drop_201021/drop_new/Output/html/drop_new_dep.svg' returned non-zero exit status 1.
  File "/home/devel/mdabad/.conda/envs/test_drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
  File "/scratch_tmp/tmpykosdfkp", line 413, in __rule_Index
  File "/home/devel/mdabad/.conda/envs/test_drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/devel/mdabad/.conda/envs/test_drop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/devel/mdabad/.conda/envs/test_drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/devel/mdabad/.conda/envs/test_drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
Exiting because a job execution failed. Look above for error message
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /scratch/devel/mdabad/PIPELINE/ext/drop_201021/drop_new/.snakemake/log/2020-11-24T091410.088437.snakemake.log
```

A part of this, each step checks FRASER installation and it needs internet connection because it checks if we have the last version.

**Comment by vyepez88** [comment]
Hi, did you run `drop update`?
Also, can you do `snakemake -n mae` to check which steps need to be done?
The `-k` parameter doesn't need a number afterwards, but the `-j` one, you can try `snakemake mae -j 1 -k`
The index rule is not working because the snakemake graph is not working, but all the rest (counting + test) should work.

**Comment by marcDabad** [comment]
I cannot follow without internet because FRASER:

```bash
(test_drop) [mdabad@cnb1 drop_new]$ snakemake mae -j 1 -k
check for missing R packages
install c-mertes/FRASER
Error: Bioconductor version cannot be validated; no internet connection?
Execution halted

```

**Comment by vyepez88** [comment]
yes, currently we have the pipeline to check if all packages are installed, including FRASER from github. If you're sure you have all the R packages, you can comment out the `drop.installRPackages()` line in the Snakemake file. In that way, the pipeline will not check the packages.

**Comment by mumichae** [comment]
please make sure that all dependencies are installed in the environment before running the pipeline. That way, drop shouldn't try to install any more packages.
I wouldn't modify the Snakefile if it's not necessary.

**Comment by marcDabad** [comment]
Every package was installed. 

At the end, I dicided to reinstall everything in a fresh environment and run a drop demo in an empty folder and it works. 

So, I can confirm that **mae** and **aberrantexpression** works without connection on my compute node.

Thanks for your work!

**Comment by marcDabad** [comment]
Re-reading, AS should work without internet or at this point is not possible?

**Comment by vyepez88** [comment]
@marcDabad it is now possible to run the aberrantSplicing pipeline without internet connection. Please install the master branch of DROP. It'll be available in bioconda in a couple of days.

**Comment by muhligs** [comment]
Hi, and thanks for providing this pipeline. 
Was the issue with running on threads without internet solved?

I get:
```
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to ftp.ncbi.nlm.nih.gov port 21 after 2273 ms: Couldn't connect to server
Calls: countSplitReads ... list_ftp_dir -> getURL -> curlPerform -> <Anonymous> -> fun
Execution halted

```
The demo works on the frontend which allow internet access. But not on the nodes (which don't have access). 
I use Drop  version 1.2.4 installed with mamba. 

Thanks
Morten

**Comment by vyepez88** [comment]
Hi. If the dataset is unstranded, the AS module uses the `getBSgenome` function to infer the strand of the split reads. That function requires connection to internet.

**Comment by muhligs** [comment]
It seems not to be `getBSgenome` that is the problem, as the code in `01_1_countRNA_splitReads_samplewise.R` before the call to `FRASER::countSplitReads` includes:
```
# If data is not strand specific, add genome info
genome <- NULL
if(strandSpecific(fds) == 0){
  genome <- getBSgenome(genomeAssembly)
}
```

Which runs on nodes lacking internet. (demo data set)

It seems to be inside the `FRASER::countSplitReads` function that the problem arises. Here, `getBSgenome` is only called if genome is a character, but it is a class 'BSgenome'

The reason I am troubleshooting this is because we would like to run this pipeline on our cluster nodes but they cannot access the internet, so I would like to find out where the connection takes place and see if I can work around it. 

I think the pipeline would have a broader clinical scope if it could be run without net access and the increased reproduceability that comes with it.

**Comment by vyepez88** [comment]
It is a class 'BSgenome' within the `countSplitReads` function because it was already created in the previous step `genome <- getBSgenome(genomeAssembly)`
We will consider predownloading the genome during the installation so that the pipeline doesn't require connection.
