### ISSUE TITLE
Can't install 1.0.1

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#123]
Hi,
I'm following the instructions on your documentation for upgrading, but it isn't working:
https://gagneurlab-drop.readthedocs.io/en/latest/installation.html#other-drop-versions

I tried:
1)
git clone https://github.com/gagneurlab/drop.git
pip install ./drop

2) pip install git+https://github.com/gagneurlab/drop.git

3) pip install git+https://github.com/gagneurlab/drop.git@1.0.1

All 3 times, drop is still at version 1.0.0.

This is based on running drop --version.
Unless drop --version wasn't updated?

**Comment by mumichae** [comment]
You should have 1.0.1
I forgot to update the version number in the code, so it still says 1.0.0
Sorry about that, it will be fixed by the next version.
