### ISSUE TITLE
Missing files in sample annotation and QC VCF file

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#125]
Hi,
I'm getting an error when running any snakemake drop pipeline:
"KeyError in line 13 of /gpfs/scratch/evrong01/droptest3/Snakefile
'GTEX100'
  File "/gpfs/scratch/evrong01/droptest3/Snakefile", line 13, in <module>
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/drop/config/DropConfig.py", line 46, in __init__
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/drop/config/submodules/AberrantExpression.py", line 21, in __init__
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/drop/config/submodules/AberrantExpression.py", line 21, in <dictcomp>"

However, I double checked and my config.yaml and samples.tsv are fine.

config.yaml:

ProjectTitle: UDP plus 100 GTEX samples
root: /gpfs/scratch/evrong01/droptest2/root            # root directory of all intermediate output
htmlOutputPath: /gpfs/scratch/evrong01/droptest2/htmlOutput  # path for HTML rendered reports
indexWithFolderName: true # whether the root base name should be part of the index name

sampleAnnotation: /gpfs/scratch/evrong01/droptest3/samples.tsv

geneAnnotation:
# multiple annotations with custom names are possible
# <annotation_name> : <path to gencode v29 annotation>
  v32: /gpfs/data/evronylab/reference-files/GRCh38_gencode-STAR/gencode.v32.primary_assembly.annotation.gtf

genomeAssembly: hg38  # either hg19 or hg38
exportCounts:
  # specify which gene annotations to include and which 
  # groups to exclude when exporting counts
  geneAnnotations:
  - v32
  excludeGroups:
  - null

aberrantExpression:
  groups: 
  - GTEX100
  fpkmCutoff: 1
  implementation: autoencoder
  padjCutoff: 0.05
  zScoreCutoff: 0
  maxTestedDimensionProportion: 3

aberrantSplicing:
  groups:
  - GTEX100
  recount: false
  longRead: false
  keepNonStandardChrs: false
  filter: true
  minExpressionInOneSample: 20
  minDeltaPsi: 0.05
  implementation: PCA
  padjCutoff: 0.05
  zScoreCutoff: 0
  deltaPsiCutoff: 0.3
  maxTestedDimensionProportion: 6

mae:
  groups:
  - UDP
  genome: /gpfs/data/evronylab/reference-files/GRCh38_gencode-STAR/GRCh38_primary_assembly_genome.fa
  gatkIgnoreHeaderCheck: true
  padjCutoff: .05
  allelicRatioCutoff: 0.8
  addAF: true
  maxAF: .001
  maxVarFreqCohort: .05
  # VCF-BAM matching
  qcVcf: /gpfs/data/evronylab/bin/drop/qc_vcf_1000G.vcf.gz       # path to common variant file e.g. qc_vcf_1000G.vcf.gz
  qcGroups:
  - UDP

tools:
  gatkCmd: gatk
  bcftoolsCmd: bcftools
  samtoolsCmd: samtools

Example of part of the samples.tsv:
RNA_ID	DNA_ID	DROP_GROUP	RNA_BAM_FILE	PAIRED_END	STRAND	COUNT_MODE	COUNT_OVERLAPS	DNA_VCF_FILE	GENE_COUNTS_FILE	ANNOTATION
GTEX-117YW_RNA	GTEX-117YW	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-117YW-0005-SM-5NQ8Z.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-1192W_RNA	GTEX-1192W	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-1192W-0005-SM-5NQBQ.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-1192X_RNA	GTEX-1192X	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-1192X-0005-SM-5NQC3.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz

**Comment by mumichae** [comment]
Could you please repost your sample annotation using code block format (triple backticks ``` before and after your snippet)? Currently it's difficult to see if the formatting is correct

**Comment by gevro** [comment]
```
RNA_ID	DNA_ID	DROP_GROUP	RNA_BAM_FILE	PAIRED_END	STRAND	COUNT_MODE	COUNT_OVERLAPS	DNA_VCF_FILE	GENE_COUNTS_FILE	ANNOTATION
GTEX-111YS_RNA	GTEX-111YS	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-111YS-0006-SM-5NQBE.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-1122O_RNA	GTEX-1122O	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-1122O-0005-SM-5O99J.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-1128S_RNA	GTEX-1128S	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-1128S-0005-SM-5P9HI.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-113IC_RNA	GTEX-113IC	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-113IC-0006-SM-5NQ9C.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-113JC_RNA	GTEX-113JC	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-113JC-0006-SM-5O997.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-117XS_RNA	GTEX-117XS	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-117XS-0005-SM-5PNU6.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-117YW_RNA	GTEX-117YW	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-117YW-0005-SM-5NQ8Z.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-1192W_RNA	GTEX-1192W	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-1192W-0005-SM-5NQBQ.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz		
GTEX-1192X_RNA	GTEX-1192X	GTEX100,GTEXALL	/gpfs/scratch/evrong01/GTEX/BAM/GTEX-1192X-0005-SM-5NQC3.Aligned.sortedByCoord.out.patched.md.bam	TRUE	no	IntersectionStrict	TRUE	/gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
```

**Comment by mumichae** [comment]
Could you update drop to the latest commit in fork mumichae/fix_import_counts? I think there might be a fix that you're misssing.

**Comment by gevro** [comment]
How do I do that? And isn't that already part of the latest main version of drop?

**Comment by mumichae** [comment]
As this is the same issue as addressed  in #114, you'll  need the latest bugfix. Please check out https://github.com/gagneurlab/drop/issues/114#issuecomment-720083617

**Comment by gevro** [comment]
Why isn't this part of the current version of drop?

In any case, there are now two new errors:

1) WARNING: 1 files missing in samples annotation. Ignoring... 
   --> I'm not sure what this means.

2) Another error:
FileExistsError in line 13 of /gpfs/scratch/evrong01/droptest3/Snakefile:
/gpfs/data/evronylab/bin/drop/qc_vcf_1000G.vcf.gz
  File "/gpfs/scratch/evrong01/droptest3/Snakefile", line 13, in <module>
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/drop/config/DropConfig.py", line 58, in __init__
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/drop/config/submodules/MonoallelicExpression.py", line 8, in __init__
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/drop/config/submodules/Submodules.py", line 14, in __init__
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/drop/config/submodules/MonoallelicExpression.py", line 21, in setDefaultKeys
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/drop/utils.py", line 41, in checkKeys

**Comment by mumichae** [comment]
The bug is still being fixed so it's not yet in the new version.

The errors you're getting state that `droptest3/Snakefile:
/gpfs/data/evronylab/bin/drop/qc_vcf_1000G.vcf.gz` does not exist. Please make sure that you have it available

**Comment by gevro** [comment]
Thanks. 1) What genome does that file belong to? I found it here, but it doesn't say if it is hg38 or hg19.
https://www.cmm.in.tum.de/public/paper/drop_analysis/resource/

2) If this file is required for DROP to run, it would be nice to include it in the default installation, for each of the common reference genomes.

3) I'm still getting this error: 
"WARNING: 1 files missing in samples annotation. Ignoring..."

4) I'm getting this error from snakemake unlock:

$ snakemake unlock --cores 1
check for missing R packages
WARNING: 1 files missing in samples annotation. Ignoring...
Structuring dependencies...
Dependencies file generated at: /tmp/tmpk2x28vnn

Building DAG of jobs...
MissingRuleException:
No rule to produce unlock (if you use input functions make sure that they don't raise unexpected exceptions).

**Comment by vyepez88** [comment]
Hi, regarding the first 2 points:
1) It corresponds to hg19. I'll update the naming and create one for hg38. Do you need the hg38 urgently?
2) We thought about that option, but currently we have it that users download only the vcf with the version they need once and then simply refer to that path.

**Comment by mumichae** [comment]
3. Is this file `/gpfs/data/evronylab/bin/drop/qc_vcf_1000G.vcf.gz` in your sample annotation? I yes, make sure that it exists or correct the path. Otherwise go through the sample annotation and identify which path is missing. I'll add an output for which file exactly is missing in the next commit.

4. Since DROP 1.0.0 the rule unlock has been removed. If your pipeline is locked, just use the snakemake option `snakemake --unlock`

**Comment by gevro** [comment]
Hi, Thanks.
1) I think it would be easier for users if you include common qc_*_1000g files for various human references (hg19, hg38) as part of the standard package download.
2) Yes, I would need hg38 when possible. Otherwise, I cannot do the analysis.
3) Set up of the qc_*_1000g file should be better explained in the documentation so people know to download and set this up, unless you will include this as part of your standard package.

4) I'm still getting this error:
"WARNING: 1 files missing in samples annotation. Ignoring..."

**Comment by mumichae** [comment]
Yes I agree that the documentation regarding the QC vcf file could be better. @vyepez88 Could you look into it?

As for the missing file issue, could you please confirm that all of the file paths are correct and point to existing files? I haven't gotten down to working on DROP yet, but it shouldn't be too difficult to go through your sample annotation and call a function to check if each file exists.

Also, if the missing file is the qc vcf the way it is presented on your error message, that would mean it's on the installation Location of DROP, which is not recommended. Please move it to a different directory if you haven't already to avoid potential issues.

**Comment by gevro** [comment]
Thanks. I found the missing file.
In the meantime, can I just use liftover to change qc_vcf_1000G.vcf.gz from hg19 to hg38?

**Comment by vyepez88** [comment]
Yes, using a liftover would be the solution. That's what I was planning to do. If you did it already, could you provide it to us so that we can upload it? Otherwise I'll do it tomorrow.

**Comment by gevro** [comment]
Sure, find attached. However, note that I only retained chr1-22, chrX, chrY, chrM. If you want the other contigs, then you should lift-over yourself.
[qc_vcf_1000G.hg38.vcf.gz](https://github.com/gagneurlab/drop/files/5507316/qc_vcf_1000G.hg38.vcf.gz)

**Comment by vyepez88** [comment]
Hi, many thanks! The hg19 qc_vcf contained only positions in chr1-22, so your liftover also contains positions in those chromosomes as well. The hg38 file you generated is now under: https://www.cmm.in.tum.de/public/paper/drop_analysis/resource/
I updated the documentation locally and will be reflected in the next DROP update.

**Comment by vyepez88** [comment]
This is now reflected in the documentation. Thanks again for pointing this out and providing the vcf file.
