### ISSUE TITLE
Reading DROP_GROUP as bool

### ISSUE THREAD

**Issue by mumichae** [gagneurlab/drop#126]
From #114

**Comment by mumichae** [comment]
[test.txt](https://github.com/gagneurlab/drop/files/5475612/test.txt)

@nicweb It seems like your missing the RNA_ID column, so all other columns are offset accordingly. Adding the column should fix the problem. Also double-check your `sa` object to make sure columns and entries  match

**Comment by nicweb** [comment]
ok my bad - I managed cut this of while constructing the example. I fixed the file, but the error still persists. Something is bad with my pandas:

cat test.tsv
RNA_ID  RNA_BAM_FILE    DNA_VCF_FILE    DNA_ID  DROP_GROUP      PAIRED_END      COUNT_MODE      COUNT_OVERLAPS  STRAND  HPO_TERMS       GENE_COUNTS_FILE        ANNOTATION
I18R008Rf02     /mnt/breast_cancer/tests/demo6/Data/rna_bam/HG00096.1.M_111124_6_chr21.bam      /mnt/breast_cancer/tests/demo6/Data/dna_vcf/demo_chr21.vcf.gz   I18D015a01      outrider,mae,fraser,blood      True    IntersectionStrict      True    no      HP:0000008      NA

The file is tab separated: 

> cut -f 1 test.tsv
> RNA_ID
> I18R008Rf02
> 
> cut -f 5 test.tsv
> DROP_GROUP
> outrider,mae,fraser,blood

But pandas does not honor the first tab and I have no clue why?! So the columns are wrong.. 

> import pandas as pd
> sa = pd.read_csv("test.tsv", sep="\t")
>  sa["RNA_ID"]
> I18R008Rf02    /mnt/breast_cancer/tests/demo6/Data/rna_bam/HG...
> Name: RNA_ID, dtype: object
> sa["DROP_GROUP"]
> I18R008Rf02    True
> Name: DROP_GROUP, dtype: bool

Any ideas?

**Comment by nicweb** [comment]
Attached the updated file
[test.txt](https://github.com/gagneurlab/drop/files/5480447/test.txt)

**Comment by mumichae** [comment]
I could reproduce the error. Your file is malformed because it has too many fields in the first line. You have 2 tabulators at the end of the line, (13 fields, 11 columns). Pandas then treats the first column as an index instead of the first column. When I remove these tabs, the file is read correctly.

In the last commit I force pandas not to interpret the first column as index to deal with your case. Try to update drop and try again to see if it fixes your problem

**Comment by nicweb** [comment]
Thank you for your effort. The latest fix enables me to run the one line sample -which fails as expected as <10 samples are valid.
The demo also runs through.

The fix is not perfect though: My unmodified sample.tsv fails at chunck 4:

> label: unnamed-chunk-4
> Quitting from lines 55-59 (/tmp/RtmpVqDpzK/file31d93c581568/SampleAnnotation.spin.Rmd)
> Error in .checkTypos(e, names_x) :
>   Object 'RNA_ID' not found amongst I18R008Rf02, /mnt/breast_cancer/cinder_backups/qmrkh_data/bam/Probe/I18R008Rf02/QMRKH078AP_I18R008Rf02_accepted_hits.bam, /mnt/breast_cancer/QMRKH/results/0031-1/Annotation/0031-1/VEP/Strelka_I18D015a01_variants_VEP.ann.vcf.gz, I18D015a01, outrider,mae,fraser,blood and 8 more

But: removing the additional tabs at the end enables me to run sampleAnnotation successfully.

Edit: I'm currently using github.com/mumichae/drop.git@fix_import_counts 7f41259
