### ISSUE TITLE
Do not require the columns GENE_COUNTS_FILE, ANNOTATION

### ISSUE THREAD

**Issue by vyepez88** [gagneurlab/drop#128]
Correct the script that parses the sample annotation table so that those 2 columns are not required by default.

**Comment by XimenaBo** [comment]
Hi, what's the best way to overpass this?
Use external matrices even if my dataset is large enough?
I would like to keep the analysis, at least at first, to my dataset only.
Thanks in advance!!

**Comment by XimenaBo** [comment]
> Hi, what's the best way to overpass this?
> Use external matrices even if my dataset is large enough?
> I would like to keep the analysis, at least at first, to my dataset only.
> Thanks in advance!!

Arrg, nevermind. I now looked in the dropdemo and saw the columns can be empty :)
Thanks!!

**Comment by vyepez88** [comment]
rename `ANNOTATION` column to `GENE_ANNOTATION`

**Comment by vyepez88** [comment]
now part of this PR: https://github.com/gagneurlab/drop/pull/164
