### ISSUE TITLE
Fraser fails due to incompatible b37 hg19 MT genome lengths

### ISSUE THREAD

**Issue by nicweb** [gagneurlab/drop#135]
The aberrantSplicing pipeline fails due to incompatible MT lengths:

> Error in mergeNamedAtomicVectors(seqlengths(x), seqlengths(y), what = c("sequence",  :
>   sequence MT has incompatible seqlengths:
>   - in 'x': 16569
>   - in 'y': 16571

All user provided references and annotation match:

Ref Fasta length:
> grep MT human_g1k_v37_decoy.dict
> @SQ     SN:MT   LN:16569        M5:c68f52674c9fb33aef52dcf399755519

Bam files:
> samtools view -H <files>.bam | grep MT
> @SQ     SN:MT   LN:16569

 The used gtf annotation also matches.

I expect the error due to the hard coded usage of
`genome <- BSgenome.Hsapiens.UCSC.hg19`  in /drop/modules/aberrant-splicing-pipeline/Counting/01_1_countRNA_splitReads_samplewise.R

but maybe I'm wrong.

Full log:

> Wed Nov 11 12:27:57 2020: FRASER object initialized for fraser
> [1] TRUE
> [Wed Nov 11 12:27:57 2020]
> Finished job 72.
> 2 of 72 steps (3%) done
> 
> [Wed Nov 11 12:27:57 2020]
> rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
>     input: /mnt/breast_cancer/tests/test1/processed_data/aberrant_splicing/datasets/cache/raw-fraser/fds.done, Scripts/AberrantSplicing/pipeline/Counting
> /01_1_countRNA_splitReads_samplewise.R
>     output: /mnt/breast_cancer/tests/test1/processed_data/aberrant_splicing/datasets/cache/raw-fraser/sample_tmp/splitCounts/sample_I18R008Ri01.done
>     log: /mnt/breast_cancer/tests/test1/.drop/tmp/AS/fraser/splitReads/I18R008Ri01.Rds
>     jobid: 26
>     wildcards: dataset=fraser, sample_id=I18R008Ri01
> 
> Load packages
> Loading required package: BSgenome
> Loading required package: rtracklayer
> 
> Attaching package: ‘rtracklayer’
> 
> The following object is masked from ‘package:plotly’:
> 
>     export
> 
> Wed Nov 11 12:28:15 2020: Count split reads for sample: I18R008Ri01
> Error in mergeNamedAtomicVectors(seqlengths(x), seqlengths(y), what = c("sequence",  :
>   sequence MT has incompatible seqlengths:
>   - in 'x': 16569
>   - in 'y': 16571
> Calls: countSplitReads ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
> In addition: Warning message:
> In FUN(...) :
>   The seqlevelsStyles from the BAM file and the annotation are not the same! Will force annotation to use the one from the BAM file.
> Execution halted
> [Wed Nov 11 12:28:41 2020]
> Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
>   jobid: 26
>     output: /mnt/breast_cancer/tests/test1/processed_data/aberrant_splicing/datasets/cache/raw-fraser/sample_tmp/splitCounts/sample_I18R008Ri01.done
>     log: /mnt/breast_cancer/tests/test1/.drop/tmp/AS/fraser/splitReads/I18R008Ri01.Rds (check log file(s) for error message)
> 
> RuleException:
> CalledProcessError in line 127 of /tmp/tmp3a54d7d5:
> Command 'set -euo pipefail;  Rscript --vanilla /mnt/breast_cancer/tests/test1/.snakemake/scripts/tmpafkv3on5.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
>   File "/tmp/tmp3a54d7d5", line 127, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
> Shutting down, this might take some time.

**Comment by nicweb** [comment]
I'm currently exploring the option to use the `BSgenome.Hsapiens.1000genomes.hs37d5` version in the affected script, but I don't know what implication this has on the up/downstream analysis...

**Comment by ischeller** [comment]
Hi, can you check which version of FRASER you are using? This has been fixed in FRASER and should no longer throw an error for FRASER version >= 1.1.3. Instead, chromosomes where this mismatch of chromosome length between the bam file and the provided `genome` happens will be discarded from counting. 
So if you want to consider the MT chromosome in your analysis, use a` genome` that has the same information as the  fasta that the reads were aligned against. 
Regarding how the choice of `genome` affects the downstream analysis: FRASER uses the provided `genome` only for unstranded data to infer the strand information of reads spanning an intron based on the dinucleotides found at the intron boundaries.

**Comment by nicweb** [comment]
Alright thanks for the info. You're right. The FRASER version is listed as 1.0.1 which seems quite old, but I don't know why. Drop requirements lists version as 1.1.1 on master and 1.2.0 on dev branch and should have been automatically installed when installing DROP. 

At the moment the scripts are still running with the hs37d5. Once finished I'll update FRASER and switch back to hg19 to see if the error persists. At the moment the user can not easily choose the hs37d5 build as reference for FRASER to use. Maybe the pipeline can in the future support this? (feature request) I know this might blow up size of the installation...

**Comment by c-mertes** [comment]
@nicweb thanks for reporting this. We are working on this to support the usage of the user-provided GTF file in the DROP config. This should fix the issue then.

**Comment by nicweb** [comment]
Great, thanks for all your feedback.

**Comment by vyepez88** [comment]
Hi, you can know use hs37d5 in the config file. These changes are reflected in the `dev` branch.
