### ISSUE TITLE
Fraser summary knitr fails with rowMeans error

### ISSUE THREAD

**Issue by nicweb** [gagneurlab/drop#149]
After updating Fraser as suggested in #135 and moving to the latest dev version the summary step of the pipeline fails with:

> Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) :
>   'x' must be an array of at least two dimensions

Please let me know in case I can provide more information about the final Fraser objects for example.

> [Tue Dec  1 22:57:29 2020]
> rule AberrantSplicing_pipeline_FRASER_Summary_R:
>     input: /mnt/breast_cancer/tests/test2/processed_data/aberrant_splicing/datasets/savedObjects/fraser/padjBetaBinomial_theta.h5, /mnt/breast_cancer/tests/test2/processed_data/aberrant_splicing/results/fraser_results.tsv, Scripts/AberrantSplicing/pipeline/FRASER/Summary.R
>     output: /mnt/breast_cancer/tests/test2/Output/html/AberrantSplicing/fraser_summary.html
>     log: /mnt/breast_cancer/tests/test2/.drop/tmp/AS/fraser/FRASER_summary.Rds
>     jobid: 6
>     wildcards: dataset=fraser
> [..snip..]
> label: unnamed-chunk-4
>   |.......................................................                                                       |  50%
>   ordinary text without R code
> 
>   |............................................................                                                  |  55%
> label: unnamed-chunk-5
> Quitting from lines 73-109 (/tmp/RtmpOJeJcq/file64991871c75a/Summary.spin.Rmd)
> Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) :
>   'x' must be an array of at least two dimensions
> Calls: render ... plotCountCorHeatmap -> .local -> rowMeans -> rowMeans -> <Anonymous>
> In addition: There were 39 warnings (use warnings() to see them)
> 
> Execution halted
> [Tue Dec  1 23:00:55 2020]
> Error in rule AberrantSplicing_pipeline_FRASER_Summary_R:
>     jobid: 6
>     output: /mnt/breast_cancer/tests/test2/Output/html/AberrantSplicing/fraser_summary.html
>     log: /mnt/breast_cancer/tests/test2/.drop/tmp/AS/fraser/FRASER_summary.Rds (check log file(s) for error message)
> 
> RuleException:
> CalledProcessError in line 254 of /tmp/tmpwjqp9fpo:
> Command 'set -euo pipefail;  Rscript --vanilla /mnt/breast_cancer/tests/test2/.snakemake/scripts/tmpdmoc3rqv.wBRender.R' returned non-zero exit status 1.
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
>   File "/tmp/tmpwjqp9fpo", line 254, in __rule_AberrantSplicing_pipeline_FRASER_Summary_R
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
>

**Comment by vyepez88** [comment]
Hi, that error also appeared to us in one of the updates from Bioconductor. Can you please reinstall your FRASER using:
`BiocManager::install('c-mertes/FRASER', ask=FALSE, update=FALSE)`

**Comment by nicweb** [comment]
I switched over to `c-mertes/FRASER@HEAD` and the pipeline completes. I'll close this issue. Thanks
