### ISSUE TITLE
transcript coordinates

### ISSUE THREAD

**Issue by projectoriented** [gagneurlab/drop#150]
Hello,

I have generated transcript coordinates from STAR using `--quantMode TranscriptomeSAM`, does DROP take alignments translated into transcript coordinates in sorted bam or just the regular alignment file?

Thanks!

**Comment by projectoriented** [comment]
@jemten _just tagging you here for updates_

**Comment by vyepez88** [comment]
Hello, 
we've never tried DROP with transcript coordinates, so there's a high chance it won't work.

**Comment by mumichae** [comment]
DROP takes BAM files that match with the given annotation file. If you use different features, then you should provide a gtf that maps these coordinates to a "gene_name" column, as that is required in the code.

**Comment by projectoriented** [comment]
Good to know, thanks for your response!
