### ISSUE TITLE
Too few IDs in DROP_GROUP when combined with public data resource in aberrantSplicing pipeline

### ISSUE THREAD

**Issue by zhouzaiwei** [gagneurlab/drop#154]
Hi,
I have one RNAseq data of rare disease case and want to combine analysis with public 125 blood RNAseq data.
It is well done in aberrantExpression pipeline.
but when do aberrantSplicing pipeline i shows too few IDs error, and only show one sample name.
I provide splitCounts.tsv.gz and spliceSiteOverlapCounts.tsv.gz in GENE_COUNTS_FILE colnum of SampleAnnotation table.
Is it possible to analysis aberrantsplicing like above methods? if yes, how to prepare the SampleAnnotation table?
Thanks!

**Comment by vyepez88** [comment]
Hi,
we're working on this. We'll let you know once it's done.

**Comment by zhouzaiwei** [comment]
Thanks!

**Comment by c-mertes** [comment]
I added this new functionality to add external splicing counts. 

Currently, we have only a dataset for fibroblasts from the Kremer paper for `hg19`.

If you have time and interest you can test it by following this instructions:

```
# 1. activate your test conda env 
# 2. install the new pipeline and FRASER
pip install git+https://github.com/gagneurlab/drop.git@merge_exFRASER_counts#egg=drop

# setup demo dir and external resource
mkdir /tmp/drop_demo /tmp/drop_resources
wget -P /tmp/drop_resources https://zenodo.org/record/4271599/files/kremer--hg19--gencode34.tar.gz
tar -xzf /tmp/drop_resources/kremer--hg19--gencode34.tar.gz -C /tmp/drop_resources

cd /tmp/drop_demo
drop demo

# Adapt sample annotation by adding the `SPLICE_COUNTS_DIR` column linking to the extracted Kremer folder. 
# one new line per sample that will be imported. 

# run pipeline
snakemake -j 20
```

**Comment by zhouzaiwei** [comment]
Thanks  a lot! I will have try.
