### ISSUE TITLE
Denoising autoencoder param for AE & AS

### ISSUE THREAD

**Issue by projectoriented** [gagneurlab/drop#163]
Hello 👋. In your documentation page regarding preparation of input data- there is a suggestion at the bottom to change the `maxTestedDimensionProportion` param in the config.yaml by dividing the samples by their respective recommended values. I wonder, does the AE and AS module do this automatically because it knows how many samples are loaded in per DROP group or would I have to preset this manually in the config.yaml beforehand? e.g. I have 53 blood samples for AE run and I'd divide that by 3 and input that number in the config.yaml - or?

Thanks! & awesome work :)

@jemten

**Comment by vyepez88** [comment]
Hi, thanks for your question. The modules already know the number of samples per group. So, if you write 3 in the config file, it will test at most 17 dimensions.
