### ISSUE TITLE
MAE result markdown fails

### ISSUE THREAD

**Issue by nicweb** [gagneurlab/drop#165]
The mae pipeline fails during the last markdowns steps (see below). Any tips appreciated how to complete the steps or what the offending object is....

> Job counts:
>         count   jobs
>         1       MonoallelicExpression_pipeline_MAE_Datasets_R
>         1       MonoallelicExpression_pipeline_MAE_Results_R
>         1       MonoallelicExpression_pipeline_QC_Datasets_R
>         1       mae
>         4
> 
> [Mon Feb  8 08:47:24 2021]
> rule MonoallelicExpression_pipeline_MAE_Results_R:
>     input: /mnt/breast_cancer/tests/mae_mod/processed_results/mae/samples/I18D015a01--I18R008Rf02_res.Rds, 
>[..... all samples go here.....]
>/I18R008Di03--I18R008Ri03_res.Rds, /mnt/breast_cancer/tests/mae_mod/processed_data/mae/gene_name_mapping_v29.tsv, Scripts/MonoallelicExpression/pipeline/MAE/Results.R
>     output: /mnt/breast_cancer/tests/mae_mod/processed_results/mae/mae/MAE_results_all_v29.tsv.gz, /mnt/breast_cancer/tests/mae_mod/processed_results/mae/mae/MAE_results_v29.tsv, /mnt/breast_cancer/tests/mae_mod/Output/html/MAE/mae--v29_results.html
>     log: /mnt/breast_cancer/tests/mae_mod/.drop/tmp/MAE/mae/v29_results.Rds
>     jobid: 5
>     wildcards: dataset=mae, annotation=v29
> 
> Loading required package: knitr
> Loading required package: rmarkdown
> [1] TRUE
> 
> 
> processing file: /tmp/RtmpBZsHsl/file40d91f169532/Results.spin.Rmd
>   |........                                                                                                      |   7%
>   ordinary text without R code
> 
>   |................                                                                                              |  14%
> label: unnamed-chunk-1 (with options)
> List of 1
>  $ echo: symbol F
> 
> Quitting from lines 26-75 (/tmp/RtmpBZsHsl/file40d91f169532/Results.spin.Rmd)
> Error in `[.data.table`(rvar, , `:=`(N, 1:.N), by = aux) :
>   Supplied 2 items to be assigned to group 1 of size 0 in column 'N'. The RHS length must either be 1 (single values are ok) or match the LHS length exactly. If you wish to 'recycle' the RHS please use rep() explicitly to make this intent clear to readers of your code.
> Calls: render ... withCallingHandlers -> withVisible -> eval -> eval -> [ -> [.data.table
> 
> Execution halted
> [Mon Feb  8 08:47:40 2021]
> Error in rule MonoallelicExpression_pipeline_MAE_Results_R:
>     jobid: 5
>     output: /mnt/breast_cancer/tests/mae_mod/processed_results/mae/mae/MAE_results_all_v29.tsv.gz, /mnt/breast_cancer/tests/mae_mod/processed_results/mae/mae/MAE_results_v29.tsv, /mnt/breast_cancer/tests/mae_mod/Output/html/MAE/mae--v29_results.html
>     log: /mnt/breast_cancer/tests/mae_mod/.drop/tmp/MAE/mae/v29_results.Rds (check log file(s) for error message)
> 
> RuleException:
> CalledProcessError in line 276 of /tmp/tmpg3bh238x:
> Command 'set -euo pipefail;  Rscript --vanilla /mnt/breast_cancer/tests/mae_mod/.snakemake/scripts/tmpgh59jdbr.wBRender.R' returned non-zero exit status 1.
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
>   File "/tmp/tmpg3bh238x", line 276, in __rule_MonoallelicExpression_pipeline_MAE_Results_R
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
>   File "/home/centos/miniconda3/envs/drop/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
>

**Comment by vyepez88** [comment]
Hi, I guess it's related to the gene_biotype column in the gtf file. 
Can you please install the latest DROP (1.0.3) and run it there?

**Comment by nicweb** [comment]
For this run I used a different gtf without gene_biotype (only gene_type). I can test with 1.0.3 anyway and will report back

**Comment by vyepez88** [comment]
can you try the `dev` branch? It includes some other fixes to the MAE pipeline

**Comment by nicweb** [comment]
The error still persists. I updated to the lastest dev and performed a drop update before rerunning the complete pipeline.

**Comment by mumichae** [comment]
@nicweb Could you check the output of a couple of the input files e.g. `/mnt/breast_cancer/tests/mae_mod/processed_results/mae/samples/I18D015a01--I18R008Rf02_res.Rds`? Could you paste a sample here?

@vyepez88 Is there a possibility that the code in the MAE results script results in an empty data table? E.g. through different chromosome formats?

**Comment by nicweb** [comment]
The input files seem fine:

> 
> head(readRDS('/mnt/breast_cancer/tests/mae_mod/processed_results/mae/samples/I18D015a01--I18R008Rf02_res.Rds'))
>   contig position variantID refAllele altAllele refCount altCount totalCount
> 1      1    14653         .         C         T       56       43         99
> 2      1    16977         .         G         A       81       15         96
> 3      1    20304         .         G         C        6        4         10
> 4      1    20321         .         A         C        6        4         10
> 5      1    20467         .         C         T        9        2         11
> 6      1   135465         .         C         T       10        0         10
>                        ID       pvalue        padj     log2FC  altRatio rare
> 1 I18D015a01--I18R008Rf02 0.8275558470 0.890286028 -0.1180566 0.4343434   NA
> 2 I18D015a01--I18R008Rf02 0.0003781047 0.002106351 -2.1699252 0.1562500   NA
> 3 I18D015a01--I18R008Rf02 0.7562245822 0.847889186 -0.3219291 0.4000000   NA
> 4 I18D015a01--I18R008Rf02 0.7562245822 0.847889186 -0.3219291 0.4000000   NA
> 5 I18D015a01--I18R008Rf02 0.1170183393 0.198636388 -1.9068891 0.1818182   NA
> 6 I18D015a01--I18R008Rf02 0.0101403416 0.020548511 -5.5015537 0.0000000   NA

anything else I can provide to help debugging?

**Comment by nicweb** [comment]
I checked all RDs in the sample directory and none are empty

**Comment by mumichae** [comment]
Thanks for the info, it definitely helps identify the problem. It looks a lot like a chromosome style issue when we merge tables in the script, where we'd expect UCSC format. @vyepez88 Can you confirm if that's the case?

**Comment by vyepez88** [comment]
Hi, indeed I think it's a chromosome style issue. I'll make a new branch and address this there.

**Comment by vyepez88** [comment]
Hi @nicweb , can you please try again by installing this branch: https://github.com/gagneurlab/drop/tree/chr_style
Maybe create a DROP group with 5 samples only and test the MAE pipeline there.

**Comment by nicweb** [comment]
The chr_style branch fixed the error - the pipeline completed. I'll have to check the output but I expect that everything is fine. Thanks!

**Comment by vyepez88** [comment]
great! please let us know if the output is fine

**Comment by vyepez88** [comment]
hi @nicweb, were you able to look at the output? does it look like you would expect it?

**Comment by nicweb** [comment]
Yup! Thanks I'll close the issue.
