### ISSUE TITLE
Expression pipeline does not rerun sample after changing sample group association

### ISSUE THREAD

**Issue by c-mertes** [gagneurlab/drop#171]
If a user runs the full pipeline with 2 groups and then decides to add a sample from one to the other group the pipeline does not re-execute it as it only depends on the counted bam file. The same goes if a sample gets dropped from a group.

Hence, we need a check on if samples are contained and if a rerun is needed. So we have to create a sample annotation file for it. It could be just a simple copy of the relevant rows. And then a trigger to run the corresponding rule or just a note to the user that he has to force it.

What do you think of this: @mumichae @vyepez88 

This is also related to #170

We should change [here](https://github.com/gagneurlab/drop/blob/master/drop/modules/aberrant-expression-pipeline/Counting/filterCounts.R) the dependencies

**Comment by c-mertes** [comment]
1. get the parameters encoded in a file -> [check here](https://github.com/gagneurlab/drop/blob/f089b637c44db4f6bea72dc75f8480adcd75f462/drop/modules/aberrant-expression-pipeline/Counting/countReads.R#L8)
    1. remove the file path as this can change
2. get the list of samples encoded in a file -> [check here](https://github.com/gagneurlab/drop/blob/f089b637c44db4f6bea72dc75f8480adcd75f462/drop/modules/aberrant-expression-pipeline/Counting/mergeCounts.R#L10)
3. encode the full sample annotation of the given dataset as input -> [check here](https://github.com/gagneurlab/drop/blob/f089b637c44db4f6bea72dc75f8480adcd75f462/drop/modules/aberrant-expression-pipeline/OUTRIDER/results.R#L12)

The check code to create the necessary files before building up the dag could be put into [here](https://github.com/gagneurlab/drop/blob/f089b637c44db4f6bea72dc75f8480adcd75f462/drop/config/submodules/AberrantExpression.py#L22)

**Comment by vyepez88** [comment]
The parameters (column names) that affect counting are:
`RNA_ID, RNA_BAM_FILE, COUNT_MODE, PAIRED_END, COUNT_OVERLAPS, STRAND`
