### ISSUE TITLE
Update only scripts that changed

### ISSUE THREAD

**Issue by c-mertes** [gagneurlab/drop#172]
When running `drop update` all scripts are getting updated. But we should do rather something where we compare the files and if they differ we need to copy them.

Doing so would enable users to not force rerun everything in the pipeline but rather only needed parts.

I would suggest something like this:
1. remove any non-existing file from `template` in `destination`
2. for each file: if missing or different md5 sum -> copy/override

this can be done in the setup drop script.

**Comment by vyepez88** [comment]
Not all scripts are getting updated, just the ones that changed.

**Comment by c-mertes** [comment]
Deleting the whole tree does not make sense in this scenario. So we should rather go through each file within the tree. 

https://github.com/gagneurlab/drop/blob/f089b637c44db4f6bea72dc75f8480adcd75f462/drop/cli.py#L33

**Comment by vyepez88** [comment]
fixed now in this pull request #179

**Comment by nickhsmith** [comment]
As this should be fixed, I am closing the issue
