### ISSUE TITLE
minSample enforcement is ignoring external counts

### ISSUE THREAD

**Issue by c-mertes** [gagneurlab/drop#173]
When checking for the minimum required sample size, external counts are ignored and not counted. This currently forces to have at least 10 samples to be counted when merging only external counts.

**Comment by c-mertes** [comment]
Test if the pipeline works if only external counts are provided

**Comment by julbtn** [comment]
Hi,

I am currently using 8 samples, for which I only have bam files and an external count matrix with more than 100 samples. And I would like to run the AberrantExpression and AberrantSplicing modules with the 1.0.4 version.
I seem to get a "Too few IDs in DROP_GROUP, please ensure that it has at least 10 IDs, group" error.
Is this version of DROP (1.0.4) considering samples from the external count matrix? and if so is it possible to run an analysis using only an external count matrix (no BAM file and/or VCF files available)?

Thank you!

**Comment by mumichae** [comment]
Hi,
unfortunately DROP doesn't include the external samples when checking, but we're working on it. We set 10 samples as the minimum, but would recommend at least 30 samples for some proper analysis. Possibly the external counts and your samples could show a strong batch effect, so it's better for the model to have more data per 'batch' to correct. But we'll let you know once we fix DROP to recognise external counts.

**Comment by nickhsmith** [comment]
The aberrantExpression pipeline should correctly count the external count files. However, as Michaela said, the splicing pipeline is still being worked on. We hope to have that and some other changes soon which will allow a more configurable DROP run.

Thanks for your patience. If you do decide to run just aberrantExpression `snakemake aberrantExpression <options> ` let us know if you have issues.

**Comment by julbtn** [comment]
Hi,
Thanks for the quick feedback. I have tried to only run the AberrantExpression module, but I get the same error, the external samples don't seem to get included. 

ValueError in line 13 of /PATH/DROP/projects/analysis_cardio/Snakefile:
Too few IDs in DROP_GROUP outrider, please ensure that it has at least 10 IDs, groups: ['HD_2', 'HD_4', 'HD_1', 'RCM_2', 'DCM_2', 'DCM_1', 'RCM_1', 'HD_3']
  File "/PATH/DROP/projects/analysis_cardio/Snakefile", line 13, in <module>
  File "/PATHDROP/1.0.4-foss-2020b-R-4.0.3/lib/python3.8/site-packages/drop/config/DropConfig.py", line 55, in __init__
  File "/PATH/DROP/1.0.4-foss-2020b-R-4.0.3/lib/python3.8/site-packages/drop/config/submodules/AberrantExpression.py", line 27, in __init__
  File "/PATH/DROP/1.0.4-foss-2020b-R-4.0.3/lib/python3.8/site-packages/drop/config/submodules/Submodules.py", line 45, in checkSubset

I've attached my configuration file and the sample annotation file.
[cardio_sampleAnnotation.pdf](https://github.com/gagneurlab/drop/files/6669071/cardio_sampleAnnotation.pdf)
[config.pdf](https://github.com/gagneurlab/drop/files/6669073/config.pdf)

(I've put "PATH" for privacy, but the full path is specified when running.)

Thanks!

**Comment by moe1619** [comment]
I believe I had similar issues. Take a look at https://github.com/gagneurlab/drop/issues/193
