### ISSUE TITLE
should RNAseq bam be marked duplicate or not?

### ISSUE THREAD

**Issue by zhouzaiwei** [gagneurlab/drop#174]
Hi,
from Nature Protocol article says: Under default settings, DROP does not require the BAM ﬁles to contain any particular tag or ﬁeld", from JCI article says: duplicates were marked with Picard. So I wan to know if we should RNAseq bam be marked duplicate or not? 
Thanks a lot!

**Comment by vyepez88** [comment]
Hi,
Currently, DROP does not have an option to count reads that are not duplicates. It simply counts all the reads from the BAM file. In the JCI article duplicate reads are marked, yet not removed. Removing duplicates is not necessarily helpful in RNA-seq data, as they can still come from different molecules, even if they look identical (https://www.biostars.org/p/55648/). You could any mark duplicates with Picard, and then check the % of duplicate reads and if it is too high for one sample, investigate it further.
