### ISSUE TITLE
Can't generate theta.h5 when running aberrantSplicing module

### ISSUE THREAD

**Issue by huangk3** [gagneurlab/drop#176]
FYI, I attached a copy of the log file. The pipeline was unable to generate the 'theta.h5' file

The pipeline was interrupted before due to a missing dependency package, so it starts directly from rule 'AberrantSplicing_pipeline_Counting_02_psi_value_calculation_FraseR_R'. Could you please take a look to see why the theta.h5 can't be produced? Below is a list of files that had been generated before the pipeline crashed:

processed_data/aberrant_splicing/datasets/savedObjects/raw-covid19$ ls
counting.done
delta_psi3.h5
delta_psi5.h5
delta_psiSite.h5
fds-object.RDS
nonSplitCounts
psi3.h5
psi5.h5
psiSite.h5
rawCountsJ.h5
rawCountsSS.h5
rawOtherCounts_psi3.h5
rawOtherCounts_psi5.h5
rawOtherCounts_psiSite.h5
splitCounts

Thank you

 
[aberrantSplicing.log](https://github.com/gagneurlab/drop/files/6051834/aberrantSplicing.log)

**Comment by c-mertes** [comment]
Could it be that you switched FRASER versions in between? As I can see you have files `psiSite.h5` but not `theta.h5`. I changed the names in this version bump: https://github.com/c-mertes/FRASER/releases/tag/1.2.0 

Updating FRASER and rerunning the count merging part should do the trick.
```
# run inside your R session
BiocManager::install("c-mertes/FRASER")

# run on your command line remove the -n if you are happy with the execution
# replace the group_name acordingly. I saw you have `covid19` in the example. 
snakemake <our runtime options> -n -f aberrantSplicing `pwd`/Output/processed_data/aberrant_splicing/datasets/savedObjects/raw-<group_name>/rawCountsSS.h5
```

This should trigger to rerun the pipeline from where the data gets merged from the counting.

**Comment by huangk3** [comment]
Thanks, @c-mertes. The FRASER update works and fixed the theta.h5 issue, but the pipeline failed in rule AberrantSplicing_pipeline_Counting_03_filter_expression_FraseR_R. A copy of the log file is attached. The error message says "Error in filterExpression(object, minExpressionInOneSample = minExpressionInOneSample,  :
  could not find symbol "object" in environment of the generic function". Any hints on where it comes from? 
[aberrantSplicing.03.log](https://github.com/gagneurlab/drop/files/6062912/aberrantSplicing.03.log)

**Comment by c-mertes** [comment]
As you had also an old `FRASER` version installed, the error looks like you have also an outdated `OUTRIDER` version. 

Can you please post the output of the two commands. This helps us to track down the underlying problem. 

```
R -e "library(FRASER); library(OUTRIDER); sessionInfo()"
drop --version
```

To fix the problem you probably should update your R libraries, especially `OUTRIDER`, by running:

```
 R -e "BiocManager::install('gagneurlab/OUTRIDER', upgrade=TRUE, ask=FALSE)"
```

**Comment by huangk3** [comment]
Thanks, @c-mertes That did the trick. I checked the .libPaths() and found that there are 2 library paths and somehow I installed FRASER and OUTRIDER in both of them. The version in the default library is outdated. The pipeline works great after I removed the default library path.
