### ISSUE TITLE
Sample Annotation File

### ISSUE THREAD

**Issue by Phillip-a-richmond** [gagneurlab/drop#178]
Hello,

I'm a bit confused on how to create the sample annotation file, and it's unclear from the wiki.

I have 4 sample bam files:
Proband, Father, Mother, HealthyControl

I obviously need to utilize additional samples for controls. I can do this by using the hg19 files you provide from Zenodo for blood: geneCounts.tsv.gz  sampleAnnotation.tsv  spliceSiteOverlapCounts.tsv.gz  splitCounts.tsv.gz

If I want to run Fraser, Outrider and MAE, what would my annotation.tsv look like? 

Something like this attached tsv?

[DH1414_SampleAnnotation.txt](https://github.com/gagneurlab/drop/files/6207778/DH1414_SampleAnnotation.txt)

Is this the recommended way to run the tool? Or should I instead pull the bam files for each control sample onto my system and refer to the bam files directly? I know that I don't add a DNA VCF to the samples, will this prevent it from running the MAE?

Thanks!
Phil

**Comment by vyepez88** [comment]
Hello,

- Sorry to hear that the wiki is unclear, I'll expand the explanations.
- We modified the way the external split counts are working, so unfortunately the Blood samples are not compatible with DROP currently. We will update them soon. It would be great if you could pull the bam files from the controls for now and refer to them directly. I'll let you know once this is fixed.
- Your sample annotation file looks good, just the following compulsory columns are missing: PAIRED_END, STRAND, COUNT_MODE, COUNT_OVERLAPS. Have a look at Box 3 of our manuscript: https://www.rdcu.be/cdMmF
- If you want to run MAE, the DNA_ID and DNA_VCF_FILE columns are needed to run MAE.
Good luck with your analysis!

Vicente
