### ISSUE TITLE
Installation error by conda

### ISSUE THREAD

**Issue by unique379r** [gagneurlab/drop#180]
Hi
I am trying to install the tool by conda but seems it has some error due to broken link of downloadable data.
```
==> script messages <==
<None>
==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum b5374ca4c7ab353baea9dc2f39a96ebf:
https://bioconductor.org/packages/3.12/data/annotation/src/contrib/GenomeInfoDbData_1.2.4.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.4.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.4_src_all.tar.gz
```

I checked, last two links are indeed broken therefore, post-link.sh script was not able to fetch the files.
Can you please fix it ?

Thanks
Rupesh Kesharwani

**Comment by nickhsmith** [comment]
Unfortunately, we have been unable to replicate your issue. Are you experiencing this issue on a fresh install (using `conda create -n drop_env -c conda-forge -c bioconda drop` to create a new conda_env named drop_env)?

Looking specifically at this package `genomeinfodbdata` there does seem to be some problem with the galaxy project link not including the most recent version of the package (there seem to be version differences between [galaxy-1.2.2](https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/) and [bioconductor-1.2.4](https://bioconductor.org/packages/release/data/annotation/html/GenomeInfoDbData.html))

If the fresh install isn't working, maybe it's possible to install this package separately using their bioconductor install instructions. It would be helpful if you could outline exactly the steps you are taking to install drop. Namely the commands you are running, the operating system, python versions, R versions, etc. All of that would be a great help in getting this solved quickly.

**Comment by unique379r** [comment]
Hi,
Thanks for your reply. I tried again and installed it correctly. It worked with demo at-least, I hope, it gonna work fine with real analysis as well. By the way, if "genomeinfodbdata" does have some problem , then how it resolved itself?

```
OS Linux: CentOS release 6.7 (Final)

conda 4.10.0

conda create -n drop python=3.7.7

conda activate drop

which python

.../Apps/envs/drop/bin/python

python --version

Python 3.7.7

conda install -c conda-forge -c bioconda drop

```

**Comment by vyepez88** [comment]
Great to hear that the installation worked. 
Maybe it was something with the latest version of the `genomeInfoDbData` package that had a bug and Bioconductor fixed it right away. Let us know if it worked with real data.

**Comment by nickhsmith** [comment]
Since this problem has seemingly resolved itself, I'm closing the issue. Please let us know if you have any problems going forward
