### ISSUE TITLE
Error running AS with GRCh37

### ISSUE THREAD

**Issue by marcDabad** [gagneurlab/drop#183]
Hi, 

Trying to run AS, I get this error:
 don't know where to find assembly report for GCF_000001405.25

This looks as an R package error. 

I google-ed for it and I found it's and error that can be fixed changing style from ncbi to ensemble.

**Comment by vyepez88** [comment]
Hi
Please have a look at the `genome` parameter in the config file and adjust it to match your chr style
https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#global-parameters
Another option is to run the pipeline with: `keepNonStandardChrs: false` in the `aberrantSplicing` dictionary, which will get rid of non-standard chromosomes.

**Comment by marcDabad** [comment]
Thanks! It was my fault. 

I saw hg19 or hg38 in config.yaml commentary but I didn't understand properly the documentation. 
I put hg19 instead of hs37d5.

Thanks.
