### ISSUE TITLE
Error running demo project

### ISSUE THREAD

**Issue by misago162** [gagneurlab/drop#19]
Hello

I'm installing the drop software in a singularity container with Centos7. I have already installed all the dependencies and the drop software as is explained in the Readme file. When I execute the drop init command, everything works fine but when I run the demo command it seems that something is not working fine. Can you help me, please? Thanks:

Singularity> cd drop-test/
Singularity> drop init
init...done
Singularity> drop demo
overwriting module scripts
resource/dna_vcf/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.exome.vcf.gz
resource/rna_bam/HG00176.4.M_120208_2_chr21.bam_trunc.bam
resource/qc_vcf_1000G.vcf.gz
resource/rna_bam/HG00103.4.M_120208_3_chr21.bam.bai
resource/qc_vcf_1000G.vcf.gz.tbi
resource/rna_bam/HG00116.2.M_120131_1_chr21.bam
resource/rna_bam/HG00149.1.M_111124_6_chr21.bam
resource/rna_bam/HG00132.2.M_111215_4_chr21.bam
resource/dna_vcf/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.exome.vcf.gz.tbi
resource/rna_bam/HG00126.1.M_111124_8_chr21.bam_trunc.bam
resource/rna_bam/HG00150.4.M_120208_7_chr21.bam_trunc.bam
resource/sample_annotation_relative.tsv
resource/rna_bam/HG00111.2.M_111215_4_chr21.bam_trunc.bam
resource/rna_bam/HG00106.4.M_120208_5_chr21.bam_trunc.bam
resource/rna_bam/HG00096.1.M_111124_6_chr21.bam_trunc.bam
resource/rna_bam/HG00126.1.M_111124_8_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00150.4.M_120208_7_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00116.2.M_120131_1_chr21.bam.bai
resource/rna_bam/HG00149.1.M_111124_6_chr21.bam.bai
resource/rna_bam/HG00176.4.M_120208_2_chr21.bam_trunc.bam.bai
resource/chr21.fa.gz
resource/rna_bam/HG00106.4.M_120208_5_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00176.4.M_120208_2_chr21.bam
resource/config.yaml
resource/rna_bam/HG00111.2.M_111215_4_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00126.1.M_111124_8_chr21.bam.bai
resource/rna_bam/HG00111.2.M_111215_4_chr21.bam
resource/rna_bam/HG00103.4.M_120208_3_chr21.bam
resource/rna_bam/HG00126.1.M_111124_8_chr21.bam
resource/rna_bam/HG00132.2.M_111215_4_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00116.2.M_120131_1_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00176.4.M_120208_2_chr21.bam.bai
resource/rna_bam/HG00096.1.M_111124_6_chr21.bam_trunc.bam.bai
resource/hpo_genes.tsv.gz
resource/rna_bam/
resource/rna_bam/HG00096.1.M_111124_6_chr21.bam.bai
resource/rna_bam/HG00106.4.M_120208_5_chr21.bam.bai
resource/rna_bam/HG00150.4.M_120208_7_chr21.bam.bai
resource/gencode_annotation_trunc.gtf
resource/rna_bam/HG00111.2.M_111215_4_chr21.bam.bai
resource/dna_vcf/
resource/rna_bam/HG00149.1.M_111124_6_chr21.bam_trunc.bam
resource/rna_bam/HG00132.2.M_111215_4_chr21.bam_trunc.bam
resource/rna_bam/HG00132.2.M_111215_4_chr21.bam.bai
resource/
resource/config_relative.yaml
resource/rna_bam/HG00103.4.M_120208_3_chr21.bam_trunc.bam
resource/rna_bam/HG00096.1.M_111124_6_chr21.bam
resource/rna_bam/HG00103.4.M_120208_3_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00150.4.M_120208_7_chr21.bam
resource/rna_bam/HG00149.1.M_111124_6_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00106.4.M_120208_5_chr21.bam
resource/fix_sample_anno.py
resource/rna_bam/HG00116.2.M_120131_1_chr21.bam_trunc.bam
Traceback (most recent call last):
  File "/usr/local/bin/drop", line 11, in <module>
    load_entry_point('drop==0.9.0', 'console_scripts', 'drop')()
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drop/cli.py", line 85, in demo
    dict_[key] = str(pathlib.Path(dict_[key]).resolve())
  File "/usr/lib64/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib64/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Singularity>

**Comment by mumichae** [comment]
Hi,

thanks for reporting the issue. Try removing all files that  have been generated in the project directory, skip `drop init` and call `drop demo directly`.

The error appears because `drop init` creates an empty `config.yaml` but `drop demo` does not overwrite the `config.yaml` file if it already exists. However this is needed in order to adapt the paths to the demo data. We will probably add a more verbose warning/error message soon.

Best,
Michaela

**Comment by misago162** [comment]
Hi Michaela

Thanks a lot for your answer. I have tried what you suggest me but I'm still receiving the same error and the config.yaml file is not empty:

 
Singularity> mkdir drop-demo
Singularity> cd drop-demo
Singularity> drop demo
resource/dna_vcf/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.exome.vcf.gz
resource/rna_bam/HG00176.4.M_120208_2_chr21.bam_trunc.bam
resource/qc_vcf_1000G.vcf.gz
resource/rna_bam/HG00103.4.M_120208_3_chr21.bam.bai
resource/qc_vcf_1000G.vcf.gz.tbi
resource/rna_bam/HG00116.2.M_120131_1_chr21.bam
resource/rna_bam/HG00149.1.M_111124_6_chr21.bam
resource/rna_bam/HG00132.2.M_111215_4_chr21.bam
resource/dna_vcf/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.exome.vcf.gz.tbi
resource/rna_bam/HG00126.1.M_111124_8_chr21.bam_trunc.bam
resource/rna_bam/HG00150.4.M_120208_7_chr21.bam_trunc.bam
resource/sample_annotation_relative.tsv
resource/rna_bam/HG00111.2.M_111215_4_chr21.bam_trunc.bam
resource/rna_bam/HG00106.4.M_120208_5_chr21.bam_trunc.bam
resource/rna_bam/HG00096.1.M_111124_6_chr21.bam_trunc.bam
resource/rna_bam/HG00126.1.M_111124_8_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00150.4.M_120208_7_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00116.2.M_120131_1_chr21.bam.bai
resource/rna_bam/HG00149.1.M_111124_6_chr21.bam.bai
resource/rna_bam/HG00176.4.M_120208_2_chr21.bam_trunc.bam.bai
resource/chr21.fa.gz
resource/rna_bam/HG00106.4.M_120208_5_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00176.4.M_120208_2_chr21.bam
resource/config.yaml
resource/rna_bam/HG00111.2.M_111215_4_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00126.1.M_111124_8_chr21.bam.bai
resource/rna_bam/HG00111.2.M_111215_4_chr21.bam
resource/rna_bam/HG00103.4.M_120208_3_chr21.bam
resource/rna_bam/HG00126.1.M_111124_8_chr21.bam
resource/rna_bam/HG00132.2.M_111215_4_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00116.2.M_120131_1_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00176.4.M_120208_2_chr21.bam.bai
resource/rna_bam/HG00096.1.M_111124_6_chr21.bam_trunc.bam.bai
resource/hpo_genes.tsv.gz
resource/rna_bam/
resource/rna_bam/HG00096.1.M_111124_6_chr21.bam.bai
resource/rna_bam/HG00106.4.M_120208_5_chr21.bam.bai
resource/rna_bam/HG00150.4.M_120208_7_chr21.bam.bai
resource/gencode_annotation_trunc.gtf
resource/rna_bam/HG00111.2.M_111215_4_chr21.bam.bai
resource/dna_vcf/
resource/rna_bam/HG00149.1.M_111124_6_chr21.bam_trunc.bam
resource/rna_bam/HG00132.2.M_111215_4_chr21.bam_trunc.bam
resource/rna_bam/HG00132.2.M_111215_4_chr21.bam.bai
resource/
resource/config_relative.yaml
resource/rna_bam/HG00103.4.M_120208_3_chr21.bam_trunc.bam
resource/rna_bam/HG00096.1.M_111124_6_chr21.bam
resource/rna_bam/HG00103.4.M_120208_3_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00150.4.M_120208_7_chr21.bam
resource/rna_bam/HG00149.1.M_111124_6_chr21.bam_trunc.bam.bai
resource/rna_bam/HG00106.4.M_120208_5_chr21.bam
resource/fix_sample_anno.py
resource/rna_bam/HG00116.2.M_120131_1_chr21.bam_trunc.bam
Traceback (most recent call last):
  File "/usr/local/bin/drop", line 11, in <module>
    load_entry_point('drop==0.9.0', 'console_scripts', 'drop')()
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drop/cli.py", line 85, in demo
    dict_[key] = str(pathlib.Path(dict_[key]).resolve())
  File "/usr/lib64/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib64/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Singularity> cat config.yaml 
projectTitle: Detection of RNA Outlier Pipeline
root:             # root directory of all intermediate output
htmlOutputPath:   # path for HTML rendered reports

# settings for wBuild - do not change
indexWithFolderName: true
fileRegex: .*\.R

sampleAnnotation: # path to sample annotation (see documenation on how to create it)

geneAnnotation:
    # multiple annotations with custom names are possible
    # <annotation_name> : <path to gencode v29 annotation>
    v29:  /path/to/gencode29.gtf.gz # example

geneAssembly: hg19  # either hg19 or hg38

aberrantExpression:
    groups: 
        - group1
        - group2
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 0.05
    zscoreCutoff: 0

aberrantSplicing:
    groups:
        - group1
    recount: false
    longRead: false
    filter: true
    minExpressionInOneSample: 20
    minDeltaPsi: 0
    correction: PCA
    padjCutoff: 0.05
    zScoreCutoff: 0
    deltaPsiCutoff: 0.3

mae:
    groups:
        - group1
        - group2
        - group3
    genome:       # path to genome sequence in fasta format
    gatkIgnoreHeaderCheck: true
    padjCutoff: .05
    allelicRatioCutoff: 0.8
    addAF: false
    maxAF: .001
    # VCF-BAM matching
    qcVcf:        # path to common variant file e.g. qc_vcf_1000G.vcf.gz
    qcGroup: mae

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools

Singularity>

**Comment by mumichae** [comment]
Hi,

are you sure that you have removed the config file before rerunning `drop demo`? Drop doesn't overwrite this file if it already exists. The problem with this file is that file paths are missing from it. Drop demo should download a different config file that contains file paths.

Best,
Michaela

**Comment by misago162** [comment]
Hi Michaela
The directory where I tried to create the demo project was empty, I mean, the config file doesn't exist in this directory. If the problem is a missing path, how can I know what is the path? As I'm working using an singularity image, I will check if from this singularity image I can reach this path. Thanks a lot for you help.

**Comment by mumichae** [comment]
Hey,
Hm, this seems strange. I couldn't reproduce the error. `drop demo` should copy a different config file from what you have pasted here. It should have relative file paths instead of comments. Then drop infers the absolute paths depending on your system.
Could it be that you are using an older version of drop where this feature hadn't been implemented yet? Could you paste the contents of `.travis.yml` within the drop repository that you pulled from github?
Best,
Michaela

**Comment by misago162** [comment]
Hi. I have installed the drop using pip:

pip install git+https://github.com/gagneurlab/drop.git

i mean, I didn't pull drop from github. The release of drop is 0.9.0.

**Comment by misago162** [comment]
Hi, one possibility about why I have this problem can be because I using a singularity container. Can you give me some advice to check if the problem is that? I mean, check some file content, execute the drop in another way and check the output, ... Thanks

**Comment by mumichae** [comment]
Hey,
Sorry for not answering, things have been a bit stressful lately.
When did you install drop? Could it be that it was some time ago? That would explain why the wrong config file gets copied. Have you tried reinstalling it?

**Comment by misago162** [comment]
Hi. sorry to bother you again with this issue. I have uninstall and reinstall drop, but cloning the repository;:

pip uninstall drop
git clone https://github.com/gagneurlab/drop.git --recurse-submodules
cd drop
pip install .
cd ..
mkdir drop-demo
drop demo

But I still have the same error. The content of the .travis.yml file within the drop repository is:

Singularity> cat .travis.yml 
language: python
sudo: required
dist: xenial

cache:
  - directories:
    - $HOME/R/Library
    - /usr/bin/R
    - $HOME/miniconda
    - $HOME/htslib
    - $HOME/bcftools

env:
  global:
    - DROP_DIR=$(pwd)
    - PROJECT_DIR="$HOME/project"
    - MINICONDA_DIR="$HOME/miniconda"
    - CONDA_SCRIPT="$MINICONDA_DIR/etc/profile.d/conda.sh"
    - R_LIBS_USER="$HOME/R/Library"
    - TAR="/bin/tar"

python:
  - "3.6.7"

addons:
  apt:
    packages:
      - r-base
      - libxml2-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libblas-dev
      - liblapack-dev
      - gfortran
      - graphviz
      - pandoc
      - tabix
    sources:
      - sourceline: 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xe298a3a825c0d65dfd57cbb651716619e084dab9'
    update: true
  
install:
  - cd $DROP_DIR
  - R -e "if ('FRASER' %in% rownames(installed.packages())) remove.packages('FRASER')"
  - R -e "install.packages('BiocManager'); BiocManager::install('remotes'); BiocManager::install('gagneurlab/FRASER', ref = 'R3.6')"
#  - R -e "if ('tMAE' %in% rownames(installed.packages())) remove.packages('tMAE')"
  - Rscript travis/installRPackages.R drop/requirementsR.txt
  - bash travis/install_bcftools.sh
  - export PATH="$HOME/bcftools:$PATH"
  - bcftools --version
  - bash travis/install_conda.sh
  - source $CONDA_SCRIPT
  - conda activate drop_env
  - pip install .

before_script:
  - mkdir -p $PROJECT_DIR
  - cd $PROJECT_DIR
  - drop demo

script:
 - cd $PROJECT_DIR
 - snakemake -n
 - snakemake aberrantExpression --cores 2
 - snakemake aberrantSplicing --cores 2
 - snakemake mae --cores 2
 - snakemake --cores 2

Singularity> 

Thanks

**Comment by mumichae** [comment]
Hi,
I think I might have identified the problem. Could you tell me which command you would use to run samtools? It could be that you encounter an error when creating the fasta index, possibly because samtools might not be available under `samtools`.

```
#!/bin/bash
set -e

# get data
wget -Nc "https://i12g-gagneurweb.informatik.tu-muenchen.de/public/paper/drop_analysis/resource.tar.gz"
tar -zxvf resource.tar.gz
rm -rf Data
mv resource Data

# prepare data
cd Data
python fix_sample_anno.py
gunzip chr21.fa.gz
samtools faidx chr21.fa

# copy config
cp config_relative.yaml ../config.yaml
```

I will look into it soonish, but for a quick fix you can either make sure that you can access samtools with the `samtools` command or you can just hardcode the path to your samtools command into the `drop/download_data.sh` file and reinstall drop before trying again.

Hope this helps,
Michaela

**Comment by misago162** [comment]
Hi,

Although I have found the problem, now I have another error with snakemake:

I'm using a CentOS-7. This version of centos still have Python-2.7. So, If in this operative system you execute only 'python', you are working with python-2.7. To work with python-3 you have to run the command python3:

Singularity> cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
Singularity> python --version
Python 2.7.5
Singularity> python3 --version
Python 3.6.8
Singularity> 

So, In the script drop/download_data.sh, to be sure that I'm executing python-3 (that is the python where Drop in installed), I have had to modify the line:

python fix_sample_anno.py

by:

python3 fix_sample_anno.py

Then, reinstall Drop and then the command 'drop demo' woks fine.

The new error is with snamake:

Singularity> snakemake -n
check for missing R packages
WARNING: Less than 30 IDs in DROP_GROUP outrider
WARNING: Less than 30 IDs in DROP_GROUP fraser
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
Executing subworkflow AE.
Error: Snakefile "/root/drop-demo/.drop/modules/aberrant-expression-pipeline/Snakefile" not found.
Singularity>

The content of the .drop directory in the demo project directory is:

Singularity> ls -l .drop
total 8
drwxr-xr-x 3 root root 4096 mar 26 17:05 modules
drwxr-xr-x 5 root root 4096 mar 26 17:07 tmp
Singularity> ls -l .drop/modules/
total 4
drwxr-xr-x 2 root root 4096 mar 26 17:05 helpers
Singularity> 

Any idea? Thanks a lot for your time.

**Comment by mumichae** [comment]
Hey,
I'm glad to see that this was the issue. I will keep this thread  open until we have implemented a fix.
Meanwhile I have moved your next question into a separate [issue](https://github.com/gagneurlab/drop/issues/21)

**Comment by misago162** [comment]
OK, I close the issue. Thanks a lot for your help.

**Comment by misago162** [comment]
The python system command has to execute python3
