### ISSUE TITLE
In ASEReadCounter.sh there is a small problem

### ISSUE THREAD

**Issue by tlz4320** [gagneurlab/drop#196]
In script ASEReadCounter.sh bam_chr and vcf_chr are extracted from vcf file and bam file. And follow that, "comm" command is called to get the overlapped chr, but comm need two input have been sorted. Therefore, for easily and robustly use, bam_chr and vcf_chr should add "sort" to extraction procedure.

**Comment by mumichae** [comment]
Thanks for noticing this. However, the input of the `comm` command should be sorted, according to the command call later on in the script.

```sh
chr_subset=$(comm -12 <(cut -f1 -d" " ${canonical} | sort -u) <(echo "${vcf_chr}" | sort -u))
chr_subset=$(comm -12 <(echo "${bam_chr}" | sort -u) <(echo "${chr_subset}") | uniq)
```

Here, `canonical` is the list of chromosomes read from a fixed file in the repository.

But I agree, it is nicer to have them sorted beforehand.

**Comment by tlz4320** [comment]
Sorry, I didn't explain it clearly. Maybe png below can explain that.
I create a test.txt file which have 4 lines, with 1 3 2 4.
![screen_cut2](https://user-images.githubusercontent.com/24791715/119602195-3952f880-be1d-11eb-90e3-1a535f2272c6.png)
First, use cat to print file and transfer it to sort with pipeline. It gets a right result.
![screen_cut1](https://user-images.githubusercontent.com/24791715/119602245-538cd680-be1d-11eb-8d32-dc01b31c24b2.png)
However, if you put data to a variate “a”, and echo that to sort, which will be wrong.
You can man echo, which will explain what I mean.
Therefore, the sort in your code is useless, you should sort it when you get the chr list from vcffile and bamfile, just like this.
```
bam_chr=$($samtools idxstats ${bam_file} | grep -vP "\t0\t0" | cut -f1 | sort -u) # only chr with coverage
vcf_chr=$($bcftools view ${vcf_file} | cut -f1 | grep -v '#' | sort -u)
```

**Comment by tlz4320** [comment]
In fact, you have use xargs in your code which I download from conda several months ago( It seems different with code in github now). But in bam_chr, you haven't used that. Another way to fix this is add xargs to "echo "${bam_chr}" | xargs -n1 |sort -u". I don't know whether you trust the default order of bam_chr is sorted. Howerver, in my sorted bam file, chr list order is just like this: chr1 chr2 chr3... but not chr1 chr10 chr11.

**Comment by tlz4320** [comment]
I found my problem, I used the old version of DROP. Your new code have sorted it.

**Comment by vyepez88** [comment]
yes, we realized that a couple of versions ago, many thanks in any case for your suggestions and desire to improve DROP.
