### ISSUE TITLE
Error in running AberrantExpression module

### ISSUE THREAD

**Issue by bijuissacch224610** [gagneurlab/drop#197]
Hi DROP Team
 
I am trying to run the DROP package on a dataset from 1000G project. However the run exits with an error in the middle. I am not sure what the problem is. Could you please assist? I have attached the error/log files with this post for guidance
 
FYI: The run for Aberrant Expression runs successfully on the demo dataset of 10 samples provided by DROP
[aberrant.log.txt](https://github.com/gagneurlab/drop/files/6524232/aberrant.log.txt)
[aberrant.err.txt](https://github.com/gagneurlab/drop/files/6524233/aberrant.err.txt)

**Comment by nickhsmith** [comment]
Thanks for using DROP, and sorry about your problem. It's a long weekend
for us in Germany, but I promise we will look into this next week.

**Comment by vyepez88** [comment]
Hi, it seems that there was an error in the rule to create the graph. Can you make sure you have write permissions on the path `/lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/NewRun/dropOut/html/` ?
In any case, can you try rerunning the pipeline with `-k`, e.g. `snakemake -k aberrantExpression --cores X`

**Comment by bijuissacch224610** [comment]
Hi Vicente

Thanks. I think that was the issue. I was creating the output folder myself instead of allowing the package to create while executing. Probably created permissions issue.

Thanks for quick reply. The pipeline is running now. I will let you know if there are additional issues.

Thanks
-Biju Issac

Lead, Field Applications
Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: Vicente Yepez ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Saturday, May 22, 2021 at 5:44 AM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Author ***@***.***>
Subject: Re: [gagneurlab/drop] Error in running AberrantExpression module (#197) [EXTERNAL]

* External Email - Caution *



Hi, it seems that there was an error in the rule to create the graph. Can you make sure you have write permissions on the path /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/NewRun/dropOut/html/ ?
In any case, can you try rerunning the pipeline with -k, e.g. snakemake -k aberrantExpression --cores X

**Comment by vyepez88** [comment]
great to hear that!

**Comment by bijuissacch224610** [comment]
HI Vicente

I had another issue pop up during the MAE module run. Can you see the error message below and suggest what the resolution might be? FYI, the job has not stopped, just this message has come in the middle of run.

######


[Tue May 25 13:13:38 2021]

rule MonoallelicExpression_pipeline_MAE_deseq_mae_R:

    input: /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/MAE/dropOut/processed_data/mae/allelic_counts/NA20772--NA20772.csv.gz, Scripts/MonoallelicExpression/pipeline/MAE/deseq_mae.R

    output: /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/MAE/dropOut/processed_results/mae/samples/NA20772--NA20772_res.Rds

    log: /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/MAE/.drop/tmp/MAE/deseq/NA20772--NA20772.Rds

    jobid: 175

    wildcards: vcf=NA20772, rna=NA20772



Using GATK jar /programs/biogrids/x86_64-linux/drop/1.0.3/share/gatk4-4.2.0.0-1/gatk-package-4.2.0.0-local.jar

Running:

    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /programs/biogrids/x86_64-linux/drop/1.0.3/share/gatk4-4.2.0.0-1/gatk-package-4.2.0.0-local.jar ASEReadCounter -R /reference_databases/1000G_Drop_data/STAR/hg37/hg19_STAR_GenomeAssembly.fa -I /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/rna-seq/alignment/NA20765Aligned.sortedByCoord.out.bam -V /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/MAE/dropOut/processed_data/mae/snvs/NA20765--NA20765.vcf.gz -L chr5 --verbosity ERROR --QUIET true --disable-sequence-dictionary-validation True

Started with deseq

Error in DESeqDataSet(se, design = design, ignoreRank) :

  counts matrix should be numeric, currently it has mode: logical

Calls: DESeq4MAE ... deseq_for_allele_specific_expression -> DESeqDataSetFromMatrix -> DESeqDataSet

Execution halted

Started with deseq

[Tue May 25 13:14:00 2021]

Error in rule MonoallelicExpression_pipeline_MAE_deseq_mae_R:

    jobid: 175

    output: /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/MAE/dropOut/processed_results/mae/samples/NA20772--NA20772_res.Rds

    log: /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/MAE/.drop/tmp/MAE/deseq/NA20772--NA20772.Rds (check log file(s) for error message)



RuleException:

CalledProcessError in line 284 of /tmp/tmp3_dabyqc:

Command 'set -euo pipefail;  Rscript --vanilla /lab-share/RC-Data-Science-e2/Public/Biju/E-GEUVADIS/MAE/.snakemake/scripts/tmpsqcnm_qh.deseq_mae.R' returned non-zero exit status 1.

  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2330, in run_wrapper

  File "/tmp/tmp3_dabyqc", line 284, in __rule_MonoallelicExpression_pipeline_MAE_deseq_mae_R

  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 569, in _callback

  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/concurrent/futures/thread.py", line 52, in run

  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 555, in cached_or_run

  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2362, in run_wrapper

Job failed, going on with independent jobs.

Select jobs to execute...


Thanks
-Biju Issac

Lead, Field Applications
Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: Vicente Yepez ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Monday, May 24, 2021 at 1:05 PM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Author ***@***.***>
Subject: Re: [gagneurlab/drop] Error in running AberrantExpression module (#197) [EXTERNAL]

* External Email - Caution *



great to hear that!
