### ISSUE TITLE
Error in rule AberrantSplicing_pipeline_FRASER_06_calculation_stats_AE_FraseR_R

### ISSUE THREAD

**Issue by bijuissacch224610** [gagneurlab/drop#199]
Hi

The AS module stops with error are finishing 96% of steps. I have attached the error log file. I am not sure what the problem is

[splicing4.err.txt](https://github.com/gagneurlab/drop/files/6548987/splicing4.err.txt)
[splicing.err.txt](https://github.com/gagneurlab/drop/files/6548988/splicing.err.txt)

**Comment by nickhsmith** [comment]
We are sorry for the problem. Unfortunately, the dependency graphs that we build are very sensitive to warning/output messages from the R installation steps. We've made a quick fix which you can install within your working environment and rerun snakemake by running the following commands:
```
pip install git+https://github.com/gagneurlab/drop.git@dep_graph_fix
snakemake -j10 -k
```
The other problem seems to be a problem with the parallelization, it seems that it originally timed out with 10 cores (but was running), and then with 20 cores it seems to be failing as R can struggle with resource management. Could you please let us know if you have the same error with 10 cores or less (as listed above)?

if it persists, please let us know. Thanks in advance

**Comment by mumichae** [comment]
@bijuissacch224610 Are you still experiencing this issue? Otherwise this issue can be closed.

**Comment by bijuissacch224610** [comment]
Has the update happened? Please keep the ticket open for 1 week while I verify

Thanks
-Biju Issac

Lead, Field Applications
Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: Michaela Mueller ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Monday, June 7, 2021 at 12:16 PM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Mention ***@***.***>
Subject: Re: [gagneurlab/drop] Error in rule AberrantSplicing_pipeline_FRASER_06_calculation_stats_AE_FraseR_R (#199) [EXTERNAL]

* External Email - Caution *



@bijuissacch224610<https://urldefense.com/v3/__https:/github.com/bijuissacch224610__;!!NZvER7FxgEiBAiR_!7acDMFIMx85ewNIYZFC625wNZWPwpCvIAoJVfOXLNheqb2TSLAM8uOz7mwUdJT-4rswHLYbMnys$> Are you still experiencing this issue? Otherwise this issue can be closed.

**Comment by mumichae** [comment]
If you are referring to the dependency graph issue, the changes are already in the `dev` branch.

    pip install git+https://github.com/gagneurlab/drop.git@dev

Alternatively you can always use the `-k` option to prevent errors from stopping other independent jobs.

**Comment by bijuissacch224610** [comment]
Thanks
-Biju Issac

Lead, Field Applications
Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: Michaela Mueller ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Monday, June 7, 2021 at 12:27 PM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Mention ***@***.***>
Subject: Re: [gagneurlab/drop] Error in rule AberrantSplicing_pipeline_FRASER_06_calculation_stats_AE_FraseR_R (#199) [EXTERNAL]

* External Email - Caution *



If you are referring to the dependency graph issue, the changes are already in the dev branch.

pip install ***@***.***

Alternatively you can always use the -k option to prevent errors from stopping other independent jobs.

**Comment by james-vincent** [comment]
Is this patch supposed to be applied in the conda installed environment?

 $ ./pip install git+https://github.com/gagneurlab/drop.git@dep_graph_fix
Collecting git+https://github.com/gagneurlab/drop.git@dep_graph_fix
  Cloning https://github.com/gagneurlab/drop.git (to revision dep_graph_fix) to /tmp/pip-req-build-renyhcwb
  Running command git clone -q https://github.com/gagneurlab/drop.git /tmp/pip-req-build-renyhcwb
  WARNING: Did not find branch or tag 'dep_graph_fix', assuming revision or ref.
  Running command git checkout -q dep_graph_fix
  error: pathspec 'dep_graph_fix' did not match any file(s) known to git.

**Comment by bijuissacch224610** [comment]
To be truthful, I have no idea on debugging this. Let me know if you run into issues, I can ask the developers to provide some guidance

Thanks
-Biju Issac

Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: james-vincent ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Thursday, June 10, 2021 at 12:22 PM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Mention ***@***.***>
Subject: Re: [gagneurlab/drop] Error in rule AberrantSplicing_pipeline_FRASER_06_calculation_stats_AE_FraseR_R (#199) [EXTERNAL]

* External Email - Caution *



Is this patch supposed to be applied in the conda installed environment?

$ ./pip install ***@***.******@***.***_graph_fix__;!!NZvER7FxgEiBAiR_!_xzwtNVUjFXug0JIx1LR2grg-jvNtP9URVs7hwEyp4E0_Gcow_4_esaLpqBHpj-Gqz7siUCfie0$>
Collecting ***@***.******@***.***_graph_fix__;!!NZvER7FxgEiBAiR_!_xzwtNVUjFXug0JIx1LR2grg-jvNtP9URVs7hwEyp4E0_Gcow_4_esaLpqBHpj-Gqz7siUCfie0$>
Cloning https://github.com/gagneurlab/drop.git<https://urldefense.com/v3/__https:/github.com/gagneurlab/drop.git__;!!NZvER7FxgEiBAiR_!_xzwtNVUjFXug0JIx1LR2grg-jvNtP9URVs7hwEyp4E0_Gcow_4_esaLpqBHpj-Gqz7sBaUJXf4$> (to revision dep_graph_fix) to /tmp/pip-req-build-renyhcwb
Running command git clone -q https://github.com/gagneurlab/drop.git<https://urldefense.com/v3/__https:/github.com/gagneurlab/drop.git__;!!NZvER7FxgEiBAiR_!_xzwtNVUjFXug0JIx1LR2grg-jvNtP9URVs7hwEyp4E0_Gcow_4_esaLpqBHpj-Gqz7sBaUJXf4$> /tmp/pip-req-build-renyhcwb
WARNING: Did not find branch or tag 'dep_graph_fix', assuming revision or ref.
Running command git checkout -q dep_graph_fix
error: pathspec 'dep_graph_fix' did not match any file(s) known to git.

**Comment by james-vincent** [comment]
I thought I was replying to the devs in the issue itself. Got the wrong one - sorry.


The problem is that the only install method described is a conda install, which we use (actually mamba). But the fix is supplied as a patch to the code in the git repo. They should push it to a new version and release.

Jim


James Vincent, PhD
Bioinformatics Software Curator
Dept. of BCMP, Harvard Medical School

**Comment by nickhsmith** [comment]
Sorry for the miscommunication. We have incorporated this fix into the dev branch and removed dep_graph_fix. If you run this instead you should install the working version:
`./pip install git+https://github.com/gagneurlab/drop.git@dev`

We had a meeting today about the life cycle of our revisions, and will be trying to work to get the conda version to match bug fixes in a faster and more consistent manner.

> Is this patch supposed to be applied in the conda installed environment?
> 
> $ ./pip install git+https://github.com/gagneurlab/drop.git@dep_graph_fix
> Collecting git+https://github.com/gagneurlab/drop.git@dep_graph_fix
> Cloning https://github.com/gagneurlab/drop.git (to revision dep_graph_fix) to /tmp/pip-req-build-renyhcwb
> Running command git clone -q https://github.com/gagneurlab/drop.git /tmp/pip-req-build-renyhcwb
> WARNING: Did not find branch or tag 'dep_graph_fix', assuming revision or ref.
> Running command git checkout -q dep_graph_fix
> error: pathspec 'dep_graph_fix' did not match any file(s) known to git.

**Comment by nickhsmith** [comment]
Also we just accepted this change into a new version bump 1.0.5 which should be listed on conda soon.
