### ISSUE TITLE
Error for : missing input file 

### ISSUE THREAD

**Issue by capricy** [gagneurlab/drop#203]
I recently applied DRP pipeline, aberrantExpression module, to a new dataset, but got the following error:

(base) [gn@ai-hpcn137 2021_May_NEMO-NDAS]$ snakemake aberrantExpression --cores 1
WARNING: 1 files missing in samples annotation. Ignoring...
WARNING: Less than 30 IDs in DROP_GROUP NEMO-NDAS
WARNING: Less than 30 IDs in DROP_GROUP NEMO-NDAS
check for missing R packages
Bioconductor version '3.12' is out-of-date; the current release version '3.13'
  is available with R version '4.1'; see https://bioconductor.org/install
Bioconductor version '3.12' is out-of-date; the current release version '3.13'
  is available with R version '4.1'; see https://bioconductor.org/install
Structuring dependencies...
Dependencies file generated at: /tmp/tmpy96a1uqj

Building DAG of jobs...
WorkflowError:
MissingInputException: Missing input files for rule markdown:
AberrantExpression/Counting/v19/Summary_NEMO-NDAS.md
MissingInputException: Missing input files for rule markdown:
Scripts_AberrantExpression_pipeline_Counting_Datasets.md

My annotation file and config file are attached below:

<img width="1138" alt="sample_anno master 2 txt" src="https://user-images.githubusercontent.com/18124356/120011063-e22f5e00-bfab-11eb-8c9b-79fac335df6d.png">
<img width="1053" alt="config yaml" src="https://user-images.githubusercontent.com/18124356/120011077-e52a4e80-bfab-11eb-943d-63ed907f7cf1.png">

Can anyone help me to figure out how to fix it? Thanks a lot

**Comment by nickhsmith** [comment]
It seems like you could be using an outdated version of drop. Could you please run `drop --version` If it's not `drop, version 1.0.4` please run `conda update drop` (assuming you are using conda as a package manager. Or `pip install git+https://github.com/gagneurlab/drop.git` ). And then run `drop update` to get to the newest version.

If that doesn't help solve the issue, please let us know and we will continue to try to help you.

**Comment by capricy** [comment]
Well, it is version 1.0.3. But 1.0.3 works for my other dataset, and so I just don't understand why it got issues for this new dataset.

Beyond updating the version, is there anything I can modify in my files so that the error would be gone? 

Also, here the error is from rule markdown. How do I find this rule? It doesn't seem to be present in any Snakefiles...

Thanks a lot...

**Comment by nickhsmith** [comment]
We are constantly trying to fix and make DROP better. In the most recent update we fixed a bug where the DROP_GROUP was mistakenly ignoring wildcards containing the `-` character. If you change the name of your DROP_GROUP from `NEMO-NDAS` to `NEMO_NDAS` that should solve the issue.

OR you can update DROP to the newest version which doesn't change the underlying analysis, but instead fixes some common bugs, and has improved sample_annotation reading/functionality that would also work.

**Comment by capricy** [comment]
I modified DROP_GROUP as suggested to "NEMO_NDAS" (see below) and the pipeline got started. However, new error occurred at "rule aberrantExpression_dependency":

===========
****Error in rule aberrantExpression_dependency:**
    jobid: 42
    output: /pipelines/DROP/2021_May_NEMO-NDAS/Output-completeRunHPCInstalled/html/aberrant-expression-pipeline_dep.svg
    shell:
        snakemake --nolock --rulegraph /pipelines/DROP/2021_May_NEMO-NDAS/Output-completeRunHPCInstalled/html/aberrant-expression-pipeline_index.html | dot -Tsvg -Grankdir=TB 
> /pipelines/DROP/2021_May_NEMO-NDAS/Output-completeRunHPCInstalled/html/aberrant-expression-pipeline_dep.svg
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Error executing rule aberrantExpression_dependency on cluster (jobid: 42, external: 29099, jobscript: /pipelines/DROP/2021_May_NEMO-NDAS/.snakemake/tmp.e2fnew9s/snakejob.aberr
antExpression_dependency.42.sh). For error details see the cluster log and the log files of the involved rule(s).
==========

Modified annotation file:
<img width="1348" alt="Screen Shot 2021-06-01 at 5 00 04 PM" src="https://user-images.githubusercontent.com/18124356/120390444-b558af00-c2fb-11eb-9567-3c12bfc4dc19.png">


What should I do for this? I saw an issue open for this, but didn't quite follow about what to do

**Comment by mumichae** [comment]
Hi, the dependency graph issues is indeed annoying and we have fixed it recently, so the fix is in the `dev` branch. In order to permanently remove the issue, I'd suggest you update to drop using

    pip install git+https://github.com/gagneurlab/drop.git 

Alternatively, you can call your pipeline with

    snakemake -k -j10

to prevent the error from running the rest of the pipeline. However, that will only go so far as to give you the method runs, but not render all of the HTML output. If you want the complete pipeline to be run, you'd need to update drop.

**Comment by mumichae** [comment]
This should be fixed with DROP 1.0.5
