### ISSUE TITLE
reading error for "paired end information" from the sample annotation table

### ISSUE THREAD

**Issue by capricy** [gagneurlab/drop#204]
Below is my sample annotation table:
<img width="1348" alt="Screen Shot 2021-06-01 at 5 00 04 PM" src="https://user-images.githubusercontent.com/18124356/120570113-5c654580-c3e5-11eb-84e5-f7bff7e6a1b7.png">

Here my samples are all single-ended; however, when the drop pipeline is started, the 'PAIRED_END' information is still "True" (see below)
====
(base) [gn@ai-submit2 2021_May_NEMO-NDAS]$ python
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import Path
>>> import drop
>>> import wbuild
>>> from wbuild.createIndex import createIndexRule, ci
>>> 
>>> configfile: "config.yaml"
>>> 
>>> projectDir = Path.cwd().resolve()
>>> drop.checkDropVersion(projectDir)
>>> _, projectPaths = drop.setupPaths(projectDir)
>>> tmp_dir = projectPaths["tmpDir"]
>>> 
>>> cfg = drop.config.DropConfig(wbuild.utils.Config())
WARNING: Less than 30 IDs in DROP_GROUP NEMO_NDAS
WARNING: Less than 30 IDs in DROP_GROUP NEMO_NDAS
>>> drop.installRPackages(cfg)
check for missing R packages
Bioconductor version '3.12' is out-of-date; the current release version '3.13'
  is available with R version '4.1'; see https://bioconductor.org/install
Bioconductor version '3.12' is out-of-date; the current release version '3.13'
  is available with R version '4.1'; see https://bioconductor.org/install
>>> sa = cfg.sampleAnnotation
>>> config = cfg.config_dict # legacy
>>> cfg.AE.getCountParams("ANV_1")
{'STRAND': 'no', 'COUNT_MODE': 'IntersectionStrict', 'PAIRED_END': True, 'COUNT_OVERLAPS': True}
>>> 
====

This will create error for later run of countReads.R in aberrant expression module. Could you please help me figure out what could be wrong?

Or is it also related to the drop version?

Thanks a lot.

**Comment by mumichae** [comment]
Hi,
I could reproduce this error with DROP version 1.0.3. In DROP version 1.0.4 we use a different conversion function which correctly parses boolean values from the sample annotation.

I'd strongly suggest you to update DROP to avoid any further bugs that 1.0.4 already adresses. This should be as simple as updating DROP in your conda environment and updating your project directory. Please make sure that you secure and custom scripts within that directory, as they will be removed with the update.

    conda activate <your_drop_environment>
    conda install -c conda-forge -c bioconda drop==1.0.4  # alternatively use mamba for much faster runtime
    cd <your_project_dir>  # make sure you back up any modified scripts you want to keep before proceeding
    drop update

Please let me know if this solves the problem.

**Comment by vyepez88** [comment]
Hi @capricy, can you please confirm if updating to DROP 1.0.4 (or even better 1.0.5) solved your error?

**Comment by capricy** [comment]
Our IT just installed drop 1.0.4 on hpc. I am testing runs. I will have results in next couple of days. Thanks.

**Comment by capricy** [comment]
I got different issues with DROP1.0.4 as indicated in a separate post

**Comment by vyepez88** [comment]
was the paired-end issue solved?

**Comment by capricy** [comment]
yes, paired-end issue is gone
