### ISSUE TITLE
Aberrant Expression Summary Error

### ISSUE THREAD

**Issue by bijuissacch224610** [gagneurlab/drop#207]
Hi 
We ran the aberrant expression module but encountered errors at the last few steps. Can you take a look at the error below and guide us to correct this.

Thanks
-Biju Issac
Sr. Bioinformatics Scientist
biju.issac@childrens.harvard.edu

Finished job 125.
123 of 127 steps (97%) done
Select jobs to execute...

[Sun Jun 13 21:04:04 2021]
rule AberrantExpression_pipeline_OUTRIDER_Summary_R:
    input: /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/processed_results/aberrant_expression/p13/outrider/outrider/ods.Rds, /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/processed_results/aberrant_expression/p13/outrider/outrider/OUTRIDER_results.tsv, Scripts/AberrantExpression/pipeline/OUTRIDER/Summary.R
    output: /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/html/AberrantExpression/Outrider/p13/Summary_outrider.html
    log: /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/.drop/tmp/AE/p13/outrider/OUTRIDER_summary.Rds
    jobid: 123
    wildcards: annotation=p13, dataset=outrider

processing file: /tmp/RtmpXbRoPu/filef9634c268f9/Datasets.spin.Rmd
Loading required package: knitr
Loading required package: rmarkdown
output file: /tmp/RtmpXbRoPu/filef9634c268f9/Datasets.knit.md

Output created: /tmp/RtmpXbRoPu/filef966de7d52b/Scripts_AberrantExpression_pipeline_Counting_Datasets.html

processing file: /tmp/RtmpuepCrF/filefde51673cea/Summary.spin.Rmd
[Sun Jun 13 21:04:06 2021]
Finished job 1.
124 of 127 steps (98%) done
`geom_smooth()` using formula 'y ~ x'
Quitting from lines 78-84 (/tmp/RtmpuepCrF/filefde51673cea/Summary.spin.Rmd) 
Error in estimateSizeFactorsForMatrix(fcMat) : 
  every gene contains at least one zero, cannot compute log geometric means
Calls: render ... plotCountGeneSampleHeatmap -> t -> estimateSizeFactorsForMatrix
In addition: Warning messages:
1: Transformation introduced infinite values in continuous y-axis 
2: Removed 54 rows containing missing values (geom_bar). 
Execution halted
[Sun Jun 13 21:04:39 2021]
Error in rule AberrantExpression_pipeline_OUTRIDER_Summary_R:
    jobid: 123
    output: /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/html/AberrantExpression/Outrider/p13/Summary_outrider.html
    log: /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/.drop/tmp/AE/p13/outrider/OUTRIDER_summary.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 79 of /tmp/tmp4uuvjsyv:
Command 'set -euo pipefail;  Rscript --vanilla /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/.snakemake/scripts/tmpx_hbr4es.wBRender.R' returned non-zero exit status 1.
  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2330, in run_wrapper
  File "/tmp/tmp4uuvjsyv", line 79, in __rule_AberrantExpression_pipeline_OUTRIDER_Summary_R
  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 569, in _callback
  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 555, in cached_or_run
  File "/programs/x86_64-linux/drop/1.0.3/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2362, in run_wrapper
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/.snakemake/log/2021-06-13T135554.377170.snakemake.log
[html.zip](https://github.com/gagneurlab/drop/files/6649034/html.zip)

**Comment by mumichae** [comment]
Hi Biju,

It seems as though something went wrong during filtering the counts. Check your `<html_path>/Scripts_AberrantExpression_pipeline_Counting_Datasets.html` file if available or the `<html_path>/AberrantExpression/Counting/` for HTML summaries of the counts to see if the counts were properly filtered. The `<html_path>` should be the one defined in your `config.yaml`.
Also check your OUTRIDER dataset file
`/lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/processed_results/aberrant_expression/p13/outrider/outrider/ods.Rds` in R to see what the count matrix looks like

```R
ods <- readRDS('/lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/processed_results/aberrant_expression/p13/outrider/outrider/ods.Rds')
cnts <- counts(ods)
cnts
```

Be sure to use R in your activated conda environment to ensure that you are using the right dependencies.

**Comment by bijuissacch224610** [comment]
Hi Micheala

This (attached) is everything from my “html” folder.

Thanks
-Biju Issac

Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: Michaela Mueller ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Monday, June 14, 2021 at 9:37 AM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Author ***@***.***>
Subject: Re: [gagneurlab/drop] Aberrant Expression Summary Error (#207) [EXTERNAL]

* External Email - Caution *



Hi Biju,

It seems as though something went wrong during filtering the counts. Check your <html_path>/Scripts_AberrantExpression_pipeline_Counting_Datasets.html file if available or the <html_path>/AberrantExpression/Counting/ for HTML summaries of the counts to see if the counts were properly filtered. The <html_path> should be the one defined in your config.yaml.
Also check your OUTRIDER dataset file
/lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/processed_results/aberrant_expression/p13/outrider/outrider/ods.Rds in R to see what the count matrix looks like

ods <- readRDS('/lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/processed_results/aberrant_expression/p13/outrider/outrider/ods.Rds')

cnts <- counts(ods)

cnts

Be sure to use R in your activated conda environment to ensure that you are using the right dependencies.

**Comment by bijuissacch224610** [comment]
Hi

I find no issues with the counts in ods.Rds file


[Table  Description automatically generated]


Thanks
-Biju Issac

Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: Michaela Mueller ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Monday, June 14, 2021 at 9:37 AM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Author ***@***.***>
Subject: Re: [gagneurlab/drop] Aberrant Expression Summary Error (#207) [EXTERNAL]

* External Email - Caution *



Hi Biju,

It seems as though something went wrong during filtering the counts. Check your <html_path>/Scripts_AberrantExpression_pipeline_Counting_Datasets.html file if available or the <html_path>/AberrantExpression/Counting/ for HTML summaries of the counts to see if the counts were properly filtered. The <html_path> should be the one defined in your config.yaml.
Also check your OUTRIDER dataset file
/lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/processed_results/aberrant_expression/p13/outrider/outrider/ods.Rds in R to see what the count matrix looks like

ods <- readRDS('/lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/AE2/dropOut/processed_results/aberrant_expression/p13/outrider/outrider/ods.Rds')

cnts <- counts(ods)

cnts

Be sure to use R in your activated conda environment to ensure that you are using the right dependencies.

**Comment by mumichae** [comment]
Hi,
I can't seem to find the files you attached, could you post them on github or paste some screenshots of the images?
This issue might also be a result of subsetting the genes when calling `plotCountGeneSampleHeatmap`. We'll have a look into that and try to figure out how to deal with this issue for this particular plot. However, once you have the fitted ODS object, you should be able to compute all OUTRIDER plots yourself. That might be useful to check how well the fit worked, while we try to fix the plotting issue.

**Comment by bijuissacch224610** [comment]
Hi Michaela

I have attached the zipped html folder to the original issue in github. Let me know if you cannot locate it.


Thanks
-Biju Issac

Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: Michaela Mueller ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Monday, June 14, 2021 at 10:21 AM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Author ***@***.***>
Subject: Re: [gagneurlab/drop] Aberrant Expression Summary Error (#207) [EXTERNAL]

* External Email - Caution *



Hi,
I can't seem to find the files you attached, could you post them on github or paste some screenshots of the images?
This issue might also be a result of subsetting the genes when calling plotCountGeneSampleHeatmap. We'll have a look into that and try to figure out how to deal with this issue for this particular plot. However, once you have the fitted ODS object, you should be able to compute all OUTRIDER plots yourself. That might be useful to check how well the fit worked, while we try to fix the plotting issue.

**Comment by mumichae** [comment]
Hi, I had a quick look in your count summary. You have some samples with significantly higher read counts than the rest. Consider removing the 4 outlier samples from you sample annotation (or add a new DROP group that excludes these samples). That should give you a better count distribution
![image](https://user-images.githubusercontent.com/51025211/121910181-edfe7c80-cd2e-11eb-9a01-638b55847fe1.png)

**Comment by bijuissacch224610** [comment]
Thanks for quickly looking into this Michaela

Is there a general rule about how much variation in total coverage I should allow between these samples? The four samples in question have more than twice the number of reads as the other samples.

Thanks
-Biju Issac

Sr. Bioinformatics Scientist
Boston Children’s Hospital
***@***.***

From: Michaela Mueller ***@***.***>
Reply-To: gagneurlab/drop ***@***.***>
Date: Monday, June 14, 2021 at 10:38 AM
To: gagneurlab/drop ***@***.***>
Cc: "Issac, Biju" ***@***.***>, Author ***@***.***>
Subject: Re: [gagneurlab/drop] Aberrant Expression Summary Error (#207) [EXTERNAL]

* External Email - Caution *



Hi, I had a quick look in your count summary. You have some samples with significantly higher read counts than the rest. Consider removing the 4 outlier samples from you sample annotation (or add a new DROP group that excludes these samples). That should give you a better count distribution
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/51025211/121910181-edfe7c80-cd2e-11eb-9a01-638b55847fe1.png__;!!NZvER7FxgEiBAiR_!-6HeYPoh-TlAoUiVFpnqVUrSuRiT_zCa78u2li_SoucdVh7xh036RBlDrthikTLXxwXYjJdaMbw$>

**Comment by vyepez88** [comment]
Hi, we haven't systematically studied size factor cutoffs. Nevertheless, from our experience, we usually remove < 0.5 and > 2. You could check the number of outliers of those 4 samples. Maybe they have too many outliers with respect to the other samples.

**Comment by mumichae** [comment]
On second glance, the counts are very low (left plot) and the percentage of counted reads vs total aligned reads is around 1% (right plot). This might be an indication that something went wrong with counting. If you are counting strand-specifically, make sure if the strand of the data is reverse or not.

Please also refer to Box 3 of the DROP paper (https://www.nature.com/articles/s41596-020-00462-5) for more information on count settings.

It is always good to check your BAM files in IGV to get a feeling for the data. It should help you identify what could have gone wrong during counting.
