### ISSUE TITLE
Using python3

### ISSUE THREAD

**Issue by mumichae** [gagneurlab/drop#21]
reposting misago's issue:

> Hi,
> 
> Although I have found the problem, now I have another error with snakemake:
> 
> I'm using a CentOS-7. This version of centos still have Python-2.7. So, If in this operative system you execute only 'python', you are working with python-2.7. To work with python-3 you have to run the command python3:
> 
> Singularity> cat /etc/centos-release
> CentOS Linux release 7.7.1908 (Core)
> Singularity> python --version
> Python 2.7.5
> Singularity> python3 --version
> Python 3.6.8
> Singularity>
> 
> So, In the script drop/download_data.sh, to be sure that I'm executing python-3 (that is the python where Drop in installed), I have had to modify the line:
> 
> python fix_sample_anno.py
> 
> by:
> 
> python3 fix_sample_anno.py
> 
> Then, reinstall Drop and then the command 'drop demo' woks fine.
> 
> The new error is with snamake:
> 
> Singularity> snakemake -n
> check for missing R packages
> WARNING: Less than 30 IDs in DROP_GROUP outrider
> WARNING: Less than 30 IDs in DROP_GROUP fraser
> Structuring dependencies...
> Dependencies file generated.
> 
> Building DAG of jobs...
> Executing subworkflow AE.
> Error: Snakefile "/root/drop-demo/.drop/modules/aberrant-expression-pipeline/Snakefile" not found.
> Singularity>
> 
> The content of the .drop directory in the demo project directory is:
> 
> Singularity> ls -l .drop
> total 8
> drwxr-xr-x 3 root root 4096 mar 26 17:05 modules
> drwxr-xr-x 5 root root 4096 mar 26 17:07 tmp
> Singularity> ls -l .drop/modules/
> total 4
> drwxr-xr-x 2 root root 4096 mar 26 17:05 helpers
> Singularity>
> 
> Any idea? Thanks a lot for your time.

**Comment by mumichae** [comment]
DROP requires python 3 to be called as `python` in order to work.
I would suggest that the cleanest and most robust way is for you to use a anaconda (or any other virtual environment that you are familiar with). The advantage of using anaconda is that it is also  availabe for python 2 and lets you install different versions of python.
Try installing miniconda (https://docs.conda.io/en/latest/miniconda.html#linux-installers) and setting up the environment there. You can use the `.travis.yml` file for help.

**Comment by misago162** [comment]
Hi. I have done some modification on my Centos7 singularity container. Now the command system 'python' execute python3. Now the drop software works fine. Thanks a lot for you help. This issue can be closed.
