### ISSUE TITLE
Error in AberrantExpression_pipeline_OUTRIDER_Summary_R

### ISSUE THREAD

**Issue by jftchau** [gagneurlab/drop#214]
Hi, there seems to be an issue when DROP attempts to summarize the OUTRIDER. I have attached the error message below. Can you please take another look at the error and what are the steps to correct this. Thanks!

Best,
Jeffrey
jftchau@connect.hku.hk

[Wed Jun 23 09:52:38 2021]
rule AberrantExpression_pipeline_OUTRIDER_Summary_R:
    input: /paedbc01/disk1/home/rnaseq/drop_HKU/Output_20210622/processed_results/aberrant_expression/v29/outrider/all/ods.Rds, /paedbc01/disk1/home/rnaseq/drop_HKU/Output_20210622/processed_results/aberrant_expression/v29/outrider/all/OUTRIDER_results.tsv, Scripts/AberrantExpression/pipeline/OUTRIDER/Summary.R
    output: /paedbc01/disk1/home/rnaseq/drop_HKU/Output_20210622/html/AberrantExpression/Outrider/v29/Summary_all.html
    log: /paedbc01/disk1/home/rnaseq/drop_HKU/.drop/tmp/AE/v29/all/OUTRIDER_summary.Rds
    jobid: 92
    wildcards: annotation=v29, dataset=all

Loading required package: knitr
Loading required package: rmarkdown

processing file: /tmp/pbs.990757.omics/RtmpU2Wps2/file60991447bbc69/Summary.spin.Rmd
`geom_smooth()` using formula 'y ~ x'
output file: /tmp/pbs.990757.omics/RtmpU2Wps2/file60991447bbc69/Summary.knit.md

pandoc: Stack space overflow: current size 33624 bytes.
pandoc: Use `+RTS -Ksize -RTS' to increase it.
Error: pandoc document conversion failed with error 2
In addition: Warning message:
In instance$preRenderHook(instance) :
  It seems your data is too big for client-side DataTables. You may consider server-side processing: https://rstudio.github.io/DT/server.html
Execution halted
[Wed Jun 23 09:53:53 2021]
Error in rule AberrantExpression_pipeline_OUTRIDER_Summary_R:
    jobid: 92
    output: /paedbc01/disk1/home/rnaseq/drop_HKU/Output_20210622/html/AberrantExpression/Outrider/v29/Summary_all.html
    log: /paedbc01/disk1/home/rnaseq/drop_HKU/.drop/tmp/AE/v29/all/OUTRIDER_summary.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 79 of /tmp/pbs.990757.omics/tmpa1a1woka:
Command 'set -euo pipefail;  Rscript --vanilla /paedbc01/disk1/home/rnaseq/drop_HKU/.snakemake/scripts/tmphykcxg2p.wBRender.R' returned non-zero exit status 1.
  File "/software/drop/1.0.4/lib/python3.7/site-packages/snakemake-6.4.0-py3.7.egg/snakemake/executors/__init__.py", line 2371, in run_wrapper
  File "/tmp/pbs.990757.omics/tmpa1a1woka", line 79, in __rule_AberrantExpression_pipeline_OUTRIDER_Summary_R
  File "/software/drop/1.0.4/lib/python3.7/site-packages/snakemake-6.4.0-py3.7.egg/snakemake/executors/__init__.py", line 569, in _callback
  File "/software/python/3.7.10/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/software/drop/1.0.4/lib/python3.7/site-packages/snakemake-6.4.0-py3.7.egg/snakemake/executors/__init__.py", line 555, in cached_or_run
  File "/software/drop/1.0.4/lib/python3.7/site-packages/snakemake-6.4.0-py3.7.egg/snakemake/executors/__init__.py", line 2383, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /paedbc01/disk1/home/rnaseq/drop_HKU/.snakemake/log/2021-06-23T095235.248887.snakemake.log

**Comment by vyepez88** [comment]
Hi, it could be that the html is unable to render the full OUTRIDER results table. A simple way to fix this is to set the `padjCutoff` to 0.05 or 0.1 in the different modules, otherwise a `samples x genes`  table is loaded. We will also fix this in a new branch.

**Comment by nickhsmith** [comment]
You can set the padjCutoff in the config file.

**Comment by nickhsmith** [comment]
Did this solve your problem? We just pushed a change to the `dev` branch that should eliminate this problem for you in the future, we will make these changes available through conda and the main branch soon.
