### ISSUE TITLE
Error in rule mae_createSNVs

### ISSUE THREAD

**Issue by bijuissacch224610** [gagneurlab/drop#219]
Hi Drop Team
I am getting the following error in the middle of my MAE run. 
Error part is pasted below. I have also attached the entire log file from the run. 
Can I request guidance on what the error is?

Thanks
-Biju
Sr. Bioinformatics Scientist
Boston Childrens Hospital

[2021-06-25T111649.437704.snakemake.log](https://github.com/gagneurlab/drop/files/6717679/2021-06-25T111649.437704.snakemake.log)

rule mae_createSNVs:
    input: Scripts/MonoallelicExpression/pipeline/resource/chr_NCBI_UCSC.txt, Scripts/MonoallelicExpression/pipeline/resource/chr_UCSC_NCBI.txt, DROP_PROJECT/Novogene/VCF_Files/qc_vcf_1000G_hs37d5.vcf.gz, DROP_PROJECT/Novogene/Alignment/SXAVI2W9Aligned.sortedByCoord.out.bam, Scripts/MonoallelicExpression/pipeline/MAE/filterSNVs.sh, DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/params/snvs/SXAVI2W9_snvParams.csv
    output: DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/QC--SXAVI2W9.vcf.gz, 
DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/QC--SXAVI2W9.vcf.gz.tbi
    jobid: 272
    wildcards: vcf=QC, rna=SXAVI2W9

[Tue Jun 22 12:29:27 2021]
Error in rule mae_createSNVs:
    jobid: 153
    output: DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/BCH_BCH-19-89596-04--SSP2MG2F.vcf.gz, DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/BCH_BCH-19-89596-04--SSP2MG2F.vcf.gz.tbi
    shell:
        
        Scripts/MonoallelicExpression/pipeline/MAE/filterSNVs.sh Scripts/MonoallelicExpression/pipeline/resource/chr_NCBI_UCSC.txt Scripts/MonoallelicExpression/pipeline/resource/chr_UCSC_NCBI.txt BCH_BCH-19-89596-04/6552/BCH_BCH-19-89596-04.realigned.recalibrated.g.vcf.gz         BCH_BCH-19-89596-04 DROP_PROJECT/Novogene/Alignment/SSP2MG2FAligned.sortedByCoord.out.bam DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/BCH_BCH-19-89596-04--SSP2MG2F.vcf.gz         bcftools samtools
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job mae_createSNVs since they might be corrupted:
DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/BCH_BCH-19-89596-04--SSP2MG2F.vcf.gz
Job failed, going on with independent jobs.

**Comment by nickhsmith** [comment]
Could you please try to run a specific command that has failed directly from the command line (inside your conda environment) this will hopefully give us some more information about why it failed. For example could you please run this command (copy pasted from your log file)?

`
Scripts/MonoallelicExpression/pipeline/MAE/ASEReadCounter.sh Scripts/MonoallelicExpression/pipeline/resource/chr_NCBI_UCSC.txt Scripts/MonoallelicExpression/pipeline/resource/chr_UCSC_NCBI.txt         /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/QC--SEI9U8W5.vcf.gz /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/Alignment/SEI9U8W5Aligned.sortedByCoord.out.bam QC--SEI9U8W5         /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/hs37d5.fa True /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/allelic_counts/QC--SEI9U8W5.csv.gz         bcftools samtools gatk
`

**Comment by bijuissacch224610** [comment]
Hi Nick

All 4 input files, RNA-seq-BAM, VCF, reference genome FASTA and QC VCF have same chromosomal style {1..2,X,Y} (withouth "chr" prefix)

**Command line**:
Scripts/MonoallelicExpression/pipeline/MAE/ASEReadCounter.sh Scripts/MonoallelicExpression/pipeline/resource/chr_NCBI_UCSC.txt Scripts/MonoallelicExpression/pipeline/resource/chr_UCSC_NCBI.txt /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/QC--S44MTGB6.vcf.gz /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/Alignment/S44MTGB6Aligned.sortedByCoord.out.bam QC--S44MTGB6 /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/hs37d5.fa True /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/allelic_counts/QC--S44MTGB6.csv.gz bcftools samtools gatk

see log file as attachment


[errLogFile.txt](https://github.com/gagneurlab/drop/files/6728433/errLogFile.txt)

**Comment by bijuissacch224610** [comment]
> Hi Nick
> 
> All 4 input files, RNA-seq-BAM, VCF, reference genome FASTA and QC VCF have same chromosomal style {1..2,X,Y} (withouth "chr" prefix)
> 
> **Command line**:
> Scripts/MonoallelicExpression/pipeline/MAE/ASEReadCounter.sh Scripts/MonoallelicExpression/pipeline/resource/chr_NCBI_UCSC.txt Scripts/MonoallelicExpression/pipeline/resource/chr_UCSC_NCBI.txt /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/QC--S44MTGB6.vcf.gz /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/Alignment/S44MTGB6Aligned.sortedByCoord.out.bam QC--S44MTGB6 /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/hs37d5.fa True /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/allelic_counts/QC--S44MTGB6.csv.gz bcftools samtools gatk
> 
> see log file as attachment
> 
> [errLogFile.txt](https://github.com/gagneurlab/drop/files/6728433/errLogFile.txt)

Does this mean that the ASEReadCounter could not compute any allelic count from the data?

**Comment by nickhsmith** [comment]
Looking at the errors, it seems like yes that is the case. ASEReadCounter is not returning any calls.

My recommendations would be as follows (although I will ping @vyepez88  and @mumichae to see their take on this)

Could you please run the following and send us your results?

1. Make sure that your VCF file is correct and complete. I would use GATK's ValidateVariants tool
` gatk ValidateVariants 
   -R /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/hs37d5.fa 
   -V /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/MAE/dropOut/processed_data/mae/snvs/QC--S44MTGB6.vcf.gz 
   --dbsnp /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/VCF_Files/qc_vcf_1000G_hs37d5.vcf.gz `

2. Make sure the BAM file is correct and complete. I would use GATK ValidateSamFile.
` GATK ValidateSamFile  
  -I /lab-share/RC-Data-Science-e2/Public/Biju/DROP_PROJECT/Novogene/Alignment/S44MTGB6Aligned.sortedByCoord.out.bam 
  -M SUMMARY
  `
  
3. Could you please just confirm which drop version you are using (`drop --version`)

**Comment by nickhsmith** [comment]
After working through the problem offline the issue was that the input BAM files did not have read groups. As a result, the ASEReadCounter filter was eliminating every read and then expectedly outputting nothing. They've added RG groups using https://gatk.broadinstitute.org/hc/en-us/articles/360037226472-AddOrReplaceReadGroups-Picard- and have since been able to run the pipeline.
