### ISSUE TITLE
Output explanation

### ISSUE THREAD

**Issue by tomh1lll** [gagneurlab/drop#220]
Could you please provide a more thorough read me file, explaining the outputs. I have currently successfully run the aberrantSplicing and aberrantExpression pipelines, and am not entirely sure what the important output files are.

I would appreciate an explanation of output files, what output files are important, and an explanation of columns in the files Output/processed_results/aberrant_splicing/results/v19/fraser/fraser/results.tsv and Output/processed_results/aberrant_expression/v38/outrider/outrider/OUTRIDER_results.tsv

As I am not sure what the best way to interpret the splicing results, and how to visualise samples which differ compared to other samples.

**Comment by mumichae** [comment]
Hi,
including some more documentation for the output definitely would be a good idea. We will try to update the DROP documentation soon.

For now, the most detailed description of the workflow and the outputs are in the HTML files (Open up the `<project_dir>_index.html` in your `htmlOutputPath`) as well as in the DROP protocol: https://www.nature.com/articles/s41596-020-00462-5.

I hope this helps for now, let us know if you have any specific questions.

**Comment by tomh1lll** [comment]
Thanks, this is helpful to some degree, but it doesn't help if I want to look at specific genes, or compare certain sets of samples. Updated documentation explaining the results would definitely be appreciated.

**Comment by antoniognmk** [comment]
Hi, sorry for bumping such a relatively old thread, but I am having a hard time understanding the MAE analysis output table columns. If you could provide an explanation of the meaning of each column would be really helpful.  Thank you for making DROP available!

**Comment by nickhsmith** [comment]
Are you referring to the `MAE_results.tsv` table? I agree that having an Output files section in the docs could be useful to explain what you get, and what you should expect, but that may take some time to put together.

Are there any specific columns that are ambiguous that we could help with, in the mean time?

**Comment by antoniognmk** [comment]
Hi @nickhsmith. Yes, that is the one. I would like to know how to interpret the following columns:

refCount
altCount
N
N_MAE
N_MAE_REF
N_MAE_ALT
N_MAE_REF_RARE
N_MAE_ALT_RARE

I surmise that the `log2FC ` column is calculated with the numbers from the `refCount `and `altCount ` columns. At first I concluded that those two columns would be the number of reads denoting expression of each allele. However, I was wondering how these numbers relate to the numbers with the other columns starting with `N`? How to interpret them?

Moreover, `N_MAE_REF`, `N_MAE_REF_RARE` and `N_MAE_ALT_RARE` columns seem to be all empty in the example output, why is that?

Thanks again

**Comment by nickhsmith** [comment]
Which version of DROP are you using by the way? You should be in DROP 1.1.0 `drop --version` from your working directory.

In the demo (1.1.0) there are no significant MAE results, but there are 335 candidates (`Output/processed_results/mae/mae/MAE_results_all_v29.tsv`). And these columns aren't present in that table or the others.

So unfortunately I'm not sure which file you're looking at. 
That being said. I'll still try to help:

These are per sample evidence:
refCount = number of reads supporting the reference for a particular sample
altCount = number of reads supporting the alternative for a particular sample

These are summary statistics:
N = number of samples 
N_MAE = number of samples that are MAE
N_MAE_REF = number of samples that are MAE for the REF
N_MAE_ALT = number of samples that are MAE for the ALT
N_MAE_REF_RARE = number of samples that are MAE for the REF and rare
N_MAE_ALT_RARE = number of samples that are MAE for the ALT and rare

**Comment by antoniognmk** [comment]
Actually, I was just checking the example output you provided in the [Nature Protocols paper](https://www.cmm.in.tum.de/public/paper/drop_analysis/webDir/html/drop_analysis_index.html#Scripts_MAEAnalysis_Overview.html), sorry for the confusion. Anyway, your explanation helped a lot, thank you very much!

**Comment by nickhsmith** [comment]
I see! Well, I'm glad that helped.
