### ISSUE TITLE
Error in Snakefile

### ISSUE THREAD

**Issue by bioinfous** [gagneurlab/drop#226]
Hello,
I am trying to run drop (1.0.5) but get this error:
TypeError in line 13 of Snakefile:
argument of type 'bool' is not iterable
  File "Snakefile", line 13, in <module>
  File "drop_env/lib/python3.9/site-packages/drop/config/DropConfig.py", line 78, in __init__
  File "drop_env/lib/python3.9/site-packages/drop/config/ExportCounts.py", line 28, in __init__
  File "drop_env/lib/python3.9/site-packages/drop/config/ExportCounts.py", line 40, in setDefaults
  File "drop_env/lib/python3.9/site-packages/drop/utils.py", line 53, in setKey
Could you please help me troubleshoot,
Thank you so much

**Comment by nickhsmith** [comment]
What does your config file look like? It should look like [line 7 of the demo config file](https://github.com/gagneurlab/drop/blob/master/drop/demo/config_relative.yaml). A yaml defined dictionary for the `geneAnnotation` variable.

```
geneAnnotation:
      v29: PATH_TO_ANNOTATION.gtf
 ```

**Comment by bioinfous** [comment]
Yes, it does look like line 7 from demo config.
geneAnnotation:
  v36:  gencode.v36lift37.annotation.v2.gtf


From: nickhsmith ***@***.***>
Date: Tuesday, July 13, 2021 at 7:06 PM
To: gagneurlab/drop ***@***.***>
Cc: Ketkar, Shamika ***@***.***>, Author ***@***.***>
Subject: Re: [gagneurlab/drop] Error in Snakefile (#226)
***CAUTION:*** This email is not from a BCM Source. Only click links or open attachments you know are safe.
________________________________

What does your config file look like? It should look like line 7 of the demo config file<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gagneurlab_drop_blob_master_drop_demo_config-5Frelative.yaml&d=DwMCaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=VnjW0eYXQ2AHeBVQ3pk_jQ&m=kG_VDL-7OAF9Av1er2e16QRyxSMQQ6T_9ooADMI0G0c&s=WbsBoTvaSNGdkitDEIaC0STMhMzxPTcaKfSKwUDjweQ&e=>. A yaml defined dictionary for the geneAnnotation variable.

geneAnnotation:

      v29: PATH_TO_ANNOTATION.gtf

**Comment by bioinfous** [comment]
Yes, it does look like line 7 from demo config.
geneAnnotation:
  v36:  gencode.v36lift37.annotation.v2.gtf

**Comment by nickhsmith** [comment]
Could you please send me the entire config file (as a text file ideally)? It seems that something has gone wrong there because a boolean value is being iterated instead of a dictionary.

**Comment by vyepez88** [comment]
Hi @bioinfous, did you get to have a look at this? You can also try our latest version 1.1.0.
