### ISSUE TITLE
Running DROP aberrant expression and aberrant splicing modules only (no VCF file)

### ISSUE THREAD

**Issue by julbtn** [gagneurlab/drop#230]
Hello,

I am trying to run the aberrant expression and aberrant splicing modules only with DROP. I don't have any VCF files in my data, only BAM files and external count matrices. From what I understood from previous issues, DROP was designed thinking that one user would want to run the 3 modules. Thus, I included in my confi.yaml file, the mae section. However, when running aberrantExpression I get this following error, which is normal since I don't have any VCF file...

**WARNING: Less than 30 IDs in DROP_GROUP all
check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmp5m1smw1y

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError (rule AberrantExpression_pipeline_Counting_mergeCounts_R, line 135, /tmp/tmp5m1smw1y):
        Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
    AberrantExpression/Counting/gencode19/Summary_all.md
MissingInputException: Missing input files for rule markdown:
Scripts_AberrantExpression_pipeline_Counting_Datasets.md**

I was thus wondering if it is actually possible to run DROP without VCF files? and If so, How should I write my config file to get passed this error? Or what should I modify to be able to run the aberrant expression and splicing modules without any VCF file? 

Thank you for your help!

[config.pdf](https://github.com/gagneurlab/drop/files/6824772/config.pdf)
[PRJNA316625_sampleAnnotation.pdf](https://github.com/gagneurlab/drop/files/6824775/PRJNA316625_sampleAnnotation.pdf)

**Comment by nickhsmith** [comment]
We are currently in the process of bumping to a new version of DROP in the next day or so which hopes to alleviate this problem. If you don't want to wait for this new version, I would recommend installing the `dev` version of drop which has a new feature allowing you to turn off any module you are not interested in running. 

you can install it via this command
`pip install git+https://github.com/gagneurlab/drop.git@dev`

then go to your working drop directory and update it using 
`drop update`

then you should be able to edit your config to include `run: false` inside the mae module

```
mae:  
   run: false
   groups: 
     - group1
     - group2
   ...
```

If that goes smoothly DROP will ignore the MAE module completely. allowing you to focus solely on aberrant expression and splicing

**Comment by julbtn** [comment]
That's great, thank you for the quick answer!
