### ISSUE TITLE
aberrantExpression final step error

### ISSUE THREAD

**Issue by bijuissacch224610** [gagneurlab/drop#237]
Hi 
If I run Aberrant Expression Module on a stranded library (sample annotation file: strand=yes), I manage to complete 98% of run and module exits with error at final step.  See below. This error does not occur if I run the module with (strand=no). Since my RNA-seq library is stranded, I wanted to know if DROP has issues running with stranded library? Or if there is a parameter I need to change for a successful run?

>>>>>>>>>>>>>
Quitting from lines 80-86 (/tmp/RtmpSIfEfa/file1039e2a301d/Summary.spin.Rmd) 
Error in estimateSizeFactorsForMatrix(fcMat) : 
  every gene contains at least one zero, cannot compute log geometric means
Calls: render ... plotCountGeneSampleHeatmap -> t -> estimateSizeFactorsForMatrix
In addition: Warning messages:
1: Transformation introduced infinite values in continuous y-axis 
2: Removed 51 rows containing missing values (geom_bar). 

Execution halted
[Sun Aug  1 15:52:55 2021]
Error in rule AberrantExpression_pipeline_OUTRIDER_Summary_R:
    jobid: 125
    output: /project/RC-Data-Science/Biju/Novogene/Novogene2/dropOut/AE/html/AberrantExpression/Outrider/hg19/Summary_outrider.html, /project/RC-Data-Science/Biju/Novogene/Novogene2/dropOut/AE/html/AberrantExpression/Outrider/hg19/OUTRIDER_results_outrider.tsv
    log: /project/RC-Data-Science/Biju/Novogene/Novogene2/dropOut/AE/.drop/tmp/AE/hg19/outrider/OUTRIDER_summary.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 79 of /tmp/tmpr6aurxjs:
Command 'set -euo pipefail;  Rscript --vanilla /project/RC-Data-Science/Biju/Novogene/Novogene2/dropOut/AE/.snakemake/scripts/tmpbogohe03.wBRender.R' returned non-zero exit status 1.
  File "/programs/x86_64-linux/drop/1.0.5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
  File "/tmp/tmpr6aurxjs", line 79, in __rule_AberrantExpression_pipeline_OUTRIDER_Summary_R
  File "/programs/x86_64-linux/drop/1.0.5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 574, in _callback
  File "/programs/x86_64-linux/drop/1.0.5/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/programs/x86_64-linux/drop/1.0.5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in cached_or_run
  File "/programs/x86_64-linux/drop/1.0.5/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2390, in run_wrapper
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /project/RC-Data-Science/Biju/Novogene/Novogene2/dropOut/AE/.snakemake/log/2021-08-01T084034.924439.snakemake.log

**Comment by vyepez88** [comment]
Hi, 
The strand is not a parameter that can be 'chosen' by the user. It is determined by the alignment and the BAM file (like hg19/hg38). If the BAM file is strand-specific, then it is either 'forward' or 'reverse' mode. Probably your data is reversed, that is why the pipeline works with `strand=no`.

**Comment by vyepez88** [comment]
For more information, check the "The gene counts are very low" entry in the Troubleshooting section of the DROP manuscript.

**Comment by vyepez88** [comment]
Hi @bijuissacch224610 , did you have a look at this?
