### ISSUE TITLE
question about MAE parameters: maxAF and maxVarFreqCohort

### ISSUE THREAD

**Issue by capricy** [gagneurlab/drop#239]
Hi Drop Support,

May I know how AF and VarFreqCohort are defined in DROP pipeline? Thanks.

C.

**Comment by nickhsmith** [comment]
Here is a link to the documentation:
https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html?highlight=AF#mono-allelic-expression-dictionary

Basically, you can set `addAF: true` to include allele frequency from gnomAD
`maxAF` is the maximum allowed frequency to be considered a rare variant (based on gnomAD)
and `maxVarFreqCohort` is the maximum allowed variant frequency within the cohort.

**Comment by capricy** [comment]
I am still confused...

My input VCF file has AF, but not cohort variant frequency. How would the pipeline handle such situation?

The documentation mentioned maxAF is Maximum allele frequency (of the minor allele) cut-off. Does it mean that the pipeline only consider minor allele here? Does the pipeline calculate the minor allele frequency from the input VCF file?

Thanks.

C.

**Comment by nickhsmith** [comment]
So there are 2 different cutoffs. addAF and maxAF work together, and maxVarFreqCohort works separtely. 

addAF says do you want to get the allele frequency from gnomAD (a world wide frequency of the variant)? and maxAF says what is the maximum allele frequency of the minor allele that you consider rare.

If gnomAD says this A>C variant happens at a rate of 1% in their database. If you set maxAF to be 5% then this is considered rare. However if you set maxAF to be 0.1% then this variant is no longer considered rare. This maxAF threshold is for you to set depending on which variants you want to prioritize in the downstream analysis.

maxVarFreqCohort doesn't involve gnomAD. It only works within the data you provide to MAE. So if you give the MAE module 100 samples, you can control for sequencing bias within your cohort. If you want to only consider variants that are generally rare within your cohort then you can use maxVarFreqCohort to control for that. If gnomAD says that a variant A>C is found 0.01% of the time, and your maxAF is set to 0.1% you would accept this variant. But if every single one of your 100 samples (100 vcf files) (running MAE) has this variant A>C this could be evidence that something hasn't gone correctly. So you can set your maxVarFreqCohort variable to be 10% meaning that if a variant is found in more than 10% of the samples you've provided it will not prioritize that variant.

**Comment by capricy** [comment]
So, according to your explanation, may I say:

1. if I have "addAF: false", maxAF won't be applied during the MAE analysis
2. if I have "addAF: true", it would only add AF from the gnomAD if the given variant is found in my sample cohort
3. if I would like to check every variant (not just the rare ones) in my samples, I can simply remove the line "maxVarFreqCohort" while setting "addAF: true"

???

Thanks.

C.

**Comment by nickhsmith** [comment]
There is a step where a filter is applied to the results. The maxAF filter
only comes into play after checking the likelihood of Mae for every
heterozygous variant.

If you don't want to filter by allele frequency then set those values to 1

1. correct. see the demo/default where this is the case.
2. It will take the variant given in the vcf, query gnomAD, and use that
information to annotate the variant. It doesn't add or remove variants from
your analysis. It's an annotation tool.
3. If you want to annotate your data using gnomAD. Set addAF: true and the
corresponding cutoffs to be 1.

**Comment by capricy** [comment]
I have two runs below:
One with parameters of --
    addAF: false
    maxAF: .01  
    maxVarFreqCohort: 0.05
    
the other one with parameters of --
    addAF: false
    maxAF: 1
    maxVarFreqCohort: 1  

I then got the almost identical outputs: identical lists, with tiny differences only on some p values

How possible could that be? I checked my VCF file and many of the variants have AF >0.05. So I really expected to see more when I set "maxVarFreqCohort to 1" ...

Thanks.

C.

**Comment by nickhsmith** [comment]
Eek! It turns out there was a bug in our code and the maxVarFreqCohort wasn't actually doing anything. I created a fix for that in branch MAE_filter.

so your 2  runs you mentioned should be essentially identical because both of them have addAF false. But with the new branch the config setting will actually affect the final results. It needs to pass that maxVarFreqCohort filter to be considered in the final results table.

**Comment by capricy** [comment]
So what do I need to do over my end for the rerun? Do I need to update the module first? Thanks.

C.

**Comment by nickhsmith** [comment]
if you are working with git you can pull and switch branches to MAE_filter.
If you aren't you can use

`pip install ***@***.***_filter`

which will install the changes.

Then go to your working directory, and update it

`drop update`

Then rerun the snakemake commands

**Comment by nickhsmith** [comment]
if you are working with git you can pull and switch branches to MAE_filter. If you aren't you can use

`pip install git+https://github.com/gagneurlab/drop.git@MAE_filter`

which will install the changes.

Then go to your working directory, and update it

`drop update`

Then rerun the snakemake commands

**Comment by capricy** [comment]
Thanks.

So may I know what is the immediate file before maxVarFreqCohort filtering?

**Comment by nickhsmith** [comment]
Output/processed_results/mae/mae/MAE_results_all_v29.tsv.gz contains all of the data with the annotations. 
Output/processed_results/mae/mae/MAE_results_v29.tsv contains only the data that passes the filters

**Comment by nickhsmith** [comment]
After talking with my colleagues we've decided to keep the rare and cohort frequency information as annotations for the two files mentioned above, but add another file, a subset of the `MAE_results_v29.tsv` called `MAE_results_v29_rare.tsv.` which only contains the rare variants.

It will be up to you to decide which file or information to take out of these final tsv files.

**Comment by capricy** [comment]
I had the latest drop (version 1.1.0) pipeline installed on August 10 (last Thursday) and used it for mae run. My parameters were:
addAF: false 
maxAF: 1 
maxVarFreqCohort: 1  

I saw that the output file, MAE_results_all_v37.tsv.gz, contained column cohort_freq. However, this file only had 644 records, which was way fewer than expected since my previous run with drop 1.0.4 (before you had this new branch) and the same parameters had >1.5 million records.

How should I explain such significant change between drop 1.1.0 and 1.0.4?

Thanks a lot.

C.

**Comment by vyepez88** [comment]
Hi, this shouldn't be the case as there is no subsetting done to the results_all table. Can you please check your:
Number of samples, Number of genes and Number of samples with significant MAE for alternative events that appear in the Results.html file? How different are they?

**Comment by capricy** [comment]
My MAE_results_v37.tsv with drop 1.1.0 has 10 records and MAE_results_v37.tsv with drop 1.0.4 has >54k records.

I further checked the intermediate files and found the outputs from the "filterSNVs.sh" were quite different:
drop 1.1.0 has bcftools norm -m-both, but drop 1.0.4 doesn't have it

Then moving to the outputs of ASEReadCounter.sh, drop 1.1.0 has much smaller output with file around 1.5k file (~100 records), but drop 1.0.4 has output around 2M file(~134K records)

So, here I see that drop 1.1.0 has larger filtered snv records, but much smaller ASE count records

How would you explain such changes?

Thanks.

C.

**Comment by nickhsmith** [comment]
The `bcftools norm -m-both` line splits variants if they are written as multiple alternative alleles. IE. A > C,G into two lines, A > C and then also A > G. So That shouldn't affect your results.

You mentioned that your MAE_results_v37.tsv with 1.0.4 has 54k variants, that is a huge amount of significant calls. Can you confirm that you are using the same `padj_cutoff`?

As for only having 644 records in the MAE_results_all.tsv.gz file that surprises me. Are the DNA vcf files you are using the same as your previous run? A different user had a problem with using gvcf files which lack the necessary annotations to work correctly.

**Comment by capricy** [comment]
I noticed that when A>C,G is split into A>C and A>G, gatk ASEReaDCounter will stop for duplicate error..., which should explain why the output became much smaller

**Comment by capricy** [comment]
another question about this new MAE_results_all_XX_tsv.gv output: what the cohort_freq mean here? I checked my original VCF file and found that AF there was different from this column.

Could you also please explain those columns: AF AF_afrAF_amr AF_eas	AF_nfe	AF_popmax	MAX_AF?

Thanks.

C.

**Comment by nickhsmith** [comment]
AF represents the allele frequency of the variant with respect to all populations worldwide. so AF_eas means Allele frequency east asian descent, afr means african descent, and so on. MAX_AF is the maximum allele frequency within an ethnic population. Cohort freq is the allele frequency within your cohort. if you have 100 samples, what percent of those 100 (and only those 100) have the same variant.

I didn't notice the bug with duplicate variants for the ASEReadcounter, so I'll look into that right away.

**Comment by nickhsmith** [comment]
Could you please share with me the ASEReadCounter log that has the duplicate error? Is your VCF file multi-allelic?

**Comment by capricy** [comment]
from gatk ASEReadCounter run:



A USER ERROR has occurred: More then one variant context at position: chr1:15274

**Comment by nickhsmith** [comment]
Thanks! I was able to reproduce the bug, and have added a fix to the branch `mae_filter_fix` 

https://github.com/gagneurlab/drop/blob/65ceaf0422f5388bf078e6f848eacf304fc24b3f/drop/modules/mae-pipeline/MAE/filterSNVs.sh

This should be added to dev soon, and hopefully the main branch next week

**Comment by capricy** [comment]
I saw you added a "grep" step. I am afraid this may introduce other bugs when parsing vcf files..

**Comment by capricy** [comment]
So, regarding the MAE module outputs, may I say:
1. MAE_results_all.XX.tsv.gz contains all the records
2. MAE_results_XX.tsv is derived from the MAE_results_all.XX.tsv.gz and contains the significant records based on the padj value and alt/ref ratio  
3. MAE_results_XX_rare.tsv is further filtered from the MAE_results_XX.tsv based on maxAF for maxVarFreqCohort


??

Thanks a lot...

C.

**Comment by nickhsmith** [comment]
Correct

**Comment by capricy** [comment]
I checked on frequency information from the file MAE_results_XX_rare.tsv and found something I don't quite understand. Below shows the truncated records:

<img width="828" alt="Screen Shot 2021-09-07 at 11 22 12 PM" src="https://user-images.githubusercontent.com/18124356/132441531-7f1444c1-46f1-451e-8b42-61505100f3a4.png">


My question: for CD44, AF_afr, AF_amr, and AF_nfe were all >0, how did it go that AF_popmax was equal to 0? 
Similar question, for RNMT, AF_afr, AF_amr, and AF_nfe were all greater than AF_popmax. Shouldn't we expect that AF_popmax was greater or equal than any individual ethnic group AF?

Thanks.

C.

**Comment by nickhsmith** [comment]
> I saw you added a "grep" step. I am afraid this may introduce other bugs when parsing vcf files..

I'm sorry I'm on vacation now. This was meant to be a quick fix, but I agree it's not an elegant solution. I will be working more on this in October.

**Comment by capricy** [comment]
While you try to work on the fix, I wonder if you would provide answer to my question in the previous post regarding the AF or AF_XXX from gnomad database?

Further question after reviewing those added AF info: since gnomad provides both filtered and unfiltered AFs, what does DROP use when annotating the output variants?

Thanks.

C.

**Comment by capricy** [comment]
I compared the outputs of MAE_results_all_XXX.tsv.gz with gnomAD browser and found inconsistency. Below is the example:

<img width="928" alt="Screen Shot 2021-09-16 at 5 32 03 PM" src="https://user-images.githubusercontent.com/18124356/133688581-9668ec09-0fb7-45bf-810a-ca812e6ad683.png">

Here PIK3CD gene at position 9781412, the AF_popmax is missing; but gnomAD has it as 0.47
Then  PIK3CD gene at position 9787840, the AF_popmax is 0.46; but gnomAD has it as 0.53

Could you please explain this? Thanks.

C.

**Comment by nickhsmith** [comment]
Thank you for your patience. I'm back in the office, and we looked at this. It seems like the accessor for gnomAD assumes we want the minor allele frequency, and not the alternative allele frequency. Looking at this gnomAD link below, you can see that the alternative allele C is more common than the reference but the frequency reported is 1-the allele freq shown. (1-0.87 = 0.13)
https://gnomad.broadinstitute.org/variant/11-35229673-T-C?dataset=gnomad_r2_1

So for the case of CD44. the alternative allele is actually more common than the reference. We will be working on recalculating the MAX_AF. But you are right, these cases are reported incorrectly which certainly leads to confusion! Thanks for finding this! 

As for the grep fix. It has been refixed in the `mae_filter_fix` branch. Which uses the GATK tool `SelectVariants` to identify the heterozygous variants after splitting a multi-allele multi-sample vcf.

**Comment by capricy** [comment]
How may I incorporate your new fix in the mae_filter_fix branch?

**Comment by nickhsmith** [comment]
Depending on how you installed DROP,

If you have cloned the DROP repository:
you can switch using `git checkout mae_filter_fix` from the DROP git directory.

you can also install it using
`pip install git+https://github.com/gagneurlab/drop.git@mae_filter_fix`

However. The developers have a meeting next week to address some issues, and hopefully get to resolve the MAX_AF issue as well. The goal is to update the dev branch then.

**Comment by vyepez88** [comment]
hi @capricy, were you able to sort this out? All the changes are now reflected in the master branch (v 1.1.1).
