### ISSUE TITLE
Too few IDs in DROP GROUP error when using external data sources

### ISSUE THREAD

**Issue by scharf-f** [gagneurlab/drop#240]
Hello Drop-Team,

I would very much like to try out your tool, but unfortunately I am encountering an issue during the sampleAnnotation step:

> ValueError in line 14 of /PATH/Snakefile:
> Too few IDs in DROP_GROUP splicing, please ensure that it has at least 10 IDs, groups: ['sample-1']
>   File "/PATH/Snakefile", line 14, in <module>
>   File "/root/miniconda3/lib/python3.6/site-packages/drop/config/DropConfig.py", line 69, in __init__
>   File "/root/miniconda3/lib/python3.6/site-packages/drop/config/submodules/AberrantSplicing.py", line 20, in __init__
>   File "/root/miniconda3/lib/python3.6/site-packages/drop/config/submodules/Submodules.py", line 54, in checkSubset

I used external count data as referenced on your github repository. As far as I understand those should be included in the counts, shouldn't they?

The same error occurs when including the aberrantExpression pipeline.

Please find attached the minimal examples of config.yml and the sampleAnnotation files I used.

Help is very much appreciated! Thanks in advance!

Kind regards,
Florentine
[sampleAnnotation.txt](https://github.com/gagneurlab/drop/files/6945202/sampleAnnotation.txt)

[config.yaml.txt](https://github.com/gagneurlab/drop/files/6944948/config.yaml.txt)

**Comment by c-mertes** [comment]
Dear @scharf-f , 
Thank you for trying out DROP and thank you for the detailed report. I'm still working  on the import functionality for splicing counts. Its currently under development. I will let you know as soon as I have a beta release you can try out. But till now only the import for gene expression counts are working.

**Comment by scharf-f** [comment]
Hello @c-mertes,

thank you very much for your response! Unfortunately, I also get an error when using the aberrant expression functionality.

I tried deactivating the aberrantSplicing block and activating the aberrantExpression block in the config.yaml (and adjusting the DROUP_GROUP value in the sampleAnnotation). Everything else is the same as in the previous example. When running

> snakemake sampleAnnotation --cores 8 

I receive this error:

> WARNING: Less than 30 IDs in DROP_GROUP expression
> TypeError in line 14 of /PATH/Snakefile:
> expected str, bytes or os.PathLike object, not NoneType

Any help would be greatly appreciated! 

Thanks in advance,
Florentine

**Comment by mumichae** [comment]
Is PATH your project directory or is it a subdirectory? If so, could you add the following above line 14?

```
print(wbuild.utils.Config())
print(projectDir)
```
Also, make sure that you're running your command from the project directory

**Comment by nickhsmith** [comment]
Could you please run `snakemake aberrantExpression -n` and see if that completes? 
Could you also please run `drop update` which should make sure that the `Scripts` directory is formatted as it should be.

Thank you

**Comment by noorsmal** [comment]
I have the same issue. I added external count files to the sampleAnnotation file and it didn't include these counts when running the drop pipeline. I have tried doing 'snakemake aberrantExpression -n' and tried verything after 'drop update', but in neither case the external counts are added to the analysis.

**Comment by nickhsmith** [comment]
@scharf-f  did you have any updates?

As for @noorsmal :
could you please open a new issues, and include your config file, a selection of your sample_annotation table and the exact error you are getting? As well as confirming the drop version you are using `drop --version`

Thanks

**Comment by nickhsmith** [comment]
We have updated the splicing module to include external splicing to increase the number of samples possible! Please follow the latest documentation and update DROP to version 1.2.1
