### ISSUE TITLE
Full MAE output

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#248]
Is there a way to download to tsv/csv the full mae pipeline output?
The html file does not have that option:

<img width="341" alt="Screen Shot 2021-08-12 at 8 00 57 PM" src="https://user-images.githubusercontent.com/47928628/129284776-58914d0c-ae5f-4e40-8ddb-153533fe0b00.png">

**Comment by nickhsmith** [comment]
it should be generated under `Output/processed_results/mae/<GROUP_NAME>/MAE_results_all_<annotation>.tsv.gz`
