### ISSUE TITLE
Problem with ScanVcfParam

### ISSUE THREAD

**Issue by Mr-Tyrannique** [gagneurlab/drop#252]
Hello everyone !

I use 1.0.5 and when I execute DROP, I have this error message: 

Error: BiocParallel errors
  element index: 1, 2
  first error: invalid class “ScanVcfParam” object: ScanVcfParam: 'geno' cannot be specified if 'samples' is 'NA'
Execution halted

I checked the headers of my vcf to make sure they match the ID I gave but nothing changes. I don't really understand what can I do to fix problem. Someone can help me ? 

Thanks !

**Comment by nickhsmith** [comment]
Could you please be more specific? What exactly were you trying to do, and at which step did the pipeline fail?

It would also be useful if you could use the latest version 1.1.0 which unfortunately isn't on conda yet, but can be installed through github.

**Comment by Mr-Tyrannique** [comment]
Hello ! Yes I can, I try to use mae module and I have a first error in step 27 with this error :
  "Error: BiocParallel errors
    element index: 1, 2
    first error: invalid class “ScanVcfParam” object: ScanVcfParam: 'geno' cannot be specified if 'samples' is 'NA'
  Execution halted"

I search the origin of this error, and I found that in the file _create_matrix_dna_rna_cor.R_ on line 36 and 37 the imports of the objects rna_samples <- snakemake @ params $ rnaIds and mae_res <- snakemake @ input $ mae_res are not done. So that the mae_res and rna_samples objects are empty. I must have made a config error, but I don't see which one...

Here is a print of the SnakeMake object:
 
`object of class "Snakemake"
Slot "input":
[[1]]
[1] "Scripts/MonoallelicExpression/pipeline/QC/create_matrix_dna_rna_cor.R"

$mae_res
NULL

$RScript
[1] "Scripts/MonoallelicExpression/pipeline/QC/create_matrix_dna_rna_cor.R"


Slot "output":
[[1]]
[1] "/data2/HOMEPierre/TESTDROP_2/processed_results/mae/mae/dna_rna_qc_matrix.Rds"

$mat_qc
[1] "/data2/HOMEPierre/TESTDROP_2/processed_results/mae/mae/dna_rna_qc_matrix.Rds"


Slot "params":
[[1]]
NULL

$rnaIds
NULL


Slot "wildcards":
[[1]]
[1] "mae"

$dataset
[1] "mae"


Slot "threads":
[1] 20

Slot "log":
[[1]]
[1] "/data2/HOMEPierre/TESTDROP_2/.drop/tmp/MAE/mae/QC_matrix.Rds"

$snakemake
[1] "/data2/HOMEPierre/TESTDROP_2/.drop/tmp/MAE/mae/QC_matrix.Rds"


Slot "resources":
[[1]]
[1] "tmpdir"

$tmpdir
[1] "/tmp"


Slot "config":
$htmlOutputPath
[1] "/data2/HOMEPierre/TESTDROP_2/HTML_results"

$processedDataPath
[1] "Output/ProcessedData"

$scriptsPath
[1] "Scripts"

$projectTitle
[1] "DROP: Detection of RNA Outliers Pipeline"

$readmePath
[1] "/data2/HOMEPierre/TESTDROP_2/readme.md"

$htmlIndex
[1] "index.html"

$indexWithFolderName
[1] FALSE

$root
[1] "/data2/HOMEPierre/TESTDROP_2"

$hpoFile
[1] "/data2/HOMEPierre/referenceRNASeq/hpo_genes.tsv.gz"

$sampleAnnotation
[1] "/data2/HOMEPierre/TESTDROP_2/sample_annotationFALSEDUPLICATES.tsv"

$geneAnnotation
$geneAnnotation$v38
[1] "/data2/HOMEPierre/referenceRNASeq/gencode.v38.primary_assembly.annotation.gtf"


$genomeAssembly
[1] "GRCh38"

$exportCounts
$exportCounts$geneAnnotations
[1] "v38"

$exportCounts$excludeGroups
NULL


$genome
[1] "/data2/HOMEPierre/referenceRNASeq/GRCh38.primary_assembly.genome.fa"

$aberrantExpression
$aberrantExpression$groups
[1] "fibro"

$aberrantExpression$fpkmCutoff
[1] 1

$aberrantExpression$implementation
[1] "autoencoder"

$aberrantExpression$padjCutoff
[1] 0.05

$aberrantExpression$zScoreCutoff
[1] 3.5

$aberrantExpression$maxTestedDimensionProportion
[1] 3

$aberrantExpression$run
[1] TRUE


$aberrantSplicing
$aberrantSplicing$run
[1] TRUE

$aberrantSplicing$groups
[1] "fibro"

$aberrantSplicing$recount
[1] TRUE

$aberrantSplicing$longRead
[1] FALSE

$aberrantSplicing$keepNonStandardChrs
[1] TRUE

$aberrantSplicing$filter
[1] TRUE

$aberrantSplicing$minExpressionInOneSample
[1] 20

$aberrantSplicing$minDeltaPsi
[1] 0.05

$aberrantSplicing$implementation
[1] "PCA"

$aberrantSplicing$padjCutoff
[1] 0.05

$aberrantSplicing$zScoreCutoff
[1] 0

$aberrantSplicing$deltaPsiCutoff
[1] 0.3

$aberrantSplicing$maxTestedDimensionProportion
[1] 6


$mae
$mae$run
[1] TRUE

$mae$groups
[1] "fibro"

$mae$gatkIgnoreHeaderCheck
[1] TRUE

$mae$padjCutoff
[1] 0.05

$mae$allelicRatioCutoff
[1] 0.8

$mae$addAF
[1] FALSE

$mae$maxAF
[1] 0.001

$mae$maxVarFreqCohort
[1] 0.05

$mae$qcVcf
[1] "/data2/HOMEPierre/referenceRNASeq/qc_vcf_1000G_GRCh38.vcf.gz"

$mae$qcGroups
[1] "mae"

$mae$gnomAD
[1] FALSE


$tools
$tools$gatkCmd
[1] "gatk"

$tools$bcftoolsCmd
[1] "bcftools"

$tools$samtoolsCmd
[1] "samtools"


$wBuildPath
[1] "/home/kave/.conda/envs/drop_env/lib/python3.9/site-packages/wbuild"

$fileRegex
[1] ".*\\.(R|md)"

$allDone
[1] "Output/all.done"


Slot "rule":
[1] "MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R"

Slot "bench_iteration":
[1] NA

Slot "scriptdir":
[1] "/data2/HOMEPierre/TESTDROP_2/Scripts/MonoallelicExpression/pipeline/QC"

Slot "source":
function (...) 
{
    wd <- getwd()
    setwd(snakemake@scriptdir)
    source(...)
    setwd(wd)
}`

I would like to use version 1.1.0 but I cannot install it, and I cannot find any documentation on the update. Maybe you can tell how can I do this ?

Thanks.

**Comment by nickhsmith** [comment]
Yes, sorry for the lack of documentation. You can install the latest version using pip

`pip install git+https://github.com/gagneurlab/drop.git`

This will install the most recent version on github (1.1.0) 
From there you need to go to your DROP working directory and run 

`drop update`

Which should update the internal scripts that have changed. You can proceed to run the pipeline again using snakemake.

**Comment by Mr-Tyrannique** [comment]
Thanks for your help ! I managed to download the new version. 

And I fix my problem, I had this error, because in the configuration file I had specified `run: true` and not indicated the groups (those indicated indicated in the DROP_GROUP column) in the aberrantSplicing and aberrantExpression modules. Therefore during the import, the "groups" variables were dictionaries and not lists.

**Comment by marcDabad** [comment]
Hi all, 
I am using `drop 1.1.14` and still have this error.

**Comment by nickhsmith** [comment]
Could you please share exactly your error and your config file. And what command you are trying to use? 

Thanks

**Comment by marcDabad** [comment]
Error:

```bash
[Tue Mar 29 14:35:04 2022]
rule MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R:
    input: Scripts/MonoallelicExpression/pipeline/QC/create_matrix_dna_rna_cor.R
    output: /scratch/groups/funcgen/rna_illumina/bulk/NAGENCOL/NAGENCOL_14_18_20/drop/Analysis/processed_results/mae/mae/dna_rna_qc_matrix.Rds
    log: /scratch/groups/funcgen/rna_illumina/bulk/NAGENCOL/NAGENCOL_14_18_20/drop/.drop/tmp/MAE/mae/QC_matrix.Rds
    jobid: 533
    wildcards: dataset=mae
    resources: tmpdir=/scratch_tmp

Error: BiocParallel errors
  1 remote errors, element index: 1
  1 unevaluated and other errors
  first remote error: invalid class “ScanVcfParam” object: ScanVcfParam: 'geno' cannot be specified if 'samples' is 'NA'
Execution halted
[Tue Mar 29 14:35:48 2022]
Error in rule MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R:
    jobid: 533
    output: /scratch/groups/funcgen/rna_illumina/bulk/NAGENCOL/NAGENCOL_14_18_20/drop/Analysis/processed_results/mae/mae/dna_rna_qc_matrix.Rds
    log: /scratch/groups/funcgen/rna_illumina/bulk/NAGENCOL/NAGENCOL_14_18_20/drop/.drop/tmp/MAE/mae/QC_matrix.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 308 of /scratch_tmp/tmpzfrltyx6:
Command 'set -euo pipefail;  Rscript --vanilla /scratch/groups/funcgen/rna_illumina/bulk/NAGENCOL/NAGENCOL_14_18_20/drop/.snakemake/scripts/tmpf3_78asm.create_matrix_dna_rna_cor.R' returned non-zero exit status 1.
  File "/scratch_tmp/tmpzfrltyx6", line 308, in __rule_MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R
  File "/scratch/devel/mdabad/env/conda/envs/drop114/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
The code used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-code-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-code-changes)'.
Complete log: .snakemake/log/2022-03-29T143326.454930.snakemake.log

``` 
Config file: https://pastebin.com/fjY1sFHR

**Comment by nickhsmith** [comment]
Looking at your config file in MAE you have the group `all` but you specify that you would like to run the `qcGroups` on samples in the `mae` group. 

You have to change the `qcGroups` to `all` or delete the group `mae` which will by default use all of the MAE `groups`

**Comment by nickhsmith** [comment]
Please let me know if this solves your issue.

**Comment by marcDabad** [comment]
Sorry for the delay, yes it worked. I didn't understand correctly the information from the documentation.

Thanks!

**Comment by thudaniel2333** [comment]
Hi, I'm having the same error although my qc group in the config.yaml file is correctly set:

[Wed Jul 27 17:51:04 2022]
rule MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R:
    input: /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45118150.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/44716038.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46829221.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46367497.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/42700978.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45562809.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46156198.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45630200.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/44529752.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/40428705.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46291309.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46430755.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46251122.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46191187.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46043805.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46234154.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45927082.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46339562.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/43411719.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/47031020.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/40166444.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45269362.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46273334.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46243240.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45574370.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/44821407.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46295185.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45838776.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46399755.Rds, Scripts/MonoallelicExpression/pipeline/QC/create_matrix_dna_rna_cor.R
    output: /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_results/mae/FIBRO_MAE/dna_rna_qc_matrix.Rds
    log: /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/fibro_103/.drop/tmp/MAE/FIBRO_MAE/QC_matrix.Rds
    jobid: 95
    reason: Missing output files: /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_results/mae/FIBRO_MAE/dna_rna_qc_matrix.Rds; Input files updated by another job: /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46273334.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46829221.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/44821407.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45630200.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46399755.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45838776.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45562809.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46234154.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46295185.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45269362.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46043805.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45927082.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46367497.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/40428705.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/42700978.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46291309.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/47031020.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46243240.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46251122.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45574370.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/44716038.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/40166444.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/43411719.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/44529752.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46339562.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46156198.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/45118150.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46430755.Rds, /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_data/mae/RNA_GT/46191187.Rds
    wildcards: dataset=FIBRO_MAE
    threads: 20
    resources: tmpdir=/tmp

Error: BiocParallel errors
  20 remote errors, element index: 1, 3, 4, 6, 7, 8, ...
  9 unevaluated and other errors
  first remote error: invalid class “ScanVcfParam” object: invalid object for slot "samples" in class "ScanVcfParam": got class "integer", should be or extend class "character"
Execution halted
[Wed Jul 27 17:51:24 2022]
Error in rule MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R:
    jobid: 95
    output: /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/mae/processed_results/mae/FIBRO_MAE/dna_rna_qc_matrix.Rds
    log: /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/fibro_103/.drop/tmp/MAE/FIBRO_MAE/QC_matrix.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 308 of /tmp/tmpwlwxtda3:
Command 'set -euo pipefail;  Rscript --vanilla /mnt/work/research/duhk/project/drop/outlier/fibroblast_53/fibro_103/.snakemake/scripts/tmp6_kp8056.create_matrix_dna_rna_cor.R' returned non-zero exit status 1.
  File "/tmp/tmpwlwxtda3", line 308, in __rule_MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R
  File "/mnt/home/duhk/anaconda3/envs/drop/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-07-26T233609.979403.snakemake.log


I've attached a screenshot of the config file below. Could you please help me check what went wrong?

![image](https://user-images.githubusercontent.com/32674759/181405003-2c856991-b192-476f-b0f6-43b4aa5ae581.png)

**Comment by thudaniel2333** [comment]
Update: I solved the issue by adding a line to the MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R script
![image](https://user-images.githubusercontent.com/32674759/181409119-b27c48c7-c6b0-44f9-b1ad-181f6cf26c10.png)

**Comment by vyepez88** [comment]
many thanks @thudaniel2333 for detecting the error and proposing a solution! I added it to the `dev` branch and will be part of the next release: https://github.com/gagneurlab/drop/commit/f1684b690a9b0e0b61cc2db32cc6b25801ce3bb2
