### ISSUE TITLE
sampleannotation.tsv requires DNA_VCF_FILE despite not needing MAE?

### ISSUE THREAD

**Issue by jftchau** [gagneurlab/drop#255]
Dear all, I have been running into this issue of being unable to run DROP on my samples if I don't have the DNA_VCF_FILE.

Here is the scenario if I don't have DNA_VCF_FILE and DNA_ID in my sampleannotation.tsv

ValueError in line 14 of /paedbc01/disk1/home/rnaseq/drop_prenatal/Snakefile:
Incorrect columns in sample annotation file. Missing:
['DNA_VCF_FILE', 'DNA_ID']
  File "/paedbc01/disk1/home/rnaseq/drop_prenatal/Snakefile", line 14, in <module>
  File "/software/drop/1.1.0/lib/python3.9/site-packages/drop/config/DropConfig.py", line 49, in __init__
  File "/software/drop/1.1.0/lib/python3.9/site-packages/drop/config/SampleAnnotation.py", line 27, in __init__
  File "/software/drop/1.1.0/lib/python3.9/site-packages/drop/config/SampleAnnotation.py", line 61, in parse

This is what my config folder looks like on the mae section.
mae:
    run: false
    groups:
        - mito
    gatkIgnoreHeaderCheck: true
    padjCutoff: 0.05
    allelicRatioCutoff: 0.8
    addAF: false
    maxAF: .001
    maxVarFreqCohort: .05
    # VCF-BAM matching
    qcVcf: /paedbc01/disk1/home/rnaseq/drop_prenatal/Data/qc_vcf_1000G_hg19.vcf.gz       # path to common variant file e.g. qc_vcf_1000G.vcf.gz
    qcGroups: mito

Despite not needing dna vcf files for non-mae purposes, it mentions that I am required to enter the columns for DNA_VCF_FILE and DNA_ID. I have also attempted to completely remove the mae section from the config.yaml file and it yields the same results. This is after I perform drop update.

One way to combat this was to create the columns of DNA_VCF_FILE and DNA_ID in the sampleannotation.tsv but keep it empty. This allows me to run drop smoothly until it reaches this step.

[Sun Sep  5 03:21:40 2021]
Finished job 133.
132 of 286 steps (46%) done

[Sun Sep  5 03:21:40 2021]
rule Pipeline_SampleAnnotation_R:
    input: /paedbc01/disk1/home/rnaseq/drop_prenatal/Data/sample_annotation.tsv, Scripts/Pipeline/SampleAnnotation.R
    output: /paedbc01/disk1/home/rnaseq/drop_prenatal/Output_20210903/processed_data/sample_anno/genes_overlapping_HPO_terms.tsv, /paedbc01/disk1/home/rnaseq/drop_prenatal/Output_20210903/html/Scripts_Pipeline_SampleAnnotation.html
    log: /paedbc01/disk1/home/rnaseq/drop_prenatal/.drop/tmp/SampleAnnotation.Rds
    jobid: 284
    resources: tmpdir=/tmp/pbs.1039273.omics

Loading required package: knitr
Loading required package: rmarkdown

processing file: /tmp/pbs.1039273.omics/Rtmptz2I1E/file6c5af456d7820/SampleAnnotation.spin.Rmd
Quitting from lines 72-79 (/tmp/pbs.1039273.omics/Rtmptz2I1E/file6c5af456d7820/SampleAnnotation.spin.Rmd)
Error in file.exists(DNA_VCF_FILE) : invalid 'file' argument
Calls: render ... eval -> [ -> [.data.table -> eval -> eval -> file.exists
Execution halted
[Sun Sep  5 03:21:41 2021]
Error in rule Pipeline_SampleAnnotation_R:
    jobid: 284
    output: /paedbc01/disk1/home/rnaseq/drop_prenatal/Output_20210903/processed_data/sample_anno/genes_overlapping_HPO_terms.tsv, /paedbc01/disk1/home/rnaseq/drop_prenatal/Output_20210903/html/Scripts_Pipeline_SampleAnnotation.html
    log: /paedbc01/disk1/home/rnaseq/drop_prenatal/.drop/tmp/SampleAnnotation.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 256 of /tmp/pbs.1039273.omics/tmp0rwye4z8:
Command 'Rscript --vanilla /paedbc01/disk1/home/rnaseq/drop_prenatal/.snakemake/scripts/tmp7t6gktzo.wBRender.R' returned non-zero exit status 1.
  File "/tmp/pbs.1039273.omics/tmp0rwye4z8", line 256, in __rule_Pipeline_SampleAnnotation_R
  File "/software/python/3.9.2/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /paedbc01/disk1/home/rnaseq/drop_prenatal/.snakemake/log/2021-09-03T190635.529246.snakemake.log

Is it possible to run the AE and AS on drop without vcf files? Thanks

**Comment by vyepez88** [comment]
Without vcf files, both modules can be run using their respective commands:
`snakemake aberrantExpression` or `snakemake aberrantSplicing`

The problem is that the rule `sampleAnnotation` requires vcf files.

**Comment by jftchau** [comment]
I see. This has solved the issue. If I don't run MAE, then I can't simply just run 
`snakemake --cores 1`

Thanks

**Comment by KuechlerO** [comment]
I would say, that this issue still persists, and also the described workaround does not work for me.

E.g. when I execute ` snakemake -n aberrantExpression`,
then I get the following error message:

```
ValueError in line 12 of /sc-scratch/sc-scratch-btg/olik_splicing_project/splice-prediction/Snakemake_DROP/Snakefile:
Incorrect columns in sample annotation file. Missing:
['DNA_VCF_FILE', 'DNA_ID']
  File "/sc-scratch/sc-scratch-btg/olik_splicing_project/splice-prediction/Snakemake_DROP/Snakefile", line 12, in <module>
  File "/home/kuechleo/mambaforge/envs/drop_env/lib/python3.10/site-packages/drop/config/DropConfig.py", line 49, in __init__
  File "/home/kuechleo/mambaforge/envs/drop_env/lib/python3.10/site-packages/drop/config/SampleAnnotation.py", line 27, in __init__
  File "/home/kuechleo/mambaforge/envs/drop_env/lib/python3.10/site-packages/drop/config/SampleAnnotation.py", line 61, in parse
```

**Comment by vyepez88** [comment]
Hi @KuechlerO, does your sample annotation file has the columns DNA_VCF_FILE and DNA_ID? If you don't have VCF files, simply add them and leave them blank.

**Comment by KuechlerO** [comment]
Ah, ok.

Yeah, updating to `drop, version 1.1.3`, and inserting the empty columns `DNA_VCF_FILE` and `DNA_ID` in  the sample-annotation file functions for me as workaround.
I can even execute now ` snakemake -n`.

Alright, I'm looking forward for the output 👍

**Comment by vyepez88** [comment]
great!
