### ISSUE TITLE
04_fit_hyperparameters_FraseR.R error message

### ISSUE THREAD

**Issue by jftchau** [gagneurlab/drop#257]
Error message in the FRASER pipeline. How do I fix the issue with h(simpleError(msg, call))? I have attempted to perform drop update to fix this issue, but not sure what the problem?

44 of 66 steps (67%) done

[Sun Sep  5 05:16:25 2021]
rule AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R:
    input: /paedbc01/disk1/home/rnaseq/drop_HKU_all/Output_20210831/processed_data/aberrant_splicing/datasets/savedObjects/all/filter.done, Scripts/AberrantSplicing/pipeline/FRASER/04_fit_hyperparameters_FraseR.R
    output: /paedbc01/disk1/home/rnaseq/drop_HKU_all/Output_20210831/processed_data/aberrant_splicing/datasets/savedObjects/all/hyper.done
    log: /paedbc01/disk1/home/rnaseq/drop_HKU_all/.drop/tmp/AS/all/04_hyper.Rds
    jobid: 498
    wildcards: dataset=all
    resources: tmpdir=/tmp/pbs.1039409.omics

Load packages
Loading assay: rawCountsJ
Loading assay: psi5
Loading assay: psi3
Loading assay: rawOtherCounts_psi5
Loading assay: rawOtherCounts_psi3
Loading assay: delta_psi5
Loading assay: delta_psi3
Loading assay: rawCountsSS
Loading assay: theta
Loading assay: rawOtherCounts_theta
Loading assay: delta_theta
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'unique': 'to' must be a finite number
Calls: %>% -> unique -> seq -> seq.default
Execution halted
[Sun Sep  5 05:16:46 2021]
Error in rule AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R:
    jobid: 498
    output: /paedbc01/disk1/home/rnaseq/drop_HKU_all/Output_20210831/processed_data/aberrant_splicing/datasets/savedObjects/all/hyper.done
    log: /paedbc01/disk1/home/rnaseq/drop_HKU_all/.drop/tmp/AS/all/04_hyper.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 206 of /tmp/pbs.1039409.omics/tmp88kselmq:
Command 'Rscript --vanilla /paedbc01/disk1/home/rnaseq/drop_HKU_all/.snakemake/scripts/tmp1l5l5a5l.04_fit_hyperparameters_FraseR.R' returned non-zero exit status 1.
  File "/tmp/pbs.1039409.omics/tmp88kselmq", line 206, in __rule_AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R
  File "/software/python/3.9.2/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /paedbc01/disk1/home/rnaseq/drop_HKU_all/.snakemake/log/2021-09-05T015044.488512.snakemake.log

Thanks!

**Comment by vyepez88** [comment]
We've never seen that error before. Two things that come to my mind:
- be sure you have `filter: true` in the `aberrantSplicing` dictionary in the config file
- be sure the server has enough memory

**Comment by projectoriented** [comment]
I recently had the same error but allocated 180G of memory fixed the problem 👍 .

**Comment by nickhsmith** [comment]
@jftchau Have you managed to solve this by allocating more memory?

Thanks in advance.

**Comment by jftchau** [comment]
To update, I have rerun everything with a brand new snakemake file and have still encountered the same error message. I have allotted 400G of memory to run this and it was still insufficient with the error message still appearing. For reference, my original drop run, the filter is true in the aberrantSplicing dictionary in the config file. Are there any other suggestions?

Thanks in advance

**Comment by nickhsmith** [comment]
That does seem like a lot of memory. Does it keep failing in the same location? When it tries to fit the hyperparameters? Sorry for the delayed response.

Just for a sanity check, are you using the most recent version of DROP? Did you use the conda build (it was only updated a couple of weeks ago). Thanks

**Comment by vyepez88** [comment]
Also have a look at the Counting summary html (`Output/html/Scripts_AberrantSplicing_pipeline_Counting_DatasetsF.html`). How many junctions do you originally count? How many are there after the filtering? It should look similar to this: https://www.cmm.in.tum.de/public/paper/drop_analysis/webDir/html/aberrantSplicing/all_countSummary.html

**Comment by jftchau** [comment]
Hi Nick, I have repeated the drop pipeline and it keeps failing at the same point, which is the 04_fit_hyperparameters_FraseR.R error message. Perhaps there is something wrong with my config.yaml file? or the sample size is too large? For your sanity, I am using drop/1.1.0.

I have repeated this on a smaller cohort and it was able to generate the results. (This cohort, I am running with GTex control samples; final size 118 samples; Smaller cohort, 42 samples without controls)

To answer Vyepez88's question, the HTML folder have not generated the HTML file you are looking for. I am not sure which file in the processed_data would help with the question on how many junctions counted?

I hope this information helps? Please let me know how to facilitate this process.

**Comment by vyepez88** [comment]
Hi Jeffrey,
To check your resources, can you please run the following in the terminal:
```
    free -m -h # look at the Mem row
    lscpu # look at the CPUs row
```
The following configuration for the config file should work:
```
aberrantSplicing:
  groups: 
    - group1
  minIds: 10
  recount: false
  longRead: false
  filter: true
  minExpressionInOneSample: 20
  minDeltaPsi: 0
  correction: PCA
  deltaPsiCutoff : 0.3
  padjCutoff: .1
  maxTestedDimensionProportion: 6
  keepNonStandardChrs: false
```
You can load the FRASER dataset (fds) object located by executing the following in R:
```
library(FRASER)
fds <- readRDS('{root_folder}/processed_data/aberrant_splicing/datasets/savedObjects/{DROP_GROUP}/fds-object.RDS')
dim(fds)
```

**Comment by jftchau** [comment]
Dear Vicente,

Here is the output for 

`free -m -h # look at the Mem row`
              total        used        free      shared  buff/cache   available
Mem:           125G         12G        9.1G        172M        104G        111G

`lscpu`
CPU(s):                48
CPU MHz:               1261.938
CPU max MHz:           2900.0000
CPU min MHz:           1200.0000

I am currently running with the new config file and I will update when there are results. Thanks!

**Comment by jftchau** [comment]
Dear Vicente,

The same error message showed up.

[Sat Nov 20 11:00:19 2021]
Error in rule AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R:
    jobid: 498
    output: /paedbc01/disk1/home/rnaseq/drop_HKU_all/Output_20211116/processed_data/aberrant_splicing/datasets/savedObjects/all/hyper.done
    log: /paedbc01/disk1/home/rnaseq/drop_HKU_all/.drop/tmp/AS/all/04_hyper.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 206 of /tmp/pbs.1073600.omics/tmpua28cc5i:
Command 'Rscript --vanilla /paedbc01/disk1/home/rnaseq/drop_HKU_all/.snakemake/scripts/tmpfkjjit6q.04_fit_hyperparameters_FraseR.R' returned non-zero exit status 1.
  File "/tmp/pbs.1073600.omics/tmpua28cc5i", line 206, in __rule_AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R
  File "/software/python/3.9.2/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /paedbc01/disk1/home/rnaseq/drop_HKU_all/.snakemake/log/2021-11-16T034637.989552.snakemake.log

I have attached my config file for aberrant splicing below.
`aberrantSplicing:
    groups:
        - all
    recount: false
    longRead: false
    keepNonStandardChrs: true
    filter: true
    minExpressionInOneSample: 20
    minDeltaPsi: 0
    implementation: PCA
    padjCutoff: 0.1
    zScoreCutoff: 0
    deltaPsiCutoff: 0.3
    maxTestedDimensionProportion: 6
`

Here is the result for the previous question you have asked
`> fds <- readRDS("fds-object.RDS")
> dim(fds)
[1]   0 117`

**Comment by vyepez88** [comment]
It seems all your junctions were filtered out.
Can you run:
```
library(FRASER)
fds <- readRDS('{root_folder}/processed_data/aberrant_splicing/datasets/savedObjects/raw-{DROP_GROUP}/fds-object.RDS')
dim(fds)
```

**Comment by jftchau** [comment]
Here is the result

`> fds2 <- readRDS("fds-object.RDS")
> dim(fds2)
[1] 1259559     117`

**Comment by vyepez88** [comment]
Can you please run the following:
```
library(FRASER)
fds <- readRDS('{root_folder}/processed_data/aberrant_splicing/datasets/savedObjects/raw-{DROP_GROUP}/fds-object.RDS')
minExpressionInOneSample <- 20
minDeltaPsi <- 0
fds <- filterExpressionAndVariability(fds, 
                        minExpressionInOneSample = minExpressionInOneSample,
                        minDeltaPsi = minDeltaPsi,
                        filter=TRUE)
dim(fds)
```

**Comment by jftchau** [comment]
This is the generated result and error message.

Thanks

```
> fds3 <- filterExpressionAndVariability(fds2,
+     minExpressionInOneSample = minExpressionInOneSample,
+     minDeltaPsi = minDeltaPsi,
+     filter=TRUE
+ )
Mon Nov 22 23:41:17 2021: Filtering out introns with low read support ...
Error in .Call2("C_h5getdimscales", filepath, name, scalename, PACKAGE = "HDF5Array") : 
  H5Fis_hdf5() returned an error
```

**Comment by vyepez88** [comment]
can you replace the second line in the code I sent you with:
```
dataset    <- "all"
workingDir <- "{root_folder}/processed_data/aberrant_splicing/datasets"
fds <- loadFraserDataSet(dir=workingDir, name=paste0("raw-", dataset))
```
and rerun the filtering function?
