### ISSUE TITLE
Error when using RefSeq GTF file

### ISSUE THREAD

**Issue by baoyl818** [gagneurlab/drop#259]
Hello , dear friend

I have successfully run DROP aberrantExpression pipeline with GeneCode GTF file. But if i use RefSeq GTF , it allways failed with the following error message : 
---------------------------------------------------------------
Import genomic features from the file as a GRanges object ... WARNING: GENE_ANNOTATION must be a column in the sample annotation table, ANNOTATION is the old column name and will be deprecated in the future

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmpgro1wdcw

Building DAG of jobs...
Job counts:
	count	jobs
	1	aberrantExpression_mergeBamStats
	1
Error: Directory cannot be locked. This usually means that another Snakemake instance is running on this directory. Another possibility is that a previous run exited unexpectedly.
[Fri Oct  1 11:00:19 2021]
Finished job 12.
3 of 13 steps (23%) done
[Fri Oct  1 11:00:19 2021]
Finished job 6.
4 of 13 steps (31%) done
OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... Error in .make_splicings(exons, cds, stop_codons) : 
  some CDS cannot be mapped to an exon
Calls: makeTxDbFromGFF -> makeTxDbFromGRanges -> .make_splicings
In addition: Warning message:
In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
Execution halted
[Fri Oct  1 11:00:52 2021]
**Error in rule AberrantExpression_pipeline_Counting_preprocessGeneAnnotation_R**:
    jobid: 5
    output: /work/BI/ylbao/5.rd_jobs/1.rna/36.20210929.1_rna/2.analyze/MS21011553/07_DROPExp/MS21011553P1_trio/Out/processed_data/aberrant_expression/RefSeq/txdb.db, /work/BI/ylbao/5.rd_jobs/1.rna/36.20210929.1_rna/2.analyze/MS21011553/07_DROPExp/MS21011553P1_trio/Out/processed_data/aberrant_expression/RefSeq/count_ranges.Rds, /work/BI/ylbao/5.rd_jobs/1.rna/36.20210929.1_rna/2.analyze/MS21011553/07_DROPExp/MS21011553P1_trio/Out/processed_data/aberrant_expression/RefSeq/gene_name_mapping_RefSeq.tsv
    log: /work/BI/ylbao/5.rd_jobs/1.rna/36.20210929.1_rna/2.analyze/MS21011553/07_DROPExp/MS21011553P1_trio/.drop/tmp/AE/RefSeq/preprocess.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 64 of /tmp/tmpv57ly9v7:
Command 'set -euo pipefail;  Rscript --vanilla /work/BI/ylbao/5.rd_jobs/1.rna/36.20210929.1_rna/2.analyze/MS21011553/07_DROPExp/MS21011553P1_trio/.snakemake/scripts/tmpzu__so2r.preprocessGeneAnnotation.R' returned non-zero exit status 1.
  File "/work/BI/ylbao/1.tools/miniconda3/envs/drop/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2330, in run_wrapper
  File "/tmp/tmpv57ly9v7", line 64, in __rule_AberrantExpression_pipeline_Counting_preprocessGeneAnnotation_R
  File "/work/BI/ylbao/1.tools/miniconda3/envs/drop/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 569, in _callback
  File "/work/BI/ylbao/1.tools/miniconda3/envs/drop/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/work/BI/ylbao/1.tools/miniconda3/envs/drop/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 555, in cached_or_run
  File "/work/BI/ylbao/1.tools/miniconda3/envs/drop/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2362, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /work/BI/ylbao/5.rd_jobs/1.rna/36.20210929.1_rna/2.analyze/MS21011553/07_DROPExp/MS21011553P1_trio/.snakemake/log/2021-10-01T105622.184864.snakemake.log
---------------------------------------------------------------

My bam is from STAR with RefSeq GTF,  gene count matrix is from htseq-count with RefSeq GTF. So, in all related steps , the GTF file are all RefSeq GTF. I cannot find the errorus reason. Please help me to check it, thank you very much. 

Best

**Comment by vyepez88** [comment]
Hi, we parse gtf files using the function `makeTxDbFromGFF` from the `GenomicFeatures` Bioconductor package. It seems the latest RefSeq gtf files are not stable (see https://github.com/Bioconductor/GenomicFeatures/issues/26). I also tried a couple of older versions and still didn't work https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/. 
For now, stick to the Gencode gtf file until that issue is resolved.

**Comment by baoyl818** [comment]
OK, Thanks very much.
