### ISSUE TITLE
No splice junction detected with FRASER

### ISSUE THREAD

**Issue by Mr-Tyrannique** [gagneurlab/drop#272]
Hello,

I am trying to use the Aberrant Splice Module, and am not detecting any splice junction on all of my samples, even though I know I must find at least one in one of my samples. I checked the script and saw that it was FRASER's `countSplitReads` function doing this counting, but I haven't seen any information about this issue in their documentation. Do you have any idea explaining this? A step in the processing of BAMS files that I have forgotten?

NB: I am in the test phase and I do not have enough data, so I copied my original files three times to be able to run the module.

Logs: 

[2021-11-08T124619.979926.snakemake.log](https://github.com/gagneurlab/drop/files/7498211/2021-11-08T124619.979926.snakemake.log)

Part of standard output (I do some printing to try to debug): 

[Mon Nov  8 13:03:10 2021]
Finished job 17.
1 of 38 steps (3%) done
Select jobs to execute...

[Mon Nov  8 13:03:10 2021]
rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    input: /data2/HOMEPierre/TESTDROP_2/Outputs/processed_data/aberrant_splicing/datasets/cache/raw-fibro/fds.done, Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
    output: /data2/HOMEPierre/TESTDROP_2/Outputs/processed_data/aberrant_splicing/datasets/cache/raw-fibro/sample_tmp/splitCounts/sample_GANS_RNA_BIS.done
    log: /data2/HOMEPierre/TESTDROP_2/.drop/tmp/AS/fibro/splitReads/GANS_RNA_BIS.Rds
    jobid: 7
    wildcards: dataset=fibro, sample_id=GANS_RNA_BIS
    threads: 3
    resources: tmpdir=/tmp

Load packages
Loading required package: rtracklayer
[1] "fibro"
[1] "/data2/HOMEPierre/TESTDROP_2/Outputs/processed_data/aberrant_splicing/datasets"
Mon Nov  8 13:03:19 2021: Count split reads for sample: GANS_RNA_BIS
Mon Nov  8 13:44:00 2021: fibro, GANDY_RNA_BIS no. splice junctions (split counts) = 0
[1] TRUE
[Mon Nov  8 13:44:00 2021]
Finished job 15.
2 of 38 steps (5%) done
Select jobs to execute...

[Mon Nov  8 13:44:00 2021]
rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    input: /data2/HOMEPierre/TESTDROP_2/Outputs/processed_data/aberrant_splicing/datasets/cache/raw-fibro/fds.done, Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
    output: /data2/HOMEPierre/TESTDROP_2/Outputs/processed_data/aberrant_splicing/datasets/cache/raw-fibro/sample_tmp/splitCounts/sample_SAAC_RNA_TER.done
    log: /data2/HOMEPierre/TESTDROP_2/.drop/tmp/AS/fibro/splitReads/SAAC_RNA_TER.Rds
    jobid: 12
    wildcards: dataset=fibro, sample_id=SAAC_RNA_TER
    threads: 3
    resources: tmpdir=/tmp

Load packages
Loading required package: rtracklayer
[1] "fibro"
[1] "/data2/HOMEPierre/TESTDROP_2/Outputs/processed_data/aberrant_splicing/datasets"
Mon Nov  8 13:44:09 2021: Count split reads for sample: SAAC_RNA_TER
Mon Nov  8 13:44:28 2021: fibro, GANDY_RNA no. splice junctions (split counts) = 0
[1] TRUE
[Mon Nov  8 13:44:28 2021]
Finished job 14.
3 of 38 steps (8%) done

**Comment by nickhsmith** [comment]
Have you looked at the samples on IGV to confirm that you indeed have split reads? The other thing you can try is to check them yourself on R

```
library("GenomicAlignments")
galignment <- readGAlignmentPairs( YOUR_BAM_FILE )
jc <- summarizeJunctions(galignment)
```

This should at the very least show that the reads are being read. If not it could point to errors in your BAM file.
`galignment` should be the alignment of your BAM file
`jc` should be the unique junctions

**Comment by vyepez88** [comment]
do you have any updates on this @Mr-Tyrannique?

**Comment by Mr-Tyrannique** [comment]
Yes, it does not work for two reasons. Firstly because I specified `--alignIntronMin 10`& `--alignIntronMax 25000` in the STAR command and secondly because I used bam files that went through GATK's SplitNCigarReads function. I've used this command for variant calling, but since it splits reads, splicing events are not detectable.

**Comment by vyepez88** [comment]
Did you try remapping?

**Comment by vyepez88** [comment]
do you have any updates on this @Mr-Tyrannique ?

**Comment by Mr-Tyrannique** [comment]
Yes, we remapping and all works !

**Comment by vyepez88** [comment]
great to hear!
