### ISSUE TITLE
error in aberrant expression pipeline with external count

### ISSUE THREAD

**Issue by noorsmal** [gagneurlab/drop#275]
I get an error in the aberrant expression module during the mergeCounts rule:

Error in rule AberrantExpression_pipeline_Counting_mergeCounts_R:
    jobid: 5
    output: data/batch1_sibs1/processed_data/aberrant_expression/v34/outrider/index/total_counts.Rds
    log: /home/noor/transcriptomics/drop_batch1/.drop/tmp/AE/v34/index/merge.Rds (check log file(s) for error message)

Traceback (most recent call last):
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2461, in run_wrapper
    raise ex
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2418, in run_wrapper
    run(
  File "/tmp/tmpnholo09m", line 156, in __rule_AberrantExpression_pipeline_Counting_mergeCounts_R
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/script.py", line 1371, in script
    executor.evaluate()
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/script.py", line 718, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/script.py", line 414, in _execute_cmd
    return shell(
  File "/home/noor/miniconda3/envs/drop2/lib/python3.10/site-packages/snakemake/shell.py", line 266, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  Rscript --vanilla /home/noor/transcriptomics/drop_batch1/.snakemake/scripts/tmp6jg408bq.mergeCounts.R' returned non-zero exit status 1.

I did this in R

> snakemake <- readRDS(".drop/tmp/AE/v34/index/merge.Rds")
> snakemake@input
(see input_mergeCounts.txt)
> source("Scripts/AberrantExpression/pipeline/Counting/mergeCounts.R")
(see output_mergeCounts.txt)

I tried two different gencode files for v34, in case the problem was a mismatch here, but error remained the same. What gencode v34 gtf file was used to create the external gene counts?
[SampleAnnotation_batch1.txt](https://github.com/gagneurlab/drop/files/7556361/SampleAnnotation_batch1.txt)
[config.txt](https://github.com/gagneurlab/drop/files/7556362/config.txt)
[input_mergeCounts.txt](https://github.com/gagneurlab/drop/files/7556363/input_mergeCounts.txt)
[Output_mergeCounts.txt](https://github.com/gagneurlab/drop/files/7556364/Output_mergeCounts.txt)

I also tried putting the external count files in a different drop_group, and in this case the mergeCounts rule worked, but I got an error later during the runOutrider step.

**Comment by vyepez88** [comment]
Hi, from what I see, your files are hg38, while the imported counts are hg19. This makes them incompatible. 
You were right about using gencode v34, but we used the one with liftover to hg19 (https://www.gencodegenes.org/human/release_34lift37.html).
Try running your pipeline without the external counts, does it work?

**Comment by noorsmal** [comment]
Are there any plans to release the hg38 version of the external counts? Or do you know of other alternatives?

When I run the pipeline without the external counts, I get a different error:

MissingOutputException in line 227 of /tmp/tmp7ua7zjqk:
Job Missing files after 5 seconds:
data/batch1_sibs1/processed_results/aberrant_expression/v34/outrider/index/ods.Rds
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 47 completed successfully, but some output files are missing. 47

job 47 is this one:
rule AberrantExpression_pipeline_OUTRIDER_runOutrider_R:
    input: data/batch1_sibs1/processed_results/aberrant_expression/v34/outrider/index/ods_unfitted.Rds, Scripts/AberrantExpression/pipeline/OUTRIDER/runOutrider.R
    output: data/batch1_sibs1/processed_results/aberrant_expression/v34/outrider/index/ods.Rds
    log: /home/noor/transcriptomics/drop_batch1/.drop/tmp/AE/v34/index/runOUTRIDER.Rds
    jobid: 47
    wildcards: annotation=v34, dataset=index
    threads: 16
    resources: tmpdir=/tmp

Again I tried in R:

> runoutrider <- readRDS(".drop/tmp/AE/v34/index/runOUTRIDER.Rds")
> runoutrider@input
[[1]]
[1] "data/batch1_sibs1/processed_results/aberrant_expression/v34/outrider/index/ods_unfitted.Rds"

[[2]]
[1] "Scripts/AberrantExpression/pipeline/OUTRIDER/runOutrider.R"

$ods
[1] "data/batch1_sibs1/processed_results/aberrant_expression/v34/outrider/index/ods_unfitted.Rds"

$RScript
[1] "Scripts/AberrantExpression/pipeline/OUTRIDER/runOutrider.R"

When I look in the "data/batch1_sibs1/processed_results/aberrant_expression/v34/outrider/index/ods_unfitted.Rds" folder, there are three files
ods-20211118.Rds 11344 kb
ods_unfitted.Rds      2137 kb
ods.Rds                          1 kb (shows as a link)

**Comment by vyepez88** [comment]
We plan to share the counts of all GTEx tissues in genome build hg38 soon. 
The script causing the error creates a symlink between ods-date and ods. I've seen cases before where the creation of the link doesn't work, for example due to not having rights. Can you create the link manually?

**Comment by noorsmal** [comment]
I was able to create the link manually and complete the workflow. I think the problem was that to create a softlink you need the full datapath, and the path given by the runOutrider script only starts within the directory of the snakefile. 

The soft link when it wasn't working was:
/data/batch1_sibs1/processed_results/aberrant_expression/v34/outrider/index/ods-20211118.Rds

and the working link created manually:
/home/noor/transcriptomics/drop_batch1/data/batch1_sibs1/processed_results/aberrant_expression/v34/outrider/index/ods-20211118.Rds

Could you give a time-estimate on the release of the GTEx genecounts?

**Comment by vyepez88** [comment]
Indeed, full paths have to be given in the config file. 
We plan to release them this year.

**Comment by vyepez88** [comment]
Hi @noorsmal, we just uploaded the GTEx hg38 counts. You can find them here: https://zenodo.org/record/6078397#.YhOuO-rMIUE
