### ISSUE TITLE
Extract RPKM value 

### ISSUE THREAD

**Issue by Ennaim1** [gagneurlab/drop#280]
Can I extract RPKM value using excel instead of R?

**Comment by nickhsmith** [comment]
I am unsure of what you are trying to do. Do you have external counts that you are trying to use as input? Or are you hoping to take the results of the DROP counting and export them to excel?

**Comment by Ennaim1** [comment]
I am hoping to take the results of DROP counting and export them to excel,
as I am not too familiar with R. Thanks!

**Comment by nickhsmith** [comment]
It's not something we export, or generally work with. FRASER and OUTRIDER both count reads, but for very different applications. OUTRIDER for example is looking at expression only at the gene level, and FRASER is looking only for spliced reads. 

However if this is something you really need, you can load the `ods_unfitted.Rds` object in R, and use the OUTRIDER `fpkm` function to calculate the fpkm. which you can export to a tsv. But you'll have to do it in R. 

```
library(OUTRIDER)
ods <- readRDS("PATH_TO_ODS_UNFITTED.rds")
fpkm <- OUTRIDER::fpkm(ods)
write.csv(fpkm,"NAME_OF_CSV_FILE.csv")
```

You can then open the csv file in excel.

**Comment by Ennaim1** [comment]
Thanks!

I am trying to look at the expression level of different genes across all
of my 56 samples, just wondering if TMP can also be obtained?
Otherwise, there would be inter-sample differences if RPKM is used, right?

**Comment by vyepez88** [comment]
Hi, you can covert FPKM into TPM by dividing the each FPKM value by the sum of all FPKM values of the respective sample, and multiplying this by 1 million. 
I highly recommend you not to do any bioinformatics analysis in Excel besides looking at or subsetting results tables.
