### ISSUE TITLE
R package dependecy issues. Pipeline_SampleAnnotation_R errors.

### ISSUE THREAD

**Issue by jcs3632** [gagneurlab/drop#283]
I installed drop using `conda create -n drop_env -c conda-forge -c bioconda drop` but it appears that I am running into some package issues when I run `snakemake --cores 1` for the drop_demo. Here are the R package errors I see. 

```
Loading required package: knitr
Error: package or namespace load failed for ‘knitr’:
 package ‘xfun’ was installed before R 4.0.0: please re-install it
Loading required package: rmarkdown
Error: package or namespace load failed for ‘rmarkdown’:
 package ‘xfun’ was installed before R 4.0.0: please re-install it
Warning message:
package ‘rmarkdown’ was built under R version 4.1.2
Error: object 'opts_knit' not found
Execution halted
```

There's also another error in Pipeline_SampleAnnotation_R.

```
Error in rule Pipeline_SampleAnnotation_R:
    jobid: 106
    output: drop_demo/Output/processed_data/sample_anno/genes_overlapping_HPO_terms.tsv, drop_demo/Output/html/Scripts_Pipeline_SampleAnnotation.html
    log: drop_demo/.drop/tmp/SampleAnnotation.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 323 of /tmp/tmp2wfnv76q:
Command 'set -euo pipefail;  Rscript --vanilla drop_demo/.snakemake/scripts/tmp9zxlngtj.wBRender.R' returned non-zero exit status 1.
  File "/storage/tmp/tmp2wfnv76q", line 323, in __rule_Pipeline_SampleAnnotation_R
  File "/storage/miniconda/envs/drop_env/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

I tried using R version 4.1.0 and Bioconductor 3.14 and still saw the same thing. How else can I install DROP?

**Comment by nickhsmith** [comment]
It seems like there is a conflict with a previous R version. Could you please check the R version within that environment?
```
conda activate drop_env
R --version
```
You can also try to reinstall `xfun` as indicated in your error message. `install.packages("xfun")` or `update.packages("xfun")`

**Comment by jcs3632** [comment]
Yes, it was an issue with my R. I was able to fix it by removing all packages and re-installing them. I followed this stackoverflow post. https://stackoverflow.com/questions/63390194/package-xxx-was-installed-before-r-4-0-0-please-re-install-it . Hopefully this can help someone in the future. Thanks!
