### ISSUE TITLE
MAE QC output interpretation

### ISSUE THREAD

**Issue by capricy** [gagneurlab/drop#286]
Hi DROP support team,

My QC html output shows 2 samples that "were annotated to match but do not" (see below):

====
![image](https://user-images.githubusercontent.com/18124356/150021694-60197c43-de4e-4cf0-87c0-073c907e3fca.png)

====

May I how what does the value mean here and what was the cutoff value for a sample identified like this?

Thanks.

Kind regards,

C.

**Comment by vyepez88** [comment]
Hi, we have a predefined cutoff of 0.85 which has worked well on our experience. We plan to have that value as a parameter in the config. You can check the histogram to see whether the 2 sample combinations indeed are out of the rest of the matching samples or not.

**Comment by capricy** [comment]
Where do I find the histogram? I see the QC only output count ~ % of overlapping variants.

**Comment by vyepez88** [comment]
in the same html, just above the section `Identify matching samples`

**Comment by capricy** [comment]
![image](https://user-images.githubusercontent.com/18124356/150204581-16deac55-f698-4356-a68c-8e0abfb1fbbe.png)

Here is the plot I have above the section "Identify matching samples". How may I figure out the 2 samples are outliers? Does the red arrow indicate the two samples outlined by the table? Thanks.

C.

**Comment by vyepez88** [comment]
Hi, yes, from the table you see that there are 2 samples with values 0.766 and 0.797 which correspond to the ones that you have pointed out. These samples can, nonetheless, still match each other. Have a look at the sequencing protocols or the number of variants of each of them (maybe they have too many variants due to some contamination?). Could they be relatives (eg siblings)?

**Comment by capricy** [comment]
Thanks. 

My next question is: 

How does the QC calculate the median of matching samples value? I wonder if the values of these two sample were included in the "matching samples" or "not matching samples"? 

C.

**Comment by vyepez88** [comment]
Median of matching samples -> median of samples above the cutoff.
Those two samples were included in the 'not matching samples'.

**Comment by capricy** [comment]
I see. Thank you.
