### ISSUE TITLE
Cannot install drop

### ISSUE THREAD

**Issue by gdeoli** [gagneurlab/drop#287]
Hi,

It might be something trivial, but 'm facing some difficulties in installing drop. I've created a new conda env, but drop is not installed.

`conda install -c conda-forge -c bioconda drop`

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: 

And it appears to freeze at this step

Any thoughts?

**Comment by nickhsmith** [comment]
DROP, unfortunately, has a lot of dependencies. You can try to use `mamba`
instead of `conda` It should be the exact same as we describe in our
installation guide but using mamba instead:

`mamba create -n drop_env -c conda-forge -c bioconda drop`

**Comment by nickhsmith** [comment]
DROP, unfortunately, has a lot of dependencies. You can try to use `mamba`
instead of `conda` It should be the exact same as we describe in our
installation guide but using mamba instead:

`mamba create -n drop_env -c conda-forge -c bioconda drop`

**Comment by gdeoli** [comment]
@nickhsmith thsanks for the reply. Mamba indeed did a better job. Perhaps, that should be added to the README.

A thing that happened, though, that you should be aware, is that it appears markdown is not installed within the env. After I installed it, everything went fine. 

```
rule AberrantSplicing_pipeline_Counting_00_define_datasets_from_anno_R:
    input: /home/ec2-user/dockerTest/dropDemo/Data/sample_annotation.tsv, Scripts/AberrantSplicing/pipeline/Counting/00_define_datasets_from_anno.R
    output: /home/ec2-user/dockerTest/dropDemo/Output/processed_data/aberrant_splicing/annotations/fraser.tsv, /home/ec2-user/dockerTest/dropDemo/Output/html/AberrantSplicing/annotations/fraser.html
    log: /home/ec2-user/dockerTest/dropDemo/.drop/tmp/AS/fraser/00_defineDataset.Rds
    jobid: 50
    wildcards: dataset=fraser
    resources: tmpdir=/tmp

Loading required package: knitr
Loading required package: rmarkdown
[1] TRUE


processing file: /tmp/RtmpvkiKlq/file19442ab68cd2/00_define_datasets_from_anno.spin.Rmd
  |............                                                                                                  |  11%
  ordinary text without R code

  |........................                                                                                      |  22%
label: unnamed-chunk-1
Load packages
Quitting from lines 26-29 (/tmp/RtmpvkiKlq/file19442ab68cd2/00_define_datasets_from_anno.spin.Rmd)
Error in library(markdown) : there is no package called 'markdown'
Calls: render ... suppressPackageStartupMessages -> withCallingHandlers -> library

Execution halted
```

**Comment by nickhsmith** [comment]
Yes we are aware. In the `dev` branch, we have made these changes, but have yet to push them to the `master` branch. Thanks for your interest in DROP.
```
