### ISSUE TITLE
Control samples at aberrant expressed genes .

### ISSUE THREAD

**Issue by marcDabad** [gagneurlab/drop#291]
Hi all, 

I found that outrider table reports some aberrant expressed gens coming from external controls. Is it possible?

We used as external data one set that you upload on you README at github. 

We specified same drop_group. 

Thanks,

**Comment by vyepez88** [comment]
Hi Marc. Yes, OUTRIDER reports all outlier genes, independently of whether they're from local or external count matrices.

**Comment by marcDabad** [comment]
May be it is a naive question:
should have same drop_group cases and control samples? or should be different?

Thanks,

**Comment by vyepez88** [comment]
It must be the same drop_group

**Comment by nickhsmith** [comment]
As Vicente says, you want to group all of the samples together so that you
have a better understanding of the expression profile of any genes in
question. Because DROP is for outlier detection you want to treat every
sample to see how different it is from the general patterns of the other
samples.

**Comment by marcDabad** [comment]
Hi @vyepez88  and @nickhsmith  I've done it properly but it was strange to me to see outliers coming from 'control' samples. 
I have to assume that is possible.Is it right?

Thanks for your help.

**Comment by vyepez88** [comment]
Hi Marc, yes, control samples can also have outliers.

**Comment by vyepez88** [comment]
We've done analyses using only controls from GTEx or GEUVADIS datasets, and we usually obtain ~5 outliers/sample on median. Outliers do not necessarily represent pathogenicity.
