### ISSUE TITLE
aberrant splicing output plotting

### ISSUE THREAD

**Issue by capricy** [gagneurlab/drop#293]
I have two questions here:

1. I would like to run function plotExpectedVsObservedPsi(), but found that it requires idx argument. I wonder how I may obtain this information for a given gene and a given junction site. For example, below I see gene LINC01128(site 4). How about if I would like to plot for gene MALAT1 and for coordinate "chr14	49853754	49862603"? 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/18124356/153682739-833de476-30f3-4d0b-8db9-b2540ccb3f14.png">

2. Regarding plotVolcano(), the plot showed that 3 records had -log10(P value) around 25 for type psi3; however I only found two in the result file: results_per_junction.tsv (see below for the plot and data output). How may I explain the discrepancy here?

<img width="738" alt="image" src="https://user-images.githubusercontent.com/18124356/153681862-ec041591-07cb-4bbd-97a9-280cbcad2a55.png">
<img width="926" alt="image" src="https://user-images.githubusercontent.com/18124356/153682474-a59a39cd-3a5f-4f50-838c-df53ada3f5e5.png">

Thanks a lot.

C.

**Comment by nickhsmith** [comment]
Sorry for the delayed response

1. @vyepez88 can answer this better than I can
2. the middle point with the pvalue doesn't meet the delta psi3 requirements in order to be considered an outlier (default > 0.3 or < 0.3) as a result it isn't highlighted. Depending on your config settings the results of this tsv file may be filtered. So that could explain it.

**Comment by ischeller** [comment]
Regarding your first question: the `plotExpectedVsObservedPsi()` function can also take one row of the results table and display expected and observed psi values for the junction identified by the coordinates in that row. For this, have a look at the examples at the bottom of the documentation of the function: `?plotExpectedVsObservedPsi`. You can for example do: `plotExpectedVsObservedPsi(fds, result=res[1,])` to visualize the first row of the results table loaded as `res`.
You could also directly create a data.table / data.frame with the junction coordinates of interest and pass this into the result argument of the plotting function, e.g. : `junction_coords <- data.table(seqnames = "chr14", start = 49853754, end = 49862603, strand = "*", type="psi3")` and then `plotExpectedVsObservedPsi(fds, result=junction_coords)`. Note that the table that you supply must contain the column `type` to identfiy for which psi type the plot should be generated.

**Comment by capricy** [comment]
Thank you for providing extra information for function plotExpectedVsObservedPsi() . However, when I plotted directly from the result, I got the following error related to the strand information:

> plotExpectedVsObservedPsi(fds,result=res[1,])
Error in .find_strand_col(df_colnames0, strand.field0, prefix) : 
  Cannnot determine strand column unambiguously. (You can use
  'ignore.strand=TRUE' to ignore strand information.)
> plotExpectedVsObservedPsi(fds,result=res[1,],ignore.strand=TRUE)
Error in .find_strand_col(df_colnames0, strand.field0, prefix) : 
  Cannnot determine strand column unambiguously. (You can use
  'ignore.strand=TRUE' to ignore strand information.)

**Comment by vyepez88** [comment]
Hi, sorry, this is a bug we currently have in DROP. The results table has one column called `STRAND` and another one called `strand`. One refers to the way of the experimental setup (strand-specific or not) and the other one to the strand of the junction (+ or -). However, this results in an error that we need to fix. Please remove one of those 2 columns from the results table and try again.

**Comment by ischeller** [comment]
To clarify, please remove the `STRAND` column and keep the `strand` column. We need the strand information of the junction in order to identify the junction and retrieve the corresponding idx in the fds object. Alternatively, renaming the `STRAND` column also works, e.g. `setnames(res, "STRAND", "STRAND_SPECIFIC")`

**Comment by capricy** [comment]
> Sorry for the delayed response
> 
> 1. @vyepez88 can answer this better than I can
> 2. the middle point with the pvalue doesn't meet the delta psi3 requirements in order to be considered an outlier (default > 0.3 or < 0.3) as a result it isn't highlighted. Depending on your config settings the results of this tsv file may be filtered. So that could explain it.

I understand highlighted requires 0.3 as cutoff. However, could you please provide more details about the filtering since I couldn't find the information for the grey dot with -log10(P value) around 25 in my result table? I have the AS analysis setting from my config.yaml file below:

aberrantExpression:


    groups: 
        - HGSC

    fpkmCutoff: 1
    implementation: autoencoder

    padjCutoff: 1    
    zScoreCutoff: 0
    maxTestedDimensionProportion: 3


Thanks.

C.

**Comment by vyepez88** [comment]
Hi, that's the aberrantExpression dictionary :)
 Can you please send the parameters for the aberrantSplicing one?

**Comment by capricy** [comment]
how may I get the parameters then?

**Comment by vyepez88** [comment]
they should be below in the config file:
![Screenshot 2022-02-15 at 16 21 36](https://user-images.githubusercontent.com/30469316/154092211-cb672b58-1ebc-4400-81c2-ca72d04bb827.png)

**Comment by capricy** [comment]
Sorry I copied the wrong section from the .yaml file. Here is the correct one:


<img width="280" alt="Screen Shot 2022-02-15 at 11 17 29 AM" src="https://user-images.githubusercontent.com/18124356/154103230-a76706a7-0430-4b21-be29-4c6c64c0b054.png">

My goal here is to match the information on the plot to the text output (or intermediate text output).

Thanks.

C.

**Comment by capricy** [comment]
I see the AS analysis outputs two final results: results_per_junction.tsv and results.tsv.

Could you please explain how these two files are related to the parameters here, specifically the following three: filter, minDeltaPsi and deltaPsiCutoff

Thanks.

C.

**Comment by nickhsmith** [comment]
The result files (`results_per_junction.tsv` and `results.tsv`) are the results of the pipeline given your cutoff values defined in your config (`padjCutoff`, `zScoreCutoff`, and `deltaPsiCutoff`). The config value `filter` corresponds to the input filtering that is done "to filter out introns that are not  detected and to remove introns with no variability between samples" (from FRASER)

The difference between the 2 files is whether or not they are aggregated and show summary values for the gene itself (including HPO terms if provided) or at the junction level. `results_by_junction.tsv` shows every junction that is considered aberrant. While `results.tsv` shows only 1 junction per gene, but also has additional terms such as the pvalue for the gene and potential HPO terms.


So in your case you will only see results that have a delta_psi > 0.1 or delta_psi < -0.1

**Comment by capricy** [comment]
Is there intermediate file between results_per_junction.tsv and fds-object.RDS?

It looks like results.tsv is just to show the first junction of the results_per_junction.tsv for a given gene. Is it right?

**Comment by nickhsmith** [comment]
No there are millions of junctions and we don't save those specifically. You can use the FRASER fds object to work with all of the junctions (`results(fds, all = TRUE)`)

In the `results.tsv` file  the supporting junction with the lowest p-value is shown. However all of the significant junctions (as defined by the config) are in the `results_per_junction.tsv` file
