### ISSUE TITLE
Error: Error in fread(snakemake@input$results)

### ISSUE THREAD

**Issue by KuechlerO** [gagneurlab/drop#296]
Hi guys,

I am stuck with an error during the execution of `rule AberrantSplicing_pipeline_FRASER_Summary_R`:

### Error
```
Error in fread(snakemake@input$results) : 
  Input is either empty, fully whitespace, or skip has been set after the last non-whitespace.
```
Complete Log: 
[Error_log.txt](https://github.com/gagneurlab/drop/files/8097901/Error_log.txt)

### Setting
For my workflow I entered 10 own samples into the sample_annotation-file and included your "154 non-strand specific fibroblasts, build hg19, Technical University of Munich" control samples (very cool btw).

### TSV-file is empty
However, I noticed, that the TSV-file, which is saved under `output/processed_results/aberrant_splicing/results/hg19_v34/fraser/big/results.tsv` in my setting, is empty.
Also a change from 0.05 to 0.1 of the `padjCutoff`-value for aberrantSplicing in the config-file, and a subsequent deletion and following recomputing of the TSV-file does produce again an empty TSV-file.
Finally a value change to 1 creates a TSV-file, which is filled with entries in abundance.

That confuses me since in your paper it says **_"FRASER typically returns a handful of aberrant splicing events per sample that are significant at an FDR<0.1"_**. So I was just anticipating way more results, especially since I included your 154 control samples.

## 1.) Question
Does the output make sense nevertheless?
Is it true, that DROP ignores external samples (e.g. none of the external samples were listed in the result-tsv)?

## 2.) Additional Question:
Do I understand correctly, that the DROP workflow does not differentiate between controls and test-samples? Instead it averages and identifies then outliers.
Then it would make sense, to great for each sample a separate group with a bunch of controls and a single sample (with its replicates), right? Because that way we can avoid having additional aberrant samples having a bias effect on the statistical evaluation.

**Comment by nickhsmith** [comment]
Unfortunately we are still working on incorporating the external counts into the aberrant splicing pipeline. @vyepez88 would know more, but this may be the reason the `results.tsv` file is empty or malformed. Because you only have 10 samples it may be that those are being processed, and because of the low number of samples (only 10) there aren't any results that pass the cutoffs leaving you with an empty file. Just for a sanity check you can set the `padjust cutoff` to something like 0.5 and see if you get any results.

To answer your specific questions
1. This is an error we are trying to fix with respect to `aberrantSplicing`. For `aberrantExpression` you should be able to use the external counts as you would expect.
2. For aberrant expression and aberrant splicing DROP doesn't perform an analysis based on traditional case/control split. Instead it builds a distribution of expected counts given the distribution of counts (either expression or splicing counts) in the dataset. Using this distribution it then identifies samples that are outliers compared to the other samples in that group.

**Comment by KuechlerO** [comment]
Thx for the quick and detailed response :)

1. Ah ok, I see. That's a shame, cause it's a really nice feature. Looking forward to its future integration.
2. Mhm, so then my assumption is correct, that it would make sense to create separate groups for each test sample, so that we do not risk skewing the distribution of expected counts by also considering aberrant samples?

#### Another question:
Does it make a difference on the calculations when I annotate explicitly RNA replicates? [(see here)](https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#config-file) Or is that just for later output presentation & annotation important?

**Comment by nickhsmith** [comment]
2. Not exactly. It makes sense to split samples into separate groups if you have a known understanding that they have different distributions for their gene expression or splicing patterns. (IE tissue types) if you have a general sample of patients of the same tissue type, then it makes sense to keep them together so you can improve the distribution fitting with more samples.

I'm not sure what you mean. The example for RNA replicates is having 2 different RNA samples (blood and muscle) for a single patient. If you have 2 technical replicates (RNA from the same patient in blood 2 times) then you could keep them within the same DROP group as long as you have unique sample identifiers

**Comment by KuechlerO** [comment]
Response A: Yes, that makes sense. Ok, I will do it then this way.

Response B: Oh yeah, true. I missed in the example that they were splitting the samples into different groups. But yes, you got me right. I was talking about technical replicates. Alright, so these have to be noted down as separate samples. Ok, got it.

Thx for the details. I will then keep on going exploring :D

**Comment by KuechlerO** [comment]
> Unfortunately we are still working on incorporating the external counts into the aberrant splicing pipeline. @vyepez88 would know more, but this may be the reason the `results.tsv` file is empty or malformed. Because you only have 10 samples it may be that those are being processed, and because of the low number of samples (only 10) there aren't any results that pass the cutoffs leaving you with an empty file. Just for a sanity check you can set the `padjust cutoff` to something like 0.5 and see if you get any results.
> 
> To answer your specific questions
> 
>     1. This is an error we are trying to fix with respect to `aberrantSplicing`. For `aberrantExpression` you should be able to use the external counts as you would expect.
> 
>     2. For aberrant expression and aberrant splicing DROP doesn't perform an analysis based on traditional case/control split. Instead it builds a distribution of expected counts given the distribution of counts (either expression or splicing counts) in the dataset. Using this distribution it then identifies samples that are outliers compared to the other samples in that group.

@nickhsmith Do you already have a plan, until when you want to have implemented the incorporation of external count matrices? Is there any way to be notified, when the new feature is implemented? I'm really interested in it! :)

**Comment by nickhsmith** [comment]
We are trying to have it done in the next week or 2, but it is still
unsure. We will first push the changes to the `dev` branch (which you are
free to use and help us test) and assuming it works well we are hoping to
push it into a new version.

Which is a long way of saying, we are hoping to have this done ASAP but
realistically in the second half of March if everything goes well.

As for a notification, I believe github has a watch feature, that may be able to set up a notification. Although I don't know all of the details.

**Comment by KuechlerO** [comment]
> We are trying to have it done in the next week or 2, but it is still unsure. We will first push the changes to the `dev` branch (which you are free to use and help us test) and assuming it works well we are hoping to push it into a new version. Which is a long way of saying, we are hoping to have this done ASAP but realistically in the second half of March if everything goes well. As for a notification, I believe github has a watch feature, that may be able to set up a notification. Although I don't know all of the details.

Just to make sure: This feature is still not supported, right? :)

**Comment by nickhsmith** [comment]
We are getting close! Things took a backward slide with respect to the timeline. But we are ironing out the kinks and making sure the compute environment/conda is built correctly and hope to make a release shortly (hopefully before Easter).
