### ISSUE TITLE
Aberrant Splicing - plotFilterExpression

### ISSUE THREAD

**Issue by SathyaDarmalinggam** [gagneurlab/drop#311]
Dear DROP team, 

Thank you once again for such a great tool! I have a (fundamental) question about one of the outputs of the splicing module which I hope I can get some clarification for - the plotFilterExpression plot which is supposedly showing the distribution of FPKM values. 

I have so far come across 2 variations of this plot, one being Fig 3a from the DROP nature paper 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/42797616/158549826-aa34e6cd-e447-43f7-b47c-4a27167bb798.png">

And the other from the html from https://www.cmm.in.tum.de/public/paper/drop_analysis/webDir/html/drop_analysis_index.html 

![image](https://user-images.githubusercontent.com/42797616/158550049-89fc9e26-5d2b-44d7-ad05-496d4e9a58f0.png)

My first question is, what is the x-axis plotting? I have looked into the source codes on both FRASER & DROP github but I can't seem to find where the values for the x-axis are coming from. 

Secondly, I was wondering why there are 2 variations of the plot generated on presumably the same dataset? What do the 2 plots mean or how are they different? Again from the source codes, there are not that many variables that can be manipulated using the plotFilterExpression function.

I am sure I am missing something very basic/fundamental here but I can't seem to figure this out. Any help/clarification from your side is greatly appreciated. Many thanks!

**Comment by vyepez88** [comment]
Hi, 
Thanks for using DROP and spotting this. 
1. We have a bug in our FRASER documentation. We are actually not plotting the `FPKM` values, but the mean counts for each junction across samples. We are now updating our documentation to reflect this.
2. The 2 plots show the same information, just that the order of the True and False are inverted. At some point, we decided to have the junctions that passed the filter (True) being plot first.

**Comment by SathyaDarmalinggam** [comment]
Dear @vyepez88 , 

Thanks for the quick reply! That somewhat makes sense now. Just to clarify, the graph is showing for each junction what the mean count is. But I still don't get how there are values from 1-10 000, does it mean there are about 10 000 junctions that passed(true) in total and this is somehow ranked for plotting? And the same for the ~100 junctions that didn't pass(false)?

Sorry for the many basic questions, I'm just trying to make sense of what is being plotted. Thanks a lot for your help!

**Comment by vyepez88** [comment]
Not really. The x-axis shows the mean counts (or coverage) of the junctions. Junctions with high coverage pass the filter, and junctions with low coverage (<100) don't pass. 
Some junctions with low coverage also pass the filter, probably because they were highly expressed, but only on a few samples, therefore the average is still low (e.g. exon creation)

**Comment by SathyaDarmalinggam** [comment]
Thanks a lot for the clarification & quick replies :)
