### ISSUE TITLE
reads counting

### ISSUE THREAD

**Issue by capricy** [gagneurlab/drop#316]
Hi DROP support team,

Do the drop modules count reads that are multiply mapped to the reference genome?

Thanks.

C.

**Comment by nickhsmith** [comment]
Hi Capricy, It depends on the module

In FRASER, we indeed do count the multi-mapped reads at each location.

For OUTRIDER we have the COUNT_OVERLAPS column in the sample annotation (true or false), so it’s up to the user.
- `true`: count the read to each of the overlapping features
- `false`: do not count the read

You can see additional documentation on the COUNT_MODE also has an effect on the counting style. See https://www.rdocumentation.org/packages/GenomicAlignments/versions/1.8.4/topics/summarizeOverlaps-methods and https://htseq.readthedocs.io/en/latest/htseqcount.html#htseqcount for more information

           • "Union" : (Default) Reads that overlap any portion of
              exactly one feature are counted. Reads that overlap
              multiple features are discarded. This is the most
              conservative of the 3 modes.

            • "IntersectionStrict" : A read must fall completely
              "within" the feature to be counted. If a read overlaps
              multiple features but falls "within" only one, the read
              is counted for that feature.  If the read is "within"
              multiple features, the read is discarded.

            • "IntersectionNotEmpty" : A read must fall in a unique
              disjoint region of a feature to be counted. When a read
              overlaps multiple features, the features are partitioned
              into disjoint intervals.  Regions that are shared between
              the features are discarded leaving only the unique
              disjoint regions. If the read overlaps one of these
              remaining regions, it is assigned to the feature the
              unique disjoint region came from.

**Comment by nickhsmith** [comment]
Does this answer your questions? If so I will close this issue later this week.

**Comment by capricy** [comment]
Yes. Thank you.
