### ISSUE TITLE
More then one variant context at position

### ISSUE THREAD

**Issue by kaznt** [gagneurlab/drop#318]
Dear Support Team,

I was trying to run mono allele expression analysis and met the error message below.
GATK reported errors several times and finally complete the job, but I'm not sure if the result is reliable.
I checked the locus in VCF file and found that the locus is actually multi allelic description.
I wonder that the multi allelic locus is derived from input VCF file (it has also multi allelic description), or called them out directly from input bam file.

Thank you for your help.

Version 1.1.3

Using GATK jar /usr/local/drop-1.1.3/share/gatk4-4.2.5.0-0/gatk-package-4.2.5.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /usr/local/drop-1.1.3/share/gatk4-4.2.5.0-0/gatk-package-4.2.5.0-local.jar ASEReadCounter -R /home/xxx/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fa -I /home/xxx/sample_sorted.bam -V /home/xxx/Output/processed_data/mae/snvs/DNAID--RNAID.vcf.gz -L chr9 --verbosity ERROR --QUIET true --disable-sequence-dictionary-validation True
***********************************************************************

A USER ERROR has occurred: More then one variant context at position: chr9:3824936

***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
Using GATK jar /usr/local/drop-1.1.3/share/gatk4-4.2.5.0-0/gatk-package-4.2.5.0-local.jar

**Comment by nickhsmith** [comment]
Yes we have seen this problem with multi-alleic positions but I thought it was fixed to be honest. When you look at the vcf file and see that it is multi-allelic is that in the original vcf file (listed in the sample annotation) or in the filtered vcf created along the way (`/home/xxx/Output/processed_data/mae/snvs/DNAID--RNAID.vcf.gz`)?

Edit
-----
If you do find that even in the filtered vcf that the multi-allelic variant is present, could you give an example of how it looks (I don't want to ask you to share private allelic data!) but if it's 
```
chr21   9825836 rs544074340 A   G   100 PASS    AC=1;AN=2   GT  0|1
chr21   9825836 rs544074340 A   TT   100 PASS    AC=1;AN=2   GT  0|2
```

A made-up example to help improve our testing could be useful.

**Comment by marcDabad** [comment]
I had several times this problem and I've run 

```bash
gatk SelectVariants \
-R ${REF}  \
--restrict-alleles-to BIALLELIC -V ${IN_VCF} -O ${OUT_VCF}
```

And everything works perfect

**Comment by kaznt** [comment]
@nickhsmith @marcDabad 
Perfect.
Thank you for your help, and sorry for late reply.
Especially, @marcDabad 's suggestion helped me a lot.
Now I could complete the run.
Thanks again.
