### ISSUE TITLE
Can drop run in offline surroundings?

### ISSUE THREAD

**Issue by kaznt** [gagneurlab/drop#319]
Dear Support team,

I need to run drop in offline surroundings because of our sample restriction.
I run drop and met the error message below.

- Can drop run in offline mode?
- How many files (resources) should be prepared separately? (I know hpo setting, but not sure others...)

Thank you for your help.

Version: 1.1.3

[Tue Mar 22 13:06:50 2022]
rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    input: /home/xxx/Output/processed_data/aberrant_splicing/datasets/cache/raw-fraser2/fds.done, Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
    output: /home/xxx/Output/processed_data/aberrant_splicing/datasets/cache/raw-fraser2/sample_tmp/splitCounts/sample_RNAID.done
    log: /xxx/.drop/tmp/AS/fraser2/splitReads/RNAID.Rds
    jobid: 18
    wildcards: dataset=fraser2, sample_id=RNAID
    threads: 2
    resources: tmpdir=/tmp

Load packages
Loading required package: rtracklayer
Tue Mar 22 13:07:07 2022: Count split reads for sample: RNAID
Error in download.file(url, destfile, quiet = TRUE) : 
  cannot open URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'
Calls: countSplitReads ... <Anonymous> -> fetch_table_from_UCSC -> fetch_table_from_url
Execution halted

**Comment by nickhsmith** [comment]
Sorry for the late response. I am curious what level of offline you are referring to? Are you able to fully download the dependencies and conda environment, but not supporting reference files like the allele frequencies for the genome? Are you able to run the demo by chance?

**Comment by kaznt** [comment]
I could download everything at installation step since I use source computer which is connected to internet.
Actually, I downloaded drop via conda in local folder in the source computer , and copied everything to the offline machine.
e.g. R library required for an analysis with hg38 was not originally installed in drop, and is interactively download from www.
Thus it failed.
Then I ran hg38 analysis in the source computer first.
After the run, I copied everything to offline machine and it worked, since R package is installed in R library folder of the installation path.
However, FRASER required chromInfo.txt.gz from UCSC interactively, and I couldn't find source code where it is written.
I don't know if it is possible to copy chromInfo.txt.gz to somewhere in installation path and avoid this download step.

Demo worked, I guess demo is hg19 and required things are already in the installation path.

**Comment by nickhsmith** [comment]
Sorry for the weird workaround, but it seems like things are mostly going well. It seems that file can be found here:
http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/

Or more directly: http://hgdownload.cse.ucsc.edu/goldenpath/hg38/database/chromInfo.txt.gz

although you're right, I'm not sure where exactly it's needed. @c-mertes @ischeller  Do you have an idea?

**Comment by kaznt** [comment]
I know where the files are in the web, and how to download them, however, I don't know where should I put downloaded files afterwords.

Due to an ethical issue, we have to use clusters without internet connection. I guess some users are in same situation...?

Thanks.

**Comment by kaznt** [comment]
Solved. Thank you for your comments.
The way of solution is tricky.
Setup internal web server and forward URL request to the intra web server referring /etc/hosts.
Then the download process was done without trouble.

Thanks anyway.
