### ISSUE TITLE
Error with external count data

### ISSUE THREAD

**Issue by thudaniel2333** [gagneurlab/drop#322]
Hi, I'm trying to run the exportCount module with an in-house dataset(40+ samples) and a GTEX dataset(700+ samples) and got the following error:

Error: BiocParallel errors
  element index: 44
  first error: subscript out of bounds
Execution halted
[Tue May  3 21:43:20 2022]
Error in rule AberrantExpression_pipeline_Counting_mergeCounts_R:
    jobid: 2
    output: /tmp/processed_data/aberrant_expression/genecode29/outrider/blood40_rna/total_counts.Rds
    log: /scripts/.drop/tmp/AE/genecode29/blood40_rna/merge.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 57 of /var/tmp/pbs.273188.mgt/tmpbnccmyxc:
Command 'set -euo pipefail;  Rscript --vanilla /scripts/.snakemake/scripts/tmp7catppxd.mergeCounts.R' returned non-zero exit status 1.
  File "/miniconda3/envs/drop/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
  File "/var/tmp/pbs.273188.mgt/tmpbnccmyxc", line 57, in __rule_AberrantExpression_pipeline_Counting_mergeCounts_R
  File "/miniconda3/envs/drop/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 574, in _callback

The complete log file and the config files are attached below.
The GTEX dataset I used was the hg38 liftover version downloaded from: https://zenodo.org/record/6078397#.YmvAOtpBy3B
I used the genecodev29 gtf file to export count files for my inhouse data. I checked the rownames and row numbers of GTEX count file and they were the same with the count files generated from in-house data.
Is it because I'm including too many GTEX samples? What is the maximal/ideal number of external samples to be included?
[sample_anno - demo.txt](https://github.com/gagneurlab/drop/files/8611027/sample_anno.-.demo.txt)
[config.yaml.txt](https://github.com/gagneurlab/drop/files/8611028/config.yaml.txt)
[drop_export.txt](https://github.com/gagneurlab/drop/files/8611035/drop_export.txt)

**Comment by vyepez88** [comment]
Hi, it could be a memory problem. Can you try with a smaller set of e.g. 5 local and 5 external samples?

**Comment by thudaniel2333** [comment]
Thanks, the problem is solved with fewer external samples.
