### ISSUE TITLE
Question: Is it possible to run without bams?

### ISSUE THREAD

**Issue by Lucpen** [gagneurlab/drop#324]
Hi!

I have recently started to run DROP and I was wondering if it is possible to run without bam files.
I know that you show that it is possible to run the aberrantExpression module with only a count file.

Would it be possible to run mae and aberrantSplicing with a count file and a vcf (with no bam files)?

**Comment by vyepez88** [comment]
Hi, unfortunately, we're still working on having the aberrantSplicing module running without BAM files. 
VCF files are only needed for the mono-allelic expression module.

**Comment by Lucpen** [comment]
Thanks for your answer, I have an additional questions. 
In that case, would you still need the bam files to run the aberrantSplicing module even if you have run the module export counts and have the splice files?

**Comment by vyepez88** [comment]
No, after you have the counts, you don't need the BAM files anymore.

**Comment by Lucpen** [comment]
Thanks! One last question. Would you always need them for the MAE one? Or is a vcf for the RNAseq created after the first run?

**Comment by vyepez88** [comment]
For the MAE module, you need BAM files from RNA-seq and VCF files from DNA (eg WES or WGS). 
VCF files from RNA-seq are not adequate for calling mono-allelic expression.

**Comment by Lucpen** [comment]
Thanks!

**Comment by 2decalcomania** [comment]
if you have a count file, you can use the R package outrider to find the aberrant expression .
