### ISSUE TITLE
Error in Counting_01_1_countRNA_splitReads_samplewise

### ISSUE THREAD

**Issue by Lucpen** [gagneurlab/drop#327]
Hi,

we have been getting an error when running the aberrant splicing module at the Counting_01_1_countRNA_splitReads_samplewise step. At first I thought that it was an out of memory problem, so I gave it 10 cores but I still get the same error.

This happened after successfully running the Aberrant expression module. 

Do you have any idea how to fix this?

Here are the command, the error, annotation (first 10 samples out of 56), config file and snakelike log:
`snakemake aberrantSplicing --cores 10 --set-threads AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R=10 --keep-going`

`
[Tue Jun  7 09:43:43 2022]
rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    input: /path/drop/14022_/Output/processed_data/aberrant_splicing/datasets/cache/raw-blood/fds.done, Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
    output: /path/drop/14022_/Output/processed_data/aberrant_splicing/datasets/cache/raw-blood/sample_tmp/splitCounts/sample_ACC8852A9.done
    log: /path/drop/14022_/.drop/tmp/AS/blood/splitReads/ACC8852A9.Rds
    jobid: 58
    wildcards: dataset=blood, sample_id=ACC8852A9
    threads: 12
    resources: tmpdir=/path/tmp

Load packages
Loading required package: rtracklayer
Tue Jun  7 09:43:56 2022: Count split reads for sample: ACC8852A9
Error in env[[as.character(i)]] <- value :
  wrong args for environment subassignment
Calls: countSplitReads ... bploop -> bploop.iterate -> <Anonymous> -> add_inorder
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
Execution halted
[Tue Jun  7 10:18:18 2022]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 58
    output: /path/drop/14022_/Output/processed_data/aberrant_splicing/datasets/cache/raw-blood/sample_tmp/splitCounts/sample_ACC8852A9.done
    log: /path/drop/14022_/.drop/tmp/AS/blood/splitReads/ACC8852A9.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 121 of /path/tmp/tmpsprlh039:
Command 'set -euo pipefail;  Rscript --vanilla /path/drop/14022_/.snakemake/scripts/tmp17j3o0b2.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/path/tmp/tmpsprlh039", line 121, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run`

[2022-06-06T155509.583818.snakemake.txt](https://github.com/gagneurlab/drop/files/8851660/2022-06-06T155509.583818.snakemake.txt)
[220527_annotation_DROP.txt](https://github.com/gagneurlab/drop/files/8851661/220527_annotation_DROP.txt)
[config.txt](https://github.com/gagneurlab/drop/files/8851662/config.txt)

**Comment by vyepez88** [comment]
Hi, it seems that out of 56 samples, only 11 need to be counted, which means 45 were previously counted. I see the following message:
```
The params used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-params-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-params-changes)'.
```
Were some parameters changed between the 2 runs? 
Altogether, I recommend running the full cohort in a new path to be sure it's run under the same conditions.
Keep us updated.

**Comment by Lucpen** [comment]
Hi, thanks for your reply. I tried to rerun as you suggested but I still get errors for some of the samples. I have attach the config file (the same as before except for working directory and now it only runs the splicing module ) and the new log. 
The command used was:
`snakemake aberrantSplicing --cores 9 --keep-going`

The error happens on the same step but on a different line:

```
[Wed Jun  8 05:21:03 2022]
rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    input: /path/drop/14022__trial2/Output/processed_data/aberrant_splicing/datasets/cache/raw-blood/fds.done, Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
    output: /path/drop/14022__trial2/Output/processed_data/aberrant_splicing/datasets/cache/raw-blood/sample_tmp/splitCounts/sample_ACC9366A10.done
    log: /path/drop/14022__trial2/.drop/tmp/AS/blood/splitReads/ACC9366A10.Rds
    jobid: 42
    wildcards: dataset=blood, sample_id=ACC9366A10
    threads: 3
    resources: tmpdir=/path/tmp

Load packages
Loading required package: rtracklayer
Wed Jun  8 05:21:14 2022: Count split reads for sample: ACC9366A10
Error in env[[as.character(i)]] <- value :
  wrong args for environment subassignment
Calls: countSplitReads ... bploop -> bploop.iterate -> <Anonymous> -> add_inorder
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
Execution halted

[Wed Jun  8 08:19:03 2022]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 42
    output: /path/drop/14022__trial2/Output/processed_data/aberrant_splicing/datasets/cache/raw-blood/sample_tmp/splitCounts/sample_ACC9366A10.done
    log: /path/drop/14022__trial2/.drop/tmp/AS/blood/splitReads/ACC9366A10.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 36 of /path/tmp/tmpxspjoyhi:
Command 'set -euo pipefail;  Rscript --vanilla /path/drop/14022__trial2/.snakemake/scripts/tmpchs0d4jh.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/path/tmp/tmpxspjoyhi", line 36, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
```

[config.txt](https://github.com/gagneurlab/drop/files/8859617/config.txt)
[log_snakemake.txt](https://github.com/gagneurlab/drop/files/8859618/log_snakemake.txt)

**Comment by nickhsmith** [comment]
I'm sorry we haven't responded recently. Could it be possible that the BAM files are not correctly formed, or aren't split for some reason? Can you please describe the library prep and alignment?

**Comment by Lucpen** [comment]
Hi,
Sorry, I did not notice your answer before.
Sequencing libraries were prepared using the Illumina Stranded mRNA Prep and sequenced on Illumina. The fastq were then trimmed with trim galore and alignment to GRCh38 was done with STAR.

I think it is unlikely that the bam files are not correctly formed, as I was able to run AberrantExpression module on the samples.

Recently I have tried to update drop to a later version and rerun with the latest conda environment. I have made some small changes on the samples included, so I have included here all the updated files. It fails on the same stage and line. However, when I looked at the output of the slurm job I realised that it is actually a memory error (see below ), even though I am running with 36 cores. Do you have any idea what could be causing this?
Thanks for your help!

`
RuleException:
CalledProcessError in line 36 of /path/tmp/tmpwtp873my:
Command 'set -euo pipefail;  Rscript --vanilla /path/RNAseq/drop/AS_fam7/.snakemake/scripts/tmpr9j4897_.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/path/tmp/tmpwtp873my", line 36, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/path/bin/miniconda3/envs/D_drop_LPP/lib/python3.11/concurrent/futures/thread.py", line 58, in run
slurmstepd: error: Job 4072324 exceeded memory limit (208499896320 > 197123899392), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 4072324 ON compute-0-8 CANCELLED AT 2022-12-01T15:21:53 ***
Will exit after finishing currently running jobs (scheduler).
`

[config.txt](https://github.com/gagneurlab/drop/files/10133326/config.txt)
[snakemake_log.txt](https://github.com/gagneurlab/drop/files/10133336/snakemake_log.txt)
[221103_DROP_AS.txt](https://github.com/gagneurlab/drop/files/10133327/221103_DROP_AS.txt)

**Comment by nickhsmith** [comment]
Can you give it more memory? what are the SLURM options you are using, and how large are your BAM files?

**Comment by Lucpen** [comment]
Hi, 
I have tried running with 50, 60 and 72 cores and it fails. I have also tried to run the step that fails with a many more cores and it still fails with the same error.
`snakemake aberrantSplicing --cores 36 --set-threads AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R=36`
Most samples are around 12GB

**Comment by vyepez88** [comment]
the limiting factor seems to be the memory. Can you try with 3 cores? (the counting step uses 3cores/sample, so in this way 1 sample at a time will be counted)

**Comment by Lucpen** [comment]
It still fails, I have also tried giving 36 cores to the first step with `--set-threads AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R=36`
so that each sample would be run on its own and it fails too.

**Comment by nickhsmith** [comment]
There is a difference between the number of threads and the memory a job takes. Can you please share with us the exact snakemake command you are using? Or your SLURM profile so that we can see what SLURM options are being set?

Thanks

**Comment by Lucpen** [comment]
Thank you for your help. I have tried to run in many different ways, giving different amounts of cores. Most of the time I have run like this:
`#SBATCH --time=48:00:00
#SBATCH --ntasks=36
snakemake aberrantSplicing --cores 36`
I have also tried:
`#SBATCH --time=48:00:00
#SBATCH --ntasks=36
snakemake aberrantSplicing --cores 36 --set-threads AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R=36`
I have tried a few different combinations with 50, 60 and 72 cores.
On Friday I finally managed to make it run a few samples by trying the suggestion of @vyepez88 like this:
`#SBATCH --time=48:00:00
#SBATCH --ntasks=72
snakemake aberrantSplicing --cores 3`
It run through 4 samples in 48h, so very inefficient. Do you have any idea on why it requires such an amount of memory and time?

**Comment by nickhsmith** [comment]
Since your problems have been memory related I would recommend using the memory designation for sbatch.

For example you can try this to give a set memory to each job. The below example will use 1 Machine (-N) with 10 cores (-n) and 100G (--mem) per job, and will spawn 20 (--jobs)  jobs at a time. You can of course adjust to your machine resources and samples

`snakemake aberrantSplicing --cluster "sbatch -N1 -n 10 --mem 100G" --jobs 20`

**Comment by Lucpen** [comment]
Thanks for the help. I have been running as you suggested but the job run out of time. After restarting it, I noticed that it restarted all the `AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R` that had previously been run and finished, even though within my config file I had `recount: false`. Is there a way to prevent this from happening? 
[config.txt](https://github.com/gagneurlab/drop/files/10176360/config.txt)

**Comment by nickhsmith** [comment]
Snakemake has changed their default rerun strategy so you may need to update the `--rerun-triggers` please refer to the README which has all of the specifics on the aberrant splicing rerunning.

I'm not sure that I understand your problem with _ran out of time_ do you mean SLURM ran past a default setting? Are there constraints on your system? Unfortunately DROP does take hours and sometimes days of compute time depending on the size of the files and the number of samples (coupled with how many compute resources are available).

**Comment by Lucpen** [comment]
Thanks for the info, I had missed the `--rerun-triggers` update. 
Yes, in our system you can only allocate resources for a limited amount of time.

**Comment by nickhsmith** [comment]
DROP can not run on full sized datasets in only a few minutes it does take hours to run. I would contact your IT person and see if they can help you work around a time-out error

**Comment by Lucpen** [comment]
Hi again, the time-out-error was popping out after running for about 100h, it has taken quite some time ~500h but now aberrant splicing has run through all the samples. As the run time is so long, I was hopping to use the splice counts again in subsequent runs. However, as I have only run the aberrant splicing module, DROP breaks when I try to execute `exportCounts.R`. Is there a way around this? Or is the best option extracting the required files from `fds-object.RDS` ?

**Comment by vyepez88** [comment]
which required files are you interested in extracting? which subsequent runs do you mean? If the `--rerun-triggers` parameter is used, DROP will not need to rerun the counting.

**Comment by Lucpen** [comment]
Hi, sorry for the ambiguous question. I have run the aberrant splicing module with the  `--rerun-triggers` option because our system can only allocate resources for a limited amount of time, so it run out of time before completing the analysis. The 52 samples took around 500 hours to run with over 30 cores. 

Now I want to use the controls that have already been run in the previously described run and add one patient that has not been run yet. Therefore, I would like to use the count tables for aberrant splicing to avoid using so much computational resources. After reading the DROP documentation I realised that I need several files to do this (`k_j_counts.tsv.gz, k_theta_counts.tsv.gz, n_psi3_counts.tsv.gz, n_psi5_counts.tsv.gz, n_theta_counts.tsv.gz`). As I have only run the aberrant splicing module, DROP breaks when I try to execute `exportCounts.R`. Is there a way around this? Or is the best option extracting the required files from `/processed_data/aberrant_splicing/datasets/savedObjects/group/fds-object.RDS`?

**Comment by vyepez88** [comment]
Hi. The way the counting is performed in the AS module is as follows.
Split reads are counted in an annotation-free way. A splice map is generated with the junctions found by the split reads per cohort. Non-split reads are counted for each junction in the splice map. As such, if one sample is added to the cohort, the splice map might change and therefore the non-split reads need to be recomputed, as well as all downstream analyses.
We recommend you checking with your IT admins how to accelerate the run. On our experience, fully counting 52 samples with 30 cores should take around 1 hour.

**Comment by Lucpen** [comment]
After updating to version 1.2.4 and downsampling to 80 million reads it run well and very fast too, I will now close this issue. Thank you for your help!
