### ISSUE TITLE
Drop demo fails - CONDA installation / bcftools: error while loading shared libraries: libgsl.so.25

### ISSUE THREAD

**Issue by aheritas** [gagneurlab/drop#333]
Hi, first of all, thank you for developing this useful package.

I followed the [installation instructions](https://gagneurlab-drop.readthedocs.io/en/latest/installation.html) and got the following error trying to run the demo:

```
[Fri Jun 24 14:54:24 2022]
Finished job 15.
9 of 108 steps (8%) done
Select jobs to execute...

[Fri Jun 24 14:54:24 2022]
rule mae_createSNVs:
    input: /home/personal/drop_demo/Scripts/MonoallelicExpression/pipeline/resource/chr_NCBI_UCSC.txt, /home/personal/drop_demo/Scripts/MonoallelicExpression/pipeline/resource/chr_UCSC_NCBI.txt, /home/personal/drop_demo/Data/qc_vcf_1000G.vcf.gz, /home/personal/drop_demo/Data/rna_bam/HG00096.1.M_111124_6_chr21.bam, /home/personal/drop_demo/Scripts/MonoallelicExpression/pipeline/MAE/filterSNVs.sh, /home/personal/drop_demo/Output/processed_data/mae/params/snvs/HG00096.1.M_111124_6_snvParams.csv
    output: /home/personal/drop_demo/Output/processed_data/mae/snvs/QC--HG00096.1.M_111124_6.vcf.gz, /home/personal/drop_demo/Output/processed_data/mae/snvs/QC--HG00096.1.M_111124_6.vcf.gz.tbi
    jobid: 96
    reason: Missing output files: /home/personal/drop_demo/Output/processed_data/mae/snvs/QC--HG00096.1.M_111124_6.vcf.gz
    wildcards: vcf=QC, rna=HG00096.1.M_111124_6
    resources: tmpdir=/tmp

Filter SNVs
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
[Fri Jun 24 14:54:24 2022]
Error in rule mae_createSNVs:
    jobid: 96
    output: /home/personal/drop_demo/Output/processed_data/mae/snvs/QC--HG00096.1.M_111124_6.vcf.gz, /home/personal/drop_demo/Output/processed_data/mae/snvs/QC--HG00096.1.M_111124_6.vcf.gz.tbi
    shell:
        
        /home/personal/drop_demo/Scripts/MonoallelicExpression/pipeline/MAE/filterSNVs.sh /home/personal/drop_demo/Scripts/MonoallelicExpression/pipeline/resource/chr_NCBI_UCSC.txt /home/personal/drop_demo/Scripts/MonoallelicExpression/pipeline/resource/chr_UCSC_NCBI.txt /home/personal/drop_demo/Data/qc_vcf_1000G.vcf.gz         QC /home/personal/drop_demo/Data/rna_bam/HG00096.1.M_111124_6_chr21.bam /home/personal/drop_demo/Output/processed_data/mae/snvs/QC--HG00096.1.M_111124_6.vcf.gz         bcftools samtools
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-06-24T145332.602063.snakemake.log
```

I am also attaching the [output](https://github.com/gagneurlab/drop/files/8978966/conda_list_drop.txt) from `conda list -n drop_env`, if that's helpful, as well as the` drop --version`: **1.1.4**.

Let me know if there is any extra information that I should provide.

Thank you for your help!

**Comment by nickhsmith** [comment]
Thank you for the notice, and we will take a look! It seems as if the DROP recipe is not as tightly defined as we thought and there have been updates to packages that no longer are compatible. We will try to figure out the offending packages ASAP. Thank you.

**Comment by nickhsmith** [comment]
In a short-term effort to fix this can you please try this with the linked `DROP.yaml` file. It is a yaml file for a conda env called `drop_test`
[DROP.yaml](https://www.cmm.in.tum.de/public/paper/drop_analysis/DROP.yaml)

Can you please try to install it using (~10 min)
`conda env create -f DROP.yaml`

- activate it using `conda activate drop_env`  (edited)
- try the demo again
  - `snakemake -c1`

**Comment by aheritas** [comment]
Dear Nick,
The`DROP.yaml` file solves the issue and I was able to run the whole demo without problems.
Thanks a lot!

**Comment by nickhsmith** [comment]
We tried again with a fresh install and now it seems to work as intended. There may have been a small window where the conda env wasn't updated for some reason.

**Comment by johnstonmj** [comment]
I encountered the same error proceeding through the demo from a fresh install today.
I did eventually get it to work, but I wanted to document here.

**(1) Demo failed**
During `rule mae_createSNVs`
with
```
Filter SNVs
bcftoolsbcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
```
  
**(2) Alternate env creation**
I tried making a new environment with the linked DROP.yaml file above in this thread:
`mamba env create --file DROP.yaml`

Warning:
```
Encountered problems while solving.
Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by libgit2-1.4.2-h6529ace_0
Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by libgit2-1.4.2-h4c07d5c_0
```

I believe this caused the roll-back of the YAML-specified version of libgit2.

Comparing the version specified in the YAML: 
`libgit2=1.4.2=h6529ace_0`

To the env after install: 
```
conda list | grep libgit2
libgit2                   1.3.0                hee63804_1    conda-forge
```

However, bcftools does successfully load shared libraries.


**(3) Different failures**
Trying again...
```
snakemake --cores 1 -n
WARNING: 21 files missing in samples annotation. Ignoring...
/home/user1/software/miniconda3/envs/drop_test/lib/python3.10/site-packages/drop/config/SampleAnnotation.py:145: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  grouped = {gr: df[df[group_key].str.contains(f'(^|{sep}){gr}({sep}|$)')][assay_id].tolist()
ValueError in line 12 of /work/user1/test_drop/Snakefile:
Too few IDs in DROP_GROUP outrider, please ensure that it has at least 10 IDs, groups: []
  File "/work/user1/test_drop/Snakefile", line 12, in <module>
  File "/home/user1/software/miniconda3/envs/drop_test/lib/python3.10/site-packages/drop/config/DropConfig.py", line 56, in __init__
  File "/home/user1/software/miniconda3/envs/drop_test/lib/python3.10/site-packages/drop/config/submodules/AberrantExpression.py", line 29, in __init__
  File "/home/user1/software/miniconda3/envs/drop_test/lib/python3.10/site-packages/drop/config/submodules/Submodules.py", line 54, in checkSubset
```

Based on the regular expression warning above, and the fact that 21 samples are missing from a demo of 22, I think that there might be issues with the regex matching within SampleAnnotation.py? Or perhaps with files left behind by the previous failed run?


**(4) Fixed with fresh directory**
I tried again using an empty directory in case some of the intermediate or demo files created were version-specific.

During the dryrun
`snakemake --cores 1 -n`
many additional R packages were installed, which I had thought would have been included with building the conda environment.

In any case, the pipeline successfully finished using the env created from the DROP.yaml above.

**Comment by nickhsmith** [comment]
I have reopened this issue for visability. We are unsure of why the conda installation is inconsistent or if it is just a discrepency with underlying libraries, as a result, our suggestion is that you use a hard-coded environment file that was generated from our successful conda installation on July 6 2022

1. Download the `DROP.yaml` file from [our webserver](https://www.cmm.in.tum.de/public/paper/drop_analysis/)
2. navigate to the `DROP.yaml` installation location (or use the full path in the next step)
3. Create the environment directly using `conda env create -f DROP.yaml`
4. Activate it using `conda activate drop_env`
5. test the installation using 
```
mkdir test_demo
cd test_demo
drop demo
```
This should install some new R packages (sorry these couldn't be packaged into the conda env) and proceed with the demo.

**Comment by nickhsmith** [comment]
@aheritas @johnstonmj can you please do me a favor, and share the contents of your ~/.condarc file? I think the problem comes from the default version of `gsl` and the conda-forge version of `gsl`

```
cat ~/.condarc
```

**Comment by johnstonmj** [comment]
Here you go @nickhsmith 

channels:
  - bioconda
  - defaults
  - r
  - conda-forge
auto_update_conda: false
channel_priority: flexible

**Comment by nickhsmith** [comment]
Ok. The order of channels is different, which may lead to some issue (despite the flexible priortiy) We have updated the documentation to force `bioconda` and `conda-forge` channels. Could you try to use the new documentation? And see if that fixes the problem for you?

```
mamba create -n drop_test -c conda-forge -c bioconda drop --override-channels

conda activate drop_test
cd <PATH/TO/DEMO>
snakemake -c1
```

**Comment by johnstonmj** [comment]
This worked for me.
Thanks @nickhsmith
