### ISSUE TITLE
AberrantSplicing_pipeline_FRASER_07_extract_results_FraseR_R fails when using sample annotation already containing STRAND_SPECIFIC column

### ISSUE THREAD

**Issue by schance995** [gagneurlab/drop#351]
For example the sample annotation in DROP's BCM UDN blood samples (https://doi.org/10.5281/zenodo.3963470) contains the STRAND_SPECIFIC column already, without containing STRAND. Running AberrantSplicing_pipeline_FRASER_07_extract_results_FraseR_R fails with the following:

```
  [1] "Results per junction extracted"
Error in merge.data.table(RES, f4, by = c("sampleID", "hgncSymbol"), all.x = TRUE) : 
  x has some duplicated column name(s): STRAND_SPECIFIC. Please remove or rename the duplicate(s) and try again.
Calls: add_HPO_cols -> merge -> merge -> merge.data.table
Execution halted
Not cleaning up .snakemake/scripts/tmpoi089ec6.07_extract_results_FraseR.R
```
The reason is because `setnames(res_junc_dt, 'STRAND', 'STRAND_SPECIFIC')` produces duplicate columns. `coalesce` could be used instead if STRAND_SPECIFIC is already present.

**Comment by vyepez88** [comment]
many thanks for noting this! to avoid confusion and further errors, I removed the `STRAND` column altogether from the results table. It's done in this commit: `f99b67b784bff81b0453570658aefc21531159f2` and will be integrated in the master branch in the next release.
