### ISSUE TITLE
Config generated by drop init does not match defaults listed in documentation

### ISSUE THREAD

**Issue by schance995** [gagneurlab/drop#355]
For example the config from drop init sets padjCutoff for aberrantExpression and aberrantSplicing is to 1, when the documentation states the default is 0.05 and 0.1 respectively. This could result in errors like #214 if one does not go through every single setting looking for a difference. The config from drop init should use the default values so that it is easier to get started.

**Comment by nickhsmith** [comment]
Thanks. Updated in the `dev` branch
