### ISSUE TITLE
Outrider error

### ISSUE THREAD

**Issue by hermean** [gagneurlab/drop#360]
I have a set of my own samples that can run successfully with the aberrantSplicing module.
However, the error message below came up with the aberrantExpression module. Any suggestion? my config.yaml, sampleannotation and the complete log were attached for your reference. Thanks!

Error in rule AberrantExpression_pipeline_OUTRIDER_Summary_R:
    jobid: 76
    output: /home/fanyanjie/drop/Novo3str_NP01_t5/Output/html/AberrantExpression/Outrider/ensembl37/Summary_NP01.html, /home/fanyanjie/drop/Novo3str_NP01_t5/Output/html/AberrantExpression/Outrider/ensembl37/OUTRIDER_results_NP01.tsv
    log: /home/fanyanjie/drop/Novo3str_NP01_t5/.drop/tmp/AE/ensembl37/NP01/OUTRIDER_summary.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 72 of /tmp/tmpzcd68zc3:
Command 'set -euo pipefail;  Rscript --vanilla /home/fanyanjie/drop/Novo3str_NP01_t5/.snakemake/scripts/tmps43xlm7h.wBRender.R' returned non-zero exit status 1.
  File "/tmp/tmpzcd68zc3", line 72, in __rule_AberrantExpression_pipeline_OUTRIDER_Summary_R
  File "/home/fanyanjie/mambaforge/envs/drop_env/lib/python3.10/concurrent/futures/thread.py", line 58, in run
[config_yaml_t5.txt](https://github.com/gagneurlab/drop/files/9401168/config_yaml_t5.txt)
[sampleAnnotation_NP01_t5.txt](https://github.com/gagneurlab/drop/files/9401169/sampleAnnotation_NP01_t5.txt)
[complete_log.txt](https://github.com/gagneurlab/drop/files/9401170/complete_log.txt)

**Comment by nickhsmith** [comment]
I think the problem is with the annotations you list in  your config. `AberrantExpression` will use all of the values you designate in the `geneAnnotation` value.

You have
```
geneAnnotation:
       ensembl38: /data/yfan/dependency/ensembl_primary_assembly/Homo_sapiens.GRCh38.99.gtf
       ensembl37: /data/yfan/dependency/ensembl_primary_assembly/Homo_sapiens.GRCh37.87.gtf   
```

The second annotation (`ensembl37`) is using GRCh37 which can't be right. Can you please update the annotation file to match GRCh38 or remove it completely

**Comment by hermean** [comment]
> I think the problem is with the annotations you list in your config. `AberrantExpression` will use all of the values you designate in the `geneAnnotation` value.
> 
> You have
> 
> ```
> geneAnnotation:
>        ensembl38: /data/yfan/dependency/ensembl_primary_assembly/Homo_sapiens.GRCh38.99.gtf
>        ensembl37: /data/yfan/dependency/ensembl_primary_assembly/Homo_sapiens.GRCh37.87.gtf   
> ```
> 
> The second annotation (`ensembl37`) is using GRCh37 which can't be right. Can you please update the annotation file to match GRCh38 or remove it completely

This solved the problem. Thanks so much!
