### ISSUE TITLE
Defining drop_group

### ISSUE THREAD

**Issue by SaraAlidadiani** [gagneurlab/drop#365]
Hi, 

I have two groups in my data, for example, =  group1: control and group2:patient. And I want to do an aberrant splicing analysis on them (compare the control and patient groups).
I am wondering how I have to define the groups in the DROP_GROUP columns of the sample_Annotation table?
I would truly appreciate it if you could guide me, please?
I really appreciate any help you can provide.

**Comment by vyepez88** [comment]
Hi Sara,
Unfortunately, the aberrant splicing module of DROP is not intended to compare between the splicing of 2 different groups. We focus on detecting aberrant spliced junctions in one same population. The analysis that you're interested in is called alternative splicing. We have used the tool LeafCutter in the past with good results and can recommend you to use it.
