### ISSUE TITLE
Error: MissingRuleException

### ISSUE THREAD

**Issue by agomez700** [gagneurlab/drop#368]
Hi all, 
wondering if anyone has come across this.
I am currently using the NatureProtocol dataset and config file to work my way through the protocol/practice use of the pipeline prior to inputting my own data. 
When I run snakemake -n that works, however whenever I try to run snakemake -aberrantExpression, aberrantSplicing, or mae it gives me: 
MissingRuleException:
No rule to produce aberrantSplicing (if you use input functions make sure that they don't raise unexpected exceptions).
(or a similar error as applicable for what I am trying to run).

has anyone encountered this or know how to fix? 
Thanks

**Comment by vyepez88** [comment]
Hi, can you double check if the `run` parameter in the config file is set to `true` in the different modules?

**Comment by agomez700** [comment]
Thank you - I thought I had tried that before but I suspect I missed one of the modules. However it is now giving me an error in line 3 of the snakefile (import drop) where it says "no module named 'drop'". Any idea how to fix?

**Comment by agomez700** [comment]
Thank you. I thought I had and it was giving me same error but have now updated again and getting different error. 
The error I now get states: 
ScannerErrorin line 12 of /lab-share/Neph-Sampson-e2/Public/AC/drop_protocol/Output/Snakefile:
mapping values are not allowed here
  in "config.yaml", line 20, column 11
  File "/lab-share/Neph-Sampson-e2/Public/AC/drop_protocol/Output/Snakefile", line 12, in <module>
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/wbuild/utils.py", line 314, in __init__
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/__init__.py", line 93, in load_all
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/constructor.py", line 45, in get_data
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/composer.py", line 27, in get_node
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
  File "/home/ch222985/.conda/envs/drop_env2/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value

Interestingly before when I attempted to run snakemake sampleAnnotation it worked without these errors and now I get the error above when I try to run that as well, but changing the config file so the run parameter was set to true was the only change I made.
Any thoughts on how to fix this or what issue may be?

**Comment by agomez700** [comment]
That worked but now I am getting the following error:
WorkflowError:
MissingInputException: Missing input files for rule markdown:
    output: /home/ch222985/Public/AC/drop_protocol/Output/html/Scripts_AberrantExpression_pipeline_aberrant_expression_readme.html
    wildcards: file=Scripts_AberrantExpression_pipeline_aberrant_expression_readme
    affected files:
        Scripts_AberrantExpression_pipeline_aberrant_expression_readme.md
MissingInputException: Missing input files for rule markdown:
    output: /home/ch222985/Public/AC/drop_protocol/Output/html/aberrant-expression-pipeline_index.html
    wildcards: file=aberrant-expression-pipeline_index
    affected files:
        aberrant-expression-pipeline_index.md

Any idea how to troubleshoot this?
Thank you for your help!

**Comment by nickhsmith** [comment]
DROP has also gone through significant changes since the original paper. Can please share your DROP version and config as well?

**Comment by agomez700** [comment]
I'm using DROP version 1.2.2. 
Below is my config file: 

projectTitle: Detection of RNA Outlier Pipeline
htmlOutputPath: /home/ch222985/Public/AC/Nature_Drop/html
indexWithFolderName: true
fileRegex: .*\.R

root: /home/ch222985/Public/AC/Nature_Drop
sampleAnnotation: /home/ch222985/Public/AC/Nature_Drop/100_Sample_Set_Annotation.tsv
geneAnnotation:
    v29: /reference_databases/1000G_Drop_data/ENSEMBL/Homo_sapiens.GRCh37.87_v2.gtf
genomeAssembly: hg19
genome: /reference_databases/ReferenceGenome/hg19/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
scanBamParam: null
exportCounts:
  geneAnnotations:
    - v29
  excludeGroups:
    - mae

aberrantExpression:
    run: true
    groups: 
      - all
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 1
    zScoreCutoff: 0
    maxTestedDimensionProportion: 3

aberrantSplicing:
    run: false
    groups: 
      - all
    recount: true
    longRead: false
    keepNonStandardChrs: true
    filter: false
    minExpressionInOneSample: 20
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 1
    zScoreCutoff: 0
    deltaPsiCutoff : 0.05
    maxTestedDimensionProportion: 6

mae:
    run: false
    groups:
      - all
    gatkIgnoreHeaderCheck: true
    padjCutoff: .05
    allelicRatioCutoff: 0.8
    addAF: false
    maxAF: .001
    maxVarFreqCohort: .04
    # VCF-BAM matching
    qcVcf: /home/ch222985/Public/AC/Nature_Drop/qc_vcf_1000G.vcf.gz
    qcGroups:
      - mae

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools


The sample annotation now runs but when I try to run snakemake aberrantExpression I get the following error: 

MissingInputException in rule markdown in line 54 of /home/ch222985/.conda/envs/drop_envN/lib/python3.10/site-packages/wbuild/wBuild.snakefile:
Missing input files for rule markdown:
    output: /home/ch222985/Public/AC/Nature_Drop/html/Scripts_AberrantExpression_pipeline_aberrant_expression_readme.html
    wildcards: file=Scripts_AberrantExpression_pipeline_aberrant_expression_readme
    affected files:
        Scripts_AberrantExpression_pipeline_aberrant_expression_readme.md

[100_Sample_Set_Annotation_copy.txt](https://github.com/gagneurlab/drop/files/9608583/100_Sample_Set_Annotation_copy.txt)

Attached is copy of sample annotation

Thank you for your help!

**Comment by nickhsmith** [comment]
Your config file seems to be based off of an old template. Can you please make sure you are using the newest template as a guide [found here](https://github.com/gagneurlab/drop/blob/master/drop/template/config.yaml)

Notably I notice some extra fields that are disrupting the run. Notably the ` fileRegex: .*.R` line. But just looking at it I also see the legacy value `scanBamParam`

I think that if you delete these 2 lines you should be able to run the module(s)

**Comment by agomez700** [comment]
That did seem to have worked and the modules start running but eventually runs up against the following error:
Error in rule AberrantSplicing_pipeline_Counting_01_3_countRNA_nonSplitReads_samplewise_R:
    jobid: 28
    output: /home/ch222985/Public/AC/Nature_Drop/processed_data/aberrant_splicing/datasets/cache/raw-local-small/sample_tmp/nonSplitCounts/sample_HG00096.1.M_111124_6.done
    log: /lab-share/Neph-Sampson-e2/Public/AC/Nature_Drop/.drop/tmp/AS/small/nonsplitReads/HG00096.1.M_111124_6.Rds (check log file(s) for error message)

RuleException:
CalledProcessErrorin line 139 of /tmp/tmpruofa589:
Command 'set -euo pipefail;  Rscript --vanilla /lab-share/Neph-Sampson-e2/Public/AC/Nature_Drop/.snakemake/scripts/tmp1_njns5d.01_3_countRNA_nonSplitReads_samplewise.R' returned non-zero exit status 134.
  File "/tmp/tmpruofa589", line 139, in __rule_AberrantSplicing_pipeline_Counting_01_3_countRNA_nonSplitReads_samplewise_R
  File "/home/ch222985/.conda/envs/drop_envN/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-09-21T132908.720703.snakemake.log

Any ideas?

**Comment by nickhsmith** [comment]
Did you make sure to follow the current instructions and template for DROP 1.2.2? You can read more here as well:
https://gagneurlab-drop.readthedocs.io/en/latest/

Can you please provide us with some of the logging information? 

Either copy paste the relevant section directly from the terminal or attach the most recent log from the `.snakemake/log/` directory

**Comment by nickhsmith** [comment]
Were there any updates on your side? Did you look into the log files?
