### ISSUE TITLE
gene annotations GTF format requirements

### ISSUE THREAD

**Issue by AnikoSabo** [gagneurlab/drop#369]
Hi, 
this question is regarding the required GTF format for gene annotations. 

I am setting up the DROP pipeline for a large project, and was able to run successfully with the latest gencode gtf file (https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/GRCh37_mapping/gencode.v41lift37.annotation.gtf.gz). 

I also have a different gtf file that "matches" the reference used for mapping the reads. Reads were mapped using STAR aligner to GRCH37 with added ERCC spike-in contigs, and MHC alternative haplotypes.  The matching GTF file is based on an old GTF Ensembl version 71 (http://ftp.ensembl.org/pub/release-71/gtf/homo_sapiens/Homo_sapiens.GRCh37.71.gtf.gz), with added annotations on those "extra" contigs (ERCC + MHC). 

The problem is that DROP run fails with the ensembl 71 gtf file, and is complaining of an error parsing gene annotations (error file attached). 

I believe the issue is the difference in the formatting of the two GTF files, the gencode GTF and the Homo_sapiens.GRCh37.71 one.  The easiest way to illustrate the difference is to look at the column 3 in each GTF file for one gene as an example:

gencode GTF file:
gene
transcript
exon
exon
exon
transcript
exon
exon
exon
exon
exon
exon

OLD ensembl gtf file:
exon
exon
exon
exon
exon
exon
exon
exon
exon
exon
exon
exon
exon
exon
exon
exon

My questions are:

1. Is the issue that the GTF has to have gene, transcript AND exons, and that having ONLY exons is breaking the parsing?

2. How important is it to "match" reference that the reads are aligned to, IF the ONLY difference is those added ERCC and MHC alternative haplotype contigs, but the backbone reference is the same GRCh37?  Could I just use the gencode gene models and be fine? 

thank you
Aniko

[drop_test_run.err.txt.txt](https://github.com/gagneurlab/drop/files/9619581/drop_test_run.err.txt.txt)

**Comment by vyepez88** [comment]
Hi Aniko,
Great to see you're using DROP for a large project :)
1. This is the script that processes the gtf file: https://github.com/gagneurlab/drop/blob/master/drop/template/Scripts/Pipeline/preprocessGeneAnnotation.R
As you can see, the gtf file needs to have both exon and gene information. You could adapt that script to meet your needs.
2. Sorry, I don't understand what you mean by the gtf "matches" the reference used. You mean the chr style? We have used both gtf files from gencode and ensembl and have had optimal results.

**Comment by AnikoSabo** [comment]
thank you for your quick reply! I really appreciate it.  I am part of the RADIANT project:
https://www.atypicaldiabetesnetwork.org/

What I meant is that the reference the reads were mapped to had chr1-22, X,Y,MT, but also ERCC contigs, and some MHC alternative haplotype contigs. While the gencode GTF file will only have annotations on chr1-22, X,Y,MT, but NO annotaions for those extra contigs (ERCC, MHC).  

 I was wondering if this would cause any problems, the lack of gene annotations for those extra contigs that were used in mapping. If not, I would happily use the latest gencode. 

Thank you

**Comment by vyepez88** [comment]
Ah I understand now. There shouldn't be any problems then, unless you are interested in quantifying genes in those contigs.
Good luck with your analyses!

**Comment by AnikoSabo** [comment]
Thanks!
