### ISSUE TITLE
splitReads from BAM file

### ISSUE THREAD

**Issue by mjbarrero** [gagneurlab/drop#371]
Hello,
I am running my own samples using BAM files to detect aberrant splicing. I used RNA STAR for the aligments (twopassMode = ‘Basic’) .  I get the following error:

Fri Sep 23 15:05:51 2022: Count split reads for sample: Normal_S1
Fri Sep 23 15:05:51 2022: Count split reads for sample: ND0743
Fri Sep 23 15:05:51 2022: Count split reads for sample: Normal_S2
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/ND0743.bai
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/Normal_blood_S1.bai
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/Normal_blood_S2.bai
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/Normal_blood_S1.bai
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/ND0743.bai
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/Normal_blood_S2.bai
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/Normal_blood_S1.bai
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/ND0743.bai
[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/Normal_blood_S2.bai
[W::hts_idx_load2] [W::hts_idx_load2] The index file is older than the data file                                                                                                                               : /data/iier/imm/BAMfiles/ND0743.baiThe index file is older than the data file:                                                                                                                                /data/iier/imm/BAMfiles/Normal_blood_S1.bai

[W::hts_idx_load2] The index file is older than the data file: /data/iier/imm/BA                                                                                                                               Mfiles/Normal_blood_S2.bai
Error in env[[as.character(i)]] <- value :
  wrong args for environment subassignment
Calls: countSplitReads ... bploop -> bploop.iterate -> <Anonymous> -> add_inorde                                                                                                                               r
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
Execution halted
[Fri Sep 23 15:06:42 2022]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_sample                                                                                                                               wise_R:
    jobid: 77
    output: Output/processed_data/aberrant_splicing/datasets/cache/raw-local-all                                                                                                                               /sample_tmp/splitCounts/sample_ND0743.done
    log: /data/iier/imm/analysis/.drop/tmp/AS/all/splitReads/ND0743.Rds (check l                                                                                                                               og file(s) for error message)

RuleException:
CalledProcessErrorin line 121 of /tmp/tmpd3s6qc7b:
Command 'set -euo pipefail;  Rscript --vanilla /data/iier/imm/analysis/.snakemak                                                                                                                               e/scripts/tmpbk25mugs.01_1_countRNA_splitReads_samplewise.R' returned non-zero e                                                                                                                               xit status 1.
  File "/tmp/tmpd3s6qc7b", line 121, in __rule_AberrantSplicing_pipeline_Countin                                                                                                                               g_01_1_countRNA_splitReads_samplewise_R
  File "/data/iier/imm/drop/drop_env/lib/python3.10/concurrent/futures/thread.py                                                                                                                               ", line 58, in run

I believe there must be a problem with the BAM or bai files. What could I try to solve it?
Thanks a lot!!!!!!

**Comment by vyepez88** [comment]
Hi, which DROP version are you using? How many samples do you have in the DROP group you're running? Was the counting successful for any of them? Can you confirm that you have enough memory in the server where you're running this?

**Comment by mjbarrero** [comment]
Hi Vicente,
Thanks a lot for your replay. I am not a bioinformatician but I will try to answer your questions the best I can.
I am using DROP version 1. 2. 2. I have 27 samples in one group and 19 samples in another group. I am using an HPC cluster and I belive memory should not be a problem. I am not sure about the counting, I can see two .rds files in the splitcounts folder. Hope this helps.

**Comment by vyepez88** [comment]
Hi, if you see files in this folder `Output/processed_data/aberrant_splicing/datasets/cache/raw-local-all /sample_tmp/splitCounts/`, it means that the counting did work for some samples. 
You can run the following:
`snakemake --cores X aberrantSplicing -k` (replacing X with the desired number of cores). The `-k` parameter means keep running, so it will try to count the split reads of all possible samples. Then, we would know which is/are the incorrect one(s).
Another potential issue I noticed is in your path ` /data/iier/imm/BA Mfiles/`, there seems to be a space between BA and Mfiles. Avoid having spaces in directory names.

**Comment by mjbarrero** [comment]
Hi Vicente,
Thanks a lot for your reply. I did not get counts in any sample. I run several tests and it won't run with strand "yes" or "reverse" although the library was stranded. It runs to the end with strand "no". Any idea why this happens? What do I miss if I run it strand "no"? Thanks a lot!

**Comment by vyepez88** [comment]
I have one idea. FRASER uses the BSgenome package to count stranded (either yes or reverse). That requires internet connection. Can you make sure your cluster has access to internet?

**Comment by mjbarrero** [comment]
Hi Vicente,
It finally turned out to be a memory problem. I have finally managed to allocate the proper resources to run the program and it worked. Thanks a lot for your help and for making this nice tool available to the non-experts.
