### ISSUE TITLE
Control counts GRCh38 and HPC usage queries!

### ISSUE THREAD

**Issue by SophieS9** [gagneurlab/drop#374]
Dear Drop Team!

I've got two queries about the use of Drop. Apologies if this isn't the right platform or if you'd prefer this split across two issues! I'm happy to repost elsewhere, just let me know!

We're running Drop on a small set of RNA samples from fibroblasts with a paied end stranded prep (24 in total) and so are looking at a control dataset to help with power. We need to use a set in GRCh38 as our corresponding DNA analysis pipeline uses this genome version. I've seen the following set https://zenodo.org/record/6078397#.YzW3BXbMKUk listed on the webpage, but I had a query about whether this is suitable for use as it's mixed tissue and not strand specific? Would this be an OK set to include? Ideally, we'd use https://zenodo.org/record/4646827#.YzW4UXbMKUk as it's fibroblasts and stranded but this is in genome build hg19 and we really need to use GRCh38. Alternatively, we could re-create the fibroblast stranded count set using GRCh38, so I was wondering if you knew if the raw data was available?! Or if you're aware of any other GRCh38 control sets? 

In addition, we're running drop on a slurm compute cluster. I'm running snakemake with 24 cores, but it's still using just one "job" on the cluster, is there a way to parallelize this across multiple jobs/nodes on the HPC? 

Thanks :)

Sophie

**Comment by vyepez88** [comment]
Hi Sophie!
This is the right platform :)
1. Unfortunately, at the moment, we don't have any fibroblasts, stranded, hg38, nor I am aware of a publicly available dataset like that (everyone seems happy with hg19...). You could be our first contributor with your 24 samples! :D
2. We built DROP in such a way that it automatically parallellizes using the provided cores. Simply running `snakemake --cores 24` should do the job. You can check that, e.g. in the counting step. Do you see 24 jobs being executed at the same time?

**Comment by SophieS9** [comment]
Thanks for getting back to me :) 

For 1. we're going to try working with the non-stranded hg38 set and turn off stranded settings for our samples - that's what my other issue is about so I'll reply in that one!

For 2. I'm requesting 24 cores on a single node, and the job is running across all of the nodes, but it's not submitting separate jobs to the cluster, just one job. I wasn't sure if this was how it's designed to run or if it's supposed to be split across jobs?

**Comment by vyepez88** [comment]
Which snakemake command are you running or how are you executing it?

**Comment by SophieS9** [comment]
We use a slurm cluster, so I'm running as follows:
```
srun --mem=256G --cpus-per-task=24 snakemake --cores 24
```

**Comment by nickhsmith** [comment]
Hi Sophie, for point No. 2 I think there is an issue with the way that you are scheduling the jobs.

By saying you want 24 cpus per task, and by giving it 24 cores, it seems like you can only run 1 task at a time. I would change `--cpus-per-task=24` to `--cpus-per-task=6` then you should be able to run 4 tasks at a time.

Additionally you can use the `snakemake --cluster` command, which is what I personally do.

```
snakemake --cluster "sbatch -N1 -n 2 --mem 50Gb" -j 12 -k 
```

This says give each job 1 node, 2 cpus, 50Gb of ram. And try to run 12 jobs at a time. If a job fails (`-k`) keep going

**Comment by SophieS9** [comment]
Thanks @nickhsmith! That's exactly the information I was after! I'm not familiar with snakemake and didn't realise that it was a generic option I could use to invoke slurm properly. It's probably outside the remit of drop, but might be handy pointing to a snakemake info page from the drop manual so that people can easily find that information, as it's making a big difference to the run time being able to parallelize! Will close the issue :)
