### ISSUE TITLE
Sample Annotation with Controls

### ISSUE THREAD

**Issue by SophieS9** [gagneurlab/drop#375]
Hi Drop Team,

Apologies for raising two issues in one day! I'm running DROP with my own samples successfully, but when I tried to add external counts, it's failing pretty much instantly with the following error message:

```
check for missing R packages
MonoallelicExpression has been turned off in the config file
rnaVariantCalling has been turned off in the config file
Structuring dependencies...
Dependencies file generated at: /tmp/tmpdi8dtof3

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError:
        MissingInputException: Missing input files for rule markdown:
            output: /home/v.so257591/Jana_RNASeq/Drop_Child_Control/AberrantExpression/Counting/gencode29/Summary_outrider.html
            wildcards: file=AberrantExpression/Counting/gencode29/Summary_outrider
            affected files:
                AberrantExpression/Counting/gencode29/Summary_outrider.md
        WorkflowError (rule AberrantExpression_pipeline_Counting_mergeCounts_R, line 135, /tmp/tmpdi8dtof3):
            Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
        output: /home/v.so257591/Jana_RNASeq/Drop_Child_Control/Scripts_AberrantExpression_pipeline_Counting_Datasets.html
        wildcards: file=Scripts_AberrantExpression_pipeline_Counting_Datasets
        affected files:
            Scripts_AberrantExpression_pipeline_Counting_Datasets.md
MissingInputException: Missing input files for rule markdown:
    output: /home/v.so257591/Jana_RNASeq/Drop_Child_Control/aberrant-expression-pipeline_index.html
    wildcards: file=aberrant-expression-pipeline_index
    affected files:
        aberrant-expression-pipeline_index.md
```

I feel like this must be an issue with my sample groups sheet, but I've tried editing it a bunch of ways and still get this error. Working completely fine if I remove the controls. I've attached the sample groups along with my config file (had to change to txt to upload) - any help would be much appreciated!

Thanks :)

Sophie 

[config.txt](https://github.com/gagneurlab/drop/files/9685666/config.txt)
[Sample_Groups_Drop_wControl.txt](https://github.com/gagneurlab/drop/files/9685667/Sample_Groups_Drop_wControl.txt)

**Comment by vyepez88** [comment]
Hi, don't worry for raising issues! :)
I cannot see any error in the config or sample annotation. I usually have lowercase `no` for the STRAND, but if you say it works without controls, then I guess that's not the problem.
Can you try the following:
`snakemake -n aberrantExpression`
`snakemake -n /home/v.so257591/Jana_RNASeq/Drop_Child_Control/AberrantExpression/Counting/gencode29/Summary_outrider.html`
Also, which DROP version are you using? (you can check that by doing `drop --version`)

**Comment by SophieS9** [comment]
Thanks for getting back to me :)

Running `snakemake -n aberrantExpression` gives the same error as above. 
Running `snakemake -n /home/v.so257591/Jana_RNASeq/Drop_Child_Control/AberrantExpression/Counting/gencode29/Summary_outrider.html` gives a subet of that error:
```
WorkflowError:
MissingInputException: Missing input files for rule markdown:
    output: /home/v.so257591/Jana_RNASeq/Drop_Child_Control/AberrantExpression/Counting/gencode29/Summary_outrider.html
    wildcards: file=AberrantExpression/Counting/gencode29/Summary_outrider
    affected files:
        AberrantExpression/Counting/gencode29/Summary_outrider.md
WorkflowError (rule AberrantExpression_pipeline_Counting_mergeCounts_R, line 135, /tmp/tmp6igp85qo):
    Function did not return str or list of str.
```

Using version 1.2.2 :)

**Comment by vyepez88** [comment]
Hi, it seems that you have two times the `GENE_COUNTS_FILE` column in the sample annotation. Can you remove the empty one and try again?

**Comment by SophieS9** [comment]
Thanks @vyepez88 that worked! I think I checked every other character in the file, but completely missed that I'd repeated the headers!

**Comment by vyepez88** [comment]
I also missed it the first time I looked at it :D good luck with your analyses!
