### ISSUE TITLE
unrecognized arguments: drop

### ISSUE THREAD

**Issue by HarryShen668** [gagneurlab/drop#381]
Hi,
As I am trying to install the DROP by mamba
`mamba create -n drop_env -c conda-forge -c bioconda drop --override-channels`
it shows 
```
usage: mamba [-h] [-V] command ...
mamba: error: unrecognized arguments: drop
````
the mamba version I used is `mamba (1.0.0)` and conda version is `conda 22.9.0`

I changed mamba to conda by
`conda create -n drop_rna -c conda-forge -c bioconda drop --override-channels`

I got 
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
```
seems can not work

**Comment by nickhsmith** [comment]
Hmm. I'm sorry you're having problems. It seems that Mamba updated their version last week, and conda 2 months ago. I wonder if that has something to do with it. Maybe the short-term solution is to downgrade your version of mamba/conda. 

When I check the version on my computer we have the following
```
[smith]$ mamba --version
mamba 0.24.0
conda 4.13.0
```

I will attempt to recreate your problem, but my guess is that DROP in combination with the new mamba/conda may have a hiccup

**Comment by nickhsmith** [comment]
Using micromamba (v1.0.0) I was able download drop and run the demo successfully.
```

**Comment by nickhsmith** [comment]
I locally updated my mamba and conda to be the same as yours, but I was unable to recreate the problem. Is there any chance you could try again and see if it has been merged with bioconda?

```
(drop_smith) mamba --version
mamba 1.0.0
conda 22.9.0
(drop_smith) 
(drop_smith)  mamba create -n drop_test_smith -c conda-forge -c bioconda drop --override-channels

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.0.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['drop']

bioconda/noarch                                      4.0MB @   2.9MB/s  1.4s
bioconda/linux-64                                    4.5MB @   3.0MB/s  1.6s
conda-forge/noarch                                  10.1MB @   3.3MB/s  3.2s
conda-forge/linux-64                                27.5MB @   3.6MB/s  7.9s
Transaction

  Prefix:~/anaconda/envs/drop_test_smith

  Updating specs:

   - drop

... 

```

**Comment by nickhsmith** [comment]
Additionally we provide a preset conda installation recipe yaml. The `DROP_1.2.2.yaml` installation file we make available on our [public server](https://www.cmm.in.tum.de/public/paper/drop_analysis/). Install this using the following command:

```
mamba env create -f DROP.yaml
```

**Comment by nickhsmith** [comment]
Were you able to take another look? I tried with a fresh install and it seemed to work

**Comment by HarryShen668** [comment]
Thanks for the information, I downgrade my version of mamba
As I notice that there are some other problems when I use the ` mamba ` command such as 
```
mamba --version
usage: mamba [-h] [-V] command ...
mamba: error: unrecognized arguments: --version
```
and
```
mamba env create -f DROP_1.2.2.yaml
usage: mamba [-h] [-V] command ...
mamba: error: unrecognized arguments: DROP_1.2.2.yaml
```
I think it might be some problems with my mamba and not the DROP, maybe I should ask the mamba team for help.
Thank you still

**Comment by nickhsmith** [comment]
You need to specify the whole path to the DROP_1.2.2.yaml

**Comment by HarryShen668** [comment]
The YAML file is under the current directory, and I have tried both AbsolutePath and RelativePath but can not work.
I think it may be another problem as `mamba --version` can not be recognized either.

**Comment by nickhsmith** [comment]
Like I said, I tried with up to date mamba and it was able to work with
this yaml and on the fly. Maybe a fresh mamba install/upgrade would work?

**Comment by nickhsmith** [comment]
Let us know how it goes. My guess would be reinstalling mamba/conda
