### ISSUE TITLE
drop demo fail for MAE

### ISSUE THREAD

**Issue by liffcardio** [gagneurlab/drop#383]
Hi. While installing drop and testing the demo, snakemake fails.
The log is attached. Thank you.
[2022-11-08T051428.048892.snakemake.log](https://github.com/gagneurlab/drop/files/9958358/2022-11-08T051428.048892.snakemake.log)

**Comment by nickhsmith** [comment]
Thanks for reaching out, and sorry you're having issues. Can you please share your drop version `drop --version`?

I think there may be a problem with the HTML writing rights? 

Could you please run using the `-k` command? This will run other jobs, and we can see if the other HTML renderings work.

```
snakemake -c1 -k
```

**Comment by liffcardio** [comment]
> Thanks for reaching out, and sorry you're having issues. Can you please share your drop version `drop --version`?
> 
> I think there may be a problem with the HTML writing rights?
> 
> Could you please run using the `-k` command? This will run other jobs, and we can see if the other HTML renderings work.
> 
> ```
> snakemake -c1 -k
> ```

Thank you for answering me. The version of drop is drop, version 1.2.2
I run snakemake -c1 -k and the log is attached. Thank you very much
[2022-11-09T015328.206027.snakemake.log](https://github.com/gagneurlab/drop/files/9966759/2022-11-09T015328.206027.snakemake.log)

**Comment by nickhsmith** [comment]
It seems like everything else worked. I'm really perplexed as to what is exactly failing in your demo.

Just for a sanity check can you do the following?
1) rerun the `mae` module, maybe something got interrupted and saved poorly? `snakemake mae -F -c1`
2) if that fails, can you please share the contents of `Output/processed_data/mae/params/results/mae_resultParams.csv`

**Comment by liffcardio** [comment]
when I run snakemake -c1 -k, not all the steps are finished. There was error too. 
It fails when I try snakemake mae -F -c1, the file is attached.
[mae_resultParams.csv](https://github.com/gagneurlab/drop/files/9980798/mae_resultParams.csv)

**Comment by nickhsmith** [comment]
What do you mean "not all the steps are finished"? Your previous log only showed 1 error, with the other processes finishing.

Can you please also share the console output of 

```
snakemake /root/drop_demo/Output/processed_results/mae/mae/MAE_results_all_v29.tsv.gz -c1
```

**Comment by liffcardio** [comment]
I'm sorry I misunderstand what you mean by everything else worked. Sorry for that.
I run the code and it failed again. the log is attached. Thank you very much.
[2022-11-11T082959.479325.snakemake.log](https://github.com/gagneurlab/drop/files/9988496/2022-11-11T082959.479325.snakemake.log)

**Comment by liffcardio** [comment]
and for console output, do you mean this file?
[mae_resultParams.csv](https://github.com/gagneurlab/drop/files/9988573/mae_resultParams.csv)

**Comment by nickhsmith** [comment]
Not quite. Can you run the following and share the file `test.txt`

`snakemake /root/drop_demo/Output/processed_results/mae/mae/MAE_results_all_v29.tsv.gz -c1 &> test.txt`

**Comment by liffcardio** [comment]
Here is the file
[test.txt](https://github.com/gagneurlab/drop/files/9988649/test.txt)

**Comment by nickhsmith** [comment]
found the error!

```
 55 Quitting from lines 113-146 (/tmp/Rtmp9XPmtp/fileca2c44b1b39d/Results.spin.Rmd)
 56 Error in fwrite(res, snakemake@output$res_all, sep = "\t", row.names = F,  :
 57   Compression in fwrite uses zlib library. Its header files were not found at the time data.table was compiled. To enable fwrite compression, please reinstall data.table and study the output for further guidance.
 58 Calls: render ... withVisible -> eval_with_user_handlers -> eval -> eval -> fwrite
```

Seems like your R package installation didn't work perfectly. 

From your terminal try to reinstall
```
R
install.packages("data.table")
```

Or check the version/stability of this
```
R
library(data.table)
```

**Comment by liffcardio** [comment]
I reinstall the package and rerun the code, but it failed again. I check the text file it still said please reinstall data.table
I check the version of data.table. It is data.table 1.14.4

**Comment by nickhsmith** [comment]
I'm not exactly sure the best way for you to fix this (either a fresh install or just fixing this package). But you can also try to reinstall directly in conda

 conda install -c conda-forge r-data.table --force-reinstall

**Comment by liffcardio** [comment]
I use docker to run the demo, I think there might be something wrong with the image. Thank you so much for the patient answer. I will let you know if conda works.

**Comment by liffcardio** [comment]
I reinstall drop by conda, and there is error when I run snakemake -n --cores 1
Building DAG of jobs...
Traceback (most recent call last):
  File "/opt/conda/envs/drop_env/lib/python3.10/site-packages/snakemake/__init__.py", line 747, in snakemake
    success = workflow.execute(
  File "/opt/conda/envs/drop_env/lib/python3.10/site-packages/snakemake/workflow.py", line 949, in execute
    self.scheduler = JobScheduler(
  File "/opt/conda/envs/drop_env/lib/python3.10/site-packages/snakemake/scheduler.py", line 373, in __init__
    from throttler import Throttler
ModuleNotFoundError: No module named 'throttler'
do you have any idea about that?

**Comment by nickhsmith** [comment]
No, sorry. We maintain the Conda recipe, not a docker container. So I can only point you to our latest conda recipe. and our installation instructions

https://gagneurlab-drop.readthedocs.io/en/latest/installation.html#installation
https://www.cmm.in.tum.de/public/paper/drop_analysis/DROP_1.2.2.yaml

**Comment by liffcardio** [comment]
I didn't use the docker this time. That error happened when I followed the file you provided to install drop by conda.

**Comment by nickhsmith** [comment]
Just to be clear you did the following using up to date conda/mamba

1. remove existing conda env
2. remove existing drop_demo dir
3. create `drop_env` from the provided hard recipe
4. activate newly create `drop_env`
5. create an empty directory
6. go into the empty dir
7. run drop demo to initialize the directory
8. run snakemake mae to check if installed correctly

These are all done by the following commands

```
conda env remove -n drop_env 
rm -rf drop_demo
mamba env create -f DROP_1.2.2.yaml
conda activate drop_env
mkdir drop_demo
cd drop_demo
drop demo
snakemake mae -c1
```

And this fails?

**Comment by liffcardio** [comment]
I am sorry to bother you. When I try to open the link of the recipe DROP_1.2.2.yaml you provided . It said I don't have permission to access the resource. I cannot open the web. I also try to use wget to download the file. It failed to download it.

**Comment by nickhsmith** [comment]
fixed.

**Comment by liffcardio** [comment]
I download the yaml file and remove the drop_env and the file of drop_demo, and then create a new environment by inputing
mamba env create -f ~/DROP_1.2.2.yaml
and it returned:
Encountered problems while solving.
Problem: nothing provides __unix needed by click-8.1.3-unix_pyhd8ed1ab_2
Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by libgit2-1.5.0-h6529ace_0
Problem: nothing provides __unix needed by pysocks-1.7.1-pyha2e5f31_6
Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by r-rcpp-1.0.9-r41h7525677_2

and then I check the environment
conda info -e
conda environments:
base                  *  /opt/conda

There is no environment of drop_env.

**Comment by nickhsmith** [comment]
My only guess is that you have an old version of conda/mamba

```
mamba --veresion
conda --version
```
you can also try `conda env create -f DROP_1.2.2.yaml`

These are the up to date versions
```
mamba 1.0.0
conda 22.9.0
```

Otherwise, I have no idea. It seems like a conda problem, maybe there are some base packages that are interfering. But I can't replicate your problem on any of the machines I have access to.

**Comment by liffcardio** [comment]
I update the conda and retry. It worked this time! Thank you so much for the patient answer. I am a beginner with bioinformatics and debugging, I really learned a lot this time. Your help really means a lot to me!
