### ISSUE TITLE
Removal of noncoding variants influences MAE calculations of coding variants

### ISSUE THREAD

**Issue by scharf-f** [gagneurlab/drop#385]
Dear DROP-Team,

first, I would like to thank you very much for the valuable resource and the support you provide! 

I am currently exploring the MAE part of your toolbox and I am encountering - for me - unexpected behaviour that I would like to ask you about.

I already did a few analyses with the MAE tool using short read RNA Seq data and the respective germline short read NGS data. Doing so I found some erroneous evaluations of noncoding variants leading to intron retentions. Since these variants are
covered by sequencing data, in (nearly) 100% of the reads we see the alternative allele, which resulted in a predicted monoallelic expression of this allele. I would think they should be put in relation to the reads spanning the fusion between the exons, however that is not my main question.

We wanted to get rid of these cases and thus removed all noncoding variants from the VCF file before running the MAE tool. We expected this to not influence the overall results, only to get rid of the above mentioned predictions.
However, we found that removing noncoding variants did alter the prediction for coding variants in one gene - in one case even to an extent where a previously statistically significant reduction of one allele (which was by the way what we expected to see) was not significant anymore (adjusted p-value changed from 0.022 to 0.09).

Is this expected behaviour? How and why are the noncoding variants influencing the prediction for coding variants? And what do you think would be appropriate - keep noncoding variants and remove them after running MAE?

Thank you very much for your help!

Kind regards,
Florentine

**Comment by vyepez88** [comment]
Hi, the adjusted p-value is intended to correct for multiple testing and its calculation depends on the:
- number of variants
- nominal p-value
As you're testing less variants, the value p-adjusted will be different. Note that doesn't matter whether the variants are coding or non-coding.
The nominal p-value depends on the counts of the reference and alternative alleles, as well as the baseMean. This baseMean is the average of the normalized counts using size factors. The size factors are computed throughout all the variants. Therefore the included variants can affect the size factors and therefore the nominal p-value. It could be that non-coding variants have a different proportion of ref/alt counts than coding ones. You can check the size factors and their influence on the results yourself by executing the following code:
```
library(data.table)
library(DESeq2)

# read data, do it for the cases will all variants, non-coding ones and coding ones
allele_counts_dt <- fread() # read the allellic counts of some sample (see processed_data/allelic_counts folder)

# create deseq object
dds <- DESeqDataSetFromMatrix(
  as.matrix(allele_counts_dt[, .(altCount, refCount)]),
  DataFrame(condition=factor(c("altAllele", "refAllele"))),
  design = ~ condition
)

# estimate the size factors and pseudo dispersion
dds <- estimateSizeFactors(dds)
sizeFactors(dds)
# dds <- estimateDispersions(dds) # impossible to determine now with only 1 sample and 2 conditions

# set dispersion
dispersions(dds) <- .05

# run wald test
dds <- nbinomWaldTest(dds)
res <- results(dds, contrast = c("condition", "altAllele", "refAllele"), 
               independentFiltering = independentFiltering)

```
Whether you should keep them, depends completely on your desired analysis.

**Comment by scharf-f** [comment]
Hello,

thank you very much for the explanation, which make perfect sense to me now.

However, I am not completely convinced concerning the altRatios calculated for noncoding variants. In case of e.g. a noncoding variant leading to an intron retention, the variant will appear in 100% of RNA reads, which obviously indicates a complete allelic loss, but which does not necessarily reflect one. What is your opinion on that?

In our case, we thus removed noncoding variants from the input VCFs prior to MAE analysis.

Thank you very much again for the clarifications!

Kind regards,
Florentine

**Comment by vyepez88** [comment]
Hi,
If an intronic, heterozygous variant causes intron retention, then I would expect to see it mono-allelically expressed with 100% of RNA reads, yes. I don't see why this will "obviously indicate complete allelic loss" and why would I not see that reflected.
