### ISSUE TITLE
Error in rule AberrantExpression_Overview_R

### ISSUE THREAD

**Issue by sav0016** [gagneurlab/drop#386]
Hello, I'm getting following error at the end of aberrant expression pipeline:

Quitting from lines 102-105 (/data2/sav0016/tmp/Rtmp1cxG9T/file65ed456cbcb21/Overview.spin.Rmd)
Error: comparison (1) is possible only for atomic and list types
In addition: Warning message:
In max(sampleID) : no non-missing arguments to max; returning -Inf

Execution halted
[Tue Nov  8 13:41:02 2022]
Error in rule AberrantExpression_Overview_R:
    jobid: 62
    output: /data2/sav0016/drop-Anicka-test/Anicka-new/Output/html/Scripts_AberrantExpression_Overview.html
    log: /data2/sav0016/drop-Anicka-test/Anicka-new/.drop/tmp/AE/Overview.Rds (check log file(s) for error message)

RuleException:
CalledProcessErrorin line 11 of /data2/sav0016/tmp/tmpj2jool0r:
Command 'set -euo pipefail;  Rscript --vanilla /data2/sav0016/drop-Anicka-test/Anicka-new/.snakemake/scripts/tmp_zg9eym_.wBRender.R' returned non-zero exit status 1.
  File "/data2/sav0016/tmp/tmpj2jool0r", line 11, in __rule_AberrantExpression_Overview_R
  File "/data2/sav0016/miniconda3/envs/drop_env_latest/lib/python3.10/concurrent/futures/thread.py", line 58, in run

Any ideas? Thank you.

J

**Comment by vyepez88** [comment]
Hi, I guess it's a similar case as in this issue: https://github.com/gagneurlab/drop/issues/372

**Comment by sav0016** [comment]
> Hi, I guess it's a similar case as in this issue: #372

I have zScoreCutoff: 0

My config:

projectTitle: Detection of RNA Outlier Pipeline
htmlOutputPath: /data2/sav0016/drop-Anicka-test/Anicka-new/Output/html
indexWithFolderName: true
root: /data2/sav0016/drop-Anicka-test/Anicka-new/Output
sampleAnnotation: /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/sample_annotation.tsv
geneAnnotation:
  v39: /data1/nf-core-tools/genome/references/Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf
genomeAssembly: hg38
genome:
  hg38: /data1/nf-core-tools/genome/references/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa
hpoFile: /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/hpo_genes.tsv.gz
random_seed: true
export counts:
    geneAnnotations:
    - v39
    groups:
    - D0
    - D1
aberrantExpression:
  run: true
  groups:
  - D0
  - D1
  fpkmCutoff: 1
  implementation: autoencoder
  padjCutoff: 0.1
  zScoreCutoff: 0
  maxTestedDimensionProportion: 3
  dassie:
    tssWindow: 500
    pasWindow: 1000
aberrantSplicing:
  run: false
  groups:
  - D0
  - D1
  recount: true
  longRead: false
  keepNonStandardChrs: false
  filter: false
  minExpressionInOneSample: 20
  minDeltaPsi: 0.05
  implementation: PCA
  padjCutoff: 0.05
  zScoreCutoff: 0
  deltaPsiCutoff: 0.05
  maxTestedDimensionProportion: 6
mae:
  run: false
  groups:
  - D0
  - D1
  gatkIgnoreHeaderCheck: true
  padjCutoff: 0.5
  allelicRatioCutoff: 0.7
  addAF: false
  maxAF: 0.001
  maxVarFreqCohort: 1
  qcVcf: /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/qc_vcf_1000G_hg38.vcf.gz
  qcGroups:
  - D0
  - D1
rnaVariantCalling:
  run: false
  groups:
  - D0
  - D1
  highQualityVCFs:
  - /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/1000G_phase1.snps.high_confidence.hg38.vcf.gz
  - /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
  dbSNP: /data1/ngs/dbsnp/dbsnp.vcf
  repeat_mask: /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/hg38_repeatMasker_sorted.bed
  createSingleVCF: false
  addAF: false
  maxAF: 0.001
  maxVarFreqCohort: 1
  hcArgs: null
  minAlt: 3
tools:
  gatkCmd: gatk
  bcftoolsCmd: bcftools
  samtoolsCmd: samtools

----
Thank you.
J

**Comment by vyepez88** [comment]
The groups shouldn't be specified in each module. Can you remove them?
How many samples do you have on each group?

**Comment by sav0016** [comment]
> The groups shouldn't be specified in each module. Can you remove them? How many samples do you have on each group?

10 and 10. But we have much more samples. So I can add them all without groups?
Thanks.

**Comment by vyepez88** [comment]
the groups should be defined outside the module only, not for each module. 
it's not just the zscoreCutoff, but also the padjCutoff, try setting it to 1

**Comment by sav0016** [comment]
> the groups should be defined outside the module only, not for each module. it's not just the zscoreCutoff, but also the padjCutoff, try setting it to 1

I will try to add more samples and without any groups.

**Comment by vyepez88** [comment]
the number of samples and groups is not a problem, simply the part of the config file where they are defined.

**Comment by sav0016** [comment]
> the number of samples and groups is not a problem, simply the part of the config file where they are defined.

Please can you explain more in which case there should be any groups? Can I run all pipelines as one batch? Thanks. I have about 200 samples with the same disease. Groups were made only based on WES data. So maybe I should run it as one batch.
Thank you very much.

**Comment by vyepez88** [comment]
Sorry for the confusion, I explained myself wrongly.
Here's an extract of your config file
```
geneAnnotations:
- v39
groups:
- D0
- D1
aberrantExpression:
run: true
groups:
- D0
- D1
```
You have defined the groups D0 and D1 both inside the aberrant expression module and outside. They should only be defined inside each module, not outside (I was previously telling you the other way around, sorry).
We usually group samples by group depending on their: tissue, sequencing parameters (e.g. strandness, genome build, polyA), and other major biological/technical bias. 
The more samples inside a group, the higher the statistical power, so I generally recommend having them inside a same group, as long as they fulfill the criteria mentioned before. You could search for biases on the heatmaps on the Summary html reports.
What exactly did you extract from your WES data to define your groups?

**Comment by sav0016** [comment]
> Sorry for the confusion, I explained myself wrongly. Here's an extract of your config file
> 
> ```
> geneAnnotations:
> - v39
> groups:
> - D0
> - D1
> aberrantExpression:
> run: true
> groups:
> - D0
> - D1
> ```
> 
> You have defined the groups D0 and D1 both inside the aberrant expression module and outside. They should only be defined inside each module, not outside (I was previously telling you the other way around, sorry). We usually group samples by group depending on their: tissue, sequencing parameters (e.g. strandness, genome build, polyA), and other major biological/technical bias. The more samples inside a group, the higher the statistical power, so I generally recommend having them inside a same group, as long as they fulfill the criteria mentioned before. You could search for biases on the heatmaps on the Summary html reports. What exactly did you extract from your WES data to define your groups?

It was by my colleague. She made groups based on some specifical SNPs but I suppose it will be better to run drop as whole batch, right? To search in results then ...

**Comment by nickhsmith** [comment]
Groups are fine. But you have to follow the YAML format. Please check out the template, the demo, and the online documentation
https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#config-file

```
aberrantExpression:  
  run: true          
  groups:            
  - outrider         
  - outrider_external
```

**Comment by sav0016** [comment]
> Groups are fine. But you have to follow the YAML format. Please check out the template, the demo, and the online documentation https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#config-file
> 
> ```
> aberrantExpression:  
>   run: true          
>   groups:            
>   - outrider         
>   - outrider_external
> ```

In fact these samples are just one large batch. And we want to find if there are some groups based on WES and RNA-Seq data ... If we will not use any grouping and have more than 200 samples. We tried to do this manually based on WES data but it is very time consuming. Can we obtain any potential groups from drop results without any grouping? Or do you recommend to use our manual grouping ... Thank you very much!

**Comment by nickhsmith** [comment]
DROP is an outlier detector, so each sample will be treated against the rest of the samples to determine whether it behaves aberrantly. We recommend using specific groups when you have reason to believe that the differences between samples isn't the result of some outlier event. 

For example if you had 100 muscle samples and 100 brain samples correctly  labeled in your `sample_annotation.tsv` ffile. It makes sense to split the groups into muscle and brain because you want to identify how a muscle sample may be an outlier amongst other muscle samples (and similarly for brain).
```
aberrantExpression:  
  run: true          
  groups:            
  - brain
  - muscle
  ```

So in your case if you have 200 samples all of the same disease it would be worth it to keep them as one group called **group1**, you would signify this group in the `sample_annotation.tsv` file. as well as for each module you decide to run. So if you'd like to run the **aberrantExpression** module your `config.yaml` would look like this:

```
aberrantExpression:  
  run: true          
  groups:            
  - group1
  ```

**Comment by sav0016** [comment]
> 



> DROP is an outlier detector, so each sample will be treated against the rest of the samples to determine whether it behaves aberrantly. We recommend using specific groups when you have reason to believe that the differences between samples isn't the result of some outlier event.
> 
> For example if you had 100 muscle samples and 100 brain samples correctly labeled in your `sample_annotation.tsv` ffile. It makes sense to split the groups into muscle and brain because you want to identify how a muscle sample may be an outlier amongst other muscle samples (and similarly for brain).
> 
> ```
> aberrantExpression:  
>   run: true          
>   groups:            
>   - brain
>   - muscle
> ```
> 
> So in your case if you have 200 samples all of the same disease it would be worth it to keep them as one group called **group1**, you would signify this group in the `sample_annotation.tsv` file. as well as for each module you decide to run. So if you'd like to run the **aberrantExpression** module your `config.yaml` would look like this:
> 
> ```
> aberrantExpression:  
>   run: true          
>   groups:            
>   - group1
> ```

Thank you very much for the very detailed answer, it helped a lot.
