### ISSUE TITLE
 MissingInputException: Missing input files for rule markdown/changeHeader

### ISSUE THREAD

**Issue by sav0016** [gagneurlab/drop#387]
Hello, I'm getting following error at the beginning of variant calling pipeline.

Update drop version for /data2/sav0016/drop-Anicka-test/Anicka-Final to version 1.2.2
WARNING: Less than 30 IDs in DROP_GROUP D0
WARNING: Less than 30 IDs in DROP_GROUP D1
WARNING: Less than 30 IDs in DROP_GROUP D0
WARNING: Less than 30 IDs in DROP_GROUP D1
/data2/sav0016/miniconda3/envs/drop_env_latest/lib/python3.10/site-packages/drop/utils.py:91: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  return  df[df[column].str.contains("(?:^|,)" + inner_regex + "(?:,|$)", na = False)]
check for missing R packages
Structuring dependencies...
Dependencies file generated at: /data2/sav0016/tmp/tmp0h0q4sx1

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError:
        MissingInputException: Missing input files for rule markdown:
            output: /data2/sav0016/drop-Anicka-test/Anicka-Final/Output/html/rnaVariantCalling/v39/Summary_D0.html
            wildcards: file=rnaVariantCalling/v39/Summary_D0
            affected files:
                rnaVariantCalling/v39/Summary_D0.md
        MissingInputException: Missing input files for rule changeHeader:
            output: /data2/sav0016/drop-Anicka-test/Anicka-Final/Output/processed_data/rnaVariantCalling/out/bam/172-01-3TR.sorted/172-01-3TR.sorted_dropHeader.bam, /data2/sav0016/drop-Anicka-test/Anicka-Final/Output/processed_data/rnaVariantCalling/out/bam/172-01-3TR.sorted/172-01-3TR.sorted_dropHeader.bam.bai, /data2/sav0016/drop-Anicka-test/Anicka-Final/Output/processed_data/rnaVariantCalling/out/bam/172-01-3TR.sorted/172-01-3TR.sorted_newDropHeader.txt
            wildcards: sample=172-01-3TR.sorted
            affected files:
                /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/rna_bam/172-01-3TR.sorted.bam.bai
    MissingInputException: Missing input files for rule markdown:
        output: /data2/sav0016/drop-Anicka-test/Anicka-Final/Output/html/Scripts_rnaVariantCalling_pipeline_countVariants_Datasets.html
        wildcards: file=Scripts_rnaVariantCalling_pipeline_countVariants_Datasets
        affected files:
            Scripts_rnaVariantCalling_pipeline_countVariants_Datasets.md
MissingInputException: Missing input files for rule markdown:
    output: /data2/sav0016/drop-Anicka-test/Anicka-Final/Output/html/rvc-pipeline_index.html
    wildcards: file=rvc-pipeline_index
    affected files:
        rvc-pipeline_index.md

----
Is there any dedicated suffix of bam file? I have them just .bam.
Thanks
J

**Comment by nickhsmith** [comment]
Can you please share your sample annotation file? It seems like there is an issue there. Please make sure you are following the manual and documentation as well.

https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html

Thanks

**Comment by sav0016** [comment]
[sample_annotation.csv](https://github.com/gagneurlab/drop/files/9961530/sample_annotation.csv)

(I changed it to csv from tsv for uploading here), thanks!!!

**Comment by nickhsmith** [comment]
I have some ideas that could help out. 
1. 10 samples per group is not that much, is there a compelling reason between splitting the DO/D1 batches?
2. Do you want to separate the RNA variant calling into the DO/D1 batches? Are there reasons for splitting them instead of processing them in one large batch? You can create multiple drop groups and specify the groups in the config.yaml file
3. Do the bam.bai files exist ? These need to exist in the same location as the bam files.

**Comment by sav0016** [comment]
> I have some ideas that could help out.
> 
> 1. 10 samples per group is not that much, is there a compelling reason between splitting the DO/D1 batches?
> 2. Do you want to separate the RNA variant calling into the DO/D1 batches? Are there reasons for splitting them instead of processing them in one large batch? You can create multiple drop groups and specify the groups in the config.yaml file
> 3. Do the bam.bai files exist ? These need to exist in the same location as the bam files.

1. I try to run all samples in one batch.
2. No
3. Yes, bai files exists. Does it take bam file like "sample.bam" or it should be some special suffix? Can I use dupmarked bams?

Thanks!

**Comment by nickhsmith** [comment]
it needs to be named `{anything}.bam` and `{anything}.bam.bai` 

I also noticed that your RNA_ID is `136-02-5TR.sorted` Does this match the sample ID within the bam file?
`samtools view -H /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/rna_bam/136-02-5TR.sorted.bam`

**Comment by sav0016** [comment]
> it needs to be named `{anything}.bam` and `{anything}.bam.bai`
> 
> I also noticed that your RNA_ID is `136-02-5TR.sorted` Does this match the sample ID within the bam file? `samtools view -H /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/rna_bam/136-02-5TR.sorted.bam`

Good point. If it takes ID from Bam read group so there is no sorted. I will try, thank you!

**Comment by sav0016** [comment]
> it needs to be named `{anything}.bam` and `{anything}.bam.bai`
> 
> I also noticed that your RNA_ID is `136-02-5TR.sorted` Does this match the sample ID within the bam file? `samtools view -H /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/rna_bam/136-02-5TR.sorted.bam`

Can be used bam file with marked duplicates?
Thank you!

**Comment by nickhsmith** [comment]
I think that's superficial. I think the main issue is the `bai` file. Looking at your error I see this:

```
affected files: /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/rna_bam/172-01-3TR.sorted.bam.bai
```

Does this file exist in this location?

**Comment by nickhsmith** [comment]
> > it needs to be named `{anything}.bam` and `{anything}.bam.bai`
> > I also noticed that your RNA_ID is `136-02-5TR.sorted` Does this match the sample ID within the bam file? `samtools view -H /data2/sav0016/drop-Anicka-test/Anicka-sample/Data/rna_bam/136-02-5TR.sorted.bam`
> 
> Can be used bam file with marked duplicates? Thank you!

It can, but the variant caller will go through the mark duplicate process.

**Comment by sav0016** [comment]
> 

I see it now ............... it is .bai and not .bam.bai .... This is problem .... I think it happened when I was unmarking duplicates because I'm not sure if I can use marked ones and the index was then created like this .... Thanks!
