### ISSUE TITLE
Custom co-variation

### ISSUE THREAD

**Issue by forrestzhaosen** [gagneurlab/drop#388]
Hi, I wondered whether the custom co-variation values could be controlled for in the AE and ASE models.

**Comment by vyepez88** [comment]
Hi, the AE and AS modules use a denoising autoencoder to control for sample covariation and gene coexpression. The ASE module performs a test for each sample independently, so there's no need to control for co-variation.

**Comment by forrestzhaosen** [comment]
> Hi, the AE and AS modules use a denoising autoencoder to control for sample covariation and gene coexpression. The ASE module performs a test for each sample independently, so there's no need to control for co-variation.

Thank you very much!
