### ISSUE TITLE
rnaVariantCalling - reheader

### ISSUE THREAD

**Issue by sav0016** [gagneurlab/drop#389]
Hello, I am having problems with reheader step during rna variant calling:

Waiting at most 5 seconds for missing files.
MissingOutputException in rule changeHeader in line 617 of /data2/sav0016/drop/all/Scripts/rnaVariantCalling/pipeline/Snakefile:
Job Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
/data2/sav0016/drop/all/Output/processed_data/rnaVariantCalling/out/bam/323-01-2TR/323-01-2TR_dropHeader.bam
/data2/sav0016/drop/all/Output/processed_data/rnaVariantCalling/out/bam/323-01-2TR/323-01-2TR_dropHeader.bam.bai completed successfully, but some output files are missing. 2739
Removing output files of failed job changeHeader since they might be corrupted:
/data2/sav0016/drop/all/Output/processed_data/rnaVariantCalling/out/bam/323-01-2TR/323-01-2TR_newDropHeader.txt
Waiting at most 5 seconds for missing files.
MissingOutputException in rule changeHeader in line 617 of /data2/sav0016/drop/all/Scripts/rnaVariantCalling/pipeline/Snakefile:
Job Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
/data2/sav0016/drop/all/Output/processed_data/rnaVariantCalling/out/bam/800-01-6TR/800-01-6TR_dropHeader.bam
/data2/sav0016/drop/all/Output/processed_data/rnaVariantCalling/out/bam/800-01-6TR/800-01-6TR_dropHeader.bam.bai completed successfully, but some output files are missing. 3323
Removing output files of failed job changeHeader since they might be corrupted:
/data2/sav0016/drop/all/Output/processed_data/rnaVariantCalling/out/bam/800-01-6TR/800-01-6TR_newDropHeader.txt
Waiting at most 5 seconds for missing files.

Path to bams and indexes are OK. Thank you very much. I tried to increase latency, did not help.
J

**Comment by liffcardio** [comment]
I got the same problem with my own data. How did you resolve this problem? Thank you.

**Comment by sav0016** [comment]
> 

I have different storage mounts on my server ... And it was problem to create hard link or something ... So I moved bams with bai to the same mount storage and it worked ... If you will still have problem, let me know, I will check if I did anything else ... :-D

**Comment by liffcardio** [comment]
Thank you very much. I will check my files again.
