### ISSUE TITLE
Unable to run aberrant expression module, getting "Missing output files" errors. 

### ISSUE THREAD

**Issue by drmurdock** [gagneurlab/drop#392]
Hi all. I'm trying to update our drop pipeline to a more recent version (1.2.1) than the one we used for our JCI paper (2020). I'm starting with the aberrant expression module but am unable to get it to run to completion. 

The first issue occurs when I run the drop init command and get the following message. I'm not sure if it means anything.

create /home/dmurdock/rnaseq/run3/Scripts
create /home/dmurdock/rnaseq/run3/.drop
create /home/dmurdock/rnaseq/run3/.drop/tmp
/home/dmurdock/rnaseq/run3/Scripts/AberrantExpression/pipeline is not a directory, copy over from drop base
/home/dmurdock/rnaseq/run3/Scripts/AberrantSplicing/pipeline is not a directory, copy over from drop base
/home/dmurdock/rnaseq/run3/Scripts/MonoallelicExpression/pipeline is not a directory, copy over from drop base
/home/dmurdock/rnaseq/run3/Scripts/rnaVariantCalling/pipeline is not a directory, copy over from drop base
init...done

Next I start the pipeline using the "snakemake aberrantExpression --cores 6" command. It will run for a minute or two before failing. I've attached the config file, sample annotation file, and output log here. I modified the template config file but it could have some errors. The sample annotation file seems to be ok though I had to add some dummy columns (DNA_ID, DNA_VCF_FILE) for it to run at all. I also only included 13 samples just to see if I can get it to run to completion on a smaller dataset.

In the log I noticed a bunch of references to "Missing output files" like in the following:

rule aberrantExpression_bamStats:
    input: /media/qvo/UDNRS5_FC1_FC2/UDN012222_FB.hg19.bam, /home/dmurdock/rnaseq/run3/Scripts/Pipeline/chr_UCSC_NCBI.txt
    output: /home/dmurdock/rnaseq/run3/Output/processed_data/aberrant_expression/bam_stats/UDN012222.txt
    jobid: 17
    reason: Missing output files: /home/dmurdock/rnaseq/run3/Output/processed_data/aberrant_expression/bam_stats/UDN012222.txt
    wildcards: sampleID=UDN012222
    resources: tmpdir=/tmp

However, I can see that file just fine in the output directory so I'm not sure what's going on. I tried troubleshooting for a while without success. Please let me know if you have any ideas.

Thanks!
David Murdock

[config.yaml.txt](https://github.com/gagneurlab/drop/files/9998221/config.yaml.txt)
[sample_annotation.txt](https://github.com/gagneurlab/drop/files/9998222/sample_annotation.txt)
[2022-11-13T143226.445985.snakemake.log](https://github.com/gagneurlab/drop/files/9998223/2022-11-13T143226.445985.snakemake.log)

**Comment by vyepez88** [comment]
Hi David,
Hope all is good. 
We restructured the folders, so that is probably why you're getting the first messages.
Can you please update to version 1.2.2? As we noted in the `What's new` section in the `Readme`: 
"Version 1.2.2 fixes some critical bugs that affected the performance of the aberrantExpression pipeline, and allows sample IDs to be numeric." 
Keep me updated.
Best,
Vicente

**Comment by drmurdock** [comment]
Thanks Vicente for the quick reply ! I will try that. What's the best way to update these days? I don't want to break anything in the process.

**Comment by vyepez88** [comment]
Last week there was an update in bioconda which is not compatible with snakemake and gave rise to many DROP issues.
Please try the approach that starts with "In the case of mamba/conda troubles" described here: https://github.com/gagneurlab/drop/tree/dev#quickstart
Your config file seemed fine and should work. Just turn off all the other modules by setting `run: false`
We're currently working in v 1.2.3 and hope to release it this upcoming week!

**Comment by drmurdock** [comment]
That did the trick Vincent. I was able to run on the smaller dataset. I'm running now on a larger one and it seems to be going fine. I'll let you know if I run into any issues. Thank you!

**Comment by vyepez88** [comment]
Great to hear! I'll close this issue then.
All the best David!
