### ISSUE TITLE
Splicing part error when running own data

### ISSUE THREAD

**Issue by liffcardio** [gagneurlab/drop#393]
Hi, I set an environment by using the DROP_1.2.2.yaml, then run the demo in the environment. It worked well. Then I use the same environment to run my own data. The expression part worked. But when I run the splicing part using
```
snakemake -c2 aberrantSplicing
```
the error came and the log is attached. the yaml file for my data is also attached.
Any help is much appreciated. Do you have a clue about this? Thank you very much.

[2022-11-15T104746.086646.snakemake.log](https://github.com/gagneurlab/drop/files/10017753/2022-11-15T104746.086646.snakemake.log)

projectTitle: "DROP: Detection of RNA Outliers"
root: /droptest/Output            # root directory of all output objects and tables
htmlOutputPath: /droptest/Output/html  # path for HTML rendered reports
indexWithFolderName: true # whether the root base name should be part of the index name

hpoFile: null  # if null, downloads it from webserver
sampleAnnotation: /droptest/Data/sample_annotation.tsv # path to sample annotation (see documentation on how to create it)

root: /droptest/Output 
sampleAnnotation: /droptest/Data/sample_annotation.tsv
geneAnnotation:
    v29: /droptest/Data/gencode.v42.chr_patch_hapl_scaff.annotation.gtf
genomeAssembly: hg38
genome: 
    gencode: /droptest/Data/GRCh38.p13.genome.fa 

hpoFile: null #relation between genes and phenotypes encoded as HPO term(necessary?)

exportCounts:
    # specify which gene annotations to include and which
    # groups to exclude when exporting counts
    geneAnnotations:
        - v29
    excludeGroups: null

genome: # path to reference genome sequence in fasta format.
    # You can define multiple reference genomes in yaml format, ncbi: path/to/ncbi, ucsc: path/to/ucsc
    # the keywords that define the path should be in the GENOME column of the sample annotation table
    gencode: /droptest/Data/GRCh38.p13.genome.fa 

aberrantExpression:
    run: true
    groups:
        - cardio 
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 0.05
    zScoreCutoff: 0
    maxTestedDimensionProportion: 3
    dassie:
        tssWindow: 500
        pasWindow: 1000

aberrantSplicing:
    run: true
    groups:
        - cardio
    recount: false
    longRead: false
    keepNonStandardChrs: false
    filter: true
    minExpressionInOneSample: 20
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 0.1
    zScoreCutoff: 0
    deltaPsiCutoff : 0.3
    maxTestedDimensionProportion: 6

mae:
    run: true
    groups:
        - cardio
    gatkIgnoreHeaderCheck: true
    padjCutoff: 0.05
    allelicRatioCutoff: 0.7
    addAF: true
    maxAF: .001
    maxVarFreqCohort: 0.05
    # VCF-BAM matching
    qcVcf: /droptest/Data/qc_vcf_1000G_hg38.vcf.gz
    qcGroups:
      - cardio

rnaVariantCalling:
    run: true
    groups:
        - cardio
    highQualityVCFs:
        - /droptest/Data/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
        - /droptest/Data/Homo_sapiens_assembly38.known_indels.vcf.gz
    dbSNP: /droptest/Data/00-All.vcf.gz
    repeat_mask: /droptest/Data/hg38_repeatMasker_sorted.bed
    createSingleVCF: true
    addAF: true
    maxAF: .001
    maxVarFreqCohort: 0.05
    hcArgs: 
    minAlt: 3

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools

**Comment by vyepez88** [comment]
Hi, can you please also attach your sample annotation?

**Comment by liffcardio** [comment]
Hi, I tried to keep running the program for the other part and found that the problem might be my bam file did not have read group tag. I added sample ID and sample name to the bam file, and run 
```
snakemake -c2
```
and the error said there is no platform information. So could you tell me what is necessary for read group tag?
Thank you very much.

**Comment by liffcardio** [comment]
Thank you for your reply. I tried to keep running the program and found out my bam file did not have read group tag. I added the read group tag and it seems working well at the moment. Thank you very much.
