### ISSUE TITLE
Error in rule AberrantSplicing_pipeline_FRASER_05_fit_autoencoder_FraseR_R

### ISSUE THREAD

**Issue by sav0016** [gagneurlab/drop#394]
Hi, please I have following error ... I am processing 240 files so I hope it would be possible to continue in this step if it will be possible to fix somehow the error. Thank you very much:

Error in rule AberrantSplicing_pipeline_FRASER_05_fit_autoencoder_FraseR_R:
    jobid: 989
    output: /data3/sav0016/drop/all/Output/processed_data/aberrant_splicing/datasets/savedObjects/group1/predictedMeans_theta.h5
    log: /data3/sav0016/drop/all/.drop/tmp/AS/group1/05_fit.Rds (check log file(s) for error message)

RuleException:
CalledProcessErrorin line 215 of /data2/sav0016/tmp/tmp2t_70a29:
Command 'set -euo pipefail;  Rscript --vanilla /data3/sav0016/drop/all/.snakemake/scripts/tmp_y2z84ba.05_fit_autoencoder_FraseR.R' returned non-zero exit status 139.
  File "/data2/sav0016/tmp/tmp2t_70a29", line 215, in __rule_AberrantSplicing_pipeline_FRASER_05_fit_autoencoder_FraseR_R
  File "/data2/sav0016/miniconda3/envs/drop_env_latest/lib/python3.10/concurrent/futures/thread.py", line 58, in run
[Wed Nov 16 22:08:42 2022]
Finished job 3997.
4332 of 4622 steps (94%) done

Best regards
Jakub

**Comment by vyepez88** [comment]
Hi, can you share the log file with the error message, the config file and sample annotation?

**Comment by sav0016** [comment]
> Hi, can you share the log file with the error message, the config file and sample annotation?

Of course.

[files.zip](https://github.com/gagneurlab/drop/files/10036145/files.zip)

Thank you very much.
J

**Comment by vyepez88** [comment]
Hi,
I see one potential error. The filter parameter in the aberrantSplicing dictionary is set to `false`. This should be `true`, otherwise all junctions with at least 1 count in 1 sample will be fitted. We recommend filtering by removing junctions with low counts across samples. Usually, this gets rid of ~80-90% of junctions. 
Other potential error is the DNA_ID. Make sure that e.g. `001TD_L001_R12_001.primers_out` is the ID inside the corresponding VCF file.
Finally, to try to nail the error can you rerun each module independently? Use the `--rerun-triggers mtime` parameter from snakemake ,e.g., `snakemake -n --rerun-triggers mtime aberrantSplicing` or `snakemake --cores 10 --rerun-triggers mtime aberrantSplicing`

**Comment by sav0016** [comment]
> 

Hi, thank you. Yes, DNA ID is same.

Using "snakemake -n --rerun-triggers mtime aberrantSplicing"
I got error:
snakemake: error: argument --rerun-triggers: invalid choice: 'aberrantSplicing' (choose from 'mtime', 'params', 'input', 'software-env', 'code')

I am careful because it was already running like four days so I would be happy to continue where it ended ... So I changed filter to true in config and how should be command now please? Thanks a lot.
J

**Comment by vyepez88** [comment]
First try:
`snakemake -n --rerun-triggers mtime aberrantSplicing` 
what's the output?

**Comment by sav0016** [comment]
> snakemake -n --rerun-triggers mtime aberrantSplicing

snakemake: error: argument --rerun-triggers: invalid choice: 'aberrantSplicing' (choose from 'mtime', 'params', 'input', 'software-env', 'code')

**Comment by vyepez88** [comment]
Can you write the --rerun parameter at the end of the command instead?

**Comment by sav0016** [comment]
> Can you write the --rerun parameter at the end of the command instead?

[rerun.log](https://github.com/gagneurlab/drop/files/10043837/rerun.log)

**Comment by vyepez88** [comment]
that looks good. Now try: `snakemake --cores X --rerun-triggers mtime aberrantSplicing`. Replace X with the desired number of provided cores

**Comment by sav0016** [comment]
> 

Great, perfect! Thanks! So in this way I should run all modules separately, right?

Or if this one will pass so I can just run snakemake --cores X --rerun-triggers mtime
to finish all the rest modules
J

**Comment by sav0016** [comment]
> that looks good. Now try: `snakemake --cores X --rerun-triggers mtime aberrantSplicing`. Replace X with the desired number of provided cores

[PCA_problem.log](https://github.com/gagneurlab/drop/files/10044740/PCA_problem.log)
I have this error now. I am running 1 core but I got this error. I am monitoring memory and I consumed about 200 GB of 7200 GB available during this step but it failed ... Thanks!
Best
J

**Comment by vyepez88** [comment]
Can you try 20 or 30 cores? Also, you do have `filter: true` in the config file, right?

**Comment by sav0016** [comment]
> Can you try 20 or 30 cores? Also, you do have `filter: true` in the config file, right?

I tried 1, 20, 30 , 40, 128, 256 ... Same error. Also I tried implementation PCA-BB-Decoder ... Did not work.
Still the same error:

rule AberrantSplicing_pipeline_FRASER_05_fit_autoencoder_FraseR_R:
    input: /data3/sav0016/drop/puente-new-all/Output/processed_data/aberrant_splicing/datasets/savedObjects/group1/hyper.done, Scripts/AberrantSplicing/pipeline/FRASER/05_fit_autoencoder_FraseR.R
    output: /data3/sav0016/drop/puente-new-all/Output/processed_data/aberrant_splicing/datasets/savedObjects/group1/predictedMeans_theta.h5
    log: /data3/sav0016/drop/puente-new-all/.drop/tmp/AS/group1/05_fit.Rds
    jobid: 495
    reason: Missing output files: /data3/sav0016/drop/puente-new-all/Output/processed_data/aberrant_splicing/datasets/savedObjects/group1/predictedMeans_theta.h5
    wildcards: dataset=group1
    threads: 30
    resources: tmpdir=/data2/sav0016/tmp

Load packages
Loading assay: rawCountsJ
Loading assay: psi5
Loading assay: psi3
Loading assay: rawOtherCounts_psi5
Loading assay: rawOtherCounts_psi3
Loading assay: delta_psi5
Loading assay: delta_psi3
Loading assay: rawCountsSS
Loading assay: theta
Loading assay: rawOtherCounts_theta
Loading assay: delta_theta
Wed Nov 30 12:38:16 2022: Running fit with correction method: PCA-BB-Decoder

   FALSE     TRUE
13262443    30358
Initial PCA loss: 2.52602255134708
[1] "Finished with fitting the E matrix. Starting now with the D fit. ..."

 *** caught segfault ***
address 0x7f30e8ac3040, cause 'memory not mapped'

Traceback:
 1: La.svd(x, nu, nv)
 2: svd(x, nu = 0, nv = k)
 3: prcomp.default(Matrix, center = FALSE, scale. = FALSE)
 4: prcomp(Matrix, center = FALSE, scale. = FALSE)
 5: svdPca(prepres$data, nPcs = nPcs, ...)
 6: pca(as.matrix(x(fds, all = TRUE)), nPcs = q, center = FALSE)
 7: initAutoencoder(copy_fds, q, rhoRange, type = type, BPPARAM = BPPARAM)
 8: fitAutoencoder(fds = fds, q = q, type = type, noiseAlpha = noiseAlpha,     rhoRange = rhoRange, lambda = lambda, convergence = convergence,     iterations = iterations, initialize = initialize, nSubset = nSubset,     weighted = weighted, control = control, BPPARAM = BPPARAM,     verbose = verbose, nrDecoderBatches = nrDecoderBatches, latentSpace = latentSpace)
 9: fitFraserAE(fds = object, q = q, type = type, noiseAlpha = noiseAlpha,     nSubset = nSubset, rhoRange = rhoRange, lambda = 0, convergence = convergence,     iterations = iterations, initialize = initialize, weighted = TRUE,     control = control, BPPARAM = BPPARAM, verbose = verbose,     subset = TRUE, nrDecoderBatches = 1, latentSpace = "PCA")
10: fit.FraserDataSet(fds, q = q, type = type, iterations = 15, implementation = implementation)
11: fit(fds, q = q, type = type, iterations = 15, implementation = implementation)
An irrecoverable exception occurred. R is aborting now ...
/usr/bin/bash: line 1: 264366 Segmentation fault      (core dumped) Rscript --vanilla /data3/sav0016/drop/puente-new-all/.snakemake/scripts/tmprtiscv_p.05_fit_autoencoder_FraseR.R
[Wed Nov 30 15:30:00 2022]
Error in rule AberrantSplicing_pipeline_FRASER_05_fit_autoencoder_FraseR_R:
    jobid: 495
    output: /data3/sav0016/drop/puente-new-all/Output/processed_data/aberrant_splicing/datasets/savedObjects/group1/predictedMeans_theta.h5
    log: /data3/sav0016/drop/puente-new-all/.drop/tmp/AS/group1/05_fit.Rds (check log file(s) for error message)

RuleException:
CalledProcessErrorin line 215 of /data2/sav0016/tmp/tmpwob12n9y:
Command 'set -euo pipefail;  Rscript --vanilla /data3/sav0016/drop/puente-new-all/.snakemake/scripts/tmprtiscv_p.05_fit_autoencoder_FraseR.R' returned non-zero exit status 139.
  File "/data2/sav0016/tmp/tmpwob12n9y", line 215, in __rule_AberrantSplicing_pipeline_FRASER_05_fit_autoencoder_FraseR_R
  File "/data2/sav0016/miniconda3/envs/drop_env_latest/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-11-30T123353.574789.snakemake.log



Thanks.
Jakub

**Comment by vyepez88** [comment]
Do you have `filter: false` in the aberrant splicing section of the config file?

**Comment by sav0016** [comment]
> Do you have `filter: false` in the aberrant splicing section of the config file?

I tried also now with filter: false ... Same result :-(

J

**Comment by nickhsmith** [comment]
Sorry you're having trouble with it. To restart the filtering process from the beginning (after counting), can you please 

1. set `filter: true` in the aberrantSplicing section of the config
2. you can try to just restart from the filtering step using the command command (please set your desired cores or cluster options)
```
snakemake -R AberrantSplicing_pipeline_Counting_03_filter_expression_FraseR_R --rerun-triggers mtime  <CORE/CLUSTER options>
```

You can also add a `-n` to do a dry run to double check that only the filtering steps (and downstream) are redone
```
snakemake -n -R AberrantSplicing_pipeline_Counting_03_filter_expression_FraseR_R --rerun-triggers mtime  <CORE/CLUSTER options>
```

This should hopefully skip the counting steps, rerun the filtering and then restart the dimensionality reduction (`PCA` or `PCA-BB-Decoder`). Let me know if this is still giving the memory/segfault error

**Comment by sav0016** [comment]
> Sorry you're having trouble with it. To restart the filtering process from the beginning (after counting), can you please
> 
> 1. set `filter: true` in the aberrantSplicing section of the config
> 2. you can try to just restart from the filtering step using the command command (please set your desired cores or cluster options)
> 
> ```
> snakemake -R AberrantSplicing_pipeline_Counting_03_filter_expression_FraseR_R --rerun-triggers mtime  <CORE/CLUSTER options>
> ```
> 
> You can also add a `-n` to do a dry run to double check that only the filtering steps (and downstream) are redone
> 
> ```
> snakemake -n -R AberrantSplicing_pipeline_Counting_03_filter_expression_FraseR_R --rerun-triggers mtime  <CORE/CLUSTER options>
> ```
> 
> This should hopefully skip the counting steps, rerun the filtering and then restart the dimensionality reduction (`PCA` or `PCA-BB-Decoder`). Let me know if this is still giving the memory/segfault error

Done! Finally! Thank you very much! :-)
J
