### ISSUE TITLE
Splicing: too many outliers reported

### ISSUE THREAD

**Issue by SathyaDarmalinggam** [gagneurlab/drop#399]
Dear DROP team, thank you as always for such a great tool. 

I recently received additional samples so re-ran both the AE & AS modules. While the AE module ran smoothly and gave me some good insights, I'm struggling with the interpretation of the splicing results. 

Number of samples = 61 (whole blood bulk RNAseq, paired-end, only diseased samples no healthy control)

Parameters used with hg38:
```
 recount: false
  longRead: false
  keepNonStandardChrs: true
  filter: true
  minExpressionInOneSample: 20
  minDeltaPsi: 0.05
  implementation: PCA
  padjCutoff: 0.05
  zScoreCutoff: 0
  deltaPsiCutoff: 0.3
  maxTestedDimensionProportion: 6
```

DROP Version: 1.1 (as I'm keeping it consistent with my previous analysis) 

The issue I'm facing is that I have too many significant outliers reported as shown in the plots. It also looks like the hyperparameter optimization plots have area under PR curve values of max 0.35. I'm currently not sure how to interpret these results due to the number of outliers reported even though I'm using default values. 

Numbers reported after filtering:
```
Number of introns (psi5 or psi3): 180036
Number of splice sites (theta): 271517
```

I'm also in the process of upgrading the DROP version but I doubt that will change the results much?

Any suggestions on your side is much appreciated, thank you :) 

<img width="778" alt="Screenshot 2022-11-29 at 10 35 03" src="https://user-images.githubusercontent.com/42797616/204492736-5d57d0b2-3d64-4230-86a8-f054c11e1301.png">

![image](https://user-images.githubusercontent.com/42797616/204492776-2afc1f85-6e15-46fc-a040-20015a7b0078.png)

**Comment by vyepez88** [comment]
Hi, we haven't updated FRASER, so the results shouldn't change at all by updating DROP. We are working, however, on a new algorithm that reduces the number of splicing outliers. We plan to have it online next week. I'll let you know.

**Comment by vyepez88** [comment]
Hi, sorry, forgot to tell you before, but we have now FRASER2 online (in DROP >1.3.3). See also here the preprint: https://www.medrxiv.org/content/10.1101/2023.03.31.23287997v1
