### ISSUE TITLE
TypeError in line 12 of Snakefile

### ISSUE THREAD

**Issue by deb0612** [gagneurlab/drop#402]
Dear sir,
I just ran  "snakemake --cores 1" by using my own data, and modified "config.yaml" file.
It showed a error below:
![image](https://user-images.githubusercontent.com/29038270/204824883-b74c3172-6170-4ab7-90c7-cc861b790645.png)
How could I revise my Snakefile file?

**Comment by vyepez88** [comment]
The Snakefile is in your project directory. In line 12, the config file is read, so you probably have an error there. Be sure that it's in yaml format and you filled all the parameters. Have a look at the documentation. https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#config-file

**Comment by deb0612** [comment]
Thanks, my  yaml file was modified from the demo file, I am not sure if I miss any parameter?
[sample_annotation.tsv.txt](https://github.com/gagneurlab/drop/files/10125708/sample_annotation.tsv.txt)
[config.yaml.txt](https://github.com/gagneurlab/drop/files/10125710/config.yaml.txt)

**Comment by vyepez88** [comment]
The potential problem is that the `root` variable appears twice

Furthermore, I suggest changing the padjCutoff to 0.05 in all modules, and in the aberrant splicing to set `filter: true` and `deltaPsiCutoff: 0.3`

**Comment by deb0612** [comment]
Thanks, I tried to mark all the duplicated parameters, and it seems worked.
