### ISSUE TITLE
Error in `[.data.table`(gtf_dt, , `:=`(N, 1:.N), by = gene_name)

### ISSUE THREAD

**Issue by JieHe233** [gagneurlab/drop#404]
Dear DROP team:
Hello, I'm testing the outrider with 10 RNA samples, and the error is shown in  the picture.
![image](https://user-images.githubusercontent.com/64524472/205243643-54b8f5e5-fe23-4e14-a6f5-80968ed516d5.png)
I used featurecounts to get the count data, and I changed the count file to such format:
![image](https://user-images.githubusercontent.com/64524472/205244236-aafeea0b-d21b-43ce-afcd-9cb8fc6d8c7a.png)
Also the sample annotation file is this format:
![image](https://user-images.githubusercontent.com/64524472/205244571-d4f7a843-2d7c-4e1f-b794-29df6b68baac.png)
Can you help me with this problem? Thanks sincerely.

**Comment by vyepez88** [comment]
Hi, just to be clear, you're only providing external counts, right?

**Comment by JieHe233** [comment]
yes, only external counts

**Comment by JieHe233** [comment]
Hello, so can I use only external counts to get the result?

**Comment by JieHe233** [comment]
@vyepez88 Hello, sorry to bother you, I'm wondering if I could use only external counts to get the result? And another question is that can I analyse aberrant exon expression by outrider?

**Comment by vyepez88** [comment]
Hi. Yes, you can use only external counts. However, the provided gtf file must have unique gene names, which seems not to be the case. Can you please double check this in the gtf file and in your count matrix?
Indeed, the aberrant expression module uses OUTRIDER, so you could directly use OUTRIDER in R if you already have the count matrix.

**Comment by JieHe233** [comment]
@vyepez88 Okay, I'll take your advice and try it first. Thanks

**Comment by vyepez88** [comment]
Hi @JieHe233, were you able to try the proposed solution?

**Comment by JieHe233** [comment]
Sorry, I didn't try OUTRIDER in R, but I suppose the reason why I failed in the previous test was that the gtf don't have unique gene names, because I successfully tested the MAE module with another gtf.
