### ISSUE TITLE
VCF source

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#41]
Hi,
What are the possible sources for the input VCF file? Does it have to be whole-genome sequencing VCF? Or can it be WES, or even RNA-seq-based VCF files?

**Comment by vyepez88** [comment]
Hi,
It can be either WES or WGS. 
To detect mono-allelic expression, we need heterozygous SNVs called from DNA-seq. Then, using RNA-Seq, we detect wether there was an expression bias towards the alternative or reference allele. If the variant is MAE towards the alternative, it will be called as homozygous in RNA-Seq data. On the contrary, if the variant is MAE towards the reference, it won't be called as a variant in RNA-Seq data. Therefore, it cannot be VCF files derived from RNA-seq.
