### ISSUE TITLE
Optimizing mapping for usage with DROP

### ISSUE THREAD

**Issue by scharf-f** [gagneurlab/drop#414]
Dear DROP-team,

I am currently working on establishing the MAE and aberrantSplicing modules on our data. Currently I am thinking about whether I could increase the performance by adapting the mapping.

I found that in the DROP manuscript you suggest to use STAR aligner with standard settings & twoPassMode = Basic. However, in the FRASER publication you suggest to additionally set chimSegmentMin to 20.

I would be very grateful if you could possibly share your assessment on how (much) it influences the performance of the MAE and aberrantSplicing detection to use one or the other, respectively?

Additionally, I wanted to ask whether you have any experience using data mapped using the RNA-Seq module of the DRAGEN pipeline?

Thank you very much for your help!

Kind regards,
Florentine

**Comment by nickhsmith** [comment]
This `chimSegmentMin` parameter is used to flag chimeric alignments (reads that align to different strands, different chromosomes or unreasonably large genomic distances) this parameter was set as a legacy option when we were writing the FRASER paper as that is how the data was processed, but it is included in the standard procedure for GTEx alignments (`chimSegmentMin` = 15) as well. 

We don't know the exact impact of this parameter on the results directly, our best guess is that for a "clean" non-cancerous dataset that the effect would be minimal as you would not expect many chimeric reads. 

As to your last question regarding DRAGEN we don't have any personal experience with it. 

I hope this answers your questions. Thanks!

**Comment by scharf-f** [comment]
Thank you very much for the clarification! Indeed this helps!

However, I do have one more question: I realized that when using the MAE module duplicates will be filtered out, but only if they have been marked as duplicates in advance (e.g. using STAR bamRemoveDuplicatesType as a second step after read mapping).

Doing so seems to not be explicitly recommended in the manuscript, but since the MAE module is taking these markings into account I was considering it to be beneficial to do so? What is your recommendation on that?

Thanks again and kind regards,
Florentine

**Comment by nickhsmith** [comment]
It should work with whichever BAM files you'd like. I would recommend using duplicated and recalibrated bam files to reduce noise, *but* there are reasons to not remove duplicates, or recalibrate depending on your end goal. It really depends on what your hypothesis and experimental design are.

If you are just using DROP-MAE then I would markduplicates.
