### ISSUE TITLE
error in MAE rule mae_createSNVs

### ISSUE THREAD

**Issue by agomez700** [gagneurlab/drop#417]
Hi all,

Successfully ran aberrant expression and aberrant splicing modules, but am running to this issue with MAE and wondering if you have any suggestions.

rule mae_createSNVs:
    input: /lab-share/Neph-Sampson-e2/Public/AC/drop_6/Scripts/Pipeline/chr_NCBI_UCSC.txt, /lab-share/Neph-Sampson-e2/Public/AC/drop_6/Scripts/Pipeline/chr_UCSC_NCBI.txt, /home/ch222985/CRDC_data/rna_seq/resource/qc_vcf_1000G_hg38.vcf.gz, /home/ch222985/CRDC_data/rna_seq/hg38/BCH-22-95062-01_R38/BCH-22-95062-01_R38_dupmarked_with_ReadGroup.bam, /lab-share/Neph-Sampson-e2/Public/AC/drop_6/Scripts/MonoallelicExpression/pipeline/MAE/filterSNVs.sh, /home/ch222985/Public/AC/drop_6/processed_data/mae/params/snvs/BCH-22-95062-01_snvParams.csv
    output: /home/ch222985/Public/AC/drop_6/processed_data/mae/snvs/BCH-22-95062-01_G38--BCH-22-95062-01.vcf.gz, /home/ch222985/Public/AC/drop_6/processed_data/mae/snvs/BCH-22-95062-01_G38--BCH-22-95062-01.vcf.gz.tbi
    jobid: 90
    reason: Missing output files: /home/ch222985/Public/AC/drop_6/processed_data/mae/snvs/BCH-22-95062-01_G38--BCH-22-95062-01.vcf.gz
    wildcards: vcf=BCH-22-95062-01_G38, rna=BCH-22-95062-01
    resources: tmpdir=/tmp

Filter SNVs
Error: subset called for sample that does not exist in header: "BCH-22-95062-01_G38". Use "--force-samples" to ignore this error.
[Fri Dec 16 08:23:06 2022]
Error in rule mae_createSNVs:
    jobid: 90
    output: /home/ch222985/Public/AC/drop_6/processed_data/mae/snvs/BCH-22-95062-01_G38--BCH-22-95062-01.vcf.gz, /home/ch222985/Public/AC/drop_6/processed_data/mae/snvs/BCH-22-95062-01_G38--BCH-22-95062-01.vcf.gz.tbi
    shell:
        
        /lab-share/Neph-Sampson-e2/Public/AC/drop_6/Scripts/MonoallelicExpression/pipeline/MAE/filterSNVs.sh /lab-share/Neph-Sampson-e2/Public/AC/drop_6/Scripts/Pipeline/chr_NCBI_UCSC.txt /lab-share/Neph-Sampson-e2/Public/AC/drop_6/Scripts/Pipeline/chr_UCSC_NCBI.txt /home/ch222985/CRDC_data/rna_seq/resource/qc_vcf_1000G_hg38.vcf.gz         BCH-22-95062-01_G38 /home/ch222985/CRDC_data/rna_seq/hg38/BCH-22-95062-01_R38/BCH-22-95062-01_R38_dupmarked_with_ReadGroup.bam /home/ch222985/Public/AC/drop_6/processed_data/mae/snvs/BCH-22-95062-01_G38--BCH-22-95062-01.vcf.gz         bcftools samtools
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-12-16T082259.853430.snakemake.log

**Comment by agomez700** [comment]
also trying to update DROP to 1.2.4 (currently have 1.2.3) .
However I've had issues with conda environments before so was trying to use the .yaml file (as this is how I installed 1.2.3 and it worked well). Currently instead of allowing me access to the yaml file it says "forbidden, you do not have permission to access this resource). Also saying the same thing for 1.2.3 despite the fact that I was previously able to download and install using that yaml file. Any suggestions?

**Comment by nickhsmith** [comment]
Sorry for the mistake with the DROP 1.2.4 permissions, those should be updated now.

As for your first error, could you please check that the sample name you designate in your sample annotation `DNA_ID` is the same as the the sampleID in the VCF itself.

`zgrep "^#CHROM" <VCF_FILE>`

Could you also share your sample annotation file, please?

**Comment by agomez700** [comment]
yes sorry you are spot on I was calling the wrong VCF file in the sample annotation so the sample names did not match the one in the annotation. file.

Sorry for the bother - you guys are always so helpful. I am trying again now that they match and will let you know if that does not fix the problem (and will close this out if it does).

**Comment by agomez700** [comment]
fixed! thank you and closing issue now.
