### ISSUE TITLE
Abnormal splicing and abnormal expression sample size is abnormal

### ISSUE THREAD

**Issue by zshu-alt** [gagneurlab/drop#419]
Hello, sorry to bother you, I only have 5 blood RNA bam files, but I want to try the abnormal splicing module, so I have to add external data, but I see abnormal splicing analysis requires external data with 5 files, and I want to use this data set ：125 strand-specific blood, build hg19, Baylor College of Medicine does not seem to have the required 5 files. Is there any way to generate these 5 files? Or do I just have to look for other bam files?? The disease I want to diagnose is neuromuscular related, I only have two such files, can I use bam files for other diseases to increase the sample size? Is this credible? Including the search for abnormal expression module, can the bam files of different diseases be analyzed together? I think the algorithm for finding outliers would allow that, but I'm not sure, okay? I hope someone could give me some advice

Let me reframe my question:
1. Can external blood data expand the sample size of abnormal splicing analysis? Can I generate my own five files of external data needed for abnormal clipping?
2. Can bam files of different diseases be combined for analysis? Including abnormal expression or splicing analysis?

I would appreciate it if you are free to answer my questions.

**Comment by vyepez88** [comment]
Hi. In order to combine your local samples with external ones, you have two options:
1. use external BAM files
2. use external count matrices
BAM files might be better suited, specially if they were sequenced and preprocessed in a similar way as the local samples. It is fine to combine different diseases.
