### ISSUE TITLE
Error in rule AberrantExpression_pipeline_OUTRIDER_runOutrider_R:

### ISSUE THREAD

**Issue by noorsmal** [gagneurlab/drop#423]
Hi, 

I'm getting an error when I run the aberrantExpression part of the pipeline. The other parts (splicing and MAE) work well. The error happens after the rule has been running for a long time on 27 samples of myself and 492 gtex samples (external counts provided by you). I have already tried lowering the YieldSize in the config.yaml to 10% of the recommended size and lowering the cores to 1 (also tried default settings on 4 or 8 cores), but this does not help and I see no large memory use. The error reads:

Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Calls: OUTRIDER ... .send_to -> <Anonymous> -> sendData.SOCK0node -> serialize
Error in serialize(data, node$con, xdr = FALSE) :
  error writing to connection
Calls: OUTRIDER ... .send_to -> <Anonymous> -> sendData.SOCK0node -> serialize
Execution halted
Error in serialize(data, node$con, xdr = FALSE) :
  error writing to connection
Calls: <Anonymous> ... .send_to -> <Anonymous> -> sendData.SOCK0node -> serialize
[Wed Jan 18 02:21:23 2023]
Error in rule AberrantExpression_pipeline_OUTRIDER_runOutrider_R:
    jobid: 73
    input: /home/noor/transcriptomics/drop_batch1/data/batch1and2_gtex/processed_results/aberrant_expression/v29/outrider/index/ods_unfitted.Rds, Scripts/AberrantExpression/pipeline/OUTRIDER/runOutrider.R
    output: /home/noor/transcriptomics/drop_batch1/data/batch1and2_gtex/processed_results/aberrant_expression/v29/outrider/index/ods.Rds
    log: /home/noor/transcriptomics/drop_batch1/.drop/tmp/AE/v29/index/runOUTRIDER.Rds (check log file(s) for error details)

RuleException:
CalledProcessError in file /tmp/tmpp_4ssaxk, line 88:
Command 'set -euo pipefail;  Rscript --vanilla /home/noor/transcriptomics/drop_batch1/.snakemake/scripts/tmprotx_dl_.runOutrider.R' returned non-zero exit status 1.
  File "/tmp/tmpp_4ssaxk", line 88, in __rule_AberrantExpression_pipeline_OUTRIDER_runOutrider_R
  File "/home/noor/miniconda3/envs/drop124/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

drop, version 1.2.4
(Installed by creating a new conda environment)

[SampleAnnotation.txt](https://github.com/gagneurlab/drop/files/10444178/SampleAnnotation.txt)
[Config.txt](https://github.com/gagneurlab/drop/files/10444181/Config.txt)

**Comment by vyepez88** [comment]
Hi, there was a problem with a specific BiocParallel release. Can you please reinstall it? In your conda environment, open R and execute:
```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("BiocParallel")

library(BiocParallel)
sessionInfo()
```
Check that it's version 1.32.5 or above. Then rerun the aberrant expression pipeline.

**Comment by vyepez88** [comment]
Hi Noor, were you able to check this?

**Comment by noorsmal** [comment]
Hi Vicente, 
Yes, I was able to run the analysis without errors after reinstalling BiocParallel. Thanks!
