### ISSUE TITLE
dataset too big?

### ISSUE THREAD

**Issue by AnikoSabo** [gagneurlab/drop#428]
Hi, 
I have successfully ran the DROPseq pipeline on a set of 35 samples.  But that was just a test, to make sure things are running smoothly. Now, to get real results I want to run a larger dataset- I tried running with 105 samples, but the pipeline crashes after it reaches 99%.  It looks like it is due to R having a limit on string character number?

Do you have any insight as to how can I fix this? I am running with 20 cores.  thank you

Here is the part of the .err file where I think it reports what the error is:

Quitting from lines 87-88 (/space1/tmp/slurm.76825/Rtmp8JBVGv/file376524283f43a1/Overview.spin.Rmd)

Error in collapse(tmp, inner = FALSE, indent) :

  R character strings are limited to 2^31-1 bytes

Calls: render ... FUN -> .local -> asJSON -> asJSON -> .local -> collapse

In addition: Warning message:

In instance$preRenderHook(instance) :

  It seems your data is too big for client-side DataTables. You may consider server-side processing: https://rstudio.github.io/DT/server.html

Execution halted

[Wed Feb  1 14:07:27 2023]

**Comment by vyepez88** [comment]
Hi,
It could be that the Results tables are too big. Did you set any cut-offs for the padj or deltapsi?

**Comment by AnikoSabo** [comment]
that might be it. It looks like I did only for deltapsi, but not padj. 
 
padjCutoff: 1
  zScoreCutoff: 0
  deltaPsiCutoff: 0.05

I will try adding padjCutoff: 0.05. Does that sound good?

**Comment by vyepez88** [comment]
Our recommended cutoffs are: 
padjCutoff: 0.1
deltaPsiCutoff: 0.3

**Comment by AnikoSabo** [comment]
Thanks. I'll modify and give it a try.

**Comment by AnikoSabo** [comment]
If I wanted to run less restrictive, and then filter the results table later I should filter on the deltapsi right (column 14 in the output)?

In the results column there is psiValue        and deltaPsi ?

Thank you

**Comment by vyepez88** [comment]
yes, you should filter the deltaPsi, which is the difference between the psi value and the average psi across samples. Note that it can be both positive or negative.

**Comment by AnikoSabo** [comment]
got it. thank you
