### ISSUE TITLE
How to make external count files

### ISSUE THREAD

**Issue by muhligs** [gagneurlab/drop#434]
Thanks for providing this tool. 

I have now carefully read the manuscript and documentation of DROP, but I failed to see how one can make an external count matrix based on ones own data. 

I have 50 blood samples that I would like to serve as controls for future samples, but when I run aberrantExpression, I appear only to get the ods and outrider_result_all objects. How do I obtain a count matrix that can serve as an input for a new run. 

The same goes for the aberrantSplicing module. How to obtain the count files. 

If you could provide e.g. example code for making it based on one of your external count-sets, that would be much appreciated.

**Comment by vyepez88** [comment]
Hi, sorry I missed this issue. The command to generate expression and splicing counts is:
`snakemake exportCounts`
See more info here: https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#export-counts-dictionary and in the rest of that page.
