### ISSUE TITLE
An error in MonoallelicExpression_pipeline_MAE_deseq_mae_R

### ISSUE THREAD

**Issue by ym-chen** [gagneurlab/drop#435]
Hi，
I encountered the following error when running the MAE module. My operating environment cannot be connected to the Internet. I have successfully run multiple batch of samples using DROP. I want to know why is such an error suddenly reported?
```
rule MonoallelicExpression_pipeline_MAE_deseq_mae_R:
    input: /mea/processed_data/mae/allelic_counts/dna12--rna12.csv.gz, Scripts/MonoallelicExpression/pipeline/MAE/deseq_mae.R
    output: /mea/processed_results/mae/samples/dna12--rna12_res.Rds
    log: /mea/.drop/tmp/MAE/deseq/dna12--rna12.Rds
    jobid: 29
    reason: Missing output files: /mea/processed_results/mae/samples/dna12--rna12_res.Rds
    wildcards: vcf=dna12, rna=rna12
    resources: tmpdir=/tmp/3792520.1.b2c_rd_s1.q

Started with deseq
Warning message:
In qf(0.99, p, m - p) : NaNs produced
Error: Bioconductor version cannot be validated; no internet connection?  See
  #troubleshooting section in vignette
In addition: Warning messages:
1: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': Timeout of 60 seconds was reached
2: In file(con, "r") :
  URL 'http://bioconductor.org/config.yaml': Timeout of 60 seconds was reached
Execution halted
Full Traceback (most recent call last):
  File "/my_conda/envs/drop/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2520, in run_wrapper
    run(
  File "/tmp/3792520.1.b2c_rd_s1.q/tmphrew0okr", line 87, in __rule_MonoallelicExpression_pipeline_MAE_deseq_mae_R
  File "/my_conda/envs/drop/lib/python3.10/site-packages/snakemake/script.py", line 1369, in script
    executor.evaluate()
  File "/my_conda/envs/drop/lib/python3.10/site-packages/snakemake/script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/my_conda/envs/drop/lib/python3.10/site-packages/snakemake/script.py", line 716, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/my_conda/envs/drop/lib/python3.10/site-packages/snakemake/script.py", line 412, in _execute_cmd
    return shell(
  File "/my_conda/envs/drop/lib/python3.10/site-packages/snakemake/shell.py", line 296, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  Rscript --vanilla /mea/.snakemake/scripts/tmp0mfy8lx8.deseq_mae.R' returned non-zero exit status 1.
```

**Comment by vyepez88** [comment]
Hi, I've never seen that. The MAE module doesn't require internet connection.
I googled the error and found this: https://support.bioconductor.org/p/9138861/
Did you install some packages manually? I would simply suggest rerunning it; or reinstall DROP in a new conda environment.

**Comment by ym-chen** [comment]
> Hi, I've never seen that. The MAE module doesn't require internet connection. I googled the error and found this: https://support.bioconductor.org/p/9138861/ Did you install some packages manually? I would simply suggest rerunning it; or reinstall DROP in a new conda environment.

Thank you so much. I'm going to try again with your suggestion.

**Comment by vyepez88** [comment]
Hi @ym-chen , were you able to check this?

**Comment by ym-chen** [comment]
@vyepez88 I tried to reinstall DROP, but it failed so many times. I find that if I set the parameter: ```addAF: false```, the MAE works successfully. But if I set ```addAF: true```, I get the above error. 
Maybe there is a problem with the installation of some packages related to this parameter, but I have no idea.
What' more, installing DROP in my cluster environment was very difficult. And the environment that works now is more like a serendipitous success. It may be network instability or firewall blocking.

**Comment by vyepez88** [comment]
I see, yes, the addAF requires internet connect to the MafDb Bioconductor package:
https://bioconductor.org/packages/release/data/annotation/html/MafDb.gnomAD.r2.1.hs37d5.html
It can be easier to install DROP using our provided yaml files. Download it from here: https://www.cmm.in.tum.de/public/paper/drop_analysis/
and execute
`mamba env create -f DROP_1.3.1.yaml`
