### ISSUE TITLE
add samples to model

### ISSUE THREAD

**Issue by kdewispelaere** [gagneurlab/drop#436]
Hi,
This might be a naive question but I suppose it's not possible to add samples to an already built model? 
Thanks! (great package btw)

**Comment by vyepez88** [comment]
Hi, not sure what you mean exactly. There is the possibility to add your samples to other count matrices.

**Comment by kdewispelaere** [comment]
So what I'm doing is I want to build a large model with drop. I'm currently using outrider and fraser in R seperately for testing. Say I built a large reference model already and the autoencoder steps have been done. If there is a new batch of counts, then I assume the existing calculated confounder corrections can't be adjusted to this new data but will have to be calculated from scratch based on the entire dataset, right?

**Comment by vyepez88** [comment]
Right, with the current design, they'll have to be calculated from scratch. Even the optimal dimension of the latent space might be different.

**Comment by kdewispelaere** [comment]
Ah yes, ofcourse. What if the added samples would have to be masked anyway. Would it then be possible since these samples wouldn't be used during autoencoding anyways.
Thank you for your time

**Comment by vyepez88** [comment]
Hi, sorry for the super late reply. Unfortunately, we haven't had good experience with masking samples from the AE. The p-values of the genes of the masked sample are not normally distributed.
