### ISSUE TITLE
Error in AS and export counts with external kidney cortex data

### ISSUE THREAD

**Issue by agomez700** [gagneurlab/drop#437]
Hi team,

I have gotten DROP to run successfully using external GTEX counts you guys have provided from fibroblasts but for some reason am running into issues w/ kidney cortex.
When running export counts I get the following error:

Error in loadFraserDataSet(dir = workingDir, name = paste0("raw-local-",  : 
  The main RDS file /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-fraser/fds-object.RDS does not exists. Did you saved it correctly before?
Execution halted
[Mon Mar  6 10:26:32 2023]
Error in rule AberrantSplicing_pipeline_Counting_01_2_countRNA_splitReads_merge_R:
    jobid: 8
    input: Scripts/AberrantSplicing/pipeline/Counting/01_2_countRNA_splitReads_merge.R
    output: /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-fraser/rawCountsJ.h5, /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/gRanges_splitCounts.rds, /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/gRanges_NonSplitCounts.rds, /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/spliceSites_splitCounts.rds
    log: /lab-share/Neph-Sampson-e2/Public/AC/drop_6/DROP_kidneycortex/.drop/tmp/AS/fraser/01_2_splitReadsMerge.Rds (check log file(s) for error details)

RuleException:
CalledProcessError in file /tmp/tmpx6w77npc, line 130:
Command 'set -euo pipefail;  Rscript --vanilla /lab-share/Neph-Sampson-e2/Public/AC/drop_6/DROP_kidneycortex/.snakemake/scripts/tmpswl8foko.01_2_countRNA_splitReads_merge.R' returned non-zero exit status 1.
  File "/tmp/tmpx6w77npc", line 130, in __rule_AberrantSplicing_pipeline_Counting_01_2_countRNA_splitReads_merge_R
  File "/lab-share/Neph-Sampson-e2/Public/AC/drop_6/mambaforge/envs/drop_env6/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.

And when running AS I get this error:
Error in loadFraserDataSet(dir = workingDir, name = paste0("raw-local-",  : 
  The main RDS file /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-fraser/fds-object.RDS does not exists. Did you saved it correctly before?
Execution halted
[Mon Mar  6 09:07:20 2023]
Error in rule AberrantSplicing_pipeline_Counting_01_2_countRNA_splitReads_merge_R:
    jobid: 7
    input: Scripts/AberrantSplicing/pipeline/Counting/01_2_countRNA_splitReads_merge.R
    output: /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-fraser/rawCountsJ.h5, /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/gRanges_splitCounts.rds, /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/gRanges_NonSplitCounts.rds, /home/ch222985/Public/AC/drop_6/DROP_kidneycortex/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/spliceSites_splitCounts.rds
    log: /lab-share/Neph-Sampson-e2/Public/AC/drop_6/DROP_kidneycortex/.drop/tmp/AS/fraser/01_2_splitReadsMerge.Rds (check log file(s) for error details)

RuleException:
CalledProcessError in file /tmp/tmp46jlo8ec, line 130:
Command 'set -euo pipefail;  Rscript --vanilla /lab-share/Neph-Sampson-e2/Public/AC/drop_6/DROP_kidneycortex/.snakemake/scripts/tmpj98sye_n.01_2_countRNA_splitReads_merge.R' returned non-zero exit status 1.
  File "/tmp/tmp46jlo8ec", line 130, in __rule_AberrantSplicing_pipeline_Counting_01_2_countRNA_splitReads_merge_R
  File "/lab-share/Neph-Sampson-e2/Public/AC/drop_6/mambaforge/envs/drop_env6/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-03-06T090640.109514.snakemake.log

Attached is my annotation and my config file
[kidneycortexannotationforupload.xlsx](https://github.com/gagneurlab/drop/files/10899987/kidneycortexannotationforupload.xlsx)

[configtoupload.txt](https://github.com/gagneurlab/drop/files/10900022/configtoupload.txt)

**Comment by vyepez88** [comment]
Hi, it seems the pipeline stopped at some point unexpectedly and the fds object was not properly stored. I suggest you rerun everything from scratch. That might be faster than finding the solution.
