### ISSUE TITLE
Usage on one sample vs many samples

### ISSUE THREAD

**Issue by mincej** [gagneurlab/drop#438]
Hello all! 
I'm curious about the usage of DROP for a single sample at a time to find significant aberrant expression events. 
In the OUTRIDER manuscript, there is the advertised ability to [find individual sample-level outlier status](https://ars.els-cdn.com/content/image/1-s2.0-S0002929718304014-gr1.jpg). However, in the DROP documentation, there is a recommended [10 samples per group](https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#:~:text=These%20parameters%20are%20directly%20used%20by%20the%20aberrantExpression%20snakemake%20command.%20Aberrant%20expression%20groups%20must%20have%20at%20least%2010%20samples%20per%20group.%20To%20use%20external%20counts%20please%20see%20the%20Using%20External%20Counts%20section.) for the splicing and expression modules. Any clarification on this would be appreciated!

**Comment by vyepez88** [comment]
Hi, 
In order to detect outliers, a sufficiently large sample size is needed. The outlier detection is performed per gene across a population; not inside an individual across genes. In the figure that you sent, the outlier is detected among many other points. DROP needs at least 10 samples per group to run, but at least 50 samples are recommended for each method.

**Comment by mincej** [comment]
Reopening for a little more clarity. I'm confused by the last statement, "needs at least 10 samples per group to run". OUTRIDER functions by identifying expression outliers across the analyzed cohort. Does group here refer to experimental condition? If so, this is somewhat limiting in a rare disease analysis context, where the experimental condition may only be a handful of individuals. Or, rather, does groups refer to internal samples against external supplemental samples? I've noticed that the output for the demo of DROP splits the results into samples and samples_external. I appreciate any clarification on the nomenclature and best practice!

**Comment by vyepez88** [comment]
Hi, yes, OUTRIDER identifies outliers across the analyzed cohort. This cohort can be composed of individuals affected with disease A, individuals affected with disease B and/or unaffected individuals; as long as the samples were originated from the same tissue and sequenced in a similar same way. 
We are aware that in rare diseases, usually only a handful of samples are needed, that is why it is possible to integrate other samples into the same cohort/group.
In the demo, we show the option to work with only local samples and a combination between local and external. There is no comparison done between the 2 groups. Each group is analyzed independently. 
Finally, we offer some external count matrices to help boost the sample size: https://github.com/gagneurlab/drop#datasets They can be downloaded without restriction.
Hope this helps!

**Comment by muhligs** [comment]
Can you elaborate a little on this? I thought that using external counts would allow to run the pipeline on a single sample. I.e. in the sample sheet have one row with a single sample followed by e.g. 50 rows of samples corresponding to an external count run. But that seems to not work due to the '10 samples minimum' rule mentioned above ?

**Comment by mincej** [comment]
I could explain. In the configuration file and the sample annotation file, there are "groups" defined. This is if you want to batch samples together to compare independently. Say your dataset has 50 skin and 50 blood samples. You might say that the group for the skin samples are "skin_group" and the blood samples are "blood_group". Then in the configuration file, you would then have something like: 
```
aberrantExpression:
  run: true
  groups:
  - blood_group
  - skin_group
```

Altogether, this information means: run OUTRIDER on the blood group, and run it separately on the skin group. There is no information cross between the two. 

The above comment means that there are external samples available, and if you wish to treat the internal and external samples as part of the same cohort, you would just assign them to one group, such as "all_group". That's how I'm operating; all of my internal samples and external samples are assigned the same group in my sample annotation file and my configuration file only has one group per module. 

My one internal sample has groups "outrider,fraser,mae", and the external samples has groups "outrider,fraser" in the sample annotation file. This means I want to compare my internal sample against the external samples in the "outrider" group defined in aberrantExpression, and against the external samples in the "fraser" group defined in aberrantSplicing module. "mae" is defined only for my internal sample because the MAE module is not restricted by sample size, and I don't need the external sample MAE information for my analysis. 

Hope this helps!

**Comment by muhligs** [comment]
Great, thanks for clarifying. 
I think i did just that, but I still got the 'less than 10 samples' error although I had one sample with a bam file and another 48 samples with external count matrix. However, if I took 9 of my 'external count' samples and made them into analysis samples (i.e. provided bamfiles and filled out STRAND etc. cols) and provided bam file paths for those and emptied the external count specific cols for those as well, it ran. So in my hands it seems as if the '10 samples'  needs to be ones with bam files that has to go through the full AE and AS modules. 
But you say that this is not the case in your hands, as I hear you? 
Could I ask you perhaps to share an annotation file for a single sample setup as you described? Tha would be much appreciated. Thanks, Morten
