### ISSUE TITLE
Does AberrantSplicing work with Murdock dataset anymore? 

### ISSUE THREAD

**Issue by mincej** [gagneurlab/drop#439]
For the dataset `125 strand-specific blood, build hg19, Baylor College of Medicine`, the alternative splicing counts file structure seem to match the publications format of `SPLIT_COUNTS_FILE` and `NON_SPLIT_COUNTS_FILE`, however the documentation no longer recommends this format and specifies a column `SPLICE_COUNTS_DIR` with the files `k_j_counts.tsv.gz`, `k_theta_counts.tsv.gz`, `n_psi3_counts.tsv.gz`, `n_psi5_counts.tsv.gz`, `n_theta_counts.tsv.gz` in such a directory. I tried to determine if I could still use the Murdock dataset. 

To test, I tried two strategies. The first was to try the deprecated format that the manuscript recommended with `SPLIT_COUNTS_FILE` and `NON_SPLIT_COUNTS_FILE`. This seems to affect how this version of DROP sees the data, as I get this error: 

```
ValueError in file PATH/DROP/Snakefile, line 12:
Too few IDs in DROP_GROUP fraser, please ensure that it has at least 10 IDs, groups: ['Sample1']
  File "PATH/DROP/Snakefile", line 12, in <module>
  File "OTHERPATH/miniconda3/envs/drop_env/lib/python3.11/site-packages/drop/config/DropConfig.py", line 65, in __init__
  File "OTHERPATH/miniconda3/envs/drop_env/lib/python3.11/site-packages/drop/config/submodules/AberrantSplicing.py", line 31, in __init__
  File "OTHERPATH/miniconda3/envs/drop_env/lib/python3.11/site-packages/drop/config/submodules/Submodules.py", line 53, in checkSubset
```

Then, when I try to instead use `SPLICE_COUNTS_DIR`, I instead get this error, unsurprisingly. 
```
WorkflowError:
WorkflowError:
    WorkflowError:
        MissingInputException: Missing input files for rule markdown:
            output: PATH/Output/Reports/AberrantSplicing/fraser_countSummary.html
            wildcards: file=AberrantSplicing/fraser_countSummary
            affected files:
                AberrantSplicing/fraser_countSummary.md
        MissingInputException: Missing input files for rule AberrantSplicing_pipeline_Counting_03_filter_expression_FraseR_R:
            output: PATH/processed_data/aberrant_splicing/datasets/savedObjects/fraser/fds-object.RDS, PATH/processed_data/aberrant_splicing/datasets/savedObjects/fraser/filter.done
            wildcards: dataset=fraser
            affected files:
                PATH/Data/External/RNAseq/Murdock_Blood_hg19/k_j_counts.tsv.gz
    MissingInputException: Missing input files for rule markdown:
        output: PATH/Output/Reports/Scripts_AberrantSplicing_pipeline_Counting_DatasetsF.html
        wildcards: file=Scripts_AberrantSplicing_pipeline_Counting_DatasetsF
        affected files:
            Scripts_AberrantSplicing_pipeline_Counting_DatasetsF.md
MissingInputException: Missing input files for rule markdown:
    output: PATH/Output/Reports/aberrant-splicing-pipeline_index.html
    wildcards: file=aberrant-splicing-pipeline_index
    affected files:
        aberrant-splicing-pipeline_index.md
```

So I have two questions: 
1. Is it possible to still use the Murdock dataset? Is there a way to convert these split and non-split files to the five files required to be in the `SPLICE_COUNTS_DIR`? 
2. Is there any form of backwards compatibility with this deprecated format, other than installing a previous version of DROP? Or would I just need to use this? 
3. If it is not, what external dataset is recommended? I was interested in the Murdock dataset because it is stranded, blood, and paired-end, which all matches the criteria for my in-house data. 

Thanks for any clarification!

**Comment by vyepez88** [comment]
Hi, you are right. That dataset is deprecated. We already contacted the authors and they said they'll rerun the counts to get the updated ones and will share with us again. I'll let you know when that happens.
Currently, unfortunately, we do not have other stranded, blood, and paired-end datasets.

**Comment by mincej** [comment]
Great, thank you for the timely reply!
