### ISSUE TITLE
Option to either ignore HTML output or how to ease the burden of one local sample against many external?

### ISSUE THREAD

**Issue by mincej** [gagneurlab/drop#440]
Hello, 
I'm running into issues, some of which are happening in HTML reports. I largely don't need the HTML reports, as I'm wanting to use the output matrix of the modules in downstream analyses, so are there options to choose not to render the R markdown files? 

The problem that motivates this was an issue I'm having with using one in-house sample against many GTEx samples. When running the AberrantExpression module, I get the error in `AberrantExpression/Counting/v29/Summary_outrider.html`, which is 

```
Quitting from lines 113-166 (PATH/Summary.spin.Rmd) 
Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
Calls: render ... FUN -> data.table -> rowMeans -> rowMeans -> <Anonymous>
```
I located this to be in the code chunk of displaying genes or samples post filtering (local, all, passed FPKM, etc.)

I suspected that this was because I had one in-house, so I tested this by making fake replicates (Samples 1 - 3 that point to the same BAM file). That confirmed it, as I got further into the rendering of the HTML file, but then was hit with this error: 

```
Error in lda.default(x, grouping, ...) : 
  variables 1 2 appear to be constant within groups
```

This makes sense, since they ARE identical. But more importantly, it confirmed my suspicion, or I'm misunderstanding the meaning of the error codes. 

So I would either appreciate help with either this specific error code, or a way to circumvent HTML report generating outside of hunting down the commands in the pipeline. What would be the greatest help, though, would be guidance on other issues I'm likely to encounter with using one sample at a time. Not necessarily with quality of output; I understand the caveats and am fully expecting that the data output is going to be affected, but my objective at the moment is to get any output whatsoever. Thanks for any guidance!

**Comment by vyepez88** [comment]
Hi,
There is no parameter to create the HTML reports. We strongly recommend creating them and checking the plots before proceeding with the analysis.
Do you have the GTEx files downloaded or do you use the count matrices? Are you able to run the pipeline with using only GTEx samples?

**Comment by mincej** [comment]
I've been using external count data provided. When only using GTEx samples, I get an error in `Scripts/AberrantExpression/pipeline/OUTRIDER/Summary.R` instead of the count summary as before: 

```
Quitting from lines 208-264 (PATH/Summary.spin.Rmd) 
Error in model.matrix.default(Terms, m) : variable 1 has no levels
Calls: render ... lda.formula -> model.matrix -> model.matrix.default
```

**Comment by mincej** [comment]
Closing this issue. I discovered the issue. 
Since I had 1 external sample, the command `cnts_mtx_local <- counts(ods, normalized = F)[,!as.logical(ods@colData$isExternal)]
` in AberrantExpression/pipeline/Counting/Summary.R led to `cnts_mtx_local` to me a 1-D array. I added a custom code chunk so ensure that this was a 2-D matrix, which was needed to prevent the above error of 

```
Quitting from lines 113-166 (PATH/Summary.spin.Rmd) 
Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
Calls: render ... FUN -> data.table -> rowMeans -> rowMeans -> <Anonymous>
```

The reason this error was raising was because the 1-D array did not have rowMeans functions, so the coercion fixed this.

**Comment by vyepez88** [comment]
Hi, I was not able to reproduce this error in the aberrant expression module. But I was able to reproduce it in the aberrant splicing module. This is now fixed in this commit and is part of the latest DROP version (1.3.0): https://github.com/gagneurlab/drop/pull/447/commits/b3536420369d472ec30a2676021cef7c24e3ec8f
Many thanks for finding it and reporting it.

**Comment by vyepez88** [comment]
Hi, this is actually fixed in 1.3.1

**Comment by mincej** [comment]
Fantastic, I've got the new version downloaded and am getting to testing it now!

**Comment by mincej** [comment]
I unfortunately have the same issues as above in the aberrantExpression module. Running the module out of the box with `drop --version == drop, version 1.3.1`, I get the error message: 
```
Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
Calls: render ... FUN -> data.table -> rowMeans -> rowMeans -> <Anonymous>
```

If I change [this line](https://github.com/gagneurlab/drop/blob/1b98b379d0c33993d25860ecf3741711a7ea0823/drop/modules/aberrant-expression-pipeline/Counting/Summary.R#L37) to `cnts_mtx_local <- counts(ods, normalized = F)[,!as.logical(ods@colData$isExternal), drop = FALSE]`, then the aberrantExpression module completes without error. 

Please refer to the configuration file and the sample annotation file here, as the information used is the same: https://github.com/gagneurlab/drop/issues/446#issuecomment-1494394066
