### ISSUE TITLE
AberrantSplicing splitReads speed up

### ISSUE THREAD

**Issue by muhligs** [gagneurlab/drop#442]
Hi, 

I am currently running 50 stranded blood samples through the external count pipeline, and I have a number of samples that time out after 48h (my set walltime limit) in the splitReads count step. Several of the samples take >24h, although some also completes in 1-3h.

The rule currently runs with three allocated cores. Is it possible to increase the number of cores for this rule to decrease runtime, and if so, how to do it. 

Thanks 

Morten

**Comment by vyepez88** [comment]
Hi, you can set up the global number of cores when executing the pipeline:
`snakemake --cores 30`
If you want to change the specific script, change the threads line in the header of the countRNA_splitReads script in the Aberrant Splicing folder: https://github.com/gagneurlab/drop/blob/master/drop/modules/aberrant-splicing-pipeline/Counting/01_1_countRNA_splitReads_samplewise.R#L17
Check with your IT team the best way of executing jobs, for us they take just a few minutes each.

**Comment by muhligs** [comment]
Thanks, 
I am not snakemake savvy, 
I run with:

`snakemake exportCounts --cluster "sbatch -N1 -n 3 --mem 50Gb --account myacc --time=48:00:00" -j 50 -k`

Could I adjust the setting in your answer directly from the CLI with:

`snakemake exportCounts --set-resources AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:cpus-per-task=10 --cluster "sbatch -N1 --mem 150Gb --account myacc --time=48:00:00" -j 50 -k`

?

**Comment by vyepez88** [comment]
I haven't tried that specific command, but looks as if it would do the job! feel free to try it and see what happens :)

**Comment by muhligs** [comment]
Thanks for input, I will try it out. Closing.
