### ISSUE TITLE
MissingOutputException in rule AberrantSplicing_pipeline_Counting_01_2_countRNA_splitReads_merge_R

### ISSUE THREAD

**Issue by mincej** [gagneurlab/drop#446]
Hey everyone, 

When running AberrantSplicing module, I get this error: 
```
MissingOutputException in rule AberrantSplicing_pipeline_Counting_01_2_countRNA_splitReads_merge_R
```

The missing file is: 
```
/Output/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-fraser/rawCountsJ.h5
```
I'm not sure if my error is because of my configuration file or my sampleAnnotation file, so I went to the `AberrantSplicing/pipeline/Counting/01_2_countRNA_splitReads_merge.R` file to add print statements to see the intermediate data to make sure it is there. However, through this exercise, I didn't see any `saveRDS` statements that look like they are tied to rawCountsJ.h5. 

At the top of the file, we have: 
```
#'  output:
#'   - countsJ: '`sm cfg.getProcessedDataDir() +
#'                          "/aberrant_splicing/datasets/savedObjects/raw-local-{dataset}/rawCountsJ.h5"`'
#'   - gRangesSplitCounts: '`sm cfg.getProcessedDataDir() + 
#'                          "/aberrant_splicing/datasets/cache/raw-local-{dataset}/gRanges_splitCounts.rds"`'
#'   - gRangesNonSplitCounts: '`sm cfg.getProcessedDataDir() + 
#'                          "/aberrant_splicing/datasets/cache/raw-local-{dataset}/gRanges_NonSplitCounts.rds"`'
#'   - spliceSites: '`sm cfg.getProcessedDataDir() + 
#'                   "/aberrant_splicing/datasets/cache/raw-local-{dataset}/spliceSites_splitCounts.rds"`'
```
Here are the following links to where some of these files are being exported: 
- [gRangesSplitCounts](https://github.com/gagneurlab/drop/blob/717ca9ccaebca2207151fded1758a5b9704f9db2/drop/modules/aberrant-splicing-pipeline/Counting/01_2_countRNA_splitReads_merge.R#L56)
- [gRangesNonSplitCounts](https://github.com/gagneurlab/drop/blob/717ca9ccaebca2207151fded1758a5b9704f9db2/drop/modules/aberrant-splicing-pipeline/Counting/01_2_countRNA_splitReads_merge.R#L65)
- [spliceSites](https://github.com/gagneurlab/drop/blob/717ca9ccaebca2207151fded1758a5b9704f9db2/drop/modules/aberrant-splicing-pipeline/Counting/01_2_countRNA_splitReads_merge.R#L70)

Yet I couldn't find an export statement for countsJ. I also searched the repository for other references of `rawCountsJ`, but couldn't find anything in files that occur earlier in the pipeline than 01_2_countRNA_splitReads_merge.R. Am I misinterpreting where this file should be exported, and is this more likely user error? Thanks for any guidance!

**Comment by mincej** [comment]
After looking through a bit, I found that the file should be written by [getSplitReadCountsForAllSamples](https://github.com/gagneurlab/drop/blob/717ca9ccaebca2207151fded1758a5b9704f9db2/drop/modules/aberrant-splicing-pipeline/Counting/01_2_countRNA_splitReads_merge.R#L49) from the FRASER package, and I also figured out that the error is raised by having 1 local sample against many external samples. Is there anything I can do to fix this?

**Comment by vyepez88** [comment]
Hi, can you make sure that the gtf file that you're using (provided in the geneAnnotation parameter) is the same one used to create the external counts?

**Comment by mincej** [comment]
Hi Vicente, I am using the hg38 external counts for GTEx. My sample annotations for these samples include `GENOME = "hg38"` and `GENE_ANNOTATION = "v29"`, and these keys are included in my configuration file as 

```
geneAnnotation:
    v29: PATH/AnnotationsExtras/Annotation/gencode.v29.annotation.gtf

genomeAssembly: hg38
genome: 
    hg38: PATH/AnnotationsExtras/Reference_Genomes/Homo_sapiens_GRCh38_dna_primary_assembly.fa 
```

To the best of my knowledge, this is what was used to create the external counts. I got this information from the manuscript, though I couldn't find a detailed procedure for external count generation, as well as from the Zenodo link [here](https://zenodo.org/record/6078397#.ZCrco9DMJD9). 

Does it matter what annotation was used to generate the local BAM files? I received the local files from collaborators, but I know what the GTF was used to create the STAR genome, but I do not know if this is the same GTF used to align the GTEx fastqs. In addition, I don't know if these need to be the same; if the GTEx fastqs were aligned to a STAR genome using the gencode v29 GTF, then local BAM files also need to be aligned to a STAR genome using the gencode v29 GTF.

**Comment by vyepez88** [comment]
Hi, gencode v29 is correct. Can you share your sample annotation table?

**Comment by mincej** [comment]
Here is both the configuration file and the sample annotation file!

[config_censored.txt](https://github.com/gagneurlab/drop/files/11139330/config_censored.txt)
[sample_annotation_gtex_censored.txt](https://github.com/gagneurlab/drop/files/11139338/sample_annotation_gtex_censored.txt)

**Comment by vyepez88** [comment]
Hi Joshua,
Thanks for sharing. Everything looks fine. I guess it is related to an issue we had where if you subset samples, the aberrant splicing module was not able to merged them. This is now fixed in DROP v1.3.0 which we released yesterday. Please install that and run it in a new directory. 
Note that with that version, you can use FRASER 2.0 by changing some parameters in the config file. Follow the documentation. Keep us updated. 
Thanks again for reporting the issues.

**Comment by mincej** [comment]
Hey Vicente, 
Thanks, I'll give this a shot when the 1.3.0 yaml drops! (I get infinite hangs when trying to use `conda create -n ...` on my HPC, so I've used the .yamls for previous versions) and let you know if that fixes the issue. 

It may be worth noting that I had some problems with data structure shape in the aberrantExpression module for 1 local sample, so to test this hypothesis in the aberrantSplicing module, I used a sample annotation of 100 external GTEx counts, our 1 local sample, and 1 local GTEx sample that we have access to the BAMs for. After setting up the annotation and configuration so that there were 2 local samples to be processed, the aberrantSplicing module completed without the error above on DROP v1.2.4. 

But I'll let you know if v1.3.0 works with only one local sample as in the sample annotation above. Thanks again for your helpful replies for these issues. This pipeline is very exciting, and it's encouraging to see how attentive yourself and the team are for fixing issues and directing others in the community using DROP!

**Comment by mincej** [comment]
Hello again, I was hesitant to open up another issue for this since I've opened a few recently, but I think I found a related error in the MAE module. 

I'm running the MAE module with only one sample, the same as above. The config and sampleAnnotation are also the same as above. I confirmed that the chromosome style matches between my RNA BAMs, my DNA VCFs, and my GTF annotation.

The error that's being raised is in `MAE/QC/DNA_RNA_matrix_plot.R`. I assume this section of the pipeline is looking at the correlation between DNA variants and RNA variants to identify any sample swapping. 
```
Error in setnames(x, value) : 
  Can't assign 2 names to a 1 column data.table
Calls: render ... colnames<- -> names<- -> names<-.data.table -> setnames
```

Since I'm only using one sample, the input `mat_qc` (and output of `MAE/QC/create_matrix_dna_rna_corr.R`) is a single value: 
```
[1] 0.9895227
```
I assume the error comes up when trying to reshape and melt, since this is the only place in the script that colnames are being assigned. Since this is only a single value without a row name or column name to reshape with and assign "DNA_ID" and "RNA_ID" to, this ends up failing. 
To fix this error, I changed line 99 in the file `drop/modules/mae-pipeline/QC/create_matrix_dna_rna_cor.R`:

From: `mat <- mat[sa[rows_in_group, DNA_ID], sa[rows_in_group, RNA_ID]]`
To:      `mat <- mat[sa[rows_in_group, DNA_ID], sa[rows_in_group, RNA_ID], drop = FALSE]`. 


This fixed this error, but that led to another error with the pheatmap shortly after: 
```
Error in cut.default(x, breaks = breaks, include.lowest = T) : 
  'breaks' are not unique
Calls: render ... scale_colours -> matrix -> scale_vec_colours -> cut -> cut.default
```

I figured this had to do with how the breaks were being calculated with only one sample, so I added: 
```
if(nrow(qc_mat) > 1 && ncol(qc_mat) > 1){
   breaks <- NA
} else {
  breaks <- c(0,1)
}
```
Just to add something basic to get the code to run. A 1x1 heatmap wouldn't show much anyways, so this was just a quick workaround. Regardless, this got the MAE module to run all the way through. 

I'm not sure if these issues have been reported before with using 1 sample for the MAE module, but I thought I would add this to the issue since this might be related!

**Comment by vyepez88** [comment]
Regarding your post from yesterday, we have now created the 1.3.1 yaml. You can find it here: https://www.cmm.in.tum.de/public/paper/drop_analysis/

**Comment by mincej** [comment]
Thanks, I've downloaded and installed it and am testing. I will let you know if the issue is solved!

**Comment by mincej** [comment]
Unfortunately, the issue still persists. While only using 1 local sample, I have the same error of missing the rawCountsJ.h5 export from script `Scripts/AberrantSplicing/pipeline/Counting/01_2_countRNA_splitReads_merge.R` while using DROP v1.3.1. Is there any other information that I can provide that may be helpful? 

I'm fairly certain the failure to export this file is during this function from FRASER which is called at [this point in the module](https://github.com/gagneurlab/drop/blob/1b98b379d0c33993d25860ecf3741711a7ea0823/drop/modules/aberrant-splicing-pipeline/Counting/01_2_countRNA_splitReads_merge.R#L49):
https://rdrr.io/github/c-mertes/FraseR/src/R/countRNAseqData.R#:~:text=getSplitReadCountsForAllSamples%20%3C%2D%20function(fds%2C%20NcpuPerSample%3D1%2C

The reason that I believe this is that I added `print(file.exists(PATH/savedObjects/raw-local-fraser/rawCountsJ.h5))` statements after every function call to determine when the file was being created. Then, I ran the module two times: once with 1 local sample and another with 1 local sample and 1 local control sample. 

In the 1 sample case, this evaluated to FALSE throughout the script, but in the 2 sample case, this evaluated to TRUE starting after the linked getSplitReadCountsForAllSamples above.

**Comment by vyepez88** [comment]
Hi, yes, you're right. We have now released yet a new version 1.3.2. Please try it. Sorry for the multiple attempts.

**Comment by vyepez88** [comment]
This release also fixes the issue you reported on the MAE module. 
As a side note, it's completely fine to keep on reporting issues! Even better when you help us finding them and even come up with a fix, many thanks!

**Comment by mincej** [comment]
See comment here: https://github.com/gagneurlab/drop/issues/450#issuecomment-1518430281
