### ISSUE TITLE
Sample annotation columns

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#45]
Hi,
There is some inconsistency in sample annotation columns listed in the protocol here: https://protocolexchange.researchsquare.com/article/pex-787/v1

versus the Documentation site

versus the example table here: https://github.com/gagneurlab/drop/blob/d30fe27368b9fe0226863dc0d0486a8d2e97ebb3/manuscript/TableS1_sample_annotation.tsv

Each of these has a different set of columns, so I'm not sure which are necessary and which are optional. For example, STRAND and SEX are only listed in some of them. It isn't clear what phase1TG  and RNA_exists are, etc.

Can you please clarify?
Thanks.

**Comment by vyepez88** [comment]
Hi, 
The columns listed in the protocol correspond to the ones required for DROP to run. But, other columns (like sex, phase1TG, ethnicity, etc.) can be included. Table S1 is a subset of the sample annotation from GEUVADIS which contains other columns not needed by DROP.

**Comment by gevro** [comment]
Thanks. In that case, I think it would help to update the Documentation site, because that does not show all the columns in the protocol site.

**Comment by vyepez88** [comment]
Thanks for the suggestion, I will clarify that in the Documentation.
