### ISSUE TITLE
DROP 1.3.1 - Error in rule AberrantSplicing_pipeline_FRASER_08_extract_results_FraseR_R

### ISSUE THREAD

**Issue by mincej** [gagneurlab/drop#450]
FRASER previously works with the dataset provided in DROP 1.2.4. After updating to FRASER 2 and DROP 1.3.1, I've started to get this new error in `AberrantSplicing_pipeline_FRASER_08_extract_results_FraseR_R`.

```
[Thu Apr  6 17:15:40 2023]
Finished job 1.
7 of 11 steps (64%) done
Thu Apr  6 17:15:29 2023: Collecting results for: jaccard (transcriptome-wide)
Thu Apr  6 17:15:42 2023: Process chunk: 1 for: jaccard
Thu Apr  6 17:15:48 2023: Process chunk: 2 for: jaccard
Thu Apr  6 17:15:55 2023: Process chunk: 3 for: jaccard
Thu Apr  6 17:16:00 2023: Process chunk: 4 for: jaccard
Thu Apr  6 17:16:07 2023: Process chunk: 5 for: jaccard
Thu Apr  6 17:16:12 2023: Process chunk: 6 for: jaccard

[1] "Results per junction extracted"
Thu Apr  6 17:16:14 2023: Collecting results for: jaccard (transcriptome-wide)
Thu Apr  6 17:16:29 2023: Process chunk: 1 for: jaccard

Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
Execution halted
```

If I use FRASER 1 in DROP 1.3.1, I also get this error: 
```
Thu Apr  6 19:34:35 2023: Collecting results for: psi3 (transcriptome-wide)
Thu Apr  6 19:34:39 2023: Process chunk: 1 for: psi3

Thu Apr  6 19:34:35 2023: Collecting results for: psi5 (transcriptome-wide)
Thu Apr  6 19:34:39 2023: Process chunk: 1 for: psi5

Thu Apr  6 19:34:35 2023: Collecting results for: theta (transcriptome-wide)
Thu Apr  6 19:34:40 2023: Process chunk: 1 for: theta

Error: BiocParallel errors
  3 remote errors, element index: 1, 2, 3
  0 unevaluated and other errors
  first remote error:
Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
Execution halted
```

This seems to be occurring in this function: https://github.com/gagneurlab/drop/blob/1b98b379d0c33993d25860ecf3741711a7ea0823/drop/modules/aberrant-splicing-pipeline/FRASER/08_extract_results_FraseR.R#L82-L84

Based on the error, I think it's happening after this code block, since it's printing the "Collecting results for: ..." messages:  
https://github.com/c-mertes/FRASER/blob/45ff4301367a41cf76105035f0d26c48de3bdf3c/R/AllGenerics.R#L743-L848

Please let me know if I can provide any useful information! I'm not sure where to start with this issue, since it seems to be in a function in the FRASER2 package.

**Comment by vyepez88** [comment]
Hi, can you please confirm whether you are running this in a brand new project folder? 
The fds (fraser dataset) objects from FRASER1 and FRASER2 are not fully compatible.

**Comment by mincej** [comment]
I have been testing DROP 1.3.1 in a brand new directory with a new ‘drop init’. However, the FRASER 1 and FRASER 2 tests above were both in the DROP 1.3.1 directory after the initial drop init.

To clarify, the FRASER1 and FRASER2 that were tested were switched in the config.yaml, I was not manually switching FRASER versions with library loads.

**Comment by vyepez88** [comment]
using which of the 2 FRASERs did you get the error?

**Comment by mincej** [comment]
I outlined in the original comment, but I get the error for both of the FRASERs. 

Error using `FRASER_version: "FRASER"`
```
Thu Apr  6 19:34:35 2023: Collecting results for: psi3 (transcriptome-wide)
Thu Apr  6 19:34:39 2023: Process chunk: 1 for: psi3

Thu Apr  6 19:34:35 2023: Collecting results for: psi5 (transcriptome-wide)
Thu Apr  6 19:34:39 2023: Process chunk: 1 for: psi5

Thu Apr  6 19:34:35 2023: Collecting results for: theta (transcriptome-wide)
Thu Apr  6 19:34:40 2023: Process chunk: 1 for: theta

Error: BiocParallel errors
  3 remote errors, element index: 1, 2, 3
  0 unevaluated and other errors
  first remote error:
Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
Execution halted
```

Error using `FRASER_version: "FRASER2"`: 
```
Thu Apr  6 17:15:29 2023: Collecting results for: jaccard (transcriptome-wide)
Thu Apr  6 17:15:42 2023: Process chunk: 1 for: jaccard
Thu Apr  6 17:15:48 2023: Process chunk: 2 for: jaccard
Thu Apr  6 17:15:55 2023: Process chunk: 3 for: jaccard
Thu Apr  6 17:16:00 2023: Process chunk: 4 for: jaccard
Thu Apr  6 17:16:07 2023: Process chunk: 5 for: jaccard
Thu Apr  6 17:16:12 2023: Process chunk: 6 for: jaccard

[1] "Results per junction extracted"
Thu Apr  6 17:16:14 2023: Collecting results for: jaccard (transcriptome-wide)
Thu Apr  6 17:16:29 2023: Process chunk: 1 for: jaccard

Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
Execution halted
```

**Comment by for3guy** [comment]
I faced just the same kind of problem running the AberrantSplicing mode (both FRASER 1 & 2). Although I tried several different options, re-installation, and update, I could not solve this problem, either. It would be greatly helpful if anyone can help me in this situation.

**Comment by vyepez88** [comment]
Hi @mincej and @for3guy, we found the error on our side. We're working on it and let you know once it's fixed. Thanks for reporting it.

**Comment by for3guy** [comment]
Thank you very much!

Seungbok Lee, M.D., Ph.D.
Seoul National University College of Medicine
Seoul 110-799, Korea
Tel +82-2-740-8963
Mobile +82-10-8427-3470

-----Original Message-----

**Comment by mincej** [comment]
Great, thanks for the update!

**Comment by liffcardio** [comment]
Hi, is there any progression for the problem? I faced just the same kind of problem by running drop1.3.2 frazer1.

**Comment by vyepez88** [comment]
This should be now fixed in release 1.3.3

**Comment by liffcardio** [comment]
Thank you very much, I will try again!

**Comment by liffcardio** [comment]
@vyepez88 I try to install the drop by drop_1_3_3.ymal file, but when I activate the environment of drop_1_3_3_orig, I can not use the command of drop init. It said do not have this command.
I notice that compared to drop_1_3_2.ymal, the size of drop_1_3_3.ymal is really small. Is there something wrong with the file?

**Comment by mincej** [comment]
Installed DROP 1.3.3, ran through Aberrant Expression, Aberrant Splicing, and MAE with one local sample no raised errors. In addition, the above FRASER error did not raise either. Thanks for the help!
