### ISSUE TITLE
The drop command cannot be executed in an environment built with drop_1_3_3.ymal

### ISSUE THREAD

**Issue by liffcardio** [gagneurlab/drop#455]
Hi, I have successfully run drop_1.2.4 by building the environment with drop_1.2.4.ymal before, I want to run drop again for some new samples, so I try to build the environment by using 'conda env create -f DROP_1_3_3.ymal'. But when I activated the environment, made a directory of drop_demo, and ran the drop demo command, it said 'drop: command not found.' Could you help me with that?

**Comment by liffcardio** [comment]
Hi, I have successfully run drop_1.2.4 by building the environment with drop_1.2.4.ymal before, I want to run drop again for some new samples, so I try to build the environment by using 'conda env create -f DROP_1_3_3.ymal'. But when I activated the environment, made a director of drop_demo, and ran the drop demo command, it said 'drop: command not found.' Could you help me with that?

**Comment by ischeller** [comment]
Hi @liffcardio , thank you for pointing this out! It seems that something went wrong on our end when creating the `DROP_1.3.3.yaml` file. I updated the file now to fix this. Can you try downloading the file again from [our public server](https://www.cmm.in.tum.de/public/paper/drop_analysis/) and then running `conda env create -f DROP_1.3.3.yaml`? This should fix the issue. Let us know in case it doesn't

**Comment by liffcardio** [comment]
Thank you for your reply! I try to download the file, but I do not have permission to access the file.

> Hi @liffcardio , thank you for pointing this out! It seems that something went wrong on our end when creating the `DROP_1.3.3.yaml` file. I updated the file now to fix this. Can you try downloading the file again from [our public server](https://www.cmm.in.tum.de/public/paper/drop_analysis/) and then running `conda env create -f DROP_1.3.3.yaml`? This should fix the issue. Let us know in case it doesn't

**Comment by ischeller** [comment]
I updated the permissions, does it work now?

**Comment by liffcardio** [comment]
I have downloaded the file. But when I run 
```
conda env create -f DROP_1.3.3.yaml
```
It said:
Pip subprocess error:
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: Could not find a version that satisfies the requirement drop==1.3.3 (from versions: 0.1.macosx-10.10-x86_64, 0.1.1.macosx-10.10-x86_64, 0.1.2.macosx-10.10-x86_64, 0.2.0.macosx-10.10-x86_64, 0.1, 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.4.0, 0.4.1)
ERROR: No matching distribution found for drop==1.3.3

failed

CondaEnvException: Pip failed

**Comment by ischeller** [comment]
Sorry for the inconvenience. I could reproduce your issue and now created a new DROP_1.3.3.yaml file from a different device. With the new file, I can successfully create the environment on my end. Could you try again to see if it fixes it for you as well?

**Comment by liffcardio** [comment]
Thank you very much.I am on vacation until the 8th. I'll try it as soon as I go back to work!

**Comment by liffcardio** [comment]
@ischeller I have built the drop1_3_3 environment by DROP_1.3.3.ymal and have run demo successfully. Thank you very much!
