### ISSUE TITLE
Unable to create environment due to 'bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0'

### ISSUE THREAD

**Issue by dfermin** [gagneurlab/drop#456]
Hello
I'm trying to install the latest release of drop 1.3.3 but it consistently fails due to a dependency.
Here is my command:
```
conda config --set channel_priority true
mamba create -n drop_env -c conda-forge -c bioconda drop --override-channels
```

And things progress nicely until:
```

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: /
|
done
ERROR conda.core.link:_execute(745): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0'.
Rolling back transaction: \ -
```

Any suggestions on how to fix this?

Thanks

**Comment by zombiebride226** [comment]
I am facing the same situation, anyone could help us, thanks!
Preparing transaction: done                                                                                                                                   
Verifying transaction: done                                                                                                                                   
Executing transaction: done                                                                                                                                   
ERROR conda.core.link:_execute(945): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0'.                
Rolling back transaction: done                                                                                                                                
                                                                                                                                                              
LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0                                                    
location of failed script: /Users/nakajimalab/miniconda3/envs/qiime2-2023.7/bin/.bioconductor-genomeinfodbdata-post-link.sh                                   
==> script messages <==                                                                                                                                       
<None>                                                                                                                                                        
==> script output <==

**Comment by vyepez88** [comment]
Hi, can you try installing DROP using the provided yaml file?
