### ISSUE TITLE
Error in if (cfg$aberrantSplicing$FRASER_version == "FRASER2")

### ISSUE THREAD

**Issue by ChiaraF32** [gagneurlab/drop#458]
Hi,

I just updated my DROP pipeline to version version 1.3.3, so that I could run the aberrant splicing module using FRASER 2.0. 

The aberrant splicing module fails near the start, with the following error message:

```
counting
Quitting from lines 26-29 (/data/tmp_drop/Rtmp3Z4sx4/file11a062f2113e/00_define_datasets_from_anno.spin.Rmd) 
Error in if (cfg$aberrantSplicing$FRASER_version == "FRASER2") { : 
  argument is of length zero
Calls: render ... eval -> eval -> source -> withVisible -> eval -> eval
```

I am running this on Ubuntu 18.04. The run. script I used is below:
```
snakemake --cores 14 --default-resources "tmpdir='/data/tmp_drop'" "mem_mb=60000"
```

**Comment by ischeller** [comment]
Hi @ChiaraF32 , did you update your `config.yaml`? I suspect that you are missing the new parameters there. Have a look at the template `config.yaml` file for DROP version 1.3.3 [here](https://github.com/gagneurlab/drop/blob/master/drop/template/config.yaml#L39).

**Comment by ChiaraF32** [comment]
Hi @ischeller 
Thanks for your help. I have updated the config.yaml file and now the pipeline is working.
