### ISSUE TITLE
Running with single sample and external counts

### ISSUE THREAD

**Issue by muhligs** [gagneurlab/drop#459]
Hi, I am having problems running the pipeline. 
I have successfully produced external counts for 48 blood samples, and I would now like to run the full pipeline on one sample using these external counts in the same drop-groups. 
I am getting a 'Too few IDs in DROP_GROUP outrider' error.

Is it not possible to run the pipeline on a single sample in addtion to a panel of external counts?  
And if it is, could someone provide an example sample_annotation.tsv and corresponding config.yaml file to look at. That would be highly appreciated and a great help. 

Thanks, 
Morten

**Comment by vyepez88** [comment]
Hi Morten, it is possible to add only 1 local sample. The demo dataset (that you can obtain by executing `drop demo` in an empty folder) contains examples of sample annotations and config files with external samples.

**Comment by muhligs** [comment]
Hi Vicente, 
It seems that this was because a '--hg38--' in the external count file path in the sample annotation sheet was rephrased to '—hg38—' by the calc spreadsheet program, and thus seized to exist, reducing sample counts to just the one local sample. 
Thanks for taking the time to answer.
