### ISSUE TITLE
Pipeline stops if group returns no results - FRASER2

### ISSUE THREAD

**Issue by mincej** [gagneurlab/drop#463]
Hello, 
I'm running 10+ different groups in parallel. Based on the error logs, some of them are returning results, but it seems like the pipeline is stopping due to an error when the pipeline has a group with no returned results. 

At rule AberrantSplicing_pipeline_FRASER_08_extract_results_FraseR_R, I get this warning and subsequent error: 

```
Loading assay: rawCountsJ
Loading assay: psi5
Loading assay: psi3
Loading assay: rawOtherCounts_psi5
Loading assay: rawOtherCounts_psi3
Loading assay: rawCountsJnonsplit
Loading assay: jaccard
Loading assay: rawOtherCounts_jaccard
Loading assay: delta_jaccard
Loading assay: delta_psi5
Loading assay: delta_psi3
Loading assay: predictedMeans_jaccard
Loading assay: pvaluesBetaBinomial_junction_jaccard
Loading assay: pvaluesBetaBinomial_jaccard
Loading assay: padjBetaBinomial_jaccard
Loading assay: rawCountsSS
Loading assay: theta
Loading assay: rawOtherCounts_theta
Loading assay: delta_theta
Loading assay: rawCountsJ
Loading assay: psi5
Loading assay: psi3
Loading assay: rawOtherCounts_psi5
Loading assay: rawOtherCounts_psi3
Loading assay: rawCountsJnonsplit
Loading assay: jaccard
Loading assay: rawOtherCounts_jaccard
Loading assay: delta_jaccard
Loading assay: delta_psi5
Loading assay: delta_psi3
Loading assay: predictedMeans_jaccard
Loading assay: rawCountsSS
Loading assay: theta
Loading assay: rawOtherCounts_theta
Loading assay: delta_theta
Loading required package: GenomicFeatures
loading introns ...
start calculating basic annotations ...
Wed May 10 09:19:02 2023: Collecting results for: jaccard (transcriptome-wide)
Wed May 10 09:19:15 2023: Process chunk: 1 for: jaccard

Warning message:
The aberrant splicing pipeline gave 0 results for the Group10 dataset. 
Wed May 10 09:19:21 2023: Collecting results for: jaccard (transcriptome-wide)
Wed May 10 09:19:37 2023: Process chunk: 1 for: jaccard

Loading required package: GenomicFeatures
Error in annotatePotentialImpact(result = res_junc_dt, txdb = txdb, fds = fds) : 
  Column 'annotatedJunction' not found in the results table!
Please run 'fds <- annotateIntronReferenceOverlap(fds, txdb)' first and then extract 
the results table using the 'results(fds, ...)' function before calling this function.
Execution halted
```

This rule completed successfully for some different groups previously in the pipeline before the pipeline reached this Group10. These successful groups did not have the same `aberrant splicing pipeline gave 0 results for the "Group" dataset` warning message, leading me to believe that this is the problem that I'm experiencing.  

I will note that the sample size is small for these groups, ~10-15, so I was expecting that there might not be results returned at a significant value, however this possible causal error is preventing the rest of the groups and modules to run. Is there a way to fix this?

**Comment by vyepez88** [comment]
Hi, yes, due to the small number of samples, it could be that there are no significant results. I thought we had checked that case, but maybe with FRASER2's updates, it's lost. We'll have a look.
On the mean time, you can overcome this by adding the `-k` option to your snakemake command which basically tells snakemake to $keep$ on running parallel tasks even if you encounter an error

**Comment by vyepez88** [comment]
thanks to @ischeller, this is now fixed in the dev branch
