### ISSUE TITLE
Information on filtered genes 

### ISSUE THREAD

**Issue by mincej** [gagneurlab/drop#465]
Hello, 
Starting with 58k genes, there is a combined 14k genes left for input to OUTRIDER after filtering. However, some of our candidate genes are not found in that list. I checked with `Output/processed_data/aberrant_expression/v29/outrider/GROUP/total_counts.Rds`, and the candidate gene is expressed in the samples with 30-120 counts, which is above the read count filter parameter set. 

My question is; does DROP document which genes are filtered out from analysis, and what the reason for filtering these genes out of analysis is? Such as "low counts", "low variance", or something to that effect? I've checked the HTML reports and tried searching through `processed_data` and `processed_results`, but I've only been able to find summary information. 

Thanks for any help!

**Comment by vyepez88** [comment]
Hi Joshua, currently we do not output the genes that are not expressed. You could compare the rows between the filtered ods and the total_counts or the ods_unfitted to find out which genes were filtered out. For OUTRIDER, the only metric we use to filter out genes is the fpkm, not the variance. If 5% of the samples have a fpkm lower than 1 for a specific gene, it gets filtered out. The cut-off of 1 can be changed in the config file. 
You could load the ods_unfitted and do the following:
```
ods_unfitted <- readRDS('/path/to/ods_unfitted.Rds')
z <- apply(fpkm(ods_unfitted), 1, quantile, .95)
n1 <- names(z)[z >= 1] # genes that passed cut-off
n2 <- names(z)[z < 1] # genes that did not pass cut-off
```

**Comment by mincej** [comment]
Could I ask for some clarification on that?

“ If 5% of the samples have a fpkm lower than 1 for a specific gene, it gets filtered out.”

This seems opposite to what is in the manual:
“fpkmCutoff | numeric | A positive number indicating the minimum FPKM per gene that 5% of the samples should have. If a gene has less it is filtered out.”

Let’s assume a sample size is 50. Based on the comment explanation, a gene would be filtered out if only 1 sample has an FPKM less than 1. In the manual explanation, 49 samples would need an FPKM less than 1 for the gene to be filtered out. Which is the correct interpretation?

**Comment by vyepez88** [comment]
Sorry for the confusion. The manual explanation is the correct. 
If you have 100 samples, and 94 have a FPKM < 1, and only 6 have a FPKM > 1, then the gene is kept.
