### ISSUE TITLE
AberrantSplicing error of drop1.2.4

### ISSUE THREAD

**Issue by liffcardio** [gagneurlab/drop#467]
Hi, I have run drop1.2.4 successfully before, I want to add some new samples so I build a new environment by drop_1.2.4.ymal which is the method I used before. But this time when I run the aberrantSplicing module, the error came out. Because I need to compare the new data with the old data in the same version of Drop. I cannot use the new version of Drop. Could you help me with this error? I attached the log file and config file below. Thank you very much!
[2023-05-15T060904.530601.snakemake.log](https://github.com/gagneurlab/drop/files/11475604/2023-05-15T060904.530601.snakemake.log)
[config.yaml.txt](https://github.com/gagneurlab/drop/files/11475628/config.yaml.txt)

**Comment by liffcardio** [comment]
I have also tried to copy last time's aberrant splicing script and run it again. But the same error came out as below:
```
Error in rule AberrantSplicing_pipeline_Counting_01_2_countRNA_splitReads_merge_R:
    jobid: 8
    output: /droptest/Output/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-cardio/rawCountsJ.h5, /droptest/Output/processed_data/aberrant_splicing/datasets/cache/raw-local-cardio/gRanges_splitCounts.rds, /droptest/Output/processed_data/aberrant_splicing/datasets/cache/raw-local-cardio/gRanges_NonSplitCounts.rds, /droptest/Output/processed_data/aberrant_splicing/datasets/cache/raw-local-cardio/spliceSites_splitCounts.rds
    log: /droptest/.drop/tmp/AS/cardio/01_2_splitReadsMerge.Rds (check log file(s) for error message)
```
I have also tried drop1.3.3 FRAZER, but the result is too few and it filtered out the gene we want to study in the result of drop1.2.4. I understand the inconvenience of solving the problem of the old version. I would really appreciate it if you would help me with that!

**Comment by ischeller** [comment]
Hi @liffcardio , I'm trying to understand what could be the issue in your case. In your attached log file, there are 115 samples that are being counted. Are those all your new data, or a mix of the data you had before and the new one? 
Unfortunately, we are not seeing the exact error that caused the `AberrantSplicing_pipeline_Counting_01_2_countRNA_splitReads_merge_R` script to fail. Could you use the indicated log for that script to interactively run the script until the error occurs? This would give us a better idea of what might be the problem in your case.  For that, you need to run 
`snakemake <- readRDS('/droptest/.drop/tmp/AS/cardio/01_2_splitReadsMerge.Rds')` 
to load the log and then run each run in the script, starting with the line 
`source(snakemake@params$setup, echo=FALSE)`

Regarding the gene that you want to study being filtered out in drop 1.3.3, did you use the original FRASER version or FRASER 2.0 in that run? In both cases, you can adapt the filtering settings in the config yaml. So if you know how the introns that you want to keep in are expressed, you can set the parameters `minExpressionInOneSample`, `quantileMinExpression` and `quantileForFiltering` to different values than the default. Have a look [in the documentation](https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#aberrant-splicing-dictionary) for a description of those parameters.

**Comment by liffcardio** [comment]
@ischeller Thank you for your reply! the 115 samples are a mix of old and new samples. I ran them in a new environment. 
I tried to run the command you wrote. I am new to bioinformatics. It might be a stupid question.
when I run 
```
snakemake <- readRDS('/droptest/.drop/tmp/AS/cardio/01_2_splitReadsMerge.Rds')
```
it said
```
bash: syntax error near unexpected token '('
```
so I run
```
snakemake <- readRDS\('/droptest/.drop/tmp/AS/cardio/01_2_splitReadsMerge.Rds'\)
```
and it said
```
bash: -: No such file or directory
```
I have checked the file, and it exists.

For drop133
I have tried both the FRASER and FRASER2, and the result I need did not come out only if I change the parameter of padjust to 0.3(FRASER) or 0.15(FRAZER2). I notice that the new padjust is calculated based on genes. I think that might be the problem.

**Comment by ischeller** [comment]
@liffcardio 

> when I run
> 
> ```
> snakemake <- readRDS('/droptest/.drop/tmp/AS/cardio/01_2_splitReadsMerge.Rds')
> ```
> 
> it said
> 
> ```
> bash: syntax error near unexpected token '('
> ```

I meant to run the above command inside R as it is R code, not on the command line (which I suspect you did based on the error). Sorry if my instructions were not clear on this point. 

> For drop133
I have tried both the FRASER and FRASER2, and the result I need did not come out only if I change the parameter of padjust to 0.3(FRASER) or 0.15(FRAZER2). I notice that the new padjust is calculated based on genes. I think that might be the problem.

You still get both an adjusted p-value on the intron level (`results_per_junction.tsv`) and on the gene level (`results.tsv` for the significant results and `results_gene_all.tsv` for all results on the gene level). But the calculation of the gene level p values changed somewhat between version 1.3.3 and 1.2.4, so this could factor into the differences you are seeing. 

However, if you are anyway only interested in one or a few previously known genes, you could try out our new feature in v1.3.3 to limit the FDR correction to a small subset of genes of interest only, see [the documentation here](https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#limiting-fdr-correction-to-subsets-of-genes-of-interest). In case you need more help with this feature, let us know.

Hope some of these suggestions help!

**Comment by liffcardio** [comment]
@ischeller thank you very much! 
I have run the script in the R. Here is the error
```
> spliceSiteCoords <- FRASER:::extractSpliceSiteCoordinates(splitCountRanges, fds)
Error in FRASER:::extractSpliceSiteCoordinates(splitCountRanges, fds):
    unused argument(fds)
```

**Comment by ischeller** [comment]
@liffcardio Is it possible that you manually modified this script or are loading the wrong FRASER version for the DROP version that you use? 
Because this line should just be
`spliceSiteCoords <- FRASER:::extractSpliceSiteCoordinates(splitCountRanges)` in v1.3.3 (FRASER 2.0)(see [here](https://github.com/gagneurlab/drop/blob/master/drop/modules/aberrant-splicing-pipeline/Counting/01_2_countRNA_splitReads_merge.R#L69)). However, it previously was `spliceSiteCoords <- FRASER:::extractSpliceSiteCoordinates(splitCountRanges, fds)` in v1.2.4 and FRASER v1. So if you are loading FRASER 2.0 in your environment, but are running DROP 1.2.4, then you will get this error. So make sure the versions of FRASER and DROP that you are using are matching.

**Comment by liffcardio** [comment]
@ischeller I didn't modify it. I built the environment by drop124.ymal, then run the command:
```
drop init
snakemake -n
```
and then I got this script
[01_2_countRNA_splitReads_merge.R.txt](https://github.com/gagneurlab/drop/files/11541596/01_2_countRNA_splitReads_merge.R.txt)

I run the version of FRASER v1. Here is my config file.

[config.yaml.txt](https://github.com/gagneurlab/drop/files/11541608/config.yaml.txt)

**Comment by ischeller** [comment]
@liffcardio If you are in your environment for DROP 1.2.4, what is the FRASER version when run `sessionInfo()` inside R? It should be < 1.99.0 (something like 1.2.2).

**Comment by liffcardio** [comment]
@ischeller it said FRASER_1.99.3

**Comment by ischeller** [comment]
@liffcardio Okay, this means you indeed got FRASER 2.0 version, so you need to downgrade to a lower version if you want to use DROP 1.2.4, e.g. by running inside R 
`remove.packages("FRASER")` to remove the current version of FRASER and then 
`devtools::install_github("c-mertes/FRASER@1.8.1")` where the number after the @ symbol specifies the release that you want to install. You can see the available releases for FRASER [here](https://github.com/c-mertes/FRASER/releases), anything lower than 1.99.0 is FRASER v1.

**Comment by liffcardio** [comment]
@ischeller It worked! Thank you very much for the detailed and patient response. It means a lot to me!
