### ISSUE TITLE
AberrantSplicing error in DROP version 1.3.3

### ISSUE THREAD

**Issue by jukerbox** [gagneurlab/drop#469]
Hello! 
In our work, we tried to use the aberrantSplicing module with command `snakemake aberrantSplicing --cores 20`, but when the Pipeline ended, the error "Error in rule AberrantSplicing_pipeline_FRASER_08_extract_results_FraseR_R:" appeared.
Also, the following error is not reflected in the log file:
[1] "Results per gene extracted".
Loading required package: GenomicFeatures
Error in annotatePotentialImpact(result = res_junc_dt, txdb = txdb, fds = fds) :
  Column 'annotatedJunction' not found in the results table!
Please run 'fds <- annotateIntronReferenceOverlap(fds, txdb)' first and then extract
the results table using the 'results(fds, ...)' function before calling this function.
 
Can you help to understand the error? Thank you!
Full logs and configuration file attached.
[2023-05-16T112152.583720.snakemake.log](https://github.com/gagneurlab/drop/files/11494061/2023-05-16T112152.583720.snakemake.log)
[config.yaml.txt](https://github.com/gagneurlab/drop/files/11494066/config.yaml.txt)

**Comment by vyepez88** [comment]
Hi, we'll have a look. How many samples do you have? It could be that you did not get any significant results. Also, which drop version are you using?

**Comment by jukerbox** [comment]
> How many samples do you have? Also, which drop version are you using?

In this run we have 10 samples.
Ver. 1.3.3

**Comment by ischeller** [comment]
Hi @jukerbox , can you try to see if installing DROP from the dev branch fixes this issue for you? I think it might be related to an issue we fixed there that occurs in case there are no significant results. 
Please let us know if that is enough to fix your problem!

**Comment by jukerbox** [comment]
@ischeller in which folder should I install the dev branch version?

**Comment by ischeller** [comment]
Hi  @jukerbox , you can follow our instructions [here](https://gagneurlab-drop.readthedocs.io/en/latest/installation.html#other-drop-versions) for how to install DROP from the dev branch. Hope this helps.

**Comment by ischeller** [comment]
Hi @jukerbox , do you have any updates on this?
