### ISSUE TITLE
Different STRAND in the same analysis

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#47]
Can samples with different STRAND values be used together in the same analysis?

**Comment by vyepez88** [comment]
If the values are 'yes' or 'reverse' then yes. If some samples were sequenced not strand-specifically, then no.

**Comment by gevro** [comment]
The problem is that GTEX control samples are STRAND = no. Does that mean I cannot use them together with my samples that are STRAND = yes?

**Comment by gevro** [comment]
And if the above is not possible, do you have any suggestions for what to do?

**Comment by gevro** [comment]
And just to clarify - what I mean is not whether it is recommended to combine stranded with unstranded samples -- I know that is not recommended.
The question is if the pipeline will run at all when combining samples with different STRAND annotations.

**Comment by mumichae** [comment]
Yes, you can run the pipeline with different strand options, as they are defined for each sample individually. This might lead to batch effects that might or might not be corrected well by the autoencoder. You could either count your samples in a strand unspecific mode or count them strand specifically and evaluate based on the heatmap in the outrider summary, how strong the batch effect is. We would recommend the former, as it minimises known effects.
