### ISSUE TITLE
Error in model.matrix.default(Terms, m) : variable 1 has no levels

### ISSUE THREAD

**Issue by ChiaraF32** [gagneurlab/drop#471]
Hi, 

I am running DROP on a collection of 9 local RNAseq samples, supplemented with GTEx count data from 492 samples.

I am having an issue with rule `AberrantExpression_pipeline_Counting_Summary_R:` 
```
Error in model.matrix.default(Terms, m) : variable 1 has no levels
Calls: render ... lda.formula -> model.matrix -> model.matrix.default
```

The same issue has been mentioned in this [thread](https://github.com/gagneurlab/drop/issues/440).

My `DROP` version is `1.3.3`, which has the fix provided in the original [thread](https://github.com/gagneurlab/drop/issues/440).

I have attached the `config.yaml` file as well as the `sampleAnnotation.tsv` and `log` file

[2_FibroMay2023.log](https://github.com/gagneurlab/drop/files/11539938/2_FibroMay2023.log)
[config.yaml.txt](https://github.com/gagneurlab/drop/files/11539937/config.yaml.txt)
[sampleAnnotation.txt](https://github.com/gagneurlab/drop/files/11539958/sampleAnnotation.txt)

**Comment by vyepez88** [comment]
Hi, can you load your count matrix and check whether there are samples with no counts? 
It should be in `root/processed_data/aberrant_expression/{gene_annot}/outrider/{DROP_group}/total_counts.Rds`

**Comment by vyepez88** [comment]
otherwise, it might be something related to the Sex matching. Can you try either filling that column for your samples or removing it altogether?

**Comment by ChiaraF32** [comment]
Hi,

I checked and there were no samples without counts. I then tried again after removing the Sex column.

The pipeline ran to completion without issue.

Thanks
