### ISSUE TITLE
Drop 1.3.3 error in AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R

### ISSUE THREAD

**Issue by muhligs** [gagneurlab/drop#473]
Hi, using drop 1.3.3 I get the following error in a run of AE, AS and MAE with one sample and external counts: 

```
Error in rule AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R:
Error: BiocParallel errors
  1 remote errors, element index: 1
  8 unevaluated and other errors
  first remote error:
Error in sample.int(length(x), size, replace, prob): invalid first argument

```

Manual inspection pinpoints the error to this part in '04_fit_hyperparameters_FraserR.R'
```
for(type in psiTypes){  #  "psi5"  "psi3"  "theta" # psi5 and psi3 fails when  optimHyperParams calls injectOutliers. 'theta' runs through.
    message(date(), ": ", type)
    fds <- optimHyperParams(fds, type=type, 
                            implementation=implementation,
                            q_param=pars_q,
                            plot = FALSE)
    fds <- saveFraserDataSet(fds)
}

```

When optimHyperParams is called, the error occurs in :
`fds_copy <- injectOutliers(fds_copy, type = type, freq = injectFreq, ...)`

Inspecting the fds object with `counts() ` gives:
```
counts(fds, type = "psi5", side = "other")  # <112 x 49> matrix of class DelayedMatrix and type "integer":
counts(fds, type = "psi3", side = "other")  # <112 x 49> matrix of class DelayedMatrix and type "integer":
counts(fds, type = "theta", side = "other") # normal matrix / array, 134 x 49

```
The type = "theta" in the loop above runs through without error, but psi3 and psi5 produce the error. 
Adding 'delayed = TRUE' in the call to `optimHyperParams()` does not solve the problem. 

Hope you can help. I am just 8 rules from my first succesful run now :)

Best 

Morten

**Comment by vyepez88** [comment]
Hi, can you double check whether your sample and the external ones have the same genome build and annotation? The usual number of exons are in the 100,000. In your case, there are only 112 which reflects that there is something wrong with the number of counted exons.

**Comment by muhligs** [comment]
Hi, yes, both genome and geneAnnotation in the config point to the same files as for the external counts run.
These are the number of entries in the external tables:
```
DESCRIPTION.txt    k_theta_counts.tsv.gz  n_theta_counts.tsv.gz
geneCounts.tsv.gz  n_psi3_counts.tsv.gz   sampleAnnotation.tsv
k_j_counts.tsv.gz  n_psi5_counts.tsv.gz
[mmn@fe-open-01 group1--hg38--v43]$ zcat geneCounts.tsv.gz | wc -l
62704
[mmn@fe-open-01 group1--hg38--v43]$ zcat k_theta_counts.tsv.gz | wc -l
350
[mmn@fe-open-01 group1--hg38--v43]$ zcat n_theta_counts.tsv.gz | wc -l
350
[mmn@fe-open-01 group1--hg38--v43]$ zcat n_psi3_counts.tsv.gz | wc -l
57171
[mmn@fe-open-01 group1--hg38--v43]$ zcat n_psi5_counts.tsv.gz | wc -l
57171
[mmn@fe-open-01 group1--hg38--v43]$ zcat k_j_counts.tsv.gz | wc -l
57171
```

**Comment by vyepez88** [comment]
which external counts are those? are you sure your BAM file is the same genome build? 
did you try running DROP only with local files?

**Comment by muhligs** [comment]
I can see that the gtex external count set has many more features. I have used the gencode.v43.basic.annotation.gtf

**Comment by vyepez88** [comment]
usually the external counts that we share are gencode 34

**Comment by muhligs** [comment]
These are our own external counts from 48 blood samples. The pipeline was restarted a few times due to slurm resource problems. The problem is always AS module counting of split reads, which sometimes takes 3-4 days per sample.

**Comment by muhligs** [comment]
Also, the externals wer made with a v1.2 drop pipeline. could that be a problem?

**Comment by muhligs** [comment]
I could use the gencode counts, which are v.29, but the problem is that they are not paired, whereas my sample(s) are. Can you point to any paired external counts?

**Comment by muhligs** [comment]
> which external counts are those? are you sure your BAM file is the same genome build? did you try running DROP only with local files?

Yes, it is the same hg38 ref for all the bams.

**Comment by vyepez88** [comment]
if it's your own counts, it's fine, you don't need to use v29, you can use whichever gencode version. I see that you have very few splice sites (350) and junctions (57171). These values should be way higher, on another dataset that I have, the splice sites are 288K and the junctions 280K. I would rerun the external counts again, there seems to be a problem there

**Comment by muhligs** [comment]
Hi again, 
I have now rerun the external counts with:
snakemake exportCounts  
--set-threads AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R=10 
--set-resources AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:time=168:00:00 
--cluster "sbatch -N1 -n 10 --mem 250Gb --account myaccount --time=168:00:00" -j 50 -k

Everything went through without errors using v1.3.3

I then ran AE, AS and MAE as above with one sample and these external count with:
snakemake --set-threads AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R=10
--set-resources AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:time=168:00:00 
--cluster "sbatch -N1 -n 10 --mem 250Gb --account myaccount --time=168:00:00" -j 50 -k

I unfortunately got the same error in AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R as above.

I also have approximately the same number of lines in the count files, i.e. only 330 in k_theta_counts and n_theta_counts and ~60,000 in the other files. 

What puzzles me is that these files seems to be in a format similar to the GteX external count files, only smaller, so I would think that they should be processed without errors. 

I am thinking about the following as a way forward: 
- Run my sample with GTeX external counts, although those are single end files and my samples are paired end. 
  Then running it with single end in the sample sheet. 
- Run my sample with GTeX external counts, and stating paired end in the sample file, just to make a comparative run to see if it survives the faulty rule. 

Can you think of anything that could be a problem with my setup. Everything was run with the same hg38 genome and a gencode.v43.basig.annotation.gtf  ?

Thanks,
Morten

**Comment by ischeller** [comment]
Hi Morten, 
can you check whether the number of introns / splice sites in the fds object of the GTEx samples from which you create the external counts is in the expected range (~200k) or already low in the fds object itself before exporting the counts?

**Comment by muhligs** [comment]
Hi, 
Can you guide me in exactly which slots in the fds this information is?
e.g.:
dim(fds@assays@data@listData$rawCountsJ)
[1] 111  51
It seems that all matrices under fds@assays@data@listData have dimension 111 x 51

Thanks,
 Morten

**Comment by ischeller** [comment]
Hi, 
you can find the information of number of introns with `dim(fds)` (this should be the 111 x 51 you got) and for the number of splice sites with `dim(nonSplicedReads(fds))`. 
So if your fds object of the GTEx samples has only 111 introns, then the problem seems to be here as you should have a lot more. Can you share the sample annotation file and config.yaml that you used for running the GTEx samples?

**Comment by muhligs** [comment]
Hi, 
Just a small correction, It is not GTEx samples, but our own samples from blood. 
Here the config.yaml file and the sample sheet. 
The GTF file is gencode v. 43 basic annotations.
[config.yaml.txt](https://github.com/gagneurlab/drop/files/11866153/config.yaml.txt)
[sample_annotation.tsv.txt](https://github.com/gagneurlab/drop/files/11866173/sample_annotation.tsv.txt)

Thanks for looking into this. 

Morten

**Comment by ischeller** [comment]
Hi, 
The sample annotation and config.yaml seem fine to me. Just to be sure, do you expect your bam files to contain transcriptome-wide expression / splicing information? Or was there some specific assay used?

Another thing you could check is whether this might be related to the filtering settings. Can you load the raw fds file before filtering and check the dimensions of it to see if you might need to adjust the filtering settings for our local control samples? You should find that file in `.../processed_data/aberrant_splicing/datasets/savedObjects/raw-group1/fds-object.RDS`. 

Hope some of this will help to locate the issue.

**Comment by muhligs** [comment]
Hi, 
They should contain transcriptome wide expression. Here is a IGV snap of GAPDH:
![image](https://github.com/gagneurlab/drop/assets/6706866/91365de5-7f53-497c-80ea-da83caf91882)

The fds has dim(fds) = NULL. 
printing gives:
```
print(fds)
-------------------- Sample data table -----------------
# A tibble: 50 × 16
   sampleID           STRAND PAIRED_END bamFile RNA_BAM_FILE DNA_VCF_FILE DNA_ID
   <chr>              <chr>  <lgl>      <chr>   <chr>        <lgl>        <lgl> 
 1 Diag_RNAseqKtrl_26 yes    TRUE       /home/… /home/mmn/d… NA           NA    
 2 Diag_RNAseqKtrl_27 yes    TRUE       /home/… /home/mmn/d… NA           NA    
 3 Diag_RNAseqKtrl_28 yes    TRUE       /home/… /home/mmn/d… NA           NA    
 4 Diag_RNAseqKtrl_29 yes    TRUE       /home/… /home/mmn/d… NA           NA    
 5 Diag_RNAseqKtrl_30 yes    TRUE       /home/… /home/mmn/d… NA           NA    
 6 Diag_RNAseqKtrl_31 yes    TRUE       /home/… /home/mmn/d… NA           NA    
 7 Diag_RNAseqKtrl_32 yes    TRUE       /home/… /home/mmn/d… NA           NA    
 8 Diag_RNAseqKtrl_33 yes    TRUE       /home/… /home/mmn/d… NA           NA    
 9 Diag_RNAseqKtrl_34 yes    TRUE       /home/… /home/mmn/d… NA           NA    
10 Diag_RNAseqKtrl_35 yes    TRUE       /home/… /home/mmn/d… NA           NA    
# ℹ 40 more rows
# ℹ 9 more variables: DROP_GROUP <chr>, COUNT_MODE <chr>, COUNT_OVERLAPS <lgl>,
#   HPO_TERMS <lgl>, GENE_COUNTS_FILE <lgl>, GENE_ANNOTATION <lgl>,
#   GENOME <chr>, SPLICE_COUNTS_DIR <lgl>, pairedEnd <lgl>
# ℹ Use `print(n = ...)` to see more rows

Number of samples:      50 
Number of junctions:    5180272 
Number of splice sites: 223152 
assays(15): rawCountsJ psi5 ... rawOtherCounts_theta delta_theta

----------------------- Settings -----------------------
Analysis name:               raw-local-group1 
Analysis is strand specific: yes 
Working directory:           '/faststorage/project/drop_rnaseq/sandbox/ec_mg/Output/processed_data/aberrant_splicing/datasets/' 

-------------------- BAM parameters --------------------
class: ScanBamParam
bamFlag (NA unless specified):
bamSimpleCigar: FALSE
bamReverseComplement: FALSE
bamTag:  
bamTagFilter:
bamWhich: 0 ranges
bamWhat:
bamMapqFilter: 0

Thanks for looking into this. It is really much appreciated.
```

**Comment by ischeller** [comment]
Okay, in the print information you can see that the raw fds object has ~5 million junctions, which is in the expected range, so until this step, it looks fine (not sure why dim(fds) returns NULL in your case, as it's clearly not null, could be related to other packages you have loaded in the interactive sesion). 
You indeed seem to loose most junctions during filtering. Can you provide the output of the functions `plotFilterExpression(fds_raw)` and `plotFilterVariability(fds_raw)` which visualize the distribution of counts and between sample variation for both filtered and not-filtered junctions? This would help to identify which paramter might need adjusting in your case.

**Comment by muhligs** [comment]
Thanks, 
I did:

fds_raw <- filterExpression(fds)
Keeping 117983 junctions out of 5180272. This is 2.28% of the junctions
fds_var <- filterVariability(fds)
Keeping 5180272 junctions out of 5180272. This is 100% of the junctions

plotFilterExpression(fds_raw)
![pfe](https://github.com/gagneurlab/drop/assets/6706866/74870dca-e2fb-434a-ba42-aac5826829b3)

plotFilterVariability(fds_var)
![pfv](https://github.com/gagneurlab/drop/assets/6706866/96697265-053a-4f1a-a9d7-31da81164020)

Thanks

**Comment by ischeller** [comment]
Okay. So when you do the filtering as here with the default parameters of FRASER, you do obtain a normal amount of introns after filtering, this looks fine. The raw fds object saved by DROP should already contain the information whether an intron passed the filter or not. So what do you get if you directly plot from the saved object, i.e. 
`fds_raw <- loadFraserDataset("../path/to/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-group1/fds-object.RDS")`

`plotFilterExpression(fds_raw)`

`plotFilterVariability(fds_raw)` ?

**Comment by muhligs** [comment]
I get two errors:

```
fds_raw <- loadFraserDataSet("/faststorage/project/drop_rnaseq/sandbox/ec_mg/Output/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-group1/fds-object.RDS")
Error in loadFraserDataSet("/faststorage/project/drop_rnaseq/sandbox/ec_mg/Output/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-group1/fds-object.RDS") : 
  The given dir does not exists: /faststorage/project/drop_rnaseq/sandbox/ec_mg/Output/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-group1/fds-object.RDS
> fds_raw <- loadFraserDataSet("/faststorage/project/drop_rnaseq/sandbox/ec_mg/Output/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-group1")
Error in loadFraserDataSet("/faststorage/project/drop_rnaseq/sandbox/ec_mg/Output/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-group1") : 
  The analysis name does not exists: Data Analysis

```

Before I loaded the fds with readRDS() and did the `filterExpression(fds) `because `plotFilterExpression(fds)` gave:
```
Error in plotFilterExpression(fds) : 
  Please calculate the expression filter values first with the filterExpression function.

```

**Comment by ischeller** [comment]
I strongly recommend to always use the `loadFraserDataSet` function to load the fds object. If you only use readRDS, not all assays will get loaded properly, as we use delayed matrices in FRASER to save memory which don't get saved in the .RDS file itself. 
I made a small error in my example code, sorry about that. It should be 
`fds_raw <- loadFraserDataset(file="../path/to/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-group1/fds-object.RDS")`
as the default of the function is load with a given working directory name and group name, and not from the fds-object.RDS file alone.

**Comment by muhligs** [comment]
Ah, much better :)

now, dim(fds_raw) gives
[1] 5180272      50

but I still need the filterExpression() run:

plotFilterExpression(fds_raw)
Error in plotFilterExpression(fds_raw) : 
  Please calculate the expression filter values first with the filterExpression function.
> plotFilterExpression(filterExpression(fds_raw))
Wed Jun 28 16:41:18 2023: Filtering out introns with low read support ...
Keeping 117983 junctions out of 5180272. This is 2.28% of the junctions
Warning messages:
1: In applyExpressionFilters_jaccard(object, minExpressionInOneSample,  :
  Filtering has already been applied previously. Introns that were already filtered out but should be kept now cannot be restored.
2: Transformation introduced infinite values in continuous y-axis 
3: Removed 9 rows containing missing values (`geom_bar()`). 

And the plot is identical to the previoius one.

**Comment by ischeller** [comment]
Did you run the aberrant_splicing pipeline on those samples only to export the counts? Then it would make sense that the filtering has not yet been calculated, as the counts get exported from the raw fds. I might have been to quick earlier to think the issue could be related to the filtering, as this part indeed does not get run when exporting counts. 
However, this indicates that the issue is in the script that does the exporting of counts, not the counting of FRASER itself, as the raw fds object has expected dimensions. One thing that could go wrong there is that we filter to known introns from the provided annotation / gtf file before exporting. Could there be a genome version mismatch between your bam files and the gtf file, i.e. are they both hg38 in your case?

**Comment by muhligs** [comment]
Correct, I ran exportCounts. 
Both gtf and the genome are hg38. 

Another thing is that (some of) these samples have very high read counts in ribosomal RNA sites. Sometimes a depth as high as 2.5 mill. reads. This has made the count splicereads rule take up to three days on 10-20 cores pr. sample. 
In the mean time (since this question was raised) I have thus filtered out the ribosomal regions, sometimes reducing the size of the bam by 50%. I am right now running on these filtered samples, which now run through the splice rule in minutes. I did one run were I set stranded = no, although the protocol is stranded. I did this because I thought setting stranded to yes could be the problem. Now, these count matrices have many more entries for the thetas. I am currently re-running on the filtered bams setting stranded back to 'yes', and I hope that the bam filtering may have solved the problem. I will let you know by tomorrow, although why it should solve the problem beats me. 
Thanks, 
Morten

**Comment by ischeller** [comment]
Okay, interesting. In case it should not work with stranded = 'yes' , can you check with the description in Box 3 of the [DROP manuscript](https://rdcu.be/cdMmF) that the value you put in the STRAND column in the sample annotation should indeed be 'yes' and not 'reverse', given the protocol used for sequencing your samples?

**Comment by muhligs** [comment]
Thanks for pointing that out. I will have to check up on the lab people. 

The stranded run takes considerably longer to count the spliced reads, an hour pr. sample vs. minutes for the non-stranded setup. 

The count k/n_theta_counts.tsv matrices for non-stranded now have 235027 entries (rather than 330). 
The gene count matrices show considerable higher counts for non-stranded than for stranded, so this might actually indicate that i need 'reverse' rather than 'yes'.

**Comment by muhligs** [comment]
Hi Ines, 

This was indeed the culprit. Running with 'reverse' strand succeeded in making external count data for our 50 local blood samples as well as using them on a following analysis with AE, AS and MAE for a single patient sample. 
This closes this issue as well as my long struggle to implement the pipeline in our setting. 
Thank you for your help!! 
Morten

**Comment by gulipeng17** [comment]
Hi,Sir:
When I using FRASER to analysis the demo data,it comes the follow error:
Error in rule AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R:
Error in .nextMethod(x = x, withDimnames = withDimnames, value = value) : 
  current and replacement dimnames() differ
Calls: optimHyperParams ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>

What should I do next?
FRASER version is 1.99.3

**Comment by ischeller** [comment]
Hi @gulipeng17 ,
can you provide more information about how you installed DROP and FRASER?
