### ISSUE TITLE
Error in rule MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R:

### ISSUE THREAD

**Issue by dfermin** [gagneurlab/drop#478]
Hello.

The DROP pipeline is working as expected until rule MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R.

There I encounter this error:
```
Error in reducer$value.cache[[as.character(idx)]] <- values :
  wrong args for environment subassignment
Calls: bplapply ... .bploop_impl -> .collect_result -> .reducer_add -> .reducer_add
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
Execution halted
```

Any suggestions on how to fix it?

Thanks

**Comment by ischeller** [comment]
Hi @dfermin , can you provide more information about your setup, e.g. how many cores and how much memory are you using? And how many samples? Did you try if it runs through if you use just 1 core?

**Comment by dfermin** [comment]
Hi @ischeller
Sorry for the late reply, I was able to run the Snakefile with just 1 core and it does finish but takes about 8 days. 
I am processing 400 samples.
I am running the data on our linux server: 88 cores and 512GB memory

**Comment by ischeller** [comment]
Hi @dfermin , 
if it works with 1 core, the error  you previously got does not seem to be related to the DROP code itself, but could have been related to an out-of-memory error on your server (although 512Gb should be plenty). How many cores did you use in that run, all available 88? If so, I would suggest to try with 10-20 cores (or half the ones you used before), and see if this fixes this issue for you.

**Comment by vyepez88** [comment]
Hi @dfermin, how many DNA and RNA samples do you have?
