### ISSUE TITLE
COUNT_MODE and COUNT_OVERLAPS - explanation

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#48]
Can you please further clarify the meanings of these annotation columns?

COUNT_MODE: either “Union”, “IntersectionStrict” or “IntersectionNotEmpty”.

COUNT_OVERLAPS: either TRUE or FALSE, depending on whether reads overlapping different regions are allowed and counted.

**Comment by vyepez88** [comment]
Please refer to the HT-Seq manual where it explains in detail: https://htseq.readthedocs.io/en/release_0.11.1/count.html
We recommend setting the count mode to IntersectionStrict, and count overlaps to TRUE, so as to assign counts to more genes.
