### ISSUE TITLE
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:

### ISSUE THREAD

**Issue by dissakova** [gagneurlab/drop#480]
I am trying to run FRASER 1.0 on a linux cluster and it crashes. Sometimes it outputs no error message, and sometimes it returns the error:

Error in reducer$value.cache[[as.character(idx)]] <- values :
Wrong args for environment sub assignment

Command: 
snakelike aberrantSplicing --cores 10
(100GB memory)

Config:

aberrantExpression:
  run: false
aberrantSplicing:
  run: true
  padjCutoff: 0.1
  FRASER_version: FRASER
exportCounts:
  excludeGroups: null
  geneAnnotations:
    - ensembl.v94
geneAnnotation:
  ensembl.v94: /mnt/isilon/bhoj_lab/projects/drop-synthetic/drop-pipeline/resources/ensembl.v94.gtf
genome: /mnt/isilon/bhoj_lab/shared/genomes/ensembl.94.Homo_sapiens.GRCh38/ensembl.94.Homo_sapiens.GRCh38.dna.primary_assembly.fa
genomeAssembly: GRCh38
hpoFile: null
htmlOutputPath: /mnt/isilon/bhoj_lab/projects/drop-synthetic/drop-pipeline/results/html
indexWithFolderName: true
mae:
  run: false
projectTitle: drop-synthetic-denovoAltEnd_0.1_6M48D
random_seed: true
root: /mnt/isilon/bhoj_lab/projects/drop-synthetic/drop-pipeline/results
sampleAnnotation: /mnt/isilon/bhoj_lab/projects/drop-synthetic/drop-pipeline/resources/denovoAltEnd_0.1_6M48D_config.tsv
tools:
  bcftoolsCmd: bcftools
  gatkCmd: gatk
  samtoolsCmd: samtools

I've tried running the same with just 1 core but still get the same result. I've looked through past similar issues and verified that the cluster is connected to the internet. Is 100GB enough, as I saw other users got a similar error and the suggestion was more memory/less cores? I am also able to run the demo project with no problems. 
Appreciate your help. Thank you!

[2023-06-30T002747.345861.snakemake.log](https://github.com/gagneurlab/drop/files/11923529/2023-06-30T002747.345861.snakemake.log)

**Comment by vyepez88** [comment]
Hi, hard to say why the counting of sample GTEX-14E6D-2926-SM-664OP.bam failed why many others succeeded. Could be a memory issue, can you try simply rerunning the pipeline with the `--rerun-triggers mtime` parameter?

**Comment by dissakova** [comment]
Doing so results in the following error (apologies, I cannot easily copy-paste from this cluster):

<img width="1470" alt="Screenshot 2023-07-03 at 11 49 02 AM" src="https://github.com/gagneurlab/drop/assets/48687336/3882ee12-7e7a-404e-86b2-6ded65fa806d">

**Comment by vyepez88** [comment]
can you try to run:
```
snakemake --unlock --cores 1
snakemake -n aberrantSplicing
```

**Comment by dissakova** [comment]
Both commands cause the same error above.

**Comment by dissakova** [comment]
> Hi, hard to say why the counting of sample GTEX-14E6D-2926-SM-664OP.bam failed why many others succeeded. Could be a memory issue, can you try simply rerunning the pipeline with the `--rerun-triggers mtime` parameter?

Also I should note that it's not consistently that file - it fails with the same error, but with different file names. So I don't think this is a file-specific issue.

**Comment by vyepez88** [comment]
can you try to run the demo again? it's as if there is something wrong with the installation.
Regarding the sample, it could be that it's different samples failing the counting, but some of them could have worked. I also saw that 8 files do not exist and that the RNA_IDs end with `.bam`. Could you try fixing that?

**Comment by dissakova** [comment]
It does seem to be something wrong with the installation... I'm getting the same error when running the demo project. I reinstalled the DROP pipeline, and I'm still getting the same error. Do you have any suggestions?

**Comment by dissakova** [comment]
Could you suggest how much memory FRASER normally requires? I'm trying to run ~700 files, made up of 16 patient files and the rest controls. Could it be that I don't have enough memory?

**Comment by dissakova** [comment]
Update: I've fixed the error with the installation. Rerunning it with --rerun-triggers mtime produces the same error as the original issue submission. 

I've also changed the RNA_IDs so they do not end in ".bam". I also checked that all of the files in the sample annotation exist, so I'm not sure what the "8 files missing in samples annotation" error might be referring to, or how to fix this. 

Same with

snakemake --unlock --cores 1
snakemake -n aberrantSplicing

This all produces the same behavior. 
Thank you!

**Comment by vyepez88** [comment]
Hi, regarding the memory, a cohort of ~700 files shouldn't need more than 400 Gb. It also depends how many cores you provide. The counting step uses 3 cores per sample. So if you provide 90 cores, 30 samples will be counted in parallel. I can assume that you by-passed the original error here, right?

**Comment by dissakova** [comment]
Yes, I fixed the original error here - ended up being some file errors not related to the pipeline. I essentially re-mapped (using STAR) a few files that had not been mapped properly.
