### ISSUE TITLE
No paired-end reads were detected in paired-end read library

### ISSUE THREAD

**Issue by dissakova** [gagneurlab/drop#482]
Hello, 
I fixed the earlier errors and have run the pipeline (aberrantSplicing, from FRASER2) nearly to completion, but about 50% through the run it crashes with: 

ERROR: No paired-end reads were detected in paired-end read library: [path to sample]
No counts were generated. 

Warning message:
In dir.create(dir, recursive=TRUE):
'[path]/results/processed_data/aberrant_splicing/datasets/cache/nonSplicedCounts/raw-local-fraser' already exists

Execution halted

This repeats for several other files. 

Full record of the run is attached, as is my config file and my sample annotation (converted to txt for ease of GitHub upload)

[config.txt](https://github.com/gagneurlab/drop/files/11973492/config.txt)

[slurm-1866144.txt](https://github.com/gagneurlab/drop/files/11973490/slurm-1866144.txt)

[synthetic_data_config_fraser_CXZKN_test.txt](https://github.com/gagneurlab/drop/files/11973501/synthetic_data_config_fraser_CXZKN_test.txt)

Thank you!

**Comment by vyepez88** [comment]
Hi Dina! 
The way we perform the counting in the AS module is:
* we count all the split reads per sample, irrespective of an annotation file
* we merge them per cohort (drop group) and generate the splice sites
* on each splice site, we count the non-split reads
From what I can see, in your case, the 2 first steps were completed, but the non-split reads did not work. Could it be that your data is not paired-end? For that step we use the featureCounts function from Rsubread. I found a similar error message from yours here: https://support.bioconductor.org/p/9141314/

**Comment by ischeller** [comment]
Hi Dina, 
are you sure your bam files indeed contain paired-end reads as specified in your sample annotation? The error seems to indicate that no paired-end reads are found in the featureCounts call that Vicente described.

**Comment by dissakova** [comment]
Thanks for the response! 
It's synthetic data, created as forward and reverse .fq files, then mapped to one file using STAR - so yes, definitely paired-end reads, but I'll check if something went wrong during this process.

**Comment by dissakova** [comment]
I've checked my data and it seems some are paired-end, and some are single-end sequencing. Is it possible to compare the two, or do all samples need to be one or the other? Will this cause any caveats I should be aware of?
Thank you @vyepez88 and @ischeller !

**Comment by ischeller** [comment]
Hi @dissakova , 
great that you found the problem! 
We don't have experience ourselves for combining a dataset with paired-end and single-end sequencing data, so we can't give advice regarding this. The count produced by FRASER is a fragment count for paired-end data and read count for single-end data, so it's possible that it has an effect on the analysis. Consider splitting your analysis into one for the paired-end and one for the single-end reads if possible.

**Comment by vyepez88** [comment]
and if you want to keep the samples together, simply specifying T/F in PAIRED_END column accordingly for each sample should make the pipeline run

**Comment by dissakova** [comment]
@vyepez88 Thank you! I ended up finding paired-end versions of the single-sequenced samples, and the pipeline works now. Thank you for your help!

**Comment by vyepez88** [comment]
great to hear! for an overview of the samples, you could execute `snakemake sampleAnnotation`. Good luck!

**Comment by dissakova** [comment]
@vyepez88 Hello Vicente, I actually realized the pipeline wasn't fully completing but instead failing at 99% completion, but still outputting a results file. I've opened a new issue as this seems unrelated to the questions above.
