### ISSUE TITLE
Error in rule AberrantSplicing_pipeline_FRASER_Summary_R:

### ISSUE THREAD

**Issue by dissakova** [gagneurlab/drop#484]
Hello, 
I thought my pipeline was working, but I've noticed  I'm getting to 99% completion with the pipeline and then getting this error: 

Quitting from lines 80-106 [unnamed-chunk-5] (/tmp/RtmplmDvBZ/file32bd7b7a7e77/Summary.spin.Rmd)
Error in 'hclust():'
! NA/NaN/Inf in foreign function call (arg 10)
Backtrace:
1. OUTRIDER: plotCountCorHeatmap(...)
2.FRASER::plotCountCorHeatmap(...)
3. FRASER (local) .local(object, ...)
4. pheatmap::pheatmap(...)
5. pheatmap:::cluster_mat(...)
6. stats:hclust(method=method)
Execution halted

My questions are - 
1. How can I solve this problem? 
2. Which files does it affect - is this affecting all the results files? I have results_gene_all.tsv result files that seem fine and that I'd like to use in downstream purposes - is this a later step than that or will this affect those results? 
3. Ideally, can I fix this issue without re-running the entire analysis, which in my case took ~10 hours? 

Log attached: 

[2023-07-09T180743.376354.snakemake.log](https://github.com/gagneurlab/drop/files/12001993/2023-07-09T180743.376354.snakemake.log)

Thank you!

**Comment by vyepez88** [comment]
Hi,
Some other user reported a similar problem. Maybe there was an update to the heatmap function we use in DROP. We are investigating it. You can, however, bypass it.
1. In your project directory, go to: `Scripts/aberrant-splicing-pipeline/FRASER/Summary.R`. Comment out the for loop that starts in line 72 and ends in line 93, which is the one that plots the heatmaps. 
2. It doesn't affect at all your results tables. It only affects the last html report.
3. Simply rerun the aberrantSplicing rule with the `--rerun-triggers mtime` parameter

**Comment by dissakova** [comment]
Thanks @vyepez88 !

**Comment by canankolakoglu** [comment]
Hi!
I have similiar issue and commenting out the for loop worked.
Thank you @vyepez88
