### ISSUE TITLE
Error in bamFile(fds[, samples(fds) == sampleID])[[1]]

### ISSUE THREAD

**Issue by dissakova** [gagneurlab/drop#485]
Hello, 
With most files the pipeline works fine, but I've encountered an issue with a couple that I've set up where the group of samples is one patient sample + all controls. I was wondering if you could help me figure out what's wrong with my setup here. 

The error that comes up is: 
Error in bamFile(fds[, samples(fds) == sampleID])[[1]]:
subscript out of bounds
calls: CountNonSplitReads
Execution Halted. 

I've attached one of the tsv files causing this error (converted to csv for upload).

Thank you!

[simulated_reads_GTEX-1KWVE-2226-SM-CXZKN-denovoAltStart_psi0.1Aligned_sorted.bam.csv](https://github.com/gagneurlab/drop/files/12129435/simulated_reads_GTEX-1KWVE-2226-SM-CXZKN-denovoAltStart_psi0.1Aligned_sorted.bam.csv)

**Comment by ischeller** [comment]
Hi  @dissakova , 
which version of DROP are you using?
