### ISSUE TITLE
drop demo not working: Error in find_NCBI_assembly_ftp_dir

### ISSUE THREAD

**Issue by SamuelNicaise** [gagneurlab/drop#490]
Hi all,

I have been trying to get the demo running. It fails with the following error: 

```
Error in find_NCBI_assembly_ftp_dir(assembly_accession, assembly_name = assembly_name) :
  unable to find FTP dir for assembly GCF_000001405.25 in
  https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/
Calls: countSplitReads ... .form_assembly_report_url -> find_NCBI_assembly_ftp_dir
Execution halted
Fri Aug 25 15:02:03 2023: Count split reads for sample: HG00103
[Fri Aug 25 15:02:03 2023]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 59
    input: /drop/Output/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/fds.done, Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
    output: /drop/Output/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/sample_tmp/splitCounts/sample_HG00096.done
    log: /drop/.drop/tmp/AS/fraser/splitReads/HG00096.Rds (check log file(s) for error details)

RuleException:
CalledProcessError in file /tmp/tmpve6itp4h, line 130:
Command 'set -euo pipefail;  Rscript --vanilla /drop/.snakemake/scripts/tmprr5l1a5w.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/tmp/tmpve6itp4h", line 130, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/opt/conda/envs/drop_env/lib/python3.11/concurrent/futures/thread.py", line 58, in run
```

Here is my completely reproducible process:

docker pull condaforge/mambaforge:latest
docker run -ti condaforge/mambaforge bash
#in container
mamba init 
source /root/.bashrc
apt-get update
apt-get install zip
mamba create -n drop_env -c conda-forge -c bioconda drop --override-channels
conda activate drop_env
drop demo
snakemake --cores 30

The container has internet access. Can you please help me to get drop up and running ? 

The error seems to be coming from the GenomeInfoDb library.
Best regards,

**Comment by AliSaadatV** [comment]
Hi all

Thanks for providing this great tool. I also get the same error while running the demo. I would appreciate your help to resolve this issue.

Best regards
Ali

**Comment by vyepez88** [comment]
Hi @SamuelNicaise, 
Is the chr style of your BAM files NCBI?
Your error seems to be related to this one: https://support.bioconductor.org/p/125101/
where certain proxy settings seem to interfere with setting the chr style to NCBI. 

@AliSaadatV, are you also running it on a container and is the chr style of your BAM files also NCBI?

**Comment by SamuelNicaise** [comment]
Thanks for this explanation, we're going to look into it with the IT dept

Best regards,

**Comment by vyepez88** [comment]
Hi @SamuelNicaise , do you have any updates?

**Comment by vyepez88** [comment]
or it could be that the website https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/ was not up at that moment
