### ISSUE TITLE
Error in reducer$value.cache[[as.character(idx)]] <- values 

### ISSUE THREAD

**Issue by ChiaraF32** [gagneurlab/drop#493]
Hi,

I am running DROP on 138 muscle RNAseq samples. I successfully ran the `aberrantExpression` module and am now trying to run the 'aberrantSplicing' module, however I am running into the following error message:

```
Error in reducer$value.cache[[as.character(idx)]] <- values : 
  wrong args for environment subassignment
Calls: countSplitReads ... .bploop_impl -> .collect_result -> .reducer_add -> .reducer_add
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
Execution halted
```

I have attached the full log file and config file for context.

My DROP version is 1.3.3.

Could you please help m e troubleshoot this issue?

[2_AS_MuscleSept2023.log](https://github.com/gagneurlab/drop/files/12668759/2_AS_MuscleSept2023.log)
[config.yaml.txt](https://github.com/gagneurlab/drop/files/12668761/config.yaml.txt)

**Comment by ChiaraF32** [comment]
Hi, 

Just bumping this issue request because it still has not been resolved.

**Comment by vyepez88** [comment]
Hi Chiara, sorry for the late reply. It seems that out of 3 samples, 2 were counted and 1 failed. It's hard to understand why.
Can you please try rerunning the workflow with the `-k` parameter? That parameter keeps running all possible steps of the pipeline, even if one failed. That will allow us to see which other samples pass and fail and try to find a pattern.

**Comment by ChiaraF32** [comment]
Hi, 

I just re-ran the pipeline on a different set of samples (fibroblast RNAseq data - see attached samplesheet) with the -k parameter but the pipeline still failed. I have attached the log file. 

I don't think it is sample-specific as I previously haven't had issues with these samples. 

[1_Fibro_AS_Nov2023.log](https://github.com/gagneurlab/drop/files/13433600/1_Fibro_AS_Nov2023.log)

[sample_annotation_Oct2023.txt](https://github.com/gagneurlab/drop/files/13433602/sample_annotation_Oct2023.txt)

**Comment by vyepez88** [comment]
Then it could be a memory issue. Can you please rerun it with the `-k` and `--rerun-triggers mtime` parameters and only giving 3 cores?

**Comment by ChiaraF32** [comment]
Unfortunately this did not work. The same issue came up.

```
Error in reducer$value.cache[[as.character(idx)]] <- values : 
  wrong args for environment subassignment
Calls: countSplitReads ... .bploop_impl -> .collect_result -> .reducer_add -> .reducer_add
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
Execution halted
[Fri Dec  8 01:34:23 2023]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 36
    input: /data/drop/Muscle_Jul2022/output/processed_data/aberrant_splicing/datasets/cache/raw-local-MUSCLE/fds.done, Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
    output: /data/drop/Muscle_Jul2022/output/processed_data/aberrant_splicing/datasets/cache/raw-local-MUSCLE/sample_tmp/splitCounts/sample_FM2606.done
    log: /data/drop/Muscle_Jul2022/.drop/tmp/AS/MUSCLE/splitReads/FM2606.Rds (check log file(s) for error details)

Select jobs to execute...
```

**Comment by vyepez88** [comment]
Hi, how many samples are there pending to be counted? Can you check if there's something different with those BAM files? Hard to say what exactly. Maybe no read groups or not sorted by position..

**Comment by ChiaraF32** [comment]
Hi,

For my muscle RNAseq cohort there are 141 samples to count and for my fibroblast RNAseq cohort there are 12 samples to count as I am using precomputed count data to supplement (https://zenodo.org/records/6078397). The issue persists for both datasets. The BAM files shouldn't be the issue as I have generated them using the same method as have always.

I recently re-ran the `drop_demo` which ran to completion so it is obviously not something wrong with my installation. 

I am not sure what else to try.

**Comment by vyepez88** [comment]
Hi,
You said that some samples did pass the counting. How many did not pass the counting for each tissue?
