### ISSUE TITLE
MissingInputException: Missing input files for rule mae_allelicCounts:

### ISSUE THREAD

**Issue by lbundalian** [gagneurlab/drop#494]
Hello. Good day. I am using DROP for almost a year and always been successful running the 2 modules - Aberrant Expression and Aberrant Splicing. However, I am having problems on MAE (Monoallelic Expression). Right now I am having this error:

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError:
        MissingInputException: Missing input files for rule mae_allelicCounts:

I tried to check the files listed in the annotation and I have validated that the files listed are existing. So from there I dont have any idea which file is this referring to

**Comment by lbundalian** [comment]
More information:
      File "/home/sc.uni-leipzig.de/pz192nijo/.conda/envs/drop_1_3_2/lib/python3.11/site-packages/drop/config/SampleAnnotation.py", line 232, in getFilePath
        MissingInputException: Missing input files for rule markdown:
            output: /work/users/pz192nijo/Projects/Schubert.DROP3/Output/html/MonoallelicExpression/mae--v19_results.html
            wildcards: file=MonoallelicExpression/mae--v19_results
            affected files:
                MonoallelicExpression/mae--v19_results.md

**Comment by lbundalian** [comment]
I reinitialize the project directory and it worked

**Comment by vyepez88** [comment]
Hi, sorry, we had a couple of deadlines recently. What exactly did you do? `drop init` ?

**Comment by lbundalian** [comment]
Yes, and it worked.  However, I am still getting errors, the MAE worked for 5 out of 8 samples and for the other samples I am getting an error which does not describe the error a lot:

Error in rule mae_createSNVs:
    jobid: 22
    input: /work/users/pz192nijo/Projects/Transcriptix.DROP3/Scripts/Pipeline/chr_NCBI_UCSC.txt, /work/users/pz192nijo/Projects/Transcriptix.DROP3/Scripts/Pipeline/chr_UCSC_NCBI.txt, /work/users/pz192nijo/Projects/Transcriptix.DROP3/Data/dna_vcf/3028761_S54-gatk-haplotype.vcf.gz, /work/users/pz192nijo/Projects/Transcriptix/results/rgbam/bam/SS_3030992_RAligned.sortedByCoord.out.bam, /work/users/pz192nijo/Projects/Transcriptix.DROP3/Scripts/MonoallelicExpression/pipeline/MAE/filterSNVs.sh, /work/users/pz192nijo/Projects/Transcriptix.DROP3/Output/processed_data/mae/params/snvs/3030992_snvParams.csv
    output: /work/users/pz192nijo/Projects/Transcriptix.DROP3/Output/processed_data/mae/snvs/3028761_S54--3030992.vcf.gz, /work/users/pz192nijo/Projects/Transcriptix.DROP3/Output/processed_data/mae/snvs/3028761_S54--3030992.vcf.gz.tbi
    shell:
        
        /work/users/pz192nijo/Projects/Transcriptix.DROP3/Scripts/MonoallelicExpression/pipeline/MAE/filterSNVs.sh /work/users/pz192nijo/Projects/Transcriptix.DROP3/Scripts/Pipeline/chr_NCBI_UCSC.txt /work/users/pz192nijo/Projects/Transcriptix.DROP3/Scripts/Pipeline/chr_UCSC_NCBI.txt /work/users/pz192nijo/Projects/Transcriptix.DROP3/Data/dna_vcf/3028761_S54-gatk-haplotype.vcf.gz         3028761_S54 /work/users/pz192nijo/Projects/Transcriptix/results/rgbam/bam/SS_3030992_RAligned.sortedByCoord.out.bam /work/users/pz192nijo/Projects/Transcriptix.DROP3/Output/processed_data/mae/snvs/3028761_S54--3030992.vcf.gz         bcftools samtools
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by lbundalian** [comment]
I dont know specifically, what has gone wrong. This thing occurs only for 2 of the sampls

**Comment by vyepez88** [comment]
maybe there is something wrong with the header or they are not sorted by position?

**Comment by lbundalian** [comment]
The tough part is I cannot tell why it actually failed based from the message. I also tried to run the command indicated in which caused the error but it didnt give any error
