### ISSUE TITLE
How to specify the correction of autoencoder

### ISSUE THREAD

**Issue by kendaida** [gagneurlab/drop#497]
Hi thank you for developing this cool tool!
I would like to specify the correction like it was performed in the figure 2C,2D in the Nature methods paper.
![image](https://github.com/gagneurlab/drop/assets/106678030/18e30816-9470-4f29-83cf-9f76e1f97ede)
I added the columns I wanted to use for correction (SEX, AGE, GROUP) to the sample annotation talbe file, but they did not appear in the output html file.
![image](https://github.com/gagneurlab/drop/assets/106678030/97bfd244-05ae-4c12-b91c-d592d448b46c)

Could you tell me how to do like you did in n the figure 2C,2D in the Nature methods paper?

Thanks,
Ken

**Comment by vyepez88** [comment]
Hi Ken, 
You can do that plot by loading the ods (OUTRIDER) object and using the plotCountCorHeatmap function.
Have a look at the OUTRIDER vignette for more info:
https://bioconductor.org/packages/devel/bioc/vignettes/OUTRIDER/inst/doc/OUTRIDER.pdf

**Comment by kendaida** [comment]
Great thank you!
