### ISSUE TITLE
Differences between FRASER1 and FRASER2

### ISSUE THREAD

**Issue by dissakov** [gagneurlab/drop#499]
Hello! 
I'm trying to reproduce an analysis that was previously run with FRASER1 with FRASER2, and anticipating similar results. However, when I run the same data with FRASER2, it only gives one outlier candidate gene, while the run with FRASER1 gave about 20. Is this intentional behavior, or is there a mistake I've made correctly configuring for FRASER2? The demo project runs without issue. 
I've attached the two config files and cummings.csv (it's cummings.tsv, but converted to csv for posting onto the forum) below. Thank you so much for your help!

Command: snakemake aberrantSplicing --nolock --cores 10 --rerun-incomplete

FRASER1 CONFIG FILE: 

aberrantExpression:
  run: false
aberrantSplicing:
  run: true
  padjCutoff: 0.1
exportCounts:
  excludeGroups: null
  geneAnnotations:
    - ensembl.v94
geneAnnotation:
  ensembl.v94: /mnt/isilon/bhoj_lab/projects/drop-cummings/resources/ensembl.v94.gtf
genome: /mnt/isilon/bhoj_lab/shared/genomes/ensembl.94.Homo_sapiens.GRCh38/ensembl.94.Homo_sapiens.GRCh38.dna.primary_assembly.fa
genomeAssembly: GRCh38
hpoFile: null
htmlOutputPath: /mnt/isilon/bhoj_lab/projects/drop-cummings/results/html
indexWithFolderName: true
mae:
  run: false
projectTitle: drop-cummings
random_seed: true
root: /mnt/isilon/bhoj_lab/projects/drop-cummings/results
sampleAnnotation: /mnt/isilon/bhoj_lab/projects/drop-cummings/resources/cummings.tsv
tools:
  bcftoolsCmd: bcftools
  gatkCmd: gatk
  samtoolsCmd: samtools

FRASER2 CONFIG FILE: 

aberrantExpression:
  run: no
aberrantSplicing:
  run: yes
  padjCutoff: 0.1
  FRASER_version: FRASER2
exportCounts:
  excludeGroups:
  geneAnnotations:
    - ensembl.v94
geneAnnotation:
  ensembl.v94: 
    /mnt/isilon/bhoj_lab/projects/drop-synthetic/drop-pipeline-exon/resources/ensembl.v94.gtf
genome: 
  /mnt/isilon/bhoj_lab/shared/genomes/ensembl.94.Homo_sapiens.GRCh38/ensembl.94.Homo_sapiens.GRCh38.dna.primary_assembly.fa
genomeAssembly: GRCh38
hpoFile:
htmlOutputPath: /mnt/isilon/bhoj_lab/projects/drop-synthetic/drop-pipeline-exon/results/html
indexWithFolderName: yes
mae:
  run: no
projectTitle: 
  cummings
random_seed: yes
root: /mnt/isilon/bhoj_lab/projects/drop-synthetic/drop-pipeline-exon/results
sampleAnnotation: 
  /mnt/isilon/bhoj_lab/projects/drop-synthetic/drop-pipeline-exon/resources/cummings.tsv
tools:
  bcftoolsCmd: bcftools
  gatkCmd: gatk
  samtoolsCmd: samtools

[cummings.csv](https://github.com/gagneurlab/drop/files/13493944/cummings.csv)

**Comment by vyepez88** [comment]
Hi, FRASER2 drastically reduces the number of outliers, but in your case may be too much. Which were the deltaPsiCutoff you used? For FRASER we recommend 0.3 and for FRASER2 0.1.

**Comment by dissakov** [comment]
I didn't modify it in the config - what are the default values?

**Comment by vyepez88** [comment]
Depends if you initialized using `drop demo` or `drop init`. The demo parameters are chosen to run the very small demo dataset. The init parameters are the recommended ones.
