### ISSUE TITLE
addAF default

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#50]
Hi,
The default in documentation for addAF is true, but drop init sets this to false. What should it be?

**Comment by vyepez88** [comment]
We set it to false in the demo as it takes too much memory and time. Users should set it to true.

**Comment by gevro** [comment]
Ok. Then drop init should be changed to set it to true by default.

Also, where does DROP get the gnomAD AF info from? Because that is not in my VCF files.

**Comment by vyepez88** [comment]
it uses the Bioconductor packages MafDb.gnomAD.r2.1.hs37d5 or MafDb.gnomAD.r2.1.GRCh38, depending on the specified genome build. They are quite heavy (around 5 Gb each), that's also why we don't enforce users to install them and run with this option as default.
