### ISSUE TITLE
Using long and short reads in the aberrant splicing analysis.

### ISSUE THREAD

**Issue by SergeyBioinformatics** [gagneurlab/drop#500]
Hello, I perform DROP Aberrant splicing pipeline and some part of my samples has short paired end and another has long single end reads. I've marked single end reads with FALSE value in sample annotation file and changed longRead parameter in Aberrant Splicing part of config.yaml file to TRUE. Ufortunately, I've received an error:

ERROR: long read assignment can only be done on single-end mode
No counts were generated.
Execution halted

The command was standard:
`snakemake --cores 30`
I don't see anything about single-end mode in the documentation. What can cause this kind of error? If it is possible to use short paired end and long single end reads in analysis at the same time?
Thanks a lot

**Comment by vyepez88** [comment]
Hi, the problem is actually not with the single-end, but with the long read. We have that parameter more as a placeholder for when we support long read data, but currently we do not.
