### ISSUE TITLE
BiocParallel errors in rule AberrantExpression_pipeline_OUTRIDER_runOutrider_R

### ISSUE THREAD

**Issue by gianfilippo** [gagneurlab/drop#504]
Hi,

I am stuck with a BiocParallel errors in rule AberrantExpression_pipeline_OUTRIDER_runOutrider_R (see below):
Sun Dec 17 13:50:51 2023: SizeFactor estimation ...
Sun Dec 17 13:50:52 2023: Controlling for confounders ...

Sun Dec 17 13:50:52 2023: SizeFactor estimation ...
Sun Dec 17 13:50:52 2023: Controlling for confounders ...

Error: BiocParallel errors
  2 remote errors, element index: 1, 2
  0 unevaluated and other errors
  first remote error:
Error in controlForConfounders(ods, q = q, implementation = implementation, : Please provide for q an integer greater than 1 and smaller than number of samples or genes.
Execution halted
[Sun Dec 17 13:50:52 2023]
Error in rule AberrantExpression_pipeline_OUTRIDER_runOutrider_R:
    jobid: 32
    input: /home/scripts/DROP/processed_results/aberrant_expression/v41/outrider/GROUP1/ods_unfitted.Rds, Scripts/AberrantExpression/pipeline/OUTRIDER/runOutrider.R
    output: /home//scripts/DROP/processed_results/aberrant_expression/v41/outrider/GROUP1/ods_fitted.Rds
    log: /home/scripts/DROP/.drop/tmp/AE/v41/GROUP1/runOUTRIDER.Rds (check log file(s) for error details)

RuleException:
CalledProcessError in file /tmp/tmpsx4xeay6, line 97:
Command 'set -euo pipefail;  Rscript --vanilla /home/scripts/DROP/.snakemake/scripts/tmph4u9s635.runOutrider.R' returned non-zero exit status 1.
  File "/tmp/tmpsx4xeay6", line 97, in __rule_AberrantExpression_pipeline_OUTRIDER_runOutrider_R
  File "/home/.conda/envs/drop_env/lib/python3.12/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-12-17T130359.683992.snakemake.log

I also reinstalled BiocParallel
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.8 (Ootpa)

Matrix products: default
BLAS/LAPACK: /home/.conda/envs/drop_env/lib/libopenblasp-r0.3.25.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocParallel_1.34.2 BiocManager_1.30.22

loaded via a namespace (and not attached):
[1] compiler_4.3.2   parallel_4.3.2   tools_4.3.2      codetools_0.2-19

My sampleTable.txt and config.yaml are attached

Can you please help ?

Thanks

[sampleTable.txt](https://github.com/gagneurlab/drop/files/13698234/sampleTable.txt)
[config.yaml.txt](https://github.com/gagneurlab/drop/files/13698248/config.yaml.txt)

**Comment by vyepez88** [comment]
Hi, it seems the error is this:
` Please provide for q an integer greater than 1 and smaller than number of samples or genes`. That refers to the encoding dimension. 
In your specific case it's due to your low number of samples (only 4 in GROUP1 and 3 in GROUP2). Are you attempting to do differential expression? If so, OUTRIDER is not the software you want.
For OUTRIDER to run, at least 10 samples are needed, although we recommend at least 50.

**Comment by drewjbeh** [comment]
Hi @gianfilippo - did you manage to resolve this error?

**Comment by gianfilippo** [comment]
Hi, I am back to this project again. 
I downloaded a matrix of external counts to work around my small control sample size. 
Not run yet, though, so I cannot say if this solves the problem

**Comment by gianfilippo** [comment]
UPDATE:
I tried to add a few external files, but I keep getting the error below. What am I doing wrong ?
[config.yaml.txt](https://github.com/gagneurlab/drop/files/14019535/config.yaml.txt)
[sampleTable.tsv.txt](https://github.com/gagneurlab/drop/files/14019536/sampleTable.tsv.txt)



======================================================
WARNING: 8 files missing in samples annotation. Ignoring...
WARNING: Less than 30 IDs in DROP_GROUP HC
WARNING: Less than 30 IDs in DROP_GROUP CR
WARNING: Less than 30 IDs in DROP_GROUP HC
WARNING: Less than 30 IDs in DROP_GROUP CR
$HOME/scripts/DROP/processed_data/aberrant_expression/params/config/AberrantExpression_config.tsv Param Files do not match. Updating to current Sample Annotation

$HOME/scripts/DROP/processed_data/aberrant_splicing/params/config/AberrantSplicing_config.tsv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
install gagneurlab/FRASER
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.17 (BiocManager 1.30.21.1), R 4.3.1 (2023-06-16)
Installing github package(s) 'gagneurlab/FRASER'
Skipping install of 'FRASER' from a github remote, the SHA1 (9aaf97f1) has not changed since last install.
  Use `force = TRUE` to force installation
installed gagneurlab/FRASER
MonoallelicExpression has been turned off in the config file
rnaVariantCalling has been turned off in the config file
Structuring dependencies...
Dependencies file generated at: /tmp/tmp57yf5e0p

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError:
        InputFunctionException (rule AberrantExpression_pipeline_Counting_mergeCounts_R, line 156, /tmp/tmp57yf5e0p):
            Error:
              KeyError: "Column 'GENE_ANNOTATION' not present in sample annotation."
            Wildcards:
              annotation=v41
              dataset=HC
            Traceback:
              File "/tmp/tmp57yf5e0p", line 52, in <lambda>
              File "$HOME/.conda/envs/drop_env_133/lib/python3.8/site-packages/drop/config/submodules/AberrantExpression.py", line 61, in getCountFiles
              File "$HOME/.conda/envs/drop_env_133/lib/python3.8/site-packages/drop/config/SampleAnnotation.py", line 276, in getImportCountFiles
              File "$HOME/.conda/envs/drop_env_133/lib/python3.8/site-packages/drop/config/SampleAnnotation.py", line 183, in subsetSampleAnnotation
        MissingInputException: Missing input files for rule markdown:
            output: $HOME/scripts/DROP/html/AberrantExpression/Counting/v41/Summary_HC.html
            wildcards: file=AberrantExpression/Counting/v41/Summary_HC
            affected files:
                AberrantExpression/Counting/v41/Summary_HC.md
    MissingInputException: Missing input files for rule markdown:
        output: $HOME/scripts/DROP/html/Scripts_AberrantExpression_pipeline_Counting_Datasets.html
        wildcards: file=Scripts_AberrantExpression_pipeline_Counting_Datasets
        affected files:
            Scripts_AberrantExpression_pipeline_Counting_Datasets.md
MissingInputException: Missing input files for rule markdown:
    output: $HOME/scripts/DROP/html/aberrant-expression-pipeline_index.html
    wildcards: file=aberrant-expression-pipeline_index
    affected files:
        aberrant-expression-pipeline_index.md

**Comment by vyepez88** [comment]
Hi, it seems that some of your DROP groups have less than 10 samples. What are you interested in comparing? All samples together? If so, they should all belong to the same group.

**Comment by gianfilippo** [comment]
Hi, I assigned all the samples to the same group, Healthy, and I still get the same error.

**Comment by gianfilippo** [comment]
Let me take it back. I found the mistake. I misspelled  GENE_ANNOTATION in the sample annotation file. Sorry about this.
I do have a different error related to FRASER unable to load a shared object. I will make a separate report for this
