### ISSUE TITLE
One sample + external data vs multiple samples + external data 

### ISSUE THREAD

**Issue by gianfilippo** [gagneurlab/drop#511]
Hi,

if I have a few samples (4 for instance) to be analyzed against normal controls (using external data, for instance), does it make more sense to define 4 groups (i.e. each group is 1 case + all external controls) or would you define a single group (i.e. all 4 cases + external controls)?

In other words, is each sample tested individually or as a group ?

Thanks

**Comment by carlalbc** [comment]
I have a similar scenario and what I am doing is that I am making two groups ("outrider", for my local samples and "outrider_external" for the external counts). In the annotation file, I have them categorized in the `RNA_ID` column and the `DROP_GROUP` column as: 

`local_sample_ID`    `outrider, outrider_external, fraser, fraser_external`  --> for our local samples 
`external_sample_ID`   `outrider, outrider_external`  -->  for the external counts related to OUTRIDER 
`external_sample_ID`   `fraser, fraser_external`  --> for the external data related to FRASER
 
First column is the `RNA_ID`  and the second corresponds to the  `DROP_GROUP`

Would be nice to know if this is ok :)

**Comment by vyepez88** [comment]
Hi @gianfilippo, in your case I would have only one group. The problem of the 1 + controls setting is that the program will also identify technical biases in the sequencing of your one sample alone. Having at least 4 samples will reduce this bias.
Hi @carlalbc, in your case I don't see any difference between the outrider and outrider_external groups as you're assigning both groups to all samples. If you want to analyze all internal and external samples together, simply have one group.

**Comment by gianfilippo** [comment]
Hi, thanks for answering.

Could you please clarify how the AE (?) handles technical bias in 1 vs 4 samples ? 

and if my 4 samples each came from a different batch, say, because they were processed at different times and/or by different people ?

Thanks

**Comment by vyepez88** [comment]
Hi, we recommend to have at the very least 30 samples. 
In a 1 vs 4 setting, the AE cannot learn any batch effect from the 1 sample.
If all your 4 samples came from a different batch, you will be capturing mostly batch/technical effects, not biological ones.

**Comment by gianfilippo** [comment]
Hi, thanks for your answer. I think I did not express myself clearly.
I am using 120 external samples and a 4 of my own (cancer samples). As far as I understand, the external samples from the links you provide are from healthy individuals. 
Within this framework, can the AE 'learn' batch effects ? do 4 samples together make a difference, as opposed to 1 sample or 4 samples together but each from a different batch ?

**Comment by vyepez88** [comment]
Hi, I see. 4 samples together are indeed better than just 1, but it might not be enough for the method to realize they're a batch and not just outliers.

**Comment by gianfilippo** [comment]
Thanks. What would be the minimum number of samples, when using external samples ?

**Comment by vyepez88** [comment]
We haven't made a systematic analysis. In the original DROP publication, we used 17 positive controls and >70% of the expression and splicing outliers were recovered. I'd say at least 5-10% of the data..

**Comment by gianfilippo** [comment]
Thanks

**Comment by carlalbc** [comment]
Just to chime in on the discussion. What if you have 4 samples from the same batch in triplicates, and then use each replicate as an individual sample? Can the replicates be considered individual samples within the pipeline? This means you would have 12 samples instead of 4 + the external samples. In addition, the 4 samples would have a high sequencing depth of ~100M read depth.

**Comment by vyepez88** [comment]
Hi, having triplicates actually harms the model. One of the assumptions of the outlier detection approach is that all samples come randomly from a population. Therefore there shouldn't be replicates.

**Comment by carlalbc** [comment]
That makes sense, so it would be better to run the replicates individually, together with the external samples, and see if the findings match later?

**Comment by vyepez88** [comment]
that would be a better strategy, yes

**Comment by carlalbc** [comment]
Perfect, thanks for your input :)

**Comment by vyepez88** [comment]
sure, I'll close the issue then
