### ISSUE TITLE
QC variants are all homozygous causing MAE rule MonoallelicExpression_pipeline_QC_deseq_qc_R to error out

### ISSUE THREAD

**Issue by wanqingshao** [gagneurlab/drop#513]
Hello,

I have a sample that errored out in rule `MonoallelicExpression_pipeline_QC_deseq_qc_R` .  Error messages are attached below. After some digging, I think the problem is that for some reason, all the variants in file `allelic_counts/QC--xxxx.csv.gz` are homozygous in this sample (either 0 read for `refCount` or 0 read in `altCount`). Do you have recommendations on how to deal with this? What variants would you recommend to maybe add into file `qc_vcf_1000G.vcf.gz` to help with the calculation? 

```
Error in estimateSizeFactorsForMatrix(counts(object), locfunc = locfunc,  : 
  every gene contains at least one zero, cannot compute log geometric means
Calls: DESeq4MAE ... estimateSizeFactors -> .local -> estimateSizeFactorsForMatrix
Execution halted
```

Many thanks in advance!

Best,
Wanqing

**Comment by vyepez88** [comment]
Hi, sorry for the late reply. 
Unfortunately, we haven't tested a case where all variants are homozygous. I suggest simply removing it from this module. (But you can keep if for the expression and splicing ones).
