### ISSUE TITLE
Aberrant splicing theta (θ) values width all have the same value 

### ISSUE THREAD

**Issue by carlalbc** [gagneurlab/drop#517]
Dear DROP team,

I am writing an issue because I am unsure if I have an error in my data, or my configuration files. 

When I evaluate the results obtained after running the aberrantSplicing module of DROP (FRASER) I find that **all** the hits for the splicing type _theta_ have a **width length** of only **2nt**. I have run the same pipeline with three different datasets and it seems to be a recurrent issue for this value. 

Do you have any idea why this could be? Could it be that I have a configuration problem? or that I have a parameter set or unset wrongly in FRASER? 

Table for reference:
<img width="1057" alt="image" src="https://github.com/gagneurlab/drop/assets/22526927/a20564b5-8466-49f7-9676-73972bb93df1">

Thank you in advance for your help!

**Comment by vyepez88** [comment]
Hi Carla, thanks for using DROP. Actually, that is not an error. The metric theta tests splice sites, not junctions, so the width is always 2 (see the start and end columns).

**Comment by carlalbc** [comment]
Ah, I see, perfect then. I was a bit confused! Thank you :))
