### ISSUE TITLE
qc_vcf_1000G.vcf.gz file

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#52]
Hi, The documentation says to download this, but I can't find it.
Thanks.

**Comment by vyepez88** [comment]
The step says "Download the test VCF file (qc_vcf_1000G.vcf.gz) and its index file from the DROP resource webpage (Online resources)"
and in Online resources there's the entry: DROP resource folder: https://i12g-gagneurweb.in.tum.de/public/paper/drop_analysis/resource/
If you clic on that link, you'll find the vcf file
