### ISSUE TITLE
Does FRASER make any comparisons between genes, or only comparing splicing within a given gene (between sample and controls)?

### ISSUE THREAD

**Issue by dissakov** [gagneurlab/drop#520]
Hello! 
Does FRASER do any correction/normalization between genes or make any assumptions about the number of causal genes in a sample? 
I'm trying to run a sample that has a few thousand splicing aberrations, but FRASER is only returning a few candidates. Is there an assumption being made that would be violated by a sample like this? 
Thank you!

**Comment by vyepez88** [comment]
Hi,
FRASER's autoencoder does normalize between co-expressed junctions, not exactly of genes. It does not take into account causal genes.
Your sample has few thousand aberrant junctions or genes? In any case it is a lot and might violate the assumptions of the model in which all samples come from the same populations and all junctions follow a Beta Binomial distribution. In that sense, FRASER is able to detect a few outliers per sample, but if there are too many (in the thousands), then the modeling might not work.
