### ISSUE TITLE
Error in MAE QC create matrix dna rna cor

### ISSUE THREAD

**Issue by bijuissac** [gagneurlab/drop#527]
Hi

I keep getting error at the create matrix step. Based on error described below, it seems to be parallel job errors. However I am not sure. Does anyone have any clue to correct this?

`rule MonoallelicExpression_pipeline_QC_create_matrix_dna_rna_cor_R:
    input: /hpcdata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_data/mae/RNA_GT/2491270_JCC454_37.Rds, /hpcdata/bcbb/bi
ssac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_data/mae/RNA_GT/2491263_JCC454_9.Rds, /hpcdata/bcbb/bissac/Clinical_Genomics/Proje
cts/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_data/mae/RNA_GT/2491261_JCC454_1.Rds, /hpcdata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_re
sults/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_data/mae/RNA_GT/2491266_JCC454_21.Rds, /hpcdata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoall
elicExpression_MAE2/Output/processed_data/mae/RNA_GT/2491271_JCC454_41.Rds, /hpcdata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/
processed_data/mae/RNA_GT/2491267_JCC454_25.Rds, /hpcdata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_data/mae/RNA_GT/2
491264_JCC454_13.Rds, /hpcdata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_data/mae/RNA_GT/2491269_JCC454_33.Rds, /hpcd
ata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_data/mae/RNA_GT/2491268_JCC454_29.Rds, /hpcdata/bcbb/bissac/Clinical_Ge
nomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_data/mae/RNA_GT/2491265_JCC454_17.Rds, Scripts/MonoallelicExpression/pipeline/QC/create_matrix_dna
_rna_cor.R
    output: /hpcdata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/Output/processed_results/mae/mae/dna_rna_qc_matrix.Rds
    log: /hpcdata/bcbb/bissac/Clinical_Genomics/Projects/Helen_Su/results/drop_results/DROP_pipeline_monoallelicExpression_MAE2/.drop/tmp/MAE/mae/QC_matrix.Rds
    jobid: 0
    reason: Forced execution
    wildcards: dataset=mae
    threads: 20
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=/hpcdata/scratch/24734494.1.all.q

Stop worker failed with the error: reached CPU time limit
Error: BiocParallel errors
  0 remote errors, element index: 
  10 unevaluated and other errors
  first remote error:
Execution halted
`

**Comment by vyepez88** [comment]
Hi, the reason seems to be this: `reached CPU time limit`
Is there a way you can allocate more resources? 1 Gb is not a lot.

**Comment by bijuissac** [comment]
Hi, sorry for not coming back to close this. We resolved the error. Digging deeper, we found out that the QC VCF and the sample data data VCF header had different assembly names (38 and hg38). The script proceeded to complete successfully once this was rectified in the headers of both VCFs to match. We did try increasing resources (our thoughts initially) but it did not help

**Comment by bijuissac** [comment]
Resolved
