### ISSUE TITLE
Default running folder is out of space

### ISSUE THREAD

**Issue by hermean** [gagneurlab/drop#529]
Dear developers,

Thank you for this great tool!

Recently I was using rnaVariantCalling and encountered a problem of space shortage on my disk (the demo run was fine, probably due to the small size). 

Here is the error message:
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_close] File write failed
samtools sort: failed to create temporary file "/home/hermean/drop/CurrentRun_hg19/Output/processed_data/rnaVariantCalling/out/bam/R003/R003_Aligned.sortedByCoord.out.bam.tmp.0023.bam": No space left on device

It appears that /home/hermean is full (only 20G space left).
My question is how to set the default disk/folder for the running, then I can select a folder with enough disk space available.

Thanks again!

**Comment by vyepez88** [comment]
Hi!
Thanks!
Yes, you can specify the path where all the output of DROP will be saved in the `root` parameter of the config file

**Comment by hermean** [comment]
Thanks very much for the quick reply and it solved the problem!
