### ISSUE TITLE
Writing `rds` files as log can crash Snakemake execution

### ISSUE THREAD

**Issue by votti** [gagneurlab/drop#535]
I noticed that this workflow often saves the `snakemake` object as a log output as `rds` objects.

Unfortunately in some `snakemake` configurations (ie a setting/executor that uses `--show-failed-logs`) this causes the whole workflow execution to crash.

The error is something in the line of:
```
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

This has been reported to `snakemake` (https://github.com/snakemake/snakemake/issues/2826) and I have authored a fix (https://github.com/snakemake/snakemake/issues/2827).

**Comment by votti** [comment]
This has now been fixed in the latest Snakemake version.

**Comment by ChiaraF32** [comment]
I am also receiving this error. 

I installed drop using conda:

```
conda env create -f DROP_1.3.3.yaml
```

In this environment, snakemake 7.32.4 is used. I tried installing a more updated version of snakemake:

```
conda install -c bioconda -c conda-forge snakemake-minimal=8.11.1
```
But this presented incompatibility issues with the DROP workflow. 

So in summary, what is the fix available that does not require installing a more recent version of snakemake (which is not compatible)?

**Comment by AtaJadidAhari** [comment]
Hi @ChiaraF32, 
This issue is fixed in the latest DROP release. Please install and use DROP 1.4.0.

**Comment by ChiaraF32** [comment]
I am using drop version 1.5.0 and still getting this issue.

**Comment by AtaJadidAhari** [comment]
Hi, can you share the full error message, your snakemake version and the command which you ran?

**Comment by ChiaraF32** [comment]
The snakemake version is `v7.32.4`. 

My run script is:

```
#!/bin/bash -l

#SBATCH --job-name=drop_muscle
#SBATCH --account=pawsey0933
#SBATCH --partition=work
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=16G
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mail-user=chiara.folland@perkins.org.au
#SBATCH --mail-type=END
#SBATCH --error=%j.%x.err
#SBATCH --output=%j.%x.out
#SBATCH --export=ALL

#Load mamba env
source /software/projects/pawsey0933/cfolland/miniforge3/etc/profile.d/mamba.sh
mamba activate /scratch/pawsey0933/cfolland/conda_envs/drop_env

#Change cache dir
export XDG_CACHE_HOME=/scratch/pawsey0933/cfolland/conda_cache

#Change to working dir
cd /scratch/pawsey0933/cfolland/drop/muscle

#Unlock working directory
snakemake -s Snakefile --cores 1 --unlock

#Run snakemake
snakemake -s Snakefile --rerun-triggers mtime --profile slurm_drop_muscle

```

The full error log is attached. 

[36885327.drop_muscle.err.txt](https://github.com/user-attachments/files/24225060/36885327.drop_muscle.err.txt)

**Comment by AtaJadidAhari** [comment]
Thanks. 

Looks like `aberrantExpression_mergeBamStats` is failing. As a workaround, you can just add `-k` option to keep running even if some jobs fail. The pipeline will probably run until the end and you will get your results as the aberrantExpression_mergeBamStats step is only required for summary.

In the meantime, can you check the status of the job on slurm? Simply Run the following commands :`sacct -j 36890273` and `seff -j 36890273`. This might hint to root of the problem.

**Comment by ChiaraF32** [comment]
Hi,

Unfortunately, this has not managed to solve my issue. 

My most recent attempt has the same issue, although it appears to be during the `AberrantExpression_pipeline_Counting_countReads_R` rule

[37585159.drop_muscle.err.txt](https://github.com/user-attachments/files/24447908/37585159.drop_muscle.err.txt)

**Comment by ChiaraF32** [comment]
I fixed this by removing a setting in my config file.

I had `show-failed-logs: True` so updated it to `show-failed-logs: False`.

I no longer get the issue with the utf-8 issue
