### ISSUE TITLE
Annotation file asks for columns that shouldn't be needed

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/drop#540]
Hi, 

I'm trying to just run FRASER 2.0 with the DROP workflow. On the config file I have set all the run options to false except for the aberrantSplicing, but when i run `snakemake --cores 1 -n`, it prompts:
`Incorrect columns in sample annotation file. Missing:
['DNA_VCF_FILE', 'DNA_ID', 'COUNT_MODE', 'COUNT_OVERLAPS', 'STRAND']`, which are columns needed for mae, rnaVariantCalling or aberrantExpression. I have created all the files using `drop init` on the new folder I have created for the project, so I suppose the command isn't calling any other config file from other folder. Thanks in advance!

Best,

Miriam

**Comment by vyepez88** [comment]
Hi Miriam, the STRAND column is needed for aberrantSplicing module. We do not have a way of checking the sample annotation's columns only when certain modules are turned on. For the other columns, please create empty columns with those names.

**Comment by mmartinezj** [comment]
Hi Vicente,
adding the columns you mentioned solved this issue, thanks!
