### ISSUE TITLE
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/drop#541]
Hi,

when trying to run the aberrant splicing module, the following error appears:

![drop_error_3](https://github.com/gagneurlab/drop/assets/119602950/5256bcc4-e82f-442a-870e-8a1378d8d36e)

(I don't have more info about the error, the only log file I found was the snakemake one and it had the same info that the screenshot). 

Also, before this error appears, at some point it states the strand is not specified:

![drop_error_4](https://github.com/gagneurlab/drop/assets/119602950/ed8d2863-45ab-4003-ae35-b50ad6abd06b)

But as you can see on the next screenshot, I have added a column for strandedness:

![strandedness](https://github.com/gagneurlab/drop/assets/119602950/d10a5665-7339-41b9-939f-09dc3243ed53)

I don't know if this is relevant for the error itself, but just in case it is related. Thanks in advance!

Best,

Miriam

**Comment by vyepez88** [comment]
Hi, this is related to the fix we are now implementing. It will be out very soon, sorry!

**Comment by mmartinezj** [comment]
Hi Vicente,

thanks for letting me know! As it was at the beginning of the workflow I thought it had something to do with the installation or my own files. I will be looking foward for the next release then, thanks for the great job!

Best,

Miriam

**Comment by AtaJadidAhari** [comment]
Hi @mmartinezj DROP 1.3.4 is available on GitHub now and you can install it using pip:
pip install git+https://github.com/gagneurlab/drop.git

**Comment by mmartinezj** [comment]
Hi Ata, thanks for the update. I have installed DROP 1.3.4 with pip, but I'm still facing errors. As my previous installation was with conda, I have installed DROP with pip and the dependencies on my own computer, but now I'm having more errors, both with the pipeline and R. I will leave some screenshots here in case I can have some help on what's going on. I have installed r-base with ubuntu but now it seems some packages/dependencies can't be installed. Thanks for the help in advance!

![r_packages](https://github.com/gagneurlab/drop/assets/119602950/e91558b2-bc6e-4af7-a671-c52020e6831f)

![error_1](https://github.com/gagneurlab/drop/assets/119602950/daa5af58-a376-4d6d-88e0-bfbe4e04ac6b)

![error_2](https://github.com/gagneurlab/drop/assets/119602950/56db82c9-cb7b-4bdc-9c58-02adc4827494)

If you need more information, please let me know.

Best,

Miriam

**Comment by AtaJadidAhari** [comment]
Hi, drop 1.3.4 is now also available in biconda since 2 hours ago. Please create a fresh environment and install it using `mamba install -c bioconda drop=1.3.4`. This will hopefully solve your issue.

If the issue still persists, please first try to run drop demo: 
```conda activate drop_env
mkdir ~/drop_demo
cd ~/drop_demo
drop demo
snakemake -c4
```
Please let me know if the demo runs through or not, then we can investigate the issue in more details.

**Comment by mmartinezj** [comment]
Hi, I have just finished running the demo with the conda install and it run smoothly. Thanks!

**Comment by vyepez88** [comment]
great to hear Miriam!

**Comment by mmartinezj** [comment]
Hi, after testing the demo run, it went smoothly, but today, when trying to use my data, I'm facing a new problem but at the same point: 

![error_3](https://github.com/gagneurlab/drop/assets/119602950/f7f89d0d-4788-4e93-95d8-f1c7b735c811)

I have rerun the demo but changing fraser to fraser2, just in case it was a problem  with fraser version, but it all went correctly too. Thus, I guess it's something related to my data, but I don't know where the problem is. Sorry for reopening the issue. I appreciate all the help and feedback! Thanks in advance.

**Comment by vyepez88** [comment]
Hi, that's usually related to memory. Can you provide more memory to the run or use less cores?

**Comment by mmartinezj** [comment]
Hi, after testing the use of different cores, indeed is a memory issue. Once I used less cores, the pipeline started running. I keep having those memory issues (even with 1 core), but that's a problem of my own resources. Thank you very much for replying so fast and all the feedback!
