### ISSUE TITLE
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R

### ISSUE THREAD

**Issue by cariocow** [gagneurlab/drop#543]
Hi, 
thanks for creating this tool. 

i have the following issue when running the drop demo. thanks for helping.

Cario

Load packages
Loading required package: rtracklayer
Error in if (strandSpecific(fds) == 0) { : the condition has length > 1
Execution halted
[Mon May 13 10:31:15 2024]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 56
    input: /home/epi2mewsl/bin/drop_demo/Output/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/fds.done, Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
    output: /home/epi2mewsl/bin/drop_demo/Output/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/sample_tmp/splitCounts/sample_HG00150.done
    log: /home/epi2mewsl/bin/drop_demo/.drop/tmp/AS/fraser/splitReads/HG00150.Rds (check log file(s) for error details)

RuleException:
CalledProcessError in file /tmp/tmpo6kcji1x, line 130:
Command 'set -euo pipefail;  Rscript --vanilla /home/epi2mewsl/bin/drop_demo/.snakemake/scripts/tmp4hbhdl2d.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/tmp/tmpo6kcji1x", line 130, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/home/epi2mewsl/bin/miniconda/envs/drop_env_133/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by henryjuho** [comment]
I just hit this same issue, for me it was resolved by downgrading the fraser version in R with:

`devtools::install_github('c-mertes/FRASER', ref="1.99.3", dependencies=TRUE)`

**Comment by AtaJadidAhari** [comment]
Installing [DROP v1.3.4](https://github.com/gagneurlab/drop/releases/tag/1.3.4 ) will solve this issue.
