### ISSUE TITLE
QUESTION: specifying samples for sampleExclusionMask in OUTRIDER 

### ISSUE THREAD

**Issue by Nicholas-Kron** [gagneurlab/drop#553]
Hi there! 

Thank you for making this convenient pipeline. I am planning on running this soon and I had a question regarding setting specific parameters for OUTRIDER that I did not see in the manual or in any issues. If I have trios in my dataset, is there a way to specify these samples in the config or annotation table to be excluded from the auto-encoder fit?

From the OUTRIDER vignette:

> 4.4.1 Excluding samples from the autoencoder fit
> Since OUTRIDER expects that each sample within the population is independent of
> all others, replicates could mask effects specific to this sample. This is also true if
> trios are present in the data, where the parents can be seen as biological replicates.
> Here, we recommend to exclude the sample of interest or the replicates from the
> fitting. Later on, for all samples P-values are calculated.
> In this rare disease data set we know that two samples (MUC1344 and MUC1365)
> have the same defect. To exclude one or both of them, we can use the sampleExclusionMask function.

Thank you!

**Comment by vyepez88** [comment]
Hi, thanks for using DROP!
Indeed, we had made the `sampleExclusionMask` function for those kind of situations. However, recently, we also got trio data and saw that the fit of the masked samples is not optimal and leads to too many outliers. We are working on a dedicated solution to deal with trios. However, if your cohort is large enough, you should be able to run it as a whole anyway.

**Comment by Nicholas-Kron** [comment]
Ok sounds good. Thank you!

**Comment by janaghub** [comment]
Hi,

I have a similar situation. I have an affected child and an unaffected mother. I grouped these two samples together with 48 external count samples. I ran the default parameters for aberrant expression and aberrant splicing modules and did not get results for candidate genes. Would you recommend using the sampleExclusionMask function for this situation? Any other recommendation would be greatly appreciated!

Jana

**Comment by vyepez88** [comment]
Hi Jana, please don't use the sampleExclusionMask. Instead, you can give the candidate genes to the pipeline. See here https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#limiting-fdr-correction-to-subsets-of-genes-of-interest
