### ISSUE TITLE
Can't load fds-object from DROP in R

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/drop#555]
Hi,
I have tried to load the fds object obtained from DROP run (aberrantSplicing module) in order to modify the plots from Overview.R, but when I try to load the object, this error arises:

![error_loading_fds](https://github.com/gagneurlab/drop/assets/119602950/593aef8f-ba72-4abc-a024-b3654a320a84)

I have tried to load the fds-object from the DROP demo run, and I could load it without any problem. I have tested this with FRASER v1.99.4 on R. 

Thanks in advance!

Miriam

Update: checking the scripts used for DROP pipeline, I found a line on the 01_0_countRNA_init script: `strandSpecific(fds) <- colData(fds)$STRAND`. When I ran it, the error was the following `Error in switch(tolower(value), no = 0L, unstranded = 0L, yes = 1L, stranded = 1L,  : 
  EXPR must be a length 1 vector`
On my annotation file, on the STRAND column I used the reverse option, but it doesn't appear on the options of the error. I don't know if this might be the problem or might help!

**Comment by AtaJadidAhari** [comment]
Hi Miriam, 

this is probably due to the changes in FRASER from v1.99.3 to v1.99.4. I suspect you have done your analysis with DROP v1.3.4 which uses FRASER v1.99.3 and probably saved fds-object with that version. Can you please try to load the fds-object with FRASER v1.99.3? 

Best,
 
Ata

**Comment by mmartinezj** [comment]
Hi Ata, 
I did the analysis with DROP v1.4.0, tried to load it with FRASER v1.99.3 and got again the same error. I tried to reinstall v1.99.4 and after this reinstalation, I was able to load the fds-object. Probably something went wrong on the previous installation and that's why it wasn´t working. Thanks for the response!

Best,

Miriam
