### ISSUE TITLE
Results doubts

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/drop#556]
Hello,
after running DROP workflow, I have some doubts regarding the results. I would be very greatful if you could help me to resolve some of these:

1) psi value vs deltapsi: when taking a look into the results table, there are 2 columns, the "psiValue" and the "deltaPSI". Does the psiValue refer to the Intron Jaccard Index observed? Regarding the deltaPSI, I do understand the deltaPSI when using software that look for differences in splicing between 2 groups, but in this case, does deltaPSI refer to the difference between the Intron Jaccard Index Observed and Expected?

2) type of alternative splicing: before moving to the Intron Jaccard Index with FRASER, I could more or less understand how FRASER stated the type of splicing event that it was happening depending on if it was psi3, psi5 or theta, but now, how does FRASER know which type of splicing event is happening (taking a look into the "potentialImpact" column)? It uses psi3, psi5 and theta internally and state the type of splicing event with those values? Also, some terms like "complex", "splicingBeyondGene" or "multigenicSplicing", what type of event do they refer to? Is there a way to know it or in order to have a more specific answer I should look for the event with the bam files in igv?

3) number of outliers: taking a look at the results_per_junction.tsv, having 15 samples per group, I have approx 61500 events with a pvalue < 0.05 (testing all the genes). Is this number a plausible result (taking into account it's transcriptome-wide) or there may be something not working as it should? 

I hope the questions are clear. If you need any clarification, please let me know. Thank you again for your hard work!

Miriam

**Comment by vyepez88** [comment]
Hi Miram,
1. If you're using FRASER2, indeed psiValue refers to the Intron Jaccard Index observed. In this case, there are no groups, so you're also right by saying that deltaPsi is the difference between the Intron Jaccard Index Observed and Expected
2. The potentialImpact is the same as before. The Jaccard is at the intron level, so e.g. splicing beyond gene means that the intron started in an annotated gene and ended somewhere outside the gene (but not in another gene)
3. It's not necessarily a lot. It also depends on how many junctions there are (usually > 100,000). You could verify that the p-values of each intron (row) are uniformly distributed. Alternatively, you could plot the global qq plot `plotQQ(fds, type = 'jaccard', global = T)` and verify that most points lie on the diagonal (it will take maybe 1 minute, see attachment)

![plot](https://github.com/gagneurlab/drop/assets/30469316/68056602-5713-4346-9f9b-a83a9920b37b)

**Comment by mmartinezj** [comment]
Thank you very much for your help and time Vicente and to other colaborators (in this and previous issues). Now I understand better the results that DROP (FRASER in this case) outputs. I hope this information may help also other people that may be starting on splicing analyses. Keep up the amazing work!

Best,

Miriam
