### ISSUE TITLE
Safe way to rerun crashed pipeline

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#559]
Hi, The drop aberrantsplicing step crashed due to a computing cluster time limit. What is the safest way to restart the pipeline so that it doesn't accidentally use partial results files that would corrupt the results?

Is snakemake -F ok?

**Comment by vyepez88** [comment]
Hi,
`snakemake -F` will force every single step to be reexecuted, including the counting. If that is what you want, go ahead. Otherwise, if you want to keep the counts and rerun everything from the merging step on, you could delete the whole contents of the following folders:
```
{root}/processed_data/aberrant_splicing/datasets/savedObjects/{DROP_GROUP}
{root}/processed_results/aberrant_splicing/datasets/savedObjects/{DROP_GROUP}
```
Then execute
`snakemake -n aberrantSplicing --rerun-triggers mtime`
The steps including and after `AberrantSplicing_pipeline_Counting_03_filter_expression_FraseR_R` should appear. If so, proceed to execute that command (providing cores and removing the -n). Keep the `--rerun-triggers mtime`

**Comment by gevro** [comment]
However, with snakemake -F I am seeing a bunch of lines like this that suggest that the counting was not redone? Is that safe? Or should I restart everything by deleting a set of folders that will clear aberrantsplicing completely?

```
Mon Jul  1 14:09:37 2024: Using existing non spliced read counts for sample: GTEX-111YS_RNA
...
Mon Jul  1 14:09:08 2024: Using existing non spliced read counts for sample: GTEX-12WSF_RNA
Mon Jul  1 14:09:08 2024: GTEX100, GTEX-12WSF_RNA no. splice junctions (non split counts) = 623348
```

**Comment by vyepez88** [comment]
The non-spliced read counts are only saved after the process is finished. They don't get saved junk by junk. However, if the process crashed in the exact second when they were saved, indeed they could be corrupted. If you think the process crashed during the non-split counting, then yes, delete everything and then rerun the whole pipeline.

**Comment by gevro** [comment]
How do I delete all the aberrant splicing output to restart that specific pipeline from scratch?

I don't want to redo other drop pipelines.

**Comment by vyepez88** [comment]
Remove the following directories:
```
{root}/processed_data/aberrant_splicing/datasets/savedObjects/raw-local-{DROP_GROUP}
{root}/processed_data/aberrant_splicing/datasets/cache/nonSplicedCounts/raw-local-{DROP_GROUP}
{root}/processed_data/aberrant_splicing/datasets/cache/otherCounts/raw-local-{DROP_GROUP}
{root}/processed_data/aberrant_splicing/datasets/savedObjects/{DROP_GROUP}
{root}/processed_results/aberrant_splicing/datasets/savedObjects/{DROP_GROUP}
```
Remove the split counts by removing, for every RNA_ID in the corresponding DROP GROUP, the following files:
```
{root}/processed_data/aberrant_splicing/datasets/cache/splitCounts/splitCounts-{RNA_ID}.RDS
```

**Comment by gevro** [comment]
What about these?

cache/raw-local-{DROP_GROUP}
processed_results/aberrant_splicing/results/v##/fraser/DROP-GROUP

files under htmlOutput (AberrantSplicing folder and Scripts_AberrantSplicing_pipeline_FRASER_Datasets.html and Scripts_AberrantSplicing_pipeline_Counting_DatasetsF.html and aberrant-splicing-pipeline_index.html

**Comment by vyepez88** [comment]
yes, those too. The results and html will be regenerated for sure once the pipeline is retriggered, but feel free to also remove them.

**Comment by gevro** [comment]
Thanks
