### ISSUE TITLE
Discrepancy between results_per_junction.tsv and results.tsv files

### ISSUE THREAD

**Issue by scharf-f** [gagneurlab/drop#562]
Dear authors,

upon our verification efforts of the aberrantSplicing module of DROP on our data I encountered discrepancies between the two mentioned output files. In the documentation you are stating about the results.tsv file: "This text file contains only significant junctions that meet the cutoffs defined in the config file, aggregated at the gene level. Any sample/gene pair is represented by only the most significant junction."
By that definition I would not expect to find calls in genes which are not present in the results_per_junction.tsv file. However, this is exactly what I encounter (actually quite regularly).

Interestingly, in two cases those are variants in positive controls we do in fact expect to see. We would miss them looking at the results_per_junction.tsv-file.

I also observed the opposite case in which I can not recover calls in genes in the results_per_junction.tsv that are listed in the results.tsv file (which I would expect to do based on the definition).

I would be very grateful for a clarification!

Also, I wanted to make sure that I get it correctly that the results listed in the html report are equivalent to the results.tsv file - is this correct?

Thank you very much,
Flo

**Comment by vyepez88** [comment]
Hi Flo,
Sorry for the super delayed reply. As you correctly mention, there are 2 results that FRASER exports:
* one performing multiple testing correction across all the junctions
* one performing multiple testing correction across all the junction of a gene, and then across genes
We have found that genes with many junctions are more prone to aberrant splicing, however, with a lower than linear relation, indicating they are more constrained. We will eventually revisit this and try to find a more optimal way of computing the multiple testing correction.

**Comment by scharf-f** [comment]
Hi Vicente,

thank you very much for the clarification! :)
