### ISSUE TITLE
External dataset sequencing variability

### ISSUE THREAD

**Issue by carlalbc** [gagneurlab/drop#567]
Dear developers,

I was wondering something about the external datasets, in particular the dataset with 330 strand-specific induced pluripotent stem cells (iPSCs), build hg19, EMBL (https://zenodo.org/records/7022459). From what I can understand the dataset is comprised with different experiments coming from different sources and with different sequencing specifications. 
Would these differences; i.e sequencing depth, read length, disease/healthy, affect the overall results by adding artifacts and missing hits in the samples of interest?

Thank you in advance for your input!

**Comment by vyepez88** [comment]
Dear Carla,
Yes, seq depth and read length can affect the results. I suggest keeping samples with similar seq depth only. We haven't made a read length analysis to be able to conclude how much it affects. |
Regarding disease/healthy, we have had good results combining them. What matters more here is if they come from different centers and were thus sequenced differently. 
Overall, I recommend integrating the different samples (as long as the seq protocol - build, strand, polyA/ribo dep and tissue match) and check for samples with too many outliers. If none stands out, then keep on with the analysis.

**Comment by carlalbc** [comment]
Perfect, thank you! And do you know if in the mentioned dataset (the 330 strand-specific iPSCs) the sequencing depth is somewhat uniform, and if yes in what range?

**Comment by vyepez88** [comment]
I don't remember, you can check if there's a mention in the original publication: https://www.nature.com/articles/s41588-021-00800-7
Otherwise, you can download the dataset and sum the counts of all the samples.

**Comment by carlalbc** [comment]
Ok, perfect! Thank you Vicente, will do the latter :)
