### ISSUE TITLE
Using log2cpm Transformation for Outlier Detection Compared to Negative Binomial Model

### ISSUE THREAD

**Issue by Conghan-01** [gagneurlab/drop#571]
Dear authors,

I am curious about the appropriateness of using a log2cpm transformation followed by Z-score calculations for outlier detection. How does this method compare to directly applying a negative binomial model, as you have done in your work?

In my eQTL analyses, I commonly use log2cpm to detect outliers, but I noticed that this method is not used in OUTRIDER. I would appreciate it if you could shed some light on why log2cpm might not be the preferred approach in this context.

I would greatly appreciate any insights you could share on this matter. 
Best regards

**Comment by vyepez88** [comment]
Hi, in OUTRIDER we do a log transformation of the counts, so the approaches can be similar. What is important is to do a gene co-expression correction, as we do with the autoencoder.
