### ISSUE TITLE
Error running MAE

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/drop#572]
Hello,

I'm trying to run the MAE module but encountered an error that I’m unable to resolve. Could you please assist me in identifying and fixing the issue? I attach the image below.

![error_mae](https://github.com/user-attachments/assets/1cfa4cad-ffa9-4d03-b0a1-0eb09550c72a)

Thank you in advance for your help.

Best,

Miriam

**Comment by vyepez88** [comment]
Hi, one reason I can think is that your fasta file is missing in the `genome` parameter (not inside the MAE dictionary).
