### ISSUE TITLE
How does Outrider process gene counts with intron-retention events

### ISSUE THREAD

**Issue by hermean** [gagneurlab/drop#573]
Dear DROP developers,

First thank you for this great tool (which really helped our clinical work) and also the effort in maintenance. 

A question about interpreting gene expression results with an intron-retention event  - could you please clarify how you calculated the gene counts? If the raw counts in a given gene region were used, I assume the reads in aberrantly included introns would be taken into account, which may offset the effect of expression reduction (if a PTC is generated and NMD is triggered). If the gene counts were transcript-mode based, the interpretation would be different.

Your explanation would be highly appreciated.
Best regards,
Yanjie

**Comment by vyepez88** [comment]
Dear Yanjie,
We detect intron retention in the aberrant splicing module. For that, we compute the reads that did not splice at each splice site of the retained intron. We do not take into account the reads located purely within the intron. See Fig 1 of the FRASER2 paper for more info: https://doi.org/10.1016/j.ajhg.2023.10.014
For the aberrant expression module, we take only reads that fall within exonic regions (including spilt reads). So here also purely intronic reads would be discarded. Hope this helps.

**Comment by hermean** [comment]
Hi, Vincent:
Thanks very much for the clarification. My issue has been solved.
