### ISSUE TITLE
Will samples with same splicing/expression abnormality harm the outlier detection model

### ISSUE THREAD

**Issue by hermean** [gagneurlab/drop#574]
We are using DROP in undiagnosed rare disease patient cohort. If I understand correctly, the underlying assumption of DROP is that all samples were taken randomly from a population, regardless of the disease status. Therefore, we used only the patient samples and treat them as a group (without control). As the datasets grow (over 200 samples now), we have a few questions regarding the best design of analysis:
1. With more patient samples, the likelihood of shared abnormality (aberrant splicing or expression events) may increase. Will this harm the outlier detection model, and should this be a concern? In this regard, is it better to obtain a control set (say 50 samples) and then perform one patient + 50 control all the time to avoid recurrent variants affecting splicing/expression.
2. In our analysis, we always avoid multiple individuals from the same family (use only the proband, but not other affected individuals from the family). Is this step necessary?

Thanks in advance!

**Comment by vyepez88** [comment]
1. indeed, it can be that patients share the same aberration. As long as it's < 1% of the cohort, they should still be detected as outliers. However, once you diagnose a patient that had aberrant expression or splicing, you could remove it from the cohort. Performing 1 patient vs many controls is not recommended, unless they were all sequenced together
2. Currently we have not figured out the best way of dealing with trios in OUTRIDER & FRASER. If you don't have that many trios in your dataset, you could have them in. The benefit is that you can see whether the parents also carry the defect and apply the segregation rules in a similar way as in DNA analysis.

**Comment by hermean** [comment]
Thanks very much for the reply.
As you mentioned <1% of the cohort should be fine - can you explain a bit further? Does outrider/fraser module in DROP set 1% as the pre-filter criteria?  We typically use the pvalue/padj value for abnormal event filtering.
Your recommendation of removing diagnosed patients is appreciated.
It would be great to hear more discussion how to deal with shared abnormality issue and minimizing the impact on aberrance detection.

**Comment by vyepez88** [comment]
As you correctly mention, OUTRIDER/FRASER don't have a filter in the %, but in the pvalue/padjusted only.
It's more or less my estimate of how many samples can share the outlier and still be padjusted significant. I've had 3 patients in a >300 sample cohort with the same splicing and expression defect and it was still significant in all 3. We haven't, however, made a systematic analysis as we would need way more samples than we currently have.
