### ISSUE TITLE
Analysis of samples with different strand specificity by DROP-1.4.0

### ISSUE THREAD

**Issue by canankolakoglu** [gagneurlab/drop#575]
Dear developers,

Thanks for this very useful pipeline.

I've used DROP-1.3.3 for a long time to perform my researches. Very recently, I've updated to DROP-1.4.0 and re-analyze my previous studies.
I tried to analyze a reverse-strand specific mRNA sample that is suspected as having a splicing anomaly. To test the splicing abnormality, I set up a Fraser analysis and created a cohort with my other samples that are not strand specific. While running the analysis, I encountered with an error that indicates that I am not able to perform an analysis with samples with different strand specificity. 

![image](https://github.com/user-attachments/assets/7cb2fe68-b62e-4072-ad17-af368a14cf62)

Can you clarify if this is a new feature or a bug. Because when I look the Drop 1.4.0. release note, I didn't recognize the information of this change.

I'll be appriciated, if you help me.

Thank you very much in advance!

Best,

Canan

**Comment by vyepez88** [comment]
Dear Canan, thanks for using DROP. This is indeed a new feature as we have had bad experiences when datasets have both stranded and unstranded data as that affects the modeling assumptions of OUTRIDER and FRASER.
