### ISSUE TITLE
Using DROP pipeline for cDNA data generated by Oxford Nanopore Sequencing ?

### ISSUE THREAD

**Issue by RxLoutre** [gagneurlab/drop#576]
Hi dear DROP team !

We are exploring possibilities to get into aberrant splicing analysis using long read RNA/cDNA sequencing from Nanopore sequencers.

Do you think it is achievable to use the DROP pipeline for this purpose ? Or do you see any potentials short comings ?

Best,

Roxane

**Comment by vyepez88** [comment]
Hi Roxane, we haven't really tried using FRASER with long read data. My guess is that it won't work out of the box and it will need some finetuning already since the counting steps.

**Comment by RxLoutre** [comment]
Hello and thanks for your fast answer ! :)
Can the tuning be done within Drop's config files from a normal user ? Or is it something that need to be adjusted in the code itself you think ?

**Comment by vyepez88** [comment]
We had implemented such parameter to simply specify in the config file (https://github.com/gagneurlab/drop/blob/master/drop/template/config.yaml#L44), however we haven't implemented it in the code. We would need to test the split read counting, the non-split read counting, the distribution of k/N and see if the Beta Binomial distribution is still appropriate. So not so straightforward, but it's in our horizon.
