### ISSUE TITLE
Question regarding input bam files for MAE

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/drop#577]
Hello,

while trying to run the MAE module, I found an error that indicates that my bams don't have a read group header. After looking for some info, I was wondering if the input bams for the MAE module need to undergo the MarkDuplicates and SplitNCigars process too before running the module, or it is just necessary to add the read groups. 

Thanks in advance.

Best,

Miriam

**Comment by vyepez88** [comment]
Hi Miriam, unfortunately the read groups is a requisite of GATK. Just adding dummy groups should solve your problem.

**Comment by mmartinezj** [comment]
Got it, thank you!

**Comment by janaghub** [comment]
Hi,
I would like to follow up on @mmartinezj 's question. 

I want to use the same bam files for all three modules; aberrant expression, aberrant splicing, and MAE. 
Previously I have used bam files for aberrant expression and aberrant splicing modules that have only been aligned, sorted and indexed (no mark duplicates, splitNcigar or Read groups). Now, I am also experiencing the issue of no read group for the MAE module. 
Would you recommend only adding read groups to the BAM and then using that same BAM file for all three modules? Or rather, still use the BAM with only alignment done on them for AE and AS modules and then use a different BAM file with Read groups (and mark duplicates and splitNcigar?) for the MAE module? 

I hope my question makes sense. 

Thank you in advance!

Kind regards,
Jana

**Comment by vyepez88** [comment]
Hi Jana,

Adding the read groups has no other effect in the BAM files, so I suggest using the one with read groups for all 3 modules (which is what I've done in other projects)
