### ISSUE TITLE
Merging RNA-Seq Datasets – Seeking Guidance

### ISSUE THREAD

**Issue by mariamaitoumelloul** [gagneurlab/drop#580]
Hello,

I am currently working with a relatively small sample size (N=36 RNA samples). From what I understand from your publication, we can improve the statistical power by merging it with another dataset, provided the tissue type (blood) and RNA-seq protocol (e.g., paired-end and stranded) are the same. 

I have found a dataset that matches these technical criteria, but it comes from a different disease cohort. Would it still be appropriate to merge with this dataset, or should I aim for a healthy cohort, such as GTEx? The challenge with GTEx is that its RNA-seq protocol does not match mine (paired-end, stranded, blood sample).

I would appreciate your guidance on this matter.

**Comment by vyepez88** [comment]
Hi, it shouldn't matter that it's from another dataset (unless there are recurrent mutations in the same genes in that disease). Try it out and check the OUTRIDER heatmaps. Good luck with your analysis!
