### ISSUE TITLE
OUTRIDER > Overexpression of TBR1 not found

### ISSUE THREAD

**Issue by juugeebee** [gagneurlab/drop#583]
Hi,

The attached ppt presents the case of overexpression of TBR1 due to a PSMD14/TBR1 fusion on patient 6624CY000185.
We ran OUTRIDER via DROP and this variant was not found.

You can find in that link the raw OUTRIDER outputs files and the DROP config file :
https://dispose.aphp.fr/userportal/?v=4.5.6#/shared/public/8c_Zd35P2Xrjz9lo/86866af4-a635-48d1-ad22-adcdd85abb95

Would you have any clues that could explain why the tool does not find the variant?
[PSMD14-TBR1.pptx](https://github.com/user-attachments/files/17378460/PSMD14-TBR1.pptx)

Thanks in advance for your help!
Julie Bogoin

**Comment by vyepez88** [comment]
Hi, I cannot access the link, it says: "Could not find shared item. It has been either moved or deleted, or the link has expired.". But, from what I can see in the IGV screenshots, the TBR1 is usually not expressed in your tissue, so it is filtered out. OUTRIDER can only model genes that are sufficiently expressed. 
Maybe you can find it via splicing analysis.

**Comment by vyepez88** [comment]
Indeed, it seems the gene is only expressed in brain:
https://www.gtexportal.org/home/gene/TBR1

**Comment by juugeebee** [comment]
Thanks for your answer! 
I updated the link :
https://dispose.aphp.fr/userportal/?v=4.5.6#/shared/public/8c_Zd35P2Xrjz9lo/86866af4-a635-48d1-ad22-adcdd85abb95

**Comment by juugeebee** [comment]
For this run, we add at least 1 control, we know it has an overexpression of TBR1. Won't it be enough to overpass filtering?

**Comment by vyepez88** [comment]
Hi, it seems that your samples are duplicated {id} and {id}_ref seem to be the same. Is this intended? Having only 1 or 2 samples passing the filtering is not enough as the default filter of OUTRIDER is an FPKM > 1 in at least 5% of the samples.
I plotted the raw data and you can see that only the sample that want (and it's replicate) are overexpressed in the whole cohort:
![image](https://github.com/user-attachments/assets/669971f2-d06c-41e4-8986-73e0ea23cbcf)

**Comment by juugeebee** [comment]
It is indeed intended. It was a way we thought to overpass the filtering...

**Comment by vyepez88** [comment]
It's not a good idea as it affects the modelling assumptions of OUTRIDER. You can change the filtering parameters `fpkmCutoff` and `percentile` of the `filterExpression` function. However, this can lead to keeping unwanted genes. I recommend simply taking the plot as confirmation that it is an extreme change as no one else in the cohort had it.
