### ISSUE TITLE
Error in rule AberrantSplicing_pipeline_Counting_01_3_countRNA_nonSplitReads_samplewise_R

### ISSUE THREAD

**Issue by alice-ncl** [gagneurlab/drop#585]
Dear DROP team,

I keep getting the following error when running DROP on a mix of own and external data, any idea? I'm using gencode v29 GTF... full log and config  attached. Also, I tried gff3 version, converting to SAF using flattenGFT from Rsubreads, and re-downloading the gft from gencode again...

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid4398 ...          ||
ERROR: no features were loaded in format SAF. The annotation format can be specified by the 'isGTFAnnotationFile' option.

No counts were generated.
Execution halted
Not cleaning up /mnt/storage/nobackup/proj/apmddwmb/Alice/DROP/Charlotte/.snakemake/scripts/tmpip3lkcjy.01_3_countRNA_nonSplitReads_samplewise.R

---------------------------------------------------------------------------------------------------------------------------------

[AberrantSplicing_pipeline_Counting_01_3_countRNA_nonSplitReads_samplewise_R.txt](https://github.com/user-attachments/files/17935005/AberrantSplicing_pipeline_Counting_01_3_countRNA_nonSplitReads_samplewise_R.txt)
[config.txt](https://github.com/user-attachments/files/17935007/config.txt)

**Comment by AtaJadidAhari** [comment]
Hi, it looks like there might be an issue with the GTF file. Are you using the one directly from [GENCODE](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz), or have you modified it to create your own version? Please ensure that the GTF format is correct. You don’t need to convert it to GFF3 or SAF yourself.

Additionally, as far as I recall, if featureCounts doesn’t detect or count any reads from the BAM file using the GTF, it may produce the same error you’re encountering. Double-check that there are reads mapped to the relevant regions and that your BAM files contain data in those regions.

let us know how it goes!

(p.s. I just noticed that you have set mem_mb=1000, this is probably not enough and you might also want to increase the memory.)

**Comment by alice-ncl** [comment]
Thank you so much for your reply! It was indeed the case of missing non-split reads in the BAM files. BAM files that we received from sequencing facility were filtered to contain split reads only for whatever reason. Creating new BAMs from raw FASTQ files helped. Thanks a lot for your help :)
