### ISSUE TITLE
Too few IDs in DROP_GROUP... please ensure that it has at least 10 IDs

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#63]
I'm comparing 100 GTEX samples to 3 families with 3 different rare diseases, each with 2, 3, and 3 samples (total 8 samples).

I gave the GTEX samples one DROP_GROUP, and the 8 unrelated samples from rare disease families a different DROP_GROUP.

However, I am getting this error:
Too few IDs in DROP_GROUP ... please ensure that it has at least 10 IDs

What is the best way to analyze a small set of rare disease families together with a large set of control samples? Should I instead put all the samples in 1 group? I guess I'm not sure how DROP actually works in terms of groups. Does DROP still find outliers even within groups? If so, what is the purpose of groups in the first place? Could I just give all samples the same group name?

**Comment by vyepez88** [comment]
DROP groups consist on analysis groups. In your case, it should be a combined analysis of the affected samples and controls, therefore, they should all belong to the same DROP group. Then, the samples are modeled together and outliers are found in all of them.
