### ISSUE TITLE
R error: dev.control

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#65]
I'm running snakemake sampleAnnotation and getting the below error.
There appears to be something in the R configuration that is not compatible with your code.

Quitting from lines 18-27 (/tmp/RtmpET6935/file1d6d9205f4556/SampleAnnotation.spin.Rmd) 
Error in dev.control(displaylist = if (record) "enable" else "inhibit") : 
  dev.control() called without an open graphics device
Calls: render ... call_block -> block_exec -> chunk_device -> dev.control
In addition: Warning messages:
1: In grDevices::png(f) : no png support in this version of R
2: In (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  unable to load shared object '/gpfs/share/apps/R/4.0.0/lib64/R/library/grDevices/libs//cairo.so':
  /gpfs/share/apps/R/4.0.0/lib64/R/library/grDevices/libs//cairo.so: cannot open shared object file: No such file or directory
3: In (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  failed to load cairo DLL

Execution halted
[Mon Jun  8 11:37:13 2020]
Error in rule Scripts_Pipeline_SampleAnnotation_R:
    jobid: 1
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/sample_anno/sample_anno.done, /gpfs/scratch/evrong01/droptest/htmlOutput/Scripts_Pipeline_SampleAnnotation.html

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest/.snakemake/log/2020-06-08T113707.550475.snakemake.log

**Comment by mumichae** [comment]
It seems as though you don't have the dependencies installed for creating svg files in R. Can you make sure whether your can do so manually in R? You might have to install cairo

**Comment by mumichae** [comment]
@vyepez88 are there any plots created in R that must be vector graphics? If so, can we use pdf instead?

**Comment by mumichae** [comment]
there seems to be a problem with generating plots in general. Does plotting work in a simple R session?

**Comment by gevro** [comment]
Thanks, I will try to recompile R.

**Comment by gevro** [comment]
Compiling R again fixed the problem.

**Comment by MichaelChirico** [comment]
I saw this somewhere else. You can check `capabilities('cairo')`. ideally the code should run this for you and provide a more helpful error message. But yes fundamentally if your R version doesn't support `cairo`, you may get this issue.
