### ISSUE TITLE
Rerun snakemake pipeline even if already run

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#67]
Is there a way to force rerun of all the jobs of a pipeline even though it was already run?

**Comment by vyepez88** [comment]
you can execute `snakemake -nF` to show all the processes that you will rerun. Afterwards, execute `snakemake -F`

**Comment by vyepez88** [comment]
to add on this, DROP is based on snakemake, so all snakemake commands work:
https://snakemake.readthedocs.io/en/stable/executing/cli.html

**Comment by gevro** [comment]
Hi, snakemake -F still doesn't work sometimes. I tried this and it is not rerunning the pipeline. This is what I get:

COMMAND: snakemake -F aberrantExpression

Subworkflow AS: Nothing to be done.
Subworkflow MAE: Nothing to be done.
Executing main workflow.
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       aberrantExpression
        1

[Wed Jun 17 10:28:45 2020]
localrule aberrantExpression:
    input: /gpfs/scratch/evrong01/droptest/.drop/tmp/AE/done
    output: /gpfs/scratch/evrong01/droptest/.drop/tmp/AE.done
    jobid: 0

Touching output file /gpfs/scratch/evrong01/droptest/.drop/tmp/AE.done.
[Wed Jun 17 10:28:45 2020]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-expression-pipeline/.snakemake/log/2020-06-17T102843.076496.snakemake.log
(END)

**Comment by gevro** [comment]
Hi, Any update about this? I've tried snakemake with -f, -F, and -R and none of them are rerunning the full pipeline from the beginning, even if the jobs were already completed. I basically want to clean the run and start over.

**Comment by vyepez88** [comment]
Hi, yes, snakemake -F will only force to run the last part of the pipeline.
In order to rerun everything, the easiest way is to delete the <root>/processed_data/aberrant_expression and <root>/processed_results/aberrant_expression folders.

**Comment by gevro** [comment]
It would help if drop has an option for cleaning a previous run.
For example snakemake aberrantExpression clean
