### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#68]
Hi,
I keep getting this error. I thought it was a memory issue, but I'm running with 70 Gb memory for 100 samples, so that should not be an issue.

 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: doTryCatch(return(expr), name, parentenv, handler)
 2: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 3: tryCatchList(expr, classes, parentenv, handlers)
 4: tryCatch({    .Call(func, .extptr(file), regions, flag, simpleCigar, tagFilter,         mapqFilter, ...)}, error = function(err) {    stop(conditionMessage(err), "\n  fil
e: ", path(file), "\n  index: ",         index(file))})
 5: .io_bam(.scan_bamfile, file, reverseComplement, yieldSize(file),     tmpl, obeyQname(file), asMates(file), qnamePrefix, qnameSuffix,     param = param)
 6: scanBam(file, param = param)
 7: scanBam(file, param = param)
 8: .load_bamcols_from_BamFile(file, param, what0, with.which_label = with.which_label)
 9: readGAlignments(file, use.names = use.names, param = param2,     with.which_label = with.which_label)
10: readGAlignments(file, use.names = use.names, param = param2,     with.which_label = with.which_label)
11: FUN(bf, param = param, ...)
12: FUN(bf, param = param, ...)
13: .countWithYieldSize(FUN, features, bf, mode, ignore.strand, inter.feature,     param, preprocess.reads, ...)
14: FUN(...)
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(expr, names, parentenv, handlers[[1L]])
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatch({    FUN(...)}, error = handle_error)
19: withCallingHandlers({    tryCatch({        FUN(...)    }, error = handle_error)}, warning = handle_warning)
20: FUN(...)
21: FUN(X[[i]], ...)
22: lapply(X, FUN_, ...)
23: bplapply(X, FUN, ..., BPREDO = BPREDO, BPPARAM = param)
24: bplapply(X, FUN, ..., BPREDO = BPREDO, BPPARAM = param)
25: bplapply(setNames(seq_along(reads), names(reads)), function(i,     FUN, reads, features, mode, ignore.strand, inter.feature,     param, preprocess.reads, ...) {    bf <- reads[[i]]    .countWithYieldSize(FUN, features, bf, mode, ignore.strand,         inter.feature, param, preprocess.reads, ...)}, FUN, reads, features, mode = match.fun(mode), ignore.strand = ignore.strand,     inter.feature = inter.feature, param = param, preprocess.reads = preprocess.reads,     ...)
26: bplapply(setNames(seq_along(reads), names(reads)), function(i,     FUN, reads, features, mode, ignore.strand, inter.feature,     param, preprocess.reads, ...) {    bf <- reads[[i]]    .countWithYieldSize(FUN, features, bf, mode, ignore.strand,         inter.feature, param, preprocess.reads, ...)}, FUN, reads, features, mode = match.fun(mode), ignore.strand = ignore.strand,     inter.feature = inter.feature, param = param, preprocess.reads = preprocess.reads,     ...)
27: .dispatchBamFiles(features, BamFileList(reads), mode, ignore.strand,     inter.feature = inter.feature, singleEnd = singleEnd, fragments = fragments,     param = param, preprocess.reads = preprocess.reads, ...)
28: .local(features, reads, mode, ignore.strand, ...)
29: summarizeOverlaps(count_ranges, bam_file, mode = count_mode,     singleEnd = !paired_end, ignore.strand = !strand_spec, fragments = F,     count.mapped.reads = T, inter.feature = inter_feature, preprocess.reads = preprocess_reads,     BPPARAM = MulticoreParam(snakemake@threads))
30: summarizeOverlaps(count_ranges, bam_file, mode = count_mode,     singleEnd = !paired_end, ignore.strand = !strand_spec, fragments = F,     count.mapped.reads = T, inter.feature = inter_feature, preprocess.reads = preprocess_reads,     BPPARAM = MulticoreParam(snakemake@threads))
An irrecoverable exception occurred. R is aborting now ...
/usr/bin/bash: line 1: 423802 Segmentation fault      Rscript --vanilla /gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-expression-pipeline/.snakemake/scripts/tmpb18uoms6.countReads.R
[Wed Jun 10 15:35:40 2020]
Error in rule Scripts_Counting_countReads_R:
    jobid: 138
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/aberrant_expression/v32/counts/GTEX-11ONC_RNA.Rds

/usr/bin/bash: line 1: 423809 Killed                  Rscript --vanilla /gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-expression-pipeline/.snakemake/scripts/tmpgqqfg8w3.countReads.R
[Wed Jun 10 15:35:41 2020]
:

 *** caught bus error ***
address 0x7ff6869431f0, cause 'non-existent physical address'

**Comment by gevro** [comment]
I tried even with 110 Gb RAM and still same error.

**Comment by gevro** [comment]
I tried with even 180 Gb data, less and more CPUs, and still getting this same error.

**Comment by mumichae** [comment]
Seems to be something system specific. We've never had this issue before. What kind of system are you using? I'm assuming some kind of linux server?
Did you manage to run the pipeline on the demo?

**Comment by mumichae** [comment]
You might want to follow [this post](https://forum.qiime2.org/t/non-existent-physical-address-caught-bus-error/11802) on the same error. Are you by any chance using R under conda? If so, I would suggest you to use a system installation of R instead, which is less often less buggy.

**Comment by gevro** [comment]
I'm not running on conda. Perhaps it is another issue with R. I can try a different installation.

However, drop demo does not work now, with a completely different error:


Error in `[.data.table`(f3, , `:=`(HPO_match, HPO_id %in% unlist(strsplit(HPO_TERMS,  : 
  The items in the 'by' or 'keyby' list are length (2). Each must be length 0; the same length as there are rows in x (after subsetting if i is provided).
Calls: add_HPO_cols -> [ -> [.data.table
Execution halted
[Fri Jun 12 00:43:43 2020]
Error in rule Scripts_OUTRIDER_results_R:
    jobid: 5
    output: /gpfs/scratch/evrong01/dropdemo/Output/processed_results/aberrant_expression/v29/outrider/outrider/OUTRIDER_results.tsv, /gpfs/scratch/evrong01/dropdemo/Output/processed_results/aberrant_expression/v29/outrider/outrider/OUTRIDER_results_all.Rds

Removing output files of failed job Scripts_OUTRIDER_results_R since they might be corrupted:
/gpfs/scratch/evrong01/dropdemo/Output/processed_results/aberrant_expression/v29/outrider/outrider/OUTRIDER_results_all.Rds
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/dropdemo/.drop/modules/aberrant-expression-pipeline/.snakemake/log/2020-06-12T003742.051653.snakemake.log

**Comment by mumichae** [comment]
OK, good news is that the issue doesn't appear in the demo. The error of the demo is easily fixed if you update drop again. Unfortunately we had missed this bug in one of our fixes, but it is now solved.

The bad news is I still don't know what the issue with MulticoreParam is. According to the thread it could be something hardware related.

**Comment by gevro** [comment]
The demo is still causing the same error. I thought I used pip to update the package. What is the correct way to update drop using pip?

How do you know the issue with my R is MulticoreParam? If you explain that, it might help me figure out the problem with my R.

**Comment by gevro** [comment]
It looks like each process (core) of the pipeline is using > 40 Gb. This is a very large amount. I think that is why it is crashing. How much RAM exactly does each core need?

**Comment by gevro** [comment]
Hi, Any suggestions on this?

**Comment by mumichae** [comment]
Parallelization in R is not the most efficient. For every core it copies the complete session, sonif 40GB are needed for the initial dataset, that would be multiplied with the numbers of cores. How many cores do you use with snakemake? And do you have a large number of samples?

**Comment by gevro** [comment]
I was trying 10 cores, because I thought that is how to scale it. But if each core needs a lot of memory, that will be inefficient. I am trying to run 100 control + 10 samples = 110 samples total. How should I run this? (cores, mem, etc)

**Comment by mumichae** [comment]
Try running with a single core to see if it runs through at all. It would take significantly longer to finish, because every single bam file has to be counted, so I would try if at least 2 cores work. An option would always be to run it overnight.
The count script (which currently fails) uses a yield size of 2Mio records that are read at once per bam file. I'm not quite sure how much that is memorywise, but it could get pretty large if you use multiple cores. How large are the bam files in average?
@vyepez88 Maybe you could give a guideline as to how much memory you usually need for counting the bam files. We usually worked with files of about 20GB each.

However, for splicing you will likely probably need even power than for the aberrant expression. @c-mertes How much memory do you recommend in general for a basic splicing task?

**Comment by gevro** [comment]
Looks like 60Gb per core is finally working for aberrantExpression.
I recommend you all put MEM requirements in your help/protocol.
