### ISSUE TITLE
Can't unlock directory

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#71]
I did snakemake --unlock, but I am still getting this error:

check for missing R packages
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
Executing subworkflow AE.
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-expression-pipeline
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.

**Comment by mumichae** [comment]
Please use`snakemake unlock`, as stated in the documentation
