### ISSUE TITLE
CRAM files

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#72]
Does DROP accept CRAM files? Because I'm getting the below error:

Error in value[[3L]](cond) : 
  failed to open BamFile: 'filename' is not a BAM file
  file: /gpfs/data/mapping/UDP-1000/RNA/UDP-1001_RNA.cram
Calls: seqlevelsStyle ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[Mon Jun 15 19:46:14 2020]
Error in rule Scripts_Counting_countReads_R:
    jobid: 167
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/aberrant_expression/v32/counts/UDP-1001_RNA.Rds

**Comment by vyepez88** [comment]
Hi,
Currently, DROP doesn't accept CRAM files.
