### ISSUE TITLE
Missing file exception

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#73]
I'm getting the below error. Not sure what the issue is.

Loading assay: psi3
Loading assay: rawOtherCounts_psi5
Loading assay: rawOtherCounts_psi3
Loading assay: delta_psi5
Loading assay: delta_psi3
Loading assay: predictedMeans_psi5
Loading assay: predictedMeans_psi3
Loading assay: zScores_psi5
Loading assay: pvaluesBetaBinomial_psi5
Loading assay: padjBetaBinomial_psi5
Loading assay: zScores_psi3
Loading assay: pvaluesBetaBinomial_psi3
Loading assay: padjBetaBinomial_psi3
Loading assay: rawCountsSS
Loading assay: psiSite
Loading assay: rawOtherCounts_psiSite
Loading assay: delta_psiSite
Loading assay: predictedMeans_psiSite
Loading assay: zScores_psiSite
Loading assay: pvaluesBetaBinomial_psiSite
Loading assay: padjBetaBinomial_psiSite
Fri Jun 19 19:34:14 2020: Writing final FRASER object ('/gpfs/scratch/evrong01/droptest/root/processed_data/aberrant_splicing/datasets//savedObjects/GTEX100/fds-object.RDS').
Waiting at most 5 seconds for missing files.
MissingOutputException in line 115 of /tmp/tmpvhlvdoxe:
Missing files after 5 seconds:
/gpfs/scratch/evrong01/droptest/root/processed_data/aberrant_splicing/datasets/savedObjects/GTEX100/pajdBetaBinomial_psiSite.h5
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-splicing-pipeline/.snakemake/log/2020-06-19T183802.842513.snakemake.log

**Comment by vyepez88** [comment]
This is probably due to a typo we used to have in FRASER that was fixed a couple of weeks ago (padjBetaBinomial was changed to padjBetaBinomial). Can you please reinstall FRASER and update DROP? Then rerun the aberrantSplicing module.

**Comment by gevro** [comment]
Isn't FRASER installed together with DROP? Do they need to be installed separately?

**Comment by c-mertes** [comment]
Currently it's only checked if it's installed and if not it's installed but we do not check the correct version right now. So to have the latest version you would need to reinstall it.

@vyepez88 or @mumichae we should have a version number check in the init script. Problem here is that we have to make it correct depending on the bioc branch used eg for 1.0.2 for bioc3.10 and 1.1.3 for devel.
