### ISSUE TITLE
Reads with ambiguous pairing

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#77]
I'm getting these warning messages. What does it mean? Is this an issue?

 counting
Warning messages:
1: In .make_GAlignmentPairs_from_GAlignments(gal, strandMode = strandMode,  :
    11612496 alignments with ambiguous pairing were dumped.
    Use 'getDumpedAlignments()' to retrieve them from the dump environment.
2: In .make_GAlignmentPairs_from_GAlignments(gal, strandMode = strandMode,  :
    11046444 alignments with ambiguous pairing were dumped.
    Use 'getDumpedAlignments()' to retrieve them from the dump environment.

**Comment by vyepez88** [comment]
It is normal that some reads are not able to be assigned to a region due to ambiguous pairing. Please refer to the Genomic Alignments manual, subsection **Ambiguous pairing** for further information: https://bioconductor.org/packages/devel/bioc/manuals/GenomicAlignments/man/GenomicAlignments.pdf

**Comment by gevro** [comment]
It looks like about 10% of my reads are ambiguous pairing. Is that a normal % ?

**Comment by vyepez88** [comment]
I checked one of my samples and I got 3.2% of ambiguous pairings. We use a poly-A enriched protocol, if you do total RNA you might get more ambiguous pairings. Have a look at the 'Obtained Read Counts' and 'Obtained Read Count Ratio' in the Count Summary html. You can see how those numbers look for the test dataset: https://www.cmm.in.tum.de/public/paper/drop_analysis/webDir/html/AberrantExpression/Counting/v29/Summary_all.html

**Comment by gevro** [comment]
I also have polyA enriched. How do these graphs show the ambiguous pairings %? What does 'Obtained read counts' and 'Obtained read count ratio' mean?

**Comment by vyepez88** [comment]
Those graphs show the total reads that were counted, and the proportion reads counted / total reads in the BAM file. Reads that were not counted can be due to falling in intronic or intergenic regions, or being ambiguous. Unfortunately, currently, we make no distinction between them.

**Comment by vyepez88** [comment]
but from your Expressed genes plot, I saw that you have ~13K expressed genes, which goes in line with other count matrices I've analyzed.

**Comment by gevro** [comment]
It doesn't quite make sense that "Obtained read count ratio" is proportion reads counted/total reads, becasue in your above Summary_all.html, the proportions are only about 35-45%. That is much too low to be due to intronic or ambiguous pairings. Is there another explanation?

**Comment by gevro** [comment]
Any update about the above?

**Comment by vyepez88** [comment]
Another reason is that, by default, we use the mode IntersectionStrict (https://htseq.readthedocs.io/en/release_0.11.1/count.html) which considers reads that fully overlap a region. That parameter can be adjusted in the config file, to for example Union, which is more permissive.

**Comment by gevro** [comment]
Which mode do you recommend?

**Comment by vyepez88** [comment]
IntersectionStrict. In that way we are sure that a read is assigned to a gene only if it fully overlaps it. Reads that span across junctions can actually mean aberrant splicing (eg exon elongation) and are counted in the aberrant splicing module.
Also, the default parameter of inter_feature is FALSE, which means that reads that fully overlap 2 different regions will be assigned to both.
