### ISSUE TITLE
Viewing plot of gene expression across all samples in aberrantExpression pipeline

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#83]
Is there an easy way, or can you add to the output a way to see a plot of the gene expression of any specific gene across all samples, for all the genes that are outliers, with the outlier sample in a different color point and labeled?

**Comment by vyepez88** [comment]
On your project folder, go to Scripts/AberrantExpressionAnalysis. Open the Overview.R file. It contains example code of how to create the plot you're asking for. The function is called plotExpressionRank(), from the OUTRIDER package. It does give a red color to the outlier, but in the current version it doesn't print a label.
This is how it looks like for the test dataset: https://www.cmm.in.tum.de/public/paper/drop_analysis/webDir/html/Scripts_AberrantExpressionAnalysis_Overview.html
We only show 1 example as plotting all outliers can mean making more than 1,000 plots which is unfeasible.
You can copy the code on that script and modify it, for example by creating a for loop that calls the plotExpressionRank() function on all the outliers.
