### ISSUE TITLE
BSgenome.Hsapiens.UCSC.hg38 not found

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#86]
I'm getting this error. I will install it manually, but you should add this to the automatic package checks and installs.

**Comment by mumichae** [comment]
Due to the large size we haven't added as a regular dependency but are working on making it dependent on the config.

**Comment by gevro** [comment]
Hi, There's another bug. I'm still getting this error even though the package is definitely installed:

ERROR:
Load packages
Loading required package: BSgenome
Loading required package: rtracklayer

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:

    export

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted
[Thu Jul  9 12:00:26 2020]
Error in rule Scripts_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 58
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/aberrant_splicing/datasets/cache/raw-GTEX100/sample_tmp/splitCounts/sample_GTEX-13CF2_RNA.done

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-splicing-pipeline/.snakemake/log/2020-07-09T115956.358371.snakemake.log


In R:
> library("BSgenome.Hsapiens.UCSC.hg38")
Loading required package: BSgenome
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: Biostrings
Loading required package: XVector

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

Loading required package: rtracklayer

**Comment by gevro** [comment]
I think the bug is that you are loading BSgenome, instead of loading BSgenome.Hsapiens.UCSC.hg38.

**Comment by vyepez88** [comment]
Hi, it's fixed now.
