### ISSUE TITLE
BiocParallel errors

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#88]
Hi, I'm getting this strange error in aberrantsplicing. These same samples ran fine for aberrantexpression.

Thu Jul  9 19:11:43 2020: Count split reads for sample: UDP-1203_RNA
Error: BiocParallel errors
  element index: 26
  first error: sequence GL000008.2 not found
Execution halted
[Thu Jul  9 19:21:26 2020]
Error in rule Scripts_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 94
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/aberrant_splicing/datasets/cache/raw-GTEX100/sample_tmp/splitCounts/sample_UDP-1203_RNA.done

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-splicing-pipeline/.snakemake/log/2020-07-09T174827.943245.snakemake.log

**Comment by vyepez88** [comment]
That corresponds to a non-standard chromosome. Counting the split reads in those can lead to errors. For that reason we included the parameter keepNonStandardChrs in the aberrant splicing dictionary. Set it to false and the non-standard chromosomes will not be counted.

**Comment by gevro** [comment]
Thanks. FYI - that is not in the documentation.

**Comment by projectoriented** [comment]
Hello,

I'm receiving a similar error but it's from AE module instead.

```
ods <- readRDS("output/processed_results/aberrant_expression/v34/outrider/blood/ods_unfitted.Rds")
implementation <- "autoencoder"
register(MulticoreParam(3))

## subset filtered and estimate
ods <- ods[mcols(ods)$passedFilter,] 
ods <- estimateSizeFactors(ods)

## find optimal encoding dimension
a <- 5 
b <- min(ncol(ods), nrow(ods)) /20  # N/3

maxSteps <- 15

Nsteps <- min(maxSteps, b) 

# Do unique in case 2 were repeated
pars_q <- round(exp(seq(log(a),log(b),length.out = Nsteps))) %>% unique
ods <- findEncodingDim(ods, params = pars_q, implementation = implementation)
```


```
> ods <- findEncodingDim(ods, params = pars_q, implementation = implementation)
Wed Apr 14 10:46:04 2021: SizeFactor estimation ...
Wed Apr 14 10:46:05 2021: Controlling for confounders ...
Wed Apr 14 10:46:05 2021: Using the autoencoder implementation for controlling.
[1] "Wed Apr 14 10:46:13 2021: Initial PCA loss: 54.7283190258117"
Error: BiocParallel errors
  element index: 1
  first error: L-BFGS-B needs finite values of 'fn'
In addition: Warning message:
stop worker failed:
  attempt to select less than one element in OneIndex 
```

There are 158 samples (blood) for this AE run and I've tried different `mp` sizes to narrow down the search parameter but am still receiving this error- help! :'(

@mumichae @vyepez88

**Comment by projectoriented** [comment]
Apologies for the spam, I'm just seeing this issue: https://github.com/gagneurlab/OUTRIDER/issues/25 & will try to resolve from there

**Comment by vyepez88** [comment]
keep us updated
