### ISSUE TITLE
Could not connect to ENSEMBL

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#91]
Hi, I'm getting the below error:

Loading assay: pvaluesBetaBinomial_psi3
Loading assay: padjBetaBinomial_psi3
Loading assay: rawCountsSS
Loading assay: psiSite
Loading assay: rawOtherCounts_psiSite
Loading assay: delta_psiSite
Loading assay: predictedMeans_psiSite
Loading assay: zScores_psiSite
Loading assay: pvaluesBetaBinomial_psiSite
Loading assay: padjBetaBinomial_psiSite
Ensembl site unresponsive, trying uswest mirror

Check if we have a internet connection! Could not connect to ENSEMBL.
Nothing was annotated!
Mon Jul 13 01:50:55 2020: Collecting results for: psi3
Mon Jul 13 01:51:05 2020: Process chunk: 1 for: psi3
Error: BiocParallel errors
  element index: 1, 2, 3
  first error: subscript contains invalid names
Execution halted
[Mon Jul 13 01:51:12 2020]
Error in rule Scripts_FRASER_07_extract_results_FraseR_R:
    jobid: 9
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/aberrant_splicing/results/GTEX100_results_per_junction.tsv, /gpfs/scratch/evrong01/droptest/root/processed_data/aberrant_splicing/results/GTEX100_results.tsv

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-splicing-pipeline/.snakemake/log/2020-07-12T095903.693965.snakemake.log

**Comment by vyepez88** [comment]
Hi, I got the same error when running it last week. It seems there are some problems/updates with the ENSEMBL database. I simply tried the following day and it worked. It could be a  persisting problem from this: http://www.ensembl.info/2020/02/18/reduced-functionality-16th-25th-march-2020/

**Comment by gevro** [comment]
Because it crashed, how do I rerun the pipeline? Do I need to rerun from scratch? Or is snakemake smart enough to know that it needs to rerun only this part?

**Comment by vyepez88** [comment]
snakemake is smart enough to know that it needs to rerun only that and the following scripts. You can check it by doing snakemake -n aberrantSplicing

**Comment by gevro** [comment]
I reran and it completed without error, but the results table is empty. Can you take a look at the results?
https://www.dropbox.com/sh/4mp8jkwnk9vzkkb/AACQ1LHEE7m7pH5vVO_OEbtka?dl=0

**Comment by vyepez88** [comment]
if you look at plot 3.1 https://www.dropbox.com/sh/4mp8jkwnk9vzkkb/AACsAmCfG2BXKDB0by8M-OLca/AberrantSplicing/GTEX100_summary_files/figure-html?dl=0&preview=unnamed-chunk-3-1.svg&subfolder_nav_tracking=1, it shows a median of 30 aberrantly spliced genes for each splice type (psi 5, psi 3 and theta), so the results table shouldn't be empty. 
Did you check both the results_per_junction and results files? Are both of them empty?

**Comment by gevro** [comment]
All I see in the FRASER -> Datasets.R web page is:
"Results
The results table can also be downloaded with the link below.
Download results table
Results table --> EMPTY"

Where can I find results_per_junction and results files?

**Comment by vyepez88** [comment]
go to <root>/processed_data/aberrant_splicing/results/ 
there are the .tsv files containing the results

**Comment by gevro** [comment]
GTEX100_results.tsv is empty
GTEX100_results_per_junction.tsv has results.

Is the problem with the ENSEMBL issue? Did that cause GTEX100_results.tsv to be empty?
I reran the pipeline, but maybe snakemake didn't know to rerun that part of the pipeline that failed before, and then that caused GTEX100_results.tsv to be empty?

**Comment by vyepez88** [comment]
can you check the hgncSymbol column in the results by junction, does it have values?
The ENSEMBL annotation happens in the same script as the extraction of the results. It could be that even though the connection to ENSEMBL worked, it was empty.

**Comment by gevro** [comment]
hgncSymbol is all = 'NA'

**Comment by gevro** [comment]
Hi, Any update about this bug?

**Comment by vyepez88** [comment]
I was not able to reproduce this error. My guess is that, even though the connection to ensembl worked, it didn't give any results. Rerunning it should fix it. 
To do that please remove the following files:
<project_dir>/.drop/tmp/AS/done
<project_dir>/.drop/tmp/AS.done
<htmlOutputPath>/*.html   # all html files, the directory is specified in the config
<root>/processed_data/aberrant_splicing/results/  # the whole directory

Then rerun the aberrant splicing module. Hopefully the connection to ensembl will work and the genes will get annotated.

**Comment by vyepez88** [comment]
were you able to update the module and rerun it successfully?

**Comment by gevro** [comment]
Yes this error was fixed.
