### ISSUE TITLE
Sample labels for batch correlation plots

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#93]
How do I plot or find out the names of the sample names on the batch correlation plots?
It would be helpful to know which samples are clustering together into batches to understand which batches are different.

**Comment by vyepez88** [comment]
Read the OUTRIDER dataset object (ods). It is located under <root>/processed_results/aberrant_expression/{genomeAssembly}/outrider/{DROP_GROUP}/ods.Rds
Run the plotCountCorHeatmap function, for example:
ods <- OUTRIDER::plotCountCorHeatmap(ods, nRowCluster = 4, nColCluster = 3, normalized = FALSE) 

normalized = FALSE -> obtain the clustering of the samples before correction
nRowCluster and nColCluster define the number of clusters to assign samples to

By assigning the command to the ods, it adds 2 columns to the colData part of the object (describing the samples) with the cluster number where each sample was assigned to for the clustering with 4 groups and 3 groups.
You can access those columns by doing:
colData(ods)$clusterNumber_4
colData(ods)$clusterNumber_3
For more details, please refer to the OUTRIDER documentation, section 4.3 http://bioconductor.org/packages/release/bioc/vignettes/OUTRIDER/inst/doc/OUTRIDER.pdf
