### ISSUE TITLE
Pseudoexon outlier not detected

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#94]
Hi,
I have a sample with a known pathogenic pseudoexon that is completely (100%) the only isoform. The pseudoexon is between two constitutive exons. So there should be 3 outliers detected by DROP:
1) Reduction in normal splicing between the flanking exons.
2) New splice site between upstream exon and the pseudoexon
3) New splice site between the downstream exon and the pseudoexon.

The results by junction table only detected # 1 and #3. But it did not detect #2. However there are many splice junction reads for #2 and there is no chance this outlier event is present in any other samples.

Can you help me figure out why #2 was not detected? This might help you improve your pipeline, because positive control cases like this where there is a very striking splice abnormality are useful.

**Comment by mumichae** [comment]
You might want to adjust the detection thresholds for FRASER to increase sensitivity.  Checkout the [preprint](https://www.biorxiv.org/content/10.1101/2019.12.18.866830v1) and [vignette](http://bioconductor.org/packages/release/bioc/vignettes/FRASER/inst/doc/FRASER.pdf) for more information

**Comment by gevro** [comment]
Is it possible to adjust the FRASER thresholds via the DROP config.yaml file?

**Comment by mumichae** [comment]
Of course, please check our the documentation https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#aberrant-splicing-dictionary

**Comment by vyepez88** [comment]
Hi, just to add on this, you can check what is your delta psi and padjust value of that junction-sample. 
First, you can find the junction using `granges(fds)`. Then, you can access the delta psi, by doing: `assays(fds)$delta_psi3` (or 5), which is a matrix. You can then go to your junction-sample of interest inside that matrix: `assays(fds)$delta_psi3[index of the junction of interest, RNA_ID]`. You can also check the padjust by doing: `assays(fds)$padjBetaBinomial_psi3`. To check all the assays inside the fds, do `names(assays(fds))`.
