### ISSUE TITLE
mae pipeline not usable - too slow

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#96]
Hi,
The MAE pipeline is running very slowly. It is not usable. See below for timestamps. Each sample is taking several hours.

check for missing R packages
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
Subworkflow AE: Nothing to be done.
Subworkflow AS: Nothing to be done.
Executing subworkflow MAE.
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	Index
	1	Scripts_MAE_Datasets_R
	1	Scripts_MAE_Results_R
	107	Scripts_MAE_deseq_mae_R
	1	Scripts_MAE_gene_name_mapping_R
	1	Scripts_QC_DNA_RNA_matrix_plot_R
	1	Scripts_QC_Datasets_R
	1	Scripts_QC_create_matrix_dna_rna_cor_R
	107	Scripts_QC_deseq_qc_R
	1	all
	107	allelic_counts
	107	allelic_counts_qc
	107	create_SNVs
	1	create_dict
	1	markdown
	545

[Tue Jul 14 00:01:54 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-11TTK-0005-SM-5O9BX.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-11TTK--GTEX-11TTK_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-11TTK--GTEX-11TTK_RNA.vcf.gz.tbi
    jobid: 363
    wildcards: vcf=GTEX-11TTK, rna=GTEX-11TTK_RNA

[Tue Jul 14 00:01:54 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-131XE-0006-SM-5P9F9.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-131XE--GTEX-131XE_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-131XE--GTEX-131XE_RNA.vcf.gz.tbi
    jobid: 400
    wildcards: vcf=GTEX-131XE, rna=GTEX-131XE_RNA

[Tue Jul 14 16:49:45 2020]
Finished job 363.
1 of 545 steps (0.18%) done

[Tue Jul 14 16:49:45 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-11OF3-0006-SM-5O9CM.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-11OF3--GTEX-11OF3_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-11OF3--GTEX-11OF3_RNA.vcf.gz.tbi
    jobid: 356
    wildcards: vcf=GTEX-11OF3, rna=GTEX-11OF3_RNA

[Tue Jul 14 17:00:45 2020]
Finished job 400.
2 of 545 steps (0.37%) done

[Tue Jul 14 17:00:45 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-11EMC-0006-SM-5O9DN.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-11EMC--GTEX-11EMC_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-11EMC--GTEX-11EMC_RNA.vcf.gz.tbi
    jobid: 345
    wildcards: vcf=GTEX-11EMC, rna=GTEX-11EMC_RNA

[Wed Jul 15 09:15:21 2020]
Finished job 356.
3 of 545 steps (0.55%) done

[Wed Jul 15 09:15:21 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-11ONC-0005-SM-5O9CY.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-11ONC--GTEX-11ONC_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-11ONC--GTEX-11ONC_RNA.vcf.gz.tbi
    jobid: 357
    wildcards: vcf=GTEX-11ONC, rna=GTEX-11ONC_RNA

[Wed Jul 15 09:26:07 2020]
Finished job 345.
4 of 545 steps (0.73%) done

[Wed Jul 15 09:26:07 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-139TT-0006-SM-5O9CG.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-139TT--GTEX-139TT_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-139TT--GTEX-139TT_RNA.vcf.gz.tbi
    jobid: 417
    wildcards: vcf=GTEX-139TT, rna=GTEX-139TT_RNA

[Thu Jul 16 02:04:43 2020]
Finished job 357.
5 of 545 steps (0.92%) done

[Thu Jul 16 02:04:43 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-1128S-0005-SM-5P9HI.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-1128S--GTEX-1128S_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-1128S--GTEX-1128S_RNA.vcf.gz.tbi
    jobid: 333
    wildcards: vcf=GTEX-1128S, rna=GTEX-1128S_RNA

[Thu Jul 16 02:15:35 2020]
Finished job 417.
6 of 545 steps (1%) done

[Thu Jul 16 02:15:35 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-1314G-0005-SM-5NQ9O.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-1314G--GTEX-1314G_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-1314G--GTEX-1314G_RNA.vcf.gz.tbi
    jobid: 399
    wildcards: vcf=GTEX-1314G, rna=GTEX-1314G_RNA

[Thu Jul 16 18:29:34 2020]
Finished job 333.
7 of 545 steps (1%) done

[Thu Jul 16 18:29:34 2020]
rule create_SNVs:
    input: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt, /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz, /gpfs/scratch/evrong01/GTEX/BAM/GTEX-12C56-0006-SM-5N9E9.Aligned.sortedByCoord.out.patched.md.bam, /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
    output: /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-12C56--GTEX-12C56_RNA.vcf.gz, /gpfs/scratch/evrong01/droptest/root/processed_data/mae/snvs/GTEX-12C56--GTEX-12C56_RNA.vcf.gz.tbi
    jobid: 381
    wildcards: vcf=GTEX-12C56, rna=GTEX-12C56_RNA

[Thu Jul 16 18:40:07 2020]
Finished job 399.
8 of 545 steps (1%) done

**Comment by vyepez88** [comment]
Hi, we usually run the MAE pipeline in vcf files generated from WES. The ones from GTEx are generated from WGS, which makes the process much slower.
DROP uses the function to count alleles from GATK, which is the one taking several hours. 
Do you need to run MAE on the GTEx samples? For this module, you do not need other samples as controls because the statistical test is done per sample, not as a group.

**Comment by gevro** [comment]
Oh ok. I will run it only on my samples then.
How do I do this? There are two settings for mae: 'groups' and 'qcGroups'.
What is the difference? Which samples should be in each type of group?

**Comment by vyepez88** [comment]
You can specify in the DROP_GROUP column in the sample annotation which are your samples, and then write that group in the mae groups parameter. A sample can belong to multiple groups, which are comma-separated in the DROP_GROUP column.
The mae 'groups' specify the groups that are going to be tested for mono-allelic expression.
The qc module checks whether a DNA and RNA combination actually match. So the qcGroups specify the groups that you want to test this. In your case you should assign the same value to both.

**Comment by gevro** [comment]
Thanks. What is the difference between the qc module of mae versus the snakemake sampleQC command?

**Comment by vyepez88** [comment]
They're the same.
If you execute snakemake mae, both the mae and qc are executed. If you execute snakemake sampleQC, only the qc is executed.
