### ISSUE TITLE
Unlock issues

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#98]
Hi,
Unlock issues are still happening.

1) Snakemake unlock gives this error:
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
MissingInputException in line 38 of /gpfs/home/evrong01/.local/lib/python3.6/site-packages/wbuild/wBuild.snakefile:
Missing input files for rule markdown:
MAE/UDP--v32_results.md
[Mon Jul 20 23:43:01 2020]
Error in rule unlock:
    jobid: 0
    output: /gpfs/scratch/evrong01/droptest/.drop/tmp/MAE/unlock
    shell:
        snakemake --unlock --configfile /gpfs/scratch/evrong01/droptest/.drop/tmp/config.yaml
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/.snakemake/log/2020-07-20T234300.144071.snakemake.log

2) snakemake --unlock works without error:
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
MissingInputException in line 38 of /gpfs/home/evrong01/.local/lib/python3.6/site-packages/wbuild/wBuild.snakefile:
Missing input files for rule markdown:
MAE/UDP--v32_results.md
[Mon Jul 20 23:43:01 2020]
Error in rule unlock:
    jobid: 0
    output: /gpfs/scratch/evrong01/droptest/.drop/tmp/MAE/unlock
    shell:
        snakemake --unlock --configfile /gpfs/scratch/evrong01/droptest/.drop/tmp/config.yaml
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline/.snakemake/log/2020-07-20T234300.144071.snakemake.log

3) But then running the mae command after the above gives this error:
check for missing R packages
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
Subworkflow AE: Nothing to be done.
Subworkflow AS: Nothing to be done.
Executing subworkflow MAE.
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.

I strongly suggest to change the pipeline so that these unlock issues don't happen. I got it to work again by deleting this directory: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline

And then doing drop update.

**Comment by gevro** [comment]
I got it to work again by deleting this directory: /gpfs/scratch/evrong01/droptest/.drop/modules/mae-pipeline

And then doing drop update.

**Comment by gevro** [comment]
The conda version of drop still has the same unlock issues...

Building DAG of jobs...
MissingInputException in line 62 of /gpfs/scratch/evrong01/droptest2/.drop/modules/mae-pipeline/Snakefile:
Missing input files for rule create_SNVs:
/gpfs/scratch/evrong01/droptest2/.drop/modules/mae-pipeline/.drop/modules/mae-pipeline/Scripts/MAE/filterSNVs.sh
/gpfs/scratch/evrong01/droptest2/.drop/modules/mae-pipeline/.drop/modules/mae-pipeline/resource/chr_UCSC_NCBI.txt
/gpfs/scratch/evrong01/droptest2/.drop/modules/mae-pipeline/.drop/modules/mae-pipeline/resource/chr_NCBI_UCSC.txt
[Tue Jul 28 19:29:12 2020]
Error in rule unlock:
    jobid: 0
    output: /gpfs/scratch/evrong01/droptest2/.drop/tmp/MAE/unlock
    shell:
        snakemake --unlock --configfile /gpfs/scratch/evrong01/droptest2/.drop/tmp/config.yaml
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest2/.drop/modules/mae-pipeline/.snakemake/log/2020-07-28T192910.678386.snakemake.log

**Comment by vyepez88** [comment]
Yes, the current conda version consists of the previous github version with some minor modifications.
This bug was already fixed, but will appear in the next stable release in ~2 weeks.
